### ISSUE TITLE
EngineYard's TFA

### ISSUE THREAD

**Issue by dsoegijono** [2factorauth/twofactorauth#1007]
Currently, it's listed as "in beta" but the [doc linked](https://support.cloud.engineyard.com/entries/40538256-Two-factor-authentication) is just a thread of a user requesting to have it enabled for himself. I don't see it as TFA being implemented system-wide. Tried googling it, and the [first search result](https://blog.engineyard.com/2015/engine-yards-two-factor-authentication) is just saying that they have TFA and mentions our site listing them as such.

Are there EngineYard users that know of a better doc to link to with their TFA instructions? Or maybe we should update the note to say that users have to request?

**Comment by mxxcon** [comment]
Perhaps ping https://twitter.com/zlatkounger for clarification(I don't use twitter) on available resources?

**Comment by RichJeanes** [comment]
Seems like this has been handled. EngineYard's entry has an exception listed and a search on their support site that they link to in their TFA blog post just gets you to he linked support thread.
Closing for house keeping.
