### ISSUE TITLE
One Year Ago

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#1009]
Just about a [year ago](https://joshldavis.com/2014/03/15/demand-two-factor-auth-support/) I had a spring break approaching and decided it'd be a good idea to make this website literally the day I flew to Seattle to look for apartments.

My first commit:
![screen shot 2015-03-12 at 8 34 01 pm](https://cloud.githubusercontent.com/assets/157801/6632661/2affc4ba-c8f7-11e4-99db-2f2205076aa4.png)

Here's what it looked like the day I started it:

![tfa start](https://joshldavis.com/img/2fa/twofactorauth.png)

The next day I posted it on HackerNews and then everything went crazy.

As of now, there are nearly 2k commits, over 250 contributors, and over 1000 issues. That's an average of 2.8 issues opened a day and 5.2 commits a day.

It's a pretty simple site and idea, but I think it's helping people be more secure on the net.

It wouldn't be here without the collaborators (especially the hardcore ones; you know who you are). So thanks all. You all are awesome. If any of you make it to Seattle, I'll buy you a beer or two.

**Comment by Carlgo11** [comment]
And thank you Josh for all your hard work with the site. We may have helped but if it wasn't for you we wouldn't be here.
Especially the kindness you and the collaborators have shown. That's the main reason I felt like contributing again after my first initial commit. :+1: 

I would say, if you ever make it you Sweden I'd buy you a beer as well but I'm still underage so... :smile:
To another year of awesome contributions! :beers:

**Comment by jamcat22** [comment]
Thank all of you for being so welcoming and awesome! I remember how excited I was when I was made collaborator. :smile:

Even though I haven't been contributing much lately, I am looking forward to contributing a lot more.

Seriously though Josh, thank you so much for creating this site.
