### ISSUE TITLE
Skype supports 2factor if you use MSFT account

### ISSUE THREAD

**Issue by ScaleOvenStove** [2factorauth/twofactorauth#102]
If you sign into Skype with your Microsoft account, and your Microsoft account has 2 factor auth turned on, then Skype supports it. Most likely over time, Skype accounts will be deprecated and Skype will only support Microsoft accounts. I think at least on your site there should be an \* with this note

**Comment by jdavis** [comment]
Awesome, thanks for the info. We added this with #118.
