### ISSUE TITLE
Permissions for logo usage difficulty

### ISSUE THREAD

**Issue by rmoriz** [2factorauth/twofactorauth#1038]
Hi,

I would like to contribute various international sites that have their HQ in Germany and provide world-wide services. However under German copyright law I'm not allowed to rip off, modify or re-upload their logos.

There should be a documented option to add sites without adding a logo image, e.g. using 

``` yaml
img: ../placeholder.png
```

**Comment by mxxcon** [comment]
@rmoriz This sounds ridiculous, and I would not be surprised if you are misinformed by intentionally-scare-mongering lawyers and companies that want to unfairly control information.
There are gotta be some Fair-Use or similar type of exclusions.
You are not "ripping off" logos. Many sites gladly provide files with their logos for use in the media.
You are not distributing, selling or promoting those logos. 
This is a free, informational site. Those logos are used purely for illustration purposes.
If you are really worried about this, create an issue with all the sites you want added, and I will create pull requests with those including logos. And if some German company have an issue with that, that company's lawyers can find a really sharp stick and shove it up their bumholes!

**Comment by jamcat22** [comment]
Sadly, Germany (and most other countries) do not have Fair Use or Fair Dealing laws. (This document outlines the laws in many different countries: http://ccarts.ca/wp-content/uploads/2011/07/FairUseandFairDealinginForeignCountries.pdf)

In fact, Google has been sued and found to have violated copyright with thumbnails on Google Images before and it is still an ongoing issue. (http://moritzlaw.osu.edu/students/groups/is/files/2013/08/8-Potzlberger.pdf)

But I doubt many companies are going to sue us or even care, so...

**Comment by Carlgo11** [comment]
Closing since #1039 exists.

**Comment by jdavis** [comment]
Good thing most of us don't live in Germany then =]

I'm closing this.

**Comment by Carlgo11** [comment]
:+1: to that comment :laughing:
