### ISSUE TITLE
Loopia now has 2FA

### ISSUE THREAD

**Issue by StefanWallin** [2factorauth/twofactorauth#1048]
@Carlgo11, It seems that since #702, they've now added it with BankID, not really a standard way outside sweden though...

If you have time to add it and figure out what category of 2FA to put it in, you are welcome. Otherwise I'll add it when I've got time.

http://blogg.loopia.se/2015/03/16/nu-kan-du-logga-in-med-tvafaktorsautentiering-hos-loopia-genom-bankid/

**Comment by Carlgo11** [comment]
Mobilt BankID?

**Comment by StefanWallin** [comment]
Yes, both Mobile and desktop versions work apparently.

**Comment by Carlgo11** [comment]
Okay I'll add TFA to loopia later today as well as BankID to the providers list.
Thanks for informing me :smiley:

**Comment by Carlgo11** [comment]
Updated Loopia's status in #1051
