### ISSUE TITLE
Link to League of Legends two-factor auth page is broken.

### ISSUE THREAD

**Issue by KeenRivals** [2factorauth/twofactorauth#1058]
The link http://forums.na.leagueoflegends.com/board/showthread.php?p=45603580#45603580 leads to an error page. I think this is the result of them moving their boards to a new platform.

**Comment by RichJeanes** [comment]
Works for me.

**Comment by mxxcon** [comment]
I get error 500 for their whole forums site...so perhaps wait until they fixed it.

**Comment by LeFouineur** [comment]
Works for me too.

**Comment by Carlgo11** [comment]
@mxxcon looks like it works in Chrome but not Firefox.

**Comment by LeFouineur** [comment]
@Carlgo11, for me it works (checked again now) in Chrome, Safari, Opera and Firefox (Nightly), from different ISPs and DNS Servers.
It must have been more of a configuration problem, DNS propagation and/or cache persistence.
Or they forgot to remove some geolocation/browser restrictions :laughing:

**Comment by Carlgo11** [comment]
Try Firefox 37.0.2. The latest stable one.
It's not geolocation restrictions. I've tried Germany, England, U.S.A and Sweden.

**Comment by Carlgo11** [comment]
Ah, I found the problem. HTTPS-Everywhere. I'm guessing both @mxxcon and I use it.

**Comment by mxxcon** [comment]
yes, that was the problem. :-1:
