### ISSUE TITLE
GateKeeper - hardware based 2FA - Please add to list

### ISSUE THREAD

**Issue by ulabs-spotbhare** [2factorauth/twofactorauth#1059]
I wanted to draw attention to GateKeeper by Untethered Labs (www.gkchain.com) as a Bluetooth 4.0 based device that can be used as 2FA for logging on to computers. I am the CEO of Untethered Labs and we are developing this technology further to allow 2FA for computers on a network, specific application areas such as health care, emergency personnel, police, general IT security, etc.

**Comment by mxxcon** [comment]
Do you think 100ft bluetooth range is a good idea for a tfa solution?

If you walk back to your computer and it's automatically unlocked then it's not TFA...

Your marketing video has an extremely vague and misleading claim "more than 40% of companies had data breach this year"...That does not sound right..

**Comment by ulabs-spotbhare** [comment]
Gatekeeper can be used as two factor authentication by disabling thr auto
unlock feature. It will the require the user to input his password AND have
the Gatekeeper to log on. This is being made more obvious in the new
enterprise version of our software that is under beta testing.

100 ft range has nothing to do with 2FA. It only represents the range of
Bluetooth.

We are not well establiahed as the solutions listed on the twofactauth
website. I apologize if it was premature to suggest adding us to the list
of 2FA providers.

**Comment by mxxcon** [comment]
@ulabs-spotbhare Well, if your solution uses Bluetooth as 2fa, 100ft range of a Bluetooth signal could be problematic since even walking to get your coffee could be close enough for the signal to still register yet far enough that you don't have a direct line-of-sight to your computer...
Perhaps if your device were to use Class 3 Bluetooth, then it would have much shorter range and battery would last even longer.

You or your developer can submit a pull request to add your site. It's just a YAML block of text.

**Comment by Carlgo11** [comment]
Well while I like your product (and wouldn't mind a free sample *cough* *cough* :wink: ) I don't think it's a TFA device. Not yet at least. Mostly because you don't have a public API yet.

**Comment by ulabs-spotbhare** [comment]
We are actually using Bluetooth 4 for communication. So in an office the
range is more like 30 feet. Also we use a ranging algorithm that the user
can configure to only unlock when the device is close to the computer.
Battery life for a CR2032 is more than 6 months. :)

Will submit the pull request. Thanks.

**Comment by ulabs-spotbhare** [comment]
Please send out a separate email to me at siddharth.potbhare@gkchain.com
and we will talk about the sample ;).

**Comment by Carlgo11** [comment]
Closing this ticket as GateKeeper doesn't have an API to use yet.
Just to explain to you @ulabs-spotbhare, the providers tab's main purpose is to help developers choose a service to use for implementing TFA.
As your product as of now doesn't have a public API to use then it can't be listed as a TFA provider.

Feel free to reopen this ticket or make a new PR once you have an API for people to use!

Thank you for taking interest in twofactorauth.org!

//@Carlgo11
