### ISSUE TITLE
Ed Snowden on Passwords (off topic but really funny)

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1065]
So this isn't really an issue or anything but I'd thought I should drop this here anyways since we're kind of working closely with this topic.
Plus I think it's hilarious. :wink: 
[![Video Label](http://img.youtube.com/vi/yzGzB-yYKcc/0.jpg)](https://www.youtube.com/watch?v=yzGzB-yYKcc)
<i>[https://www.youtube.com/watch?v=yzGzB-yYKcc](https://www.youtube.com/watch?v=yzGzB-yYKcc) if the iframe doesn't load corretly</i>

**Comment by jdavis** [comment]
Your second link doesn't link to the video where the picture is from =]

Regardless, good video. I liked the Margaret Thatcher one.
