### ISSUE TITLE
Add Pacific Continental

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#1070]
This is just a reminder for myself more than anything. They do have 2FA too.

https://www.therightbank.com/

**Comment by Carlgo11** [comment]
@jdavis if you tell me what different TFA solutions they have I could make a PR for you if you don't have the time.

**Comment by mxxcon** [comment]
@Carlgo11 according to https://www.therightbank.com/files/capital-pacific-bank-online-services-instructions.pdf they seem to use sms and voice.
