### ISSUE TITLE
Paypal 2FA is not only avaliable in the US/Canada

### ISSUE THREAD

**Issue by rugk** [2factorauth/twofactorauth#1072]
On the website it states Paypal's 2FA would only be available in the US and Canada.
However this can't be true, because at least for Germany I can say that SMS authentication is available there too.
Here is a screenshot:
![paypal_2fa_sms](https://cloud.githubusercontent.com/assets/11966684/7169598/388d907c-e3c7-11e4-87fa-ec3f8a741cd4.png)
That's the link: https://www.paypal.com/de/cgi-bin/webscr?cmd=_register-security-key-mobile

I've even heard that hardware-token-authentication is available in Germany (and maybe other countries too), but I couldn't verify this until now.

**Comment by mxxcon** [comment]
This should be addressed in #1026

**Comment by rugk** [comment]
Okay, however @Carlgo11 said that it would only be available in one country (meaning US) there, which is obviously not true.

Also more information about the hardware token. Now I can confirm that it's also available in Germany.
Here is the link: https://www.paypal.com/de/cgi-bin/webscr?cmd=xpt/Marketing/securitycenter/general/PPSecurityKey-outside

**Comment by Carlgo11** [comment]
Recent convo with me and Paypal discussing this: https://twitter.com/AskPayPal/status/588318272719695873

**Comment by rugk** [comment]
@Carlgo11 
Ah, okay thanks. So we know now in which countries it's available. Great!

**Comment by jamcat22** [comment]
Closing in favor of #1026, #1073, and #1074.

**Comment by rugk** [comment]
@Carlgo11
Would you mind to ask if this list of countries where 2FA is available also applies to ebay?
Or does somebody already know whether it does or whether not?
