### ISSUE TITLE
Clean up branches in this repo.

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#1078]
We have a bunch of branches in this repo that seem to be abandoned. Delete them?
~~https://github.com/jdavis/twofactorauth/tree/awesome-1.0 last commit Mar 22, 2014~~
~~https://github.com/jdavis/twofactorauth/tree/bot last commit Mar 23, 2014, never merged.~~
~~https://github.com/jdavis/twofactorauth/tree/contributing_doc_changes last commit Mar 20, 2015. Merged Mar 26.~~
~~https://github.com/jdavis/twofactorauth/tree/patch-6 last commit Sep 8, 2014, never merged.~~
https://github.com/jdavis/twofactorauth/tree/script last commit Dec 10, 2014, never merged.
~~https://github.com/jdavis/twofactorauth/tree/travis-update last commit and merged Feb 8, 2015.~~
https://github.com/jdavis/twofactorauth/tree/utility-patch last commit Mar 20, 2015, never merged.

**Comment by mxxcon** [comment]
@RichJeanes do we still need /contributing_doc_changes branch?
@Carlgo11 do we still need /patch-6 branch?

**Comment by Carlgo11** [comment]
Nope. You can delete it

**Comment by RichJeanes** [comment]
Yup. That one's been merged.

**Comment by jdavis** [comment]
I cleaned up awesome/bot.

**Comment by mxxcon** [comment]
:+1:

**Comment by mxxcon** [comment]
@ilyakatz What's the plan with script branch?

**Comment by Carlgo11** [comment]
@mxxcon non at the moment. Ilya said he had to take a break from our repo for a while and asked for anyone else to continue the work.

**Comment by RichJeanes** [comment]
I think the utility patch is kinda stalled until we get the region tagging sorted out since so much of it is going to be very region specific, relating to physical utilities.
I suggest closing this issue for housekeeping. @mxxcon Satisfactory?

**Comment by ilyakatz** [comment]
hey guys, i have a bit more time now but i have't followed what has been happing in the project, so if you still think the script branch makes sense, I can work dedicate some time to it

**Comment by mxxcon** [comment]
@RichJeanes Yes, most branches have been cleaned up, so I'm "officially" closing this.
Regarding Ilya's script, can continue to discuss it here or open a new issue or on https://gitter.im/jdavis/twofactorauth
