### ISSUE TITLE
Hook Mobile 

### ISSUE THREAD

**Issue by ell20** [2factorauth/twofactorauth#1085]
Hi, our company is a provider for SMS based 2FA solutions. I noticed that we're not on the list and would like to be added to this list. Is raising an issue ticket here sufficient or is there an additional process?

Thanks

**Comment by mxxcon** [comment]
See https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md
If you don't know how to do such things, your developers should.

**Comment by jdavis** [comment]
It looks like #1088 covers this. Closing.
