### ISSUE TITLE
Please add Adobe ID to list

### ISSUE THREAD

**Issue by mikeshupp** [2factorauth/twofactorauth#1109]
Please add Adobe ID to list (I attempted to, per "Add your own favorite site by submitting a
pull request on the GitHub repo" but haven't yet figured out how to do correctly)

**Comment by Carlgo11** [comment]
@mikeshupp I recommend reading the tutorial on our [wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_SITE).
Try going through it step by step.

Best regards,
@Carlgo11

**Comment by jamcat22** [comment]
Closing due to #1167.
