### ISSUE TITLE
Intuit TurboTax needs to be on the list of sites lacking two factor authentication.

### ISSUE THREAD

**Issue by gpshead** [2factorauth/twofactorauth#111]
They don't support two factor but they do hold all of your personal financial information.

https://ttlc.intuit.com/questions/2060465-two-factor-authentication is a joke.

**Comment by jdavis** [comment]
+1 It belongs in the Finance section.

**Comment by jdavis** [comment]
@gpshead Would you be able to add it to Finance? If not, myself or someone else might be able to.
