### ISSUE TITLE
Add information about multiple account / team support

### ISSUE THREAD

**Issue by rasky** [2factorauth/twofactorauth#1111]
One problem I sometime find with 2FA is that there are services which are commonly needed to be shared among multiple people (e.g.: colleagues in a work environment), but they either don't have "team" support (that is, multiple personal logins to manage the same resource) or it's available only on higher plans. This has a strong impact on 2FA, because it basically makes it impossible to use, as it's hard to share a token (hw and/or sw) or worse relay a SMS.

For instance:
- Twitter doesn't have any support for team accounts, so 2FA cannot be used for all company accounts (usually managed by multiple people) and/or celebrity accounts (managed by media managers).
- Cloudflare has only recently added team support, but only in the enterprise plan ($2000/mo). If you want to have multiple people manage the domains and the configurations, you need to disable 2FA.
- Mailchimp: it's normal to share mailing-list management with multiple colleagues, but there is no team support, so the 2FA must be kept disabled.

There are of course many services where team support is available for free (e.g.: Heroku, AWS) or the service is designed to be used with personal accounts that can interoperate (e.g.: Dropbox, Campfire), so I think it makes sense to highlight those services that make 2FA harder to implement.

**Comment by RichJeanes** [comment]
I feel like providing team is beyond the scope of Twofactorauth.org and is more of an issue with the service provider's feature set, not with their TFA.
Consensus?

**Comment by RichJeanes** [comment]
I feel like providing team is beyond the scope of Twofactorauth.org and is more of an issue with the service provider's feature set, not with their TFA.
Consensus?

**Comment by jamcat22** [comment]
I agree.
