### ISSUE TITLE
Wells Fargo does NOT support two factor auth

### ISSUE THREAD

**Issue by tonybruess** [2factorauth/twofactorauth#1114]
Wells Fargo has had this page on "advanced access" for a long time now. https://www.wellsfargo.com/privacy-security/advanced-access/

I have both a phone number and RSA device on my Wells Fargo account. At login I have never been prompted to enter a code.

**Comment by Carlgo11** [comment]
Have you tried with multiple IPs (and cookies turned off)?

**Comment by mxxcon** [comment]
@mrapple So then why did they provide it to you? :smile: Can you ask them in what cases they are used?

**Comment by tonybruess** [comment]
Yes, I've always logged into my account from various locations (including using a VPN) without being prompted for two factor. The only times I'm asked for a code is when using direct pay to pay employees. I can transfer money, view account statements, etc without ever entering a code.

**Comment by Carlgo11** [comment]
haha well that's "secure"... :disappointed: 
So would you mind making a PR about this @mrapple?

**Comment by tonybruess** [comment]
If I must :stuck_out_tongue_winking_eye:

**Comment by Carlgo11** [comment]
Yeah that would be great. Also, try contacting Wells Fargo. Maybe they can tell us when this extra security layer is used so that we could add a note about it on the site.

**Comment by tonybruess** [comment]
#1115 

Interesting Facebook thread: https://www.facebook.com/wellsfargo/posts/575879875758205

It sounds like people that have tried to contact them have been unsuccessful. Sigh.

**Comment by Carlgo11** [comment]
Moving discussion to #1115
