### ISSUE TITLE
What's with SchoolSoft?

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1116]
Is this because they don't have a Twitter handle?
![schoolsoft](https://cloud.githubusercontent.com/assets/6753081/7484293/aece73ae-f33b-11e4-9341-2b9e26b26057.png)

**Comment by jamcat22** [comment]
Yep

**Comment by Carlgo11** [comment]
Indeed.
It would be nice with a mailto option as well for those few companies who don't use Twitter at all.
