### ISSUE TITLE
German Postal Bank (Deutsche Postbank)

### ISSUE THREAD

**Issue by arisboch** [2factorauth/twofactorauth#1123]
I'd like for them to have that kinda service.

**Comment by mxxcon** [comment]
@arisboch feel free to create a pull request for this site.

**Comment by arisboch** [comment]
How can I do that?

(EDIT: Signature removed by @Carlgo11)

**Comment by Carlgo11** [comment]
@arisboch look at the [wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_SITE).

**Comment by RichJeanes** [comment]
@arisboch Would you like to submit a pull request for this site? If not, you can provide the necessary details about it (see [CONTRIBUTING.md](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md)) and we will add it to our list of sites to be added. Please note that this site is maintained by volunteers and it may not be handled immediately.
