### ISSUE TITLE
@2FAorg on Twitter

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1124]
Hi guys!
If you've missed it, we have a twitter account that I created with Josh's permission a while back.
After sharing the password with him I haven't really touched it. If any of you **collaborators** want access to it then email me!
Carlgo11 [AT] carlgo11.com or for those of you who use PGP/GPG: [0x1994E0C6](https://keybase.io/carlgo11/key.asc)

If you have TweetDeck that's preferred over any other client as it's easier to share twitter accounts that way.

Take care!
//Carl

**Comment by Carlgo11** [comment]
No one interested? Okay.
I've seen some of you on twitter so I thought that some of you (like @jamcat22) would be interested.
I'm closing this ticket then.

**Comment by jamcat22** [comment]
@carlgo11 Sorry. Just been very busy recently and haven't had time to fix my PGP key. I'll send you an email today or tomorrow.

**Comment by RichJeanes** [comment]
That Keybase.io site looks awesome. I like the social media key verification thing they've got going on. Much nicer than relying on PGP's standing web of trust if your network of contacts (who actually use PGP) is small.

**Comment by jamcat22** [comment]
@Carlgo11 Just sent you an email.
@RichJeanes Do you want an invite to keybase.io? I have a few.

**Comment by mxxcon** [comment]
I don't know how exactly TweetDeck shares accounts(if it's through its system or stragith up gives you username/password).
I use LastPass for password management and quiet often use its builtin Share feature to send accounts to other people. I can share them with or without disclosing the shared account's password too.

**Comment by jamcat22** [comment]
Maybe we should have a system of 2FA on our Twitter. Either share through TweetDeck (which doesn't use passwords) and enable 2FA for a certain phone on the Twitter, or we could setup a Google Voice number protected by 2FA from Google that protects our Twitter account.

**Comment by RichJeanes** [comment]
@jamcat22 An invite would be awesome. I want to start using PGP more, but starting a web of trust when you don't interact face-to-face with other savvys much (or your relationship is entirely electronic) is difficult.

**Comment by Carlgo11** [comment]
@RichJeanes I sent you an invite

**Comment by RichJeanes** [comment]
@Carlgo11 I got it. Thank you!

**Comment by Carlgo11** [comment]
No problem. Now may I ask why everyone is active today?
I just woke up with >60 unread emails from this project.

**Comment by RichJeanes** [comment]
I had a lot this morning, too. Productive weekend for everyone, I guess. I just decided it was time to do some more house keeping on the issues so I've been trying to close out threads and handle small site add requests. I'm sure that's a fair bit of your notification clutter.
