### ISSUE TITLE
PassBy[ME]: the next generation, two factor authentication solution (developed by Microsec Ltd., Hungary)

### ISSUE THREAD

**Issue by cserbetty** [2factorauth/twofactorauth#1126]
Our state-of-the-art, portable authentication solution is a brand new, next generation solution that can be used in any environment where authenticating the user accesing an online service is highly important. It is a real two-factor technology where both the devices and communication channels are separate. It eliminates the use of SMS and one-time passwords since users can accept or decline the authentication transaction directly on their smart device. 
We would like to be added to the Two Factor Auth Providers' list, please advice which details you may need to do it.

**Comment by mxxcon** [comment]
@cserbetty drop the marking bs hype. You are not selling this to us.
Ask your developers to read https://github.com/jdavis/twofactorauth/wiki/I-want-to-add-a-TFA-provider-to-the-list and https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md

**Comment by RichJeanes** [comment]
You don't need to sell your product to us. TFA.org is just a listing to help users and developers make informed decisions. They are the ones you need to convince.
You (or your development team) are free to submit a Pull Request to suggest the addition of your product. You can view our [CONTRIBUTING documentation](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md) and our [FAQ on adding a provider](https://github.com/jdavis/twofactorauth/wiki/I-want-to-add-a-TFA-provider-to-the-list) for details. Please read through our site documentation and description to get a better understanding of our goals for the site.

**Comment by mxxcon** [comment]
:+1: :smile:

**Comment by cserbetty** [comment]
All right, thank you for the infos.
