### ISSUE TITLE
paypal: nope they don't support 2FA for a Hungarian account

### ISSUE THREAD

**Issue by agroszer** [2factorauth/twofactorauth#113]
The site says:
The Security Key is currently not available. Please try again later.

**Comment by benifei** [comment]
The SMS Security Key isn't available in France (outside the USA?).

**Comment by Vanhouttethomas** [comment]
Neither in Belgium nor The Netherlands; so probably not available in Europe all together?

**Comment by jdavis** [comment]
This is similar to #49. I'm closing it for now.

**Comment by benifei** [comment]
#49 seems to be carrier issues (that affect "small percentage of users"). Paypal does not support 2FA for international customers (i.e. the rest of the world).
