### ISSUE TITLE
Overlap between categories / duplicate entries

### ISSUE THREAD

**Issue by dupuy** [2factorauth/twofactorauth#1131]
I just submitted #1129 to add DigitalOcean to the Cloud providers (as I saw Linode there) and only afterwards did I see that they are already listed under Hosting providers.  Both linode and rackspace are listed in cloud and hosting, and should probably be removed from cloud.

Another duplicate is amazon, which appears in both payments and retail - but those are separate sides of a huge business, so maybe not redundant?

Also while searching for other duplicates, noticed that gocardless (which was maybe moved from developer to payments) still has icons in both.  I'll submit a PR to remove the unused icon from developer.

**Comment by mxxcon** [comment]
Rackspace's cloud business is as big as their physical hosting business. Furthermore, it should NOT be removed because Rackspace's login system to cloud services is separate from physical hosting.

Linode does seem to be a dupe.

So what are you suggesting regarding these categories?

**Comment by dupuy** [comment]
If there are separate login/auth instances for rackspace, listing it separately in both would make sense, I guess, although a link from one to the other might be a good idea (at least as a comment in the YAML source).  Linode is really pretty much a VPS service, though, so should be removed from Cloud.

In the larger picture, it might help to add something in the "Cloud computing" category header that says "(see also Hosting/VPS)" and vice versa, as well as similar cross-linking for Banking <-> Investing and Social <-> Communication, and possibly some one way links for Finance -> Banking, Finance -> Payments.  The basic idea is that if you scroll down and get to some category with services similar to the one you're looking for, but you don't see the one you're looking for, there should be a clue as to another place it might be.

Or, just a simple search box up at the top?

**Comment by mxxcon** [comment]
Well, everybody has CTRL-F...

"VPS" and "Cloud" are pretty broad terms. You say Linode should be vps, yet smack on the home page they say "Cloud Hosting", so your and their definition of vps vs cloud do not match..

**Comment by Carlgo11** [comment]
yup I agree with @mxxcon

**Comment by dupuy** [comment]
I'm fine with moving both Linode and DigitalOcean (as they are pretty much comparable) to the Cloud computing group as well - the point is to eliminate the duplicate Linode entry in one of the categories, since unlike Rackspace, they only have one class of service and one authentication method.

**Comment by mxxcon** [comment]
@dupuy pullrequest welcome. :)

**Comment by jamcat22** [comment]
Closing due to #1251.
