### ISSUE TITLE
StatusPage.io

### ISSUE THREAD

**Issue by kenperkins** [2factorauth/twofactorauth#1133]
Would love to see this added, I have no idea as to the current status of their offerings.

**Comment by RichJeanes** [comment]
We would love to see you contribute to the site! See [CONTRIBUTING.md](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md) and [our wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_SITE). If you're new to using Git, there are tons of tutorials to help you out around the internet!
I would also suggest Tweeting at them asking if they have plans to support TFA (support accounts are often more responsive than primaries if available).

**Comment by kenperkins** [comment]
I'd love to contribute; just swamped with other changes. I'm pretty active on GH but time is finite.

**Comment by RichJeanes** [comment]
@kenperkins I guess I should have checked out your profile before suggesting tutorials. Haha.
