### ISSUE TITLE
Navy Federal Credit Union

### ISSUE THREAD

**Issue by laughingass** [2factorauth/twofactorauth#1135]
Hello twofactor.org friends and compatriots! I'm new here, so please be gentle with me.
Is there a guide for how I can best submit requests or even contribute?
Here's my request to add my credit union to your watch-list for 2FA:
navyfederal.org
Navy Federal Credit Union. Despite its name, it serves all branches of the US military and is the largest credit union in the world. Wikipedia.com, the one-stop-source-of-all-knowlege-known-and-unknown ;) , says, "As of August 2014, Navy Federal had over $60 billion USD in assets, and over 5 million members."
Thank you! Live Long and Verify!

**Comment by Carlgo11** [comment]
Hi @laughingass!
Great! We're always looking for more sites to add!
I recommend you look at [this guide on our wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_SITE).

Feel free to post a comment here if you have any questions.

**Comment by laughingass** [comment]
Hi Carlgo11, thank you for your quick reply. I briefly reviewed the helpful H2G2-style guide. One thing immediately comes to mind, the definition of a word: 

"Vol-unteer. Verb-Noun. Two parts. Vol, meaning to kill ones self, and Unteer, without pay." 

Although I'm very excited about your organizations role in a robust and secure society, I'm afraid to tell you at this point I would not be a good fit, as I would quickly begin to exhibit obsessive-compulsive behaviors typically associated with the more highly productive members of nerd-dumb. My doctor has me in remedial treatment for several years now, and I'm happy to report remission is a word he is beginning to admit might maybe possibly exist. I'll keep struggling to convince him. 

In the mean time, but not angry time, is there a way for me to submit an extremely long list of sites I know have 2FA, and one or two that don't, whereupon you add them to your magical list?

Thank you for your ongoing volunteer work and consideration!
