### ISSUE TITLE
Travis Timeouts

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1145]
I think we need to do some reworking on the link checking. We've gotten to the point that we have so many links that they can't all be reliably checked within the Travis timeout window and I don't think sticking `travis_wait` on it is a good idea (though I think it's perfectly fine on `bundle install`).

Is checking all of them every time necessary? Is there a way to check just newly added links? Maybe we could periodically run a script (manually?) to check all if necessary?

**Comment by mxxcon** [comment]
Yes, it would be best to check just the affected URL(s).
Also does our https://github.com/jdavis/twofactorauth/blob/master/Gemfile.lock need to be that big? I imagine quiet a lot of Travis' time is spent installing those gems. Can we decrease their number or be less strict about versions just in case they are already installed on build nodes?(unless build nodes always start empty?)

**Comment by Carlgo11** [comment]
Well that would be rather difficult to setup wouldn't it? I mean there's no way for the script to see what's changed.

And while we're on the topic of html-proofer, I'm thinking we need a way to check if the http links are available as https as well.

**Comment by RichJeanes** [comment]
It can't use any diff info from GitHub?

Didn't someone experiment with HTTPS checks? (@jdavis maybe?)

**Comment by mxxcon** [comment]
How would you automate http vs https check and know if https site is the same as http?
Does any of this help us? http://docs.travis-ci.com/user/speeding-up-the-build/

**Comment by jamcat22** [comment]
OOOOOOOOOOOOO!!!!!!!!!!!!!
What if we cache our dependencies?!?!?!?!?!?!?!
Since we just changed to the container-based architecture, this is now possible for open-source projects like us. (YAY!)

I feel like being enthusiastic today!!! :smile:
[Here's the doc on caching.](http://docs.travis-ci.com/user/caching/)
[Here's the doc on container-based builds.](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)

**Comment by mxxcon** [comment]
@jamcat22 It's already in our `.travis.yml`

**Comment by jamcat22** [comment]
Oh. So it just wasn't doing anything until now?

**Comment by mxxcon** [comment]
I added cache line when I added #1237.

**Comment by jamcat22** [comment]
_facepalm_

**Comment by Carlgo11** [comment]
And from what I can tell it isn't working atm

**Comment by jamcat22** [comment]
Wait, don't we overwrite the install step?

**Comment by jamcat22** [comment]
Do we have to use [this](http://docs.travis-ci.com/user/caching/#With-a-custom-install-step) to cache?

**Comment by jamcat22** [comment]
With fbd504598cd40ae3d48592aab369e11a1f046679 and #1312, this issue has been resolved.

Discussion on reimplementing html-proofer or a similar solution should be directed to #1265.
