### ISSUE TITLE
Dynamic list visited pages

### ISSUE THREAD

**Issue by ad-m** [2factorauth/twofactorauth#1163]
I am believe using something like http://lcamtuf.coredump.cx/cachetime/ or http://samy.pl/csshack/ to list pages which person have ever seen can make 2FA more popular.

**Comment by mxxcon** [comment]
How would that make it more popular?
If anything, it will confuse users how the heck that site knows which sites they go to.

**Comment by ad-m** [comment]
It make more popular due easier set up. I do not think, section "Suggested" induce excessive confusing.

**Comment by RichJeanes** [comment]
I think I hate when sites when websites use my browser data to try and do things for me without my permission...

**Comment by Carlgo11** [comment]
Same here
