### ISSUE TITLE
Apple Two factor Authentication update

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1168]
So if you're a tech geek like me you've probably already seen the news.
'[Apple-Craig](https://www.apple.com/pr/bios/craig-federighi.html)' said 5 minutes ago on the #WWDC2015 keynote that Apple have remade their TFA system so that "all devices"(iOS 9 devices I'd guess) support it now.

As I have Apple dev access I'll post updates concerning Apple's TFA solution here.
![WWDC2015 keynote](https://puu.sh/ihgro/aaed4ac342.png)

**Comment by jamcat22** [comment]
Super excited for this! I'll update too as I find new Apple ID enabled sites and check iOS 9 out. I'll also keep [my list](https://github.com/jdavis/twofactorauth/issues/975#issuecomment-74323029) up to date, and hopefully, I won't need it anymore!
