### ISSUE TITLE
Google Auth as a provider?

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1172]
Is this because devs can tie in to Google as an SSO provider? If so, I think we should change the link to something about that, rather than to their page talking about how TFA works.
Also, if that's the case, then we might need to re-evaluate how we view SSO as a TFA implementation in regards to what is already on the site (again?).

**Comment by mxxcon** [comment]
Rich, it's a page where we list both, 2fa clients(like google authenticator app) and FreeOTP and full-on providers like Duo or Symantec.

**Comment by RichJeanes** [comment]
Oh, okay. I didn't realize it was listing clients as well. Being titled "Providers", I think of back-end providers.

**Comment by mxxcon** [comment]
originally it was just clients, but then it expanded
