### ISSUE TITLE
Providers list

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#1209]
Why did you remove the providers list?

**Comment by mxxcon** [comment]
See #1177.

**Comment by RichJeanes** [comment]
That seems pretty conclusive.

**Comment by ghost** [comment]
can i get the list of providers?
I'm working on an article and that list will be of good use to my research.

**Comment by mxxcon** [comment]
@ZeevM3 It's in the git history of that pull request.

**Comment by Carlgo11** [comment]
Here for example, https://github.com/jdavis/twofactorauth/blob/5f2aa495dfc176dbf8042594a31086ca1ef8ca17/_data/providers.yml

**Comment by kunala** [comment]
I feel like the page was quite useful in comparisons, even in consideration of some of the annoyances. Is anyone up for bringing it back?

**Comment by smholloway** [comment]
Nope. Feel free to fork the repo and make twofactorauthproviders.org with providers still intact.

**Comment by mxxcon** [comment]
Perhaps maybe even a topic on http://www.slant.co would be a better place. There each provider could list as many advantages/disadvantages as they want to..
