### ISSUE TITLE
Rackspace TFA is "In Progress"

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#121]
As per http://feedback.rackspace.com/forums/71021-product-feedback/suggestions/1633921-please-provide-2-factor-access-for-the-management it appears that Rackspace is working on a two factor auth and users can send a request for early access.

**Comment by jdavis** [comment]
That's great they are working on it.

However, I refuse to add them to the "progress" status without an acknowledgement that they are seeing the #SupportTwoFactorAuth demand on Twitter ;)

No one gets off the hook that easily =]
