### ISSUE TITLE
make CONTRIBUTING.md's "New Sites" section more descriptive

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1218]
Looks like most people read the CONTRIBUTING.md and entirely skip the Wiki.
While that in itself is a step forward than how it used to be there's stuff that exists on the more-updated wiki than the CONTRIBUTING.md.
Could someone (preferably native English speaking) person update the CONTRIBUTING.md so that it explains what to add when adding a site with TFA and what to add for a site without TFA.

Many thanks!

//Carl

**Comment by jamcat22** [comment]
I'll do this when I get home (in about 30 mins).

Been meaning to do this for awhile. :D

**Comment by Carlgo11** [comment]
great! :smiley:

**Comment by Carlgo11** [comment]
*aheam*

**Comment by jamcat22** [comment]
Sorry. Was stuck on what to do about the exception link thing. I'll just comment it out until @jdavis gets back.
