### ISSUE TITLE
Update semantic-ui?

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1228]
Hello,
While I worked on creating a new section to later add in a PR I noticed that the semantic-ui icons I wanted didn't exist in our version of semantic-ui. Could we update the lib?

//Carl

**Comment by Carlgo11** [comment]
Since Josh isn't here maybe someone else can answer this?
@mxxcon?

**Comment by mxxcon** [comment]
Do you want to just update just missing images or the whole lib? If imagines I think it shouldn't break anything. I don't know js, so no idea about that. :(

**Comment by Carlgo11** [comment]
update the whole semantic-ui version. I tried looking up how to download semantic-ui but I really don't understand how to deploy it.
It was much easier in the 90s. On one used libs to make things look pretty. All just "amazing" gifs.

**Comment by jamcat22** [comment]
How about I just make a branch in my repo, update the whole lib, see what changes we originally made (since we didn't make many) and test it locally?

When I get home in a few hours I would be able to do it.

**Comment by Carlgo11** [comment]
Yeah but I just don't see how to get the necessary files to do so. #noob
