### ISSUE TITLE
PayPal doesn't support SMS (for my account) but only PayPal Security Key

### ISSUE THREAD

**Issue by guyarad** [2factorauth/twofactorauth#124]
Which costs 30$ and is a physical thingie.
My account is Israeli, so it's possible it's related...

**Comment by jdavis** [comment]
It looks like there are other countries that have this too. It first showed up in issue #113.

Like I mentioned there, it is similar to #49, and individual country issues currently aren't on the roadmap.

**Comment by smiley** [comment]
Just a heads up: I'm not even offered that option. (Also from Israel) Going to the security key options just says they aren't available, so it looks like even the proprietary PayPal Security Key isn't supported here anymore.

If PayPal only support the US and a few more countries, why not reflect it on the website? I realize that individual country issues aren't planned at this point, but this is clearly a rest-of-world issue.

**Comment by Carlgo11** [comment]
@smiley #1026

**Comment by smiley** [comment]
@Carlgo11 Ah, got it. Sorry for adding yet another confused comment to the mix.

**Comment by Carlgo11** [comment]
hehe, no worries :wink:
