### ISSUE TITLE
Banks - Lloyds is listed as supported while Halifax is not

### ISSUE THREAD

**Issue by JacksterD** [2factorauth/twofactorauth#1249]
I noticed that under the banking category, Lloyds Bank is listed as supporting 2FA while Halifax is listed as not supporting 2FA.

Both support the same 2FA system for adding new payees or actioning large transfers.

**Comment by mxxcon** [comment]
@JacksterD submit pull request to correct this disparity.

**Comment by Carlgo11** [comment]
Looks like Halifax was added by someone without mentioning this ticket.
Also, [lloydsbankinggroup.com](http://www.lloydsbankinggroup.com/).
