### ISSUE TITLE
[OffTopic] Does Two Factor Authentication Actually Weaken Security?

### ISSUE THREAD

**Issue by rugk** [2factorauth/twofactorauth#1256]
Although it's a bit off topic I think this is a nice read:
https://paul.reviews/does-two-factor-authentication-actually-weaken-security/

IMO it shows quite good that it's also important how the 2FA is implemented. Or that there are at least some 'risks' with 2FA.

**Comment by Carlgo11** [comment]
Yeah we've heard from Paul before.
He has some opinions that doesn't quite match ours.

**Comment by mxxcon** [comment]
A bit of click-bait article title.
He conclues it saying:

> Using 2FA will almost certainly increase security. Not using it however, exposes you to much greater risk and arguably weakens security.
> Like passwords, this is a failing in the methodology, not the method itself.

**Comment by rugk** [comment]
@mxxcon :+1: Yes it's really a bit click bait, but his conclusion is indeed fine.
