### ISSUE TITLE
Hetzner now supports two factor auth

### ISSUE THREAD

**Issue by doppelgrau** [2factorauth/twofactorauth#1261]
An announcement in the customer support forum (http://forum.hetzner.de/wbb2/thread.php?threadid=22478) was made, that hetzner now supports two factor authentication using yubi-key or RFC 6238/TOTP/Google Authenticator.

**Comment by mxxcon** [comment]
@doppelgrau would you like to submit a pullrequest for this?

That forum url requires login, can't read it. :(

**Comment by doppelgrau** [comment]
Pull request created, hope it's ok.
https://github.com/jdavis/twofactorauth/pull/1262
