### ISSUE TITLE
please update RiseUp

### ISSUE THREAD

**Issue by ail1020** [2factorauth/twofactorauth#1263]
SpiderOak does support a form of 2FA: https://spideroak.com/articles/2factor-authentication-to-your-spideroak-account

RiseUp used to support 2FA, but no longer does: https://help.riseup.net/en/email/webmail/2factorauth

**Comment by RichJeanes** [comment]
Would you care to update these yourself? If not, they will go into a queue to be taken care when collaborators have time.

**Comment by mxxcon** [comment]
Regarding SpiderOak see #1052.

**Comment by ail1020** [comment]
I've updated the title to only include RiseUp since SpiderOak is sitting in a half-done limbo for years.

@RichJeanes I'll sure give it a try. No guarantees though.

**Comment by jamcat22** [comment]
Closing due to #1267.
