### ISSUE TITLE
Refactor main.yml

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#127]
Now the list is growing longer and longer, perhaps it's worth refactoring `main.yml` into multiple files for each category or maybe even each entry?
That will make it easier for people to contribute changes without having to constantly resync with upstream...

**Comment by jdavis** [comment]
This is a great idea and I definitely agree. When I first started, I tried having each section (social.yml, finance.yml, etc) a separate yaml file. I ran into a few different constraints that showed up with Liquid (the Jekyll template rendering library).

It is worth revisiting to see if we can get this working.
