### ISSUE TITLE
Charles Schwab Link Broken

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#1270]
As per this Tweet: https://twitter.com/RyanRicketts/status/630821197077307392

**Comment by mxxcon** [comment]
I tried to find a new URL to use but couldn't.
But holy crap are they incompetent. This is not security, this is security theater. Limit passwords to 8 characters. They claim they use EV cert when they don't. They have mixed-content errors all over the place.

This is a lot of hot air https://www.schwab.com/public/schwab/nn/legal_compliance/schwabsafe
I found this page, but no idea if it's still current https://www.schwab.com/public/schwab/nn/pl_help/token_help_faq.html

**Comment by jamcat22** [comment]
First link is total marketing crap. :P

Second doesn't even tell you how to get a token.

If we can't find a link, I'd be happy to create a doc page for it.

**Comment by Carlgo11** [comment]
@jamcat22 speaking of doing stuff... *cough* #1218

**Comment by jamcat22** [comment]
I was waiting for @jdavis to come back and explain the whole exception link thing, but I think I'll just comment it out.

**Comment by Carlgo11** [comment]
There's no doc link that does anything more than mention briefly the token.
I'll create a PR to remove the old link.
