### ISSUE TITLE
Interesting Fork of a Fork

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1277]
https://github.com/Nitrokey/dongleauth
By Nitrokey themselves, none the less.
Though they appear to have forgotten to change the project description...

**Comment by jamcat22** [comment]
So. Many. [Branches](https://github.com/Nitrokey/dongleauth/branches/all).

**Comment by Carlgo11** [comment]
is that even legal? I don't know that much about the MIT license but under GPL\* they can't reuse code if they don't give credit to the original creator (aka Josh I guess?)

**Comment by RichJeanes** [comment]
They do. Look at the very bottom of http://dongleauth.info
Also, looks like they're hosting on the same server as nitrokey.com because that's the cert you get when you try the secure version. Makes sense, I guess, but you'd (or rather I'd) expect at least a redirect.

**Comment by Carlgo11** [comment]
Ah didn't see that they had an actual website yet. And great, if it's a TFA company hosting the site I bet they're super objective! :disappointed:

**Comment by jamcat22** [comment]
@Carlgo11 Well, I'd think they would be. Let's them show how many websites support their authenticators.

More sites using "dongleauth", more money for them.
