### ISSUE TITLE
CMSs

### ISSUE THREAD

**Issue by jobthomas** [2factorauth/twofactorauth#1279]
WordPress (self-hosted) has several options for 2FA.
Added to that: WooCommerce and Sensei as well because of the above.

https://wordpress.org/plugins/tags/2-factor-authentication
https://wordpress.org/plugins/tags/2fa
https://wordpress.org/plugins/tags/two-factor

**Comment by Carlgo11** [comment]
Hi @jobthomas,
although it's true that there's multiple TFA plugins for WordPress it's not something we'll add.
WordPress falls under a category we don't list. Just like WordPress there are programs that adds TFA to OpenSSH. That said we don't list OpenSSH on twofactorauth.org. The same applies to Windows login window, Linux distributions, and OSX.
