### ISSUE TITLE
Steam can be used with other authenticators

### ISSUE THREAD

**Issue by jabbink** [2factorauth/twofactorauth#1280]
For `Steam` the table says that it only works with the official app, but `WinAuth` has the algorithm implemented (and `WinAuth` is open source) so it could possibly be added to other authenticator applications. It doesn't work out of the box though, as Steam does not use the "default" Base10 codes.

More information: https://winauth.com/2015/06/11/steam-guard-mobile/

**Comment by mxxcon** [comment]
Well, we don't list specific clients that support it, so I'm not sure what we can do with this information..

**Comment by jabbink** [comment]
Well, currently the site says it only works with the official client, but any client allowing the encoding to be changed can be used. This case can IMO be compared to the Battle.net 2FA which the site lists without a restriction, but this one also requires you to extract your totp secret in a hacky way and use a client that supports a length of 8 instead of 6 (which many clients don't support).

**Comment by Carlgo11** [comment]
@jabbink Read it again. 
`Authentication on non-phone devices is not officially supported.`

"**Officially**"

```
of·fi·cial·ly
əˈfiSHəlē/
adverb
adverb: officially

    in a formal and public way.
    "next month the election campaign will officially begin"
        with the authority of the government or some other organization.
        "it was officially acknowledged that the economy was in recession"
        in public and for official purposes but not necessarily so in reality.
        "there is a possibility he was murdered—officially, he died in a car crash"
```

As in, there can very well be other apps or programs for authenticating without the official steam mobile app but it's not officially supported by Valve Corporation.

**Comment by mxxcon** [comment]
@jabbink If I remember correctly, the thinking behind that phrasing was that it might not be obvious to people that you need just the regular Steam mobile client to use 2fa, as opposed to a single-purpose 2fa such as battle.net authenticator. People might have been expecting Steam authenticator as a separate app.
