### ISSUE TITLE
Adding XenForo forum software

### ISSUE THREAD

**Issue by rugk** [2factorauth/twofactorauth#1296]
The forum software XenForo has added a built in 2FA support to [it's latest version 1.5](https://xenforo.com/community/threads/two-step-verification-and-security-improvements.99881/).

As it's a forum software so it's a bit difficult to decide whether it's a provider or a website which provides 2FA.
But as you removed the provider list anyway what do you think about adding XenForo? And if you think adding it would be good what do you think which category would it fit best?

**Comment by mxxcon** [comment]
Since not every site will have it enabled, I think it's better if we list sites that do use it.

**Comment by Carlgo11** [comment]
And since we don't add self-hosting software.

**Comment by jamcat22** [comment]
What about #1190?

**Comment by jamcat22** [comment]
Maybe we should add an area of the site that helps developers enable 2FA on local infrastructure?

Been wanting to do that for awhile.

**Comment by Carlgo11** [comment]
meh, it's rather vague. Most 2FA solutions for self-hosted site software are often addons/plugins. It's much harder to know whether they work and are up to date.

btw, am I the only one who's avatar got removed? o.o

**Comment by jamcat22** [comment]
Well why don't we show things that natively support it, link to various plugins for the ones that don't, and encourage the ones that don't natively support it (even if they have plugins) to support it?

**Comment by Carlgo11** [comment]
Well, maybe. Let's bring it up on gitter or slack.

**Comment by rugk** [comment]
> Since not every site will have it enabled, I think it's better if we list sites that do use it.

It's enabled by default (from the forum-owners perspective). :smile: 
It's even not easy to disable it globally (and there were enough [complains about this](https://xenforo.com/community/threads/option-to-disable-2fa-globally.99945/))

So if you really want to list (let's say) 75% of all forums using XenForo then that's also possible of course, but I don't think that's such good. :wink: 
So you can start with https://xenforo.com/community as they of course offer it on their own forum too.

**Comment by rugk** [comment]
@Carlgo11
Any explanation why you're closing this issue?

**Comment by Carlgo11** [comment]
I think I've already explained that. We don't list self-hosting services.
