### ISSUE TITLE
Slack invites

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1302]
Hello everybody,

So as some of you might already know we have a [slack team](https://twofactorauth.slack.com) now.
As I only know a few of the collaborators' email addresses I need everyone else (that's active nowadays) to send me an email so that I can add them.

The following contributors haven't been added yet:
- [x] @smholloway
- [x] @ilyakatz
- [x] @mxxcon
- [x] @dsoegijono
- [x] @mwww
- [x] @computmaxer
- [ ] @zach-taylor

Jacob summarized the use of Slack very well:

> Slack for discussion that is between contributors/people close to the group.
> Gitter for stuff for everyone who cares about the repo.
> Twitter for Twitter stuff.
> Github for Github stuff. 

Hopefully I'll see y'all there :wink: 
(Sorry for the mass ping)

**Comment by computmaxer** [comment]
Mine is *********_@**_********.com

**Comment by Carlgo11** [comment]
@computmaxer thanks. Added!

I removed your email address so that no spam bot will find it.

**Comment by ilyakatz** [comment]
@Carlgo11 i haven't had much time to participate in this, but if you feel that you need someone with my skills, I'll happily contribute on demand. You have my email address

**Comment by Carlgo11** [comment]
Would love to have you there @ilyakatz. Just sent an invite :smiley:

**Comment by michaeldavis-wf** [comment]
Mine is mike.philip.davis@gmail.com

**Comment by dsoegijono** [comment]
@Carlgo11 My email is *********_@**_*******.com

**Comment by Carlgo11** [comment]
Great! Added.

**Comment by Carlgo11** [comment]
Just 2 more people then. @mxxcon?

**Comment by mxxcon** [comment]
@gmail.com

**Comment by jamcat22** [comment]
Just invited you @mxxcon. :smile:

**Comment by Carlgo11** [comment]
Great. I'm guessing this Zach guy isn't active on github at all anymore so I'll just close this ticket now.

**Comment by nicolamattina** [comment]
Maybe this tutorial on how to automate Slack invites can be useful.Take a look:
https://blog.stamplay.com/launch-your-community-with-a-fully-automated-slack-signup-page/
