### ISSUE TITLE
Please add FirstDirect

### ISSUE THREAD

**Issue by piersjones** [2factorauth/twofactorauth#1305]
FirstDirect (a UK bank) supports 2 factor auth...
You use the mobile app to generate a code for the website

**Comment by mxxcon** [comment]
@piersjones would you like to submit a pull request adding it?

**Comment by piersjones** [comment]
Yes please! Apologies if I should have done that, the process is a little unclear

**Comment by Carlgo11** [comment]
@piersjones look at the wiki for help when adding a new site to the list. 
There are 2 guides. One for [sites already supporting TFA](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_TFA_SITE) and one for [sites who don't](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_SITE).

**Comment by Carlgo11** [comment]
Is it different from HSBC's [digital secure key](https://www.hsbc.co.uk/1/2/ways-to-bank/internet-banking)?
I see First Direct is an affiliate of the HSBC group.

**Comment by piersjones** [comment]
I think they're the same process (very similar apps, too) but FirstDirect
is marketed as an separate organisation so it's certainly worth calling out
that they share a common solution.

**Comment by piersjones** [comment]
Also worth noting that HSBC offers both app-based 2FA and a physical
SecureKey device, whereas FirstDirect only offers app-based auth.

**Comment by edmorley** [comment]
> Also worth noting that HSBC offers both app-based 2FA and a physical SecureKey device, whereas FirstDirect only offers app-based auth.

FirstDirect offers both, I've seen a FirstDirect SecureKey in person.

**Comment by Carlgo11** [comment]
Then that's settled. FirstDirect won't be added since HSBC already is.
Thanks for the info @edmorley :smiley:

**Comment by mxxcon** [comment]
@Carlgo11 I disagree. They are different banks. Just because you have HSBC account, doesn't mean you have FirstDirect account.

**Comment by piersjones** [comment]
@mxxcon Very true - when you're shopping for a bank account it's not immediately obvious that they are affiliated! I think even if it doesn't have its own entry, it should be noted next to HSBC.

**Comment by MaplesThroughWindows** [comment]
Hi,

I notice that First Direct still isn't on the list anywhere, either on its own or in the HSBC entry.  I'm requesting that someone add a pull request for this (and I'm afraid it won't be me; please see my first post [here](https://github.com/2factorauth/twofactorauth/issues/1514)).

As pierjones said above, HSBC and First Direct are marketed as entirely separate organisations, with only careful research linking the two, so each should be represented on the list in some way.
