### ISSUE TITLE
OpenSRS - no 2FA support

### ISSUE THREAD

**Issue by DanielSwain** [2factorauth/twofactorauth#1311]
OpenSRS is a registrar and should be listed in the Domains section.  They had a security breach a couple of weeks ago:
https://opensrs.com/blog/2015/08/security-update/

and have been contemplating 2FA since 2009:
https://forum.opensrs.com/viewtopic.php?f=8&t=194

They still don't support 2FA.  I think they should be listed under Domains and their lack of 2FA noted.

**Comment by mxxcon** [comment]
@DanAtShenTech would you like to submit a pull request adding it?

**Comment by jamcat22** [comment]
Closed with #1313.
