### ISSUE TITLE
Fidelity 401k now supports 2FA

### ISSUE THREAD

**Issue by j2xl** [2factorauth/twofactorauth#1320]
If you have two-factor authentication enabled for a Fidelity account, logging into retirement accounts at 401k.com (Fidelity's retirement benefits site) now prompts you for your authentication code.

Please remove the note at the bottom of the "How to Setup 2FA for Fidelity" section on /notes/fidelity/.

**Comment by jamcat22** [comment]
Do they use the same login and password system?

**Comment by j2xl** [comment]
Yes. I have the same account for my Fidelity investment accounts (which I've had for 10+ years) and for retirement benefits (401(k) established 1 year ago). I enabled 2FA last October and in the last couple of months I've noticed that it's enforced whether I log in on fidelity.com or 401k.com.

In the past, if I logged in to 401k.com I wasn't prompted for 2FA until I clicked a link that took me to an investment account (link from 401k.com to fidelity.com). Now I'm prompted for 2FA at logon on either site.

**Comment by j2xl** [comment]
In addition, the number to call is now 800-544-6666:

![image](https://cloud.githubusercontent.com/assets/3752878/9834326/33af1d1e-596a-11e5-917c-4eaa88469293.png)

**Comment by jamcat22** [comment]
Great! Thanks for telling us. I'll make a PR in a couple of minutes.

**Comment by j2xl** [comment]
Thank you! I appreciate the quick response.
