### ISSUE TITLE
Is cPanel suitable for addition?

### ISSUE THREAD

**Issue by edmorley** [2factorauth/twofactorauth#1330]
[cPanel](http://cpanel.com/) is used by many shared hosting providers to give people access to their accounts. However it does not currently support 2FA:
https://features.cpanel.net/topic/two-factor-authentication-is-a-must

cPanel isn't a "site" per-se, but software used by many other sites.
I can imagine many of the hosting providers listed on here could (fairly reasonably) answer "yeah we don't support 2FA since cPanel doesn't" - so it would be good to put pressure on cPanel too.

Does it still count for inclusion? I've read https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria but am still not sure.

Thanks :-)

**Comment by edmorley** [comment]
An example cPanel dashboard can be found here:
http://x3demoa.cpx3demo.com:2082/login/?user=x3demoa&pass=x3demoa

**Comment by mxxcon** [comment]
But you've probably also seen https://github.com/steadramon/cpanel_addon-twostepauth
So if stock software doesn't support it, but this feature is available through a plugin, is it a `no` or a `yes`?

**Comment by edmorley** [comment]
Ah I hadn't seen that addon (afaict it's something that only the owner of the cPanel install can set up). In which case this means shared hosting providers don't have an excuse not to use it on their cPanel installs, so having cPanel as it's own entry on this site makes less sense.
