### ISSUE TITLE
FreeDNS.afraid.org?

### ISSUE THREAD

**Issue by Efreak** [2factorauth/twofactorauth#1338]
I'd submit a pull request, but I'm not entirely sure how to explain it. FreeDNS isn't exactly standard 2FA; when I log in from a new email address, I have to click a link in an email they send me to add that IP to the whitelist. This isn't related to a cookie or a 2FA code, it's the IP address I'm logging in from.

**Comment by RichJeanes** [comment]
That seems like a bad way to do it, seeing as most home IPs are dynamic.

**Comment by Carlgo11** [comment]
Does that even qualify as TFA?

**Comment by RichJeanes** [comment]
Well if we have a check box for email... It's just whitelisting IPs instead of browser cookies.

**Comment by jamcat22** [comment]
I'd say it qualifies.
