### ISSUE TITLE
Small UI issue on warning popup (Apple iCloud)

### ISSUE THREAD

**Issue by dsoegijono** [2factorauth/twofactorauth#1353]
<img width="1251" alt="screen shot 2015-10-05 at 2 46 41 pm" src="https://cloud.githubusercontent.com/assets/867840/10275411/66ee39b2-6b71-11e5-8b77-d4e115b4e906.png">

URL doesn't wrap on Chrome/Safari. It works fine on Firefox.

**Comment by jamcat22** [comment]
Closing via #1354.
