### ISSUE TITLE
Steam has added support to factor authentication for phones.

### ISSUE THREAD

**Issue by MCherrey** [2factorauth/twofactorauth#1357]
It is detailed [here](https://support.steampowered.com/kb_article.php?ref=8625-WRAH-9030#whyphone) It is called "Steam Guard Mobile Authenticator"

**Comment by Carlgo11** [comment]
And for that reason Steam is listed as a service with TFA.

**Comment by MCherrey** [comment]
It is not marked as supporting SMS, which it does now.

[image: Inline image 1]

-- Matthew Cherrey

"This isn't freedom. We're holding a gun to every citizen's head and
calling it security." _\- Captain America, The Winter Soldier_

"The easiest way to stop piracy is not by putting anti-piracy technology to
work. It's by giving those people a service that's better than what they're
receiving from the pirates."\* - Gabe Newell, Valve CEO*

"A hero can be anyone, even a man doing something as simple and reassuring
as putting a coat around a little boy's shoulder to let him know that the
world hasn't ended."\* - Batman, The Dark Knight Rises*

"I often compare open source to science. To where science took this whole
notion of developing ideas in the open and improving on other peoples'
ideas and making it into what science is today and the incredible advances
that we have had." _\- Linus Torvalds, C__hief architect of the Linux kernel_

**Comment by MCherrey** [comment]
![image](https://cloud.githubusercontent.com/assets/14442144/10310881/362113ee-6c12-11e5-9051-aa9d496d03e6.png)

**Comment by mxxcon** [comment]
Looking at Steam'sb doc site, unless I'm mistaken, SMS is only used for recovery, not for every day code generation.

**Comment by Carlgo11** [comment]
Indeed.

> You will now be able to reset your password or Steam Guard Authenticator via SMS.

**Comment by jamcat22** [comment]
#1201 and #1203 have more info on this.

**Comment by RichJeanes** [comment]
And on top of that, they don't provide any support for their phone/SMS services. It says my Google Voice number is "invalid" and when I opened a support ticket, they took three weeks to tell me that they don't provide any support. WTF?

**Comment by MCherrey** [comment]
My bad, I didn't realize that the sms function was only for account recovery. Hopefully they will add sms  two-factor authentication support to the login as well.

**Comment by MCherrey** [comment]
Actually, Steam just updated their app, and now allows for you to choose
two-factor for your phone

**Comment by mxxcon** [comment]
@Nightshaxx I am running Steam 2.1.1 and I can't confirm that..

![screenshot_2015-10-15-09-40-15](https://cloud.githubusercontent.com/assets/847140/10515359/157b12c8-7321-11e5-8f38-5780a4e260fa.png)

**Comment by Carlgo11** [comment]
Same on iPhone.
![steam](https://cloud.githubusercontent.com/assets/3535780/10516918/c380bf92-735a-11e5-8213-9ebf29900fb5.jpg)

Steam Mobile v.1.5.6
