### ISSUE TITLE
Column Widths

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1360]
Could we set a minimum width for the site name column so that the "In Progress" button isn't two lines tall? It doesn't look very good and it makes the site longer for no reason.

Also, could we look at text alignment in that column as well? When text runs to the third line (I assume it's hitting a max width? Eg. Boeing Employee Credit Union), could we get it aligned with the other text? I think it would look better and be easier to read.

**Comment by fpigerre** [comment]
Hello @RichJeanes,

I'll take a look and see if I can fix these issues as soon as possible.

**Comment by RichJeanes** [comment]
Awesome! Thanks, @psgs!

I'm okay with the button being aligned with the cell, not the text, since it has its own border to distinguish it and guide the eye.

**Comment by RichJeanes** [comment]
So I just looked at the live site having this merged in and it looks like it did affect the "In Progress" buttons. Whether it just moved them up closer to the text or moved them to be aligned with the right of the logo, I can't say for sure, but I thought they used to be centered in the cell below the logo...?

Also, is it just me, or did it make every row taller, too? Was the top of the text always aligned with the top of the logo?

![alignment](https://cloud.githubusercontent.com/assets/6753081/10432493/364c8198-70c0-11e5-95e3-ebc81e8f6539.png)

I'm sorry. I would be more than willing to help with this, but CSS is the bane of my existence.

**Comment by Carlgo11** [comment]
> CSS is the bane of my existence.

Amen to that!

**Comment by Carlgo11** [comment]
uhm update on this?
@psgs?

**Comment by fpigerre** [comment]
It seems that the text to the right of the logos has shifted up, however, I think that the cell sizes are the same. In terms of the website's design, I don't know how to shift the "In Progress" button so that it fits well aesthetically.
If the "In Progress" button is shifted below the icon and text, the entire row will increase in size, however, if it isn't aligned below the icon and text, the entire column will increase in width.

**Comment by fpigerre** [comment]
This issue has been resolved in pull request #1486.
