### ISSUE TITLE
Maximum column width issues?

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#1366]
Is this new?

![code](https://cloud.githubusercontent.com/assets/6753081/10432848/ce57c0d6-70c2-11e5-8d4c-1345de92fb84.png)

![frank](https://cloud.githubusercontent.com/assets/6753081/10432830/aff5f388-70c2-11e5-82e0-5f61e6c74d8e.png)

![nfn](https://cloud.githubusercontent.com/assets/6753081/10432806/957304d8-70c2-11e5-9883-805d7fca1773.png)
This is why I don't CSS. :laughing:

**Comment by fpigerre** [comment]
This issue has been resolved in pull request #1486.
