### ISSUE TITLE
Schwab 2FA not very good, maybe shouldn't qualify?

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#1375]
I have a Schwab account and visited the twofactorauth site to see if Schwab supported 2FA. Your data says that it does, but then I found this:

http://www.jeremytunnell.com/posts/swab-password-policies-and-two-factor-authentication-a-comedy-of-errors

...which would lead me to believe that their implementation is so shoddy that it shouldn't qualify as having implemented 2FA. Has their implementation changed since this article was written? If not, the site probably shouldn't inform people that Schwab supports 2FA.

**Comment by fpigerre** [comment]
Hello @tonybecker,

Thanks for opening this issue! :+1: 
Information relating to Jeremy Tunnell's blog post has also previously been discussed in issue #914.
Recently, we have had a few problems with Schwab documentation links and customer support.
In light of what are clearly bad security practices and customer support, we will definitely reconsider Charles Schwab's inclusion on [twofactorauth.org](https://twofactorauth.org) as Two Factor Authentication compliant.

Thankyou,
psgs :palm_tree:

**Comment by jamcat22** [comment]
It seems like they have updated their password policies to provide better security. See their new policies [here](http://www.schwab.com/public/schwab/client_home/password_format).

This solves strikes one, three, and four in the article. They now have better password requirements, token activation (while still not the best) has a better likelihood of working, and password parsing is now ok.

**Comment by jamcat22** [comment]
Thanks for making an issue! Feel free to make another issue or PR if something else comes up.
