### ISSUE TITLE
http://twofactorauth.org/favicon.ico is 404

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#138]
http://twofactorauth.org/ does not have a favicon. :)
Which causes each page load to generate 2 404 requests.

**Comment by jdavis** [comment]
The logo at the top is literally just generated from SemanticUI. I used it to make a OpenGraph image and it is located here: http://twofactorauth.org/img/logo.png
![twofactorauth](http://twofactorauth.org/img/logo.png)

We could just turn that into a little favicon.
