### ISSUE TITLE
Joomla (software) now supports U2F

### ISSUE THREAD

**Issue by Vednier** [2factorauth/twofactorauth#1390]
With this set of plugins, actually - https://www.akeebabackup.com/download/yubikey/yubikey-2-0-0.html

**Comment by Carlgo11** [comment]
Hello @Vednier,

Thank you for your interest in contributing to our project.

You can read up on how to contribute via the [Contribute.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) file.

I'll just go over some basic things here which you might find useful.
- The services listed on our site must meet our site criteria which can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria).
- We don't list self-hosted services such as [Wordpress](https://wordpress.org/) or [Drupal](https://www.drupal.org/).
- We only count two factor authentication which protects upon login and not just for 'sensitive actions'.
- Plugins and addons aren't considered as a way of TFA. TFA must be added natively for it to be listed as `tfa: Yes` on our site.
