### ISSUE TITLE
Amazon retail now supports 2fa.

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#1393]
As @clex25 mentioned, Amazon store now supports 2fa. Here are screenshots.
![clipboard01](https://cloud.githubusercontent.com/assets/847140/10893364/647b4a24-8176-11e5-87b7-14cb1cc9de70.png)
![clipboard02](https://cloud.githubusercontent.com/assets/847140/10893365/647b7c92-8176-11e5-800a-a010886d1add.png)
![clipboard03](https://cloud.githubusercontent.com/assets/847140/10893366/647eb6d2-8176-11e5-8062-a7b875d783b6.png)

**Comment by clex25** [comment]
It also supports voice calls and TOTP application. [documentation](https://www.amazon.com/gp/help/customer/display.html/ref=help_search_1-5?ie=UTF8&nodeId=201596330&qid=1446498215&sr=1-5)

**Comment by Carlgo11** [comment]
@clex25 see #1394.
I can't find anything about phone calls.

**Comment by Kallb123** [comment]
Seems to be limited to Amazon.com, or at least isn't enabled on Amazon.co.uk.

Customer services said

> Amazon.com and Amazon.co.uk are independent website and we do business independently. So we have different security policies. So there is nothing to worry about it, your account is safe with us.

**Comment by Carlgo11** [comment]
@Kallb123 #1395

**Comment by Kallb123** [comment]
@Carlgo11 thanks! Apologies for my failed search attempts.

**Comment by Carlgo11** [comment]
No worries.
