### ISSUE TITLE
Fidelity

### ISSUE THREAD

**Issue by hypatia** [2factorauth/twofactorauth#140]
Apparently if you call up fidelity they will set up a Symantec VIP token for you: http://thefinancebuff.com/security-token-fidelity-schwab-etrade.html

Not sure you want to handle that since it's not publicly documented anywhere official, so I filed an issue rather than just adding it myself :)

**Comment by hypatia** [comment]
Here's more documentation of how to do this: http://www.bogleheads.org/forum/viewtopic.php?f=2&t=108267

I've seen reports in some places that they will only do this if you have more than some $ value invested with them, which is pretty wack if true.

**Comment by jdavis** [comment]
That's painful and sad. We could just add Fidelity to the site and maybe they'd get the message that it needs to be improved.

**Comment by hypatia** [comment]
the twitters tell me they do support it kinda sorta: see "transaction security" on this page: https://www.fidelity.com/security/how-fidelity-keeps-you-safe
so it's not 2fa right on login, but close enough for me to feel better :)

**Comment by warmlogic** [comment]
I actually just turned on Fidelity's two-factor authentication yesterday (by calling them), and I have to say that it works well. It really is 2FA on login, as the first link you posted says. You can use the VeriSign VIP Access phone app (iOS and Android), which is the same thing as the "key" icon link for e*trade on http://twofactorauth.org. PayPal and eBay use the VIP Access app as well. No idea about account balances...

**Comment by hypatia** [comment]
@warmlogic so it sounds like if you want the login auth you have to call them, but the transaction auth anyone can get.

**Comment by jdavis** [comment]
We addressed this in #148, thanks for pointing it out, @hypatia!

**Comment by reillyeon** [comment]
The feature is also not available for workplace accounts but you have to call them to find that out.
