### ISSUE TITLE
Twitch now supports TFA

### ISSUE THREAD

**Issue by AdamTReineke** [2factorauth/twofactorauth#1400]
[Blog post about it](http://blog.twitch.tv/2015/11/two-factor-authentication-now-available-on-your-twitch-account/), works via Authy.

**Comment by Carlgo11** [comment]
Added in #1401.

P.S. for the next time you use markdown, it's `[text](URL)` and not the opposite. :wink:

**Comment by jdavis** [comment]
Thanks, Adam! :smile:
