### ISSUE TITLE
Please add UBS AG

### ISSUE THREAD

**Issue by huggi** [2factorauth/twofactorauth#1406]
``` websites:
  - name: UBS AG
    url: https://www.ubs.com/
    img:  https://en.wikipedia.org/wiki/UBS#/media/File:UBS_Logo.svg 
    tfa: Yes
    sms: Yes
    email: Yes
    phone: Yes
    software: Yes
    hardware: Yes
    doc: https://www.ubs.com/global/en/investment-bank/neo-onboarding.html
```

Reference: https://en.wikipedia.org/wiki/UBS

**Comment by Carlgo11** [comment]
@huggi would you like to add the site yourself?
You can read the [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) for info on how to add sites to our list.

**Comment by huggi** [comment]
No, I was customer of that bank a few years ago.

Today I learned about P2P-Payment and http://paymit.namics.com/ which made it to the finals for an award. My favourite (technology wise) banks in Switzerland are using it: UBS, ZKB, but SIX is just another SP which can play man in the middle. 

And that 2FA is important for everyone.

**Comment by RichJeanes** [comment]
Being a former customer means you can't make a PR about it?

Also, that doc link just says that they have 2FA, it doesn't actually talk about what kinds, how to set it up, or how to use it on their site. Is there a doc page more like that?

**Comment by mxxcon** [comment]
I tried to find more info on UBS's 2fa, but haven't found anything useful. :/

**Comment by Carlgo11** [comment]
Yeah same here. I find hardware 2FA but not anything else.
