### ISSUE TITLE
Please update Wealthfront.com - now has MFA

### ISSUE THREAD

**Issue by bmauney** [2factorauth/twofactorauth#1412]
Hi TwoFactorAuth Team,

Apologies if this isn't the right place to log such a request. Quick aside: I love that you all are trying to drive awareness/adoption on this - it's working!

Could you please update Wealthfront.com's status? We now support two-step verification using text message or an authenticator app like Google Authenticator.

We announced support for Two-Step Authentication on our blog here: https://blog.wealthfront.com/secure-wealthfront-accounts-two-step-authentication/

Our FAQs, including step-by-step instructions, can be found here: https://pages.wealthfront.com/faqs/how-do-i-enable-two-step-authentication-on-my-account/

Please let me know if I can provide any additional info.

Thanks,
- Brad

**Comment by RichJeanes** [comment]
That looks great. All the necessary info. If you or someone on your team would like to, you are certainly welcome to submit a Pull Request with the changes. Otherwise it will be updated when one of our volunteer contributors gets to it.
