### ISSUE TITLE
Add Ting

### ISSUE THREAD

**Issue by kevniinvek** [2factorauth/twofactorauth#1415]
ting.com supports
Two factor authentication method 

Authenticator app

SMS (text message)

**Comment by mxxcon** [comment]
@kevniinvek do you have any links to their documentation?

**Comment by kevniinvek** [comment]
the only documentation I can find is a message in the account settings
https://ting.com/account/update_account_info

What is Two-factor authentication?

Two-factor authentication adds another level of security to your Ting
account by requiring you to enter a unique code when logging in from a new
location. This code will be sent to your phone, either in your chosen
authenticator app or via text message.

On Thu, Nov 19, 2015 at 7:36 AM, mxxcon notifications@github.com wrote:

> @kevniinvek https://github.com/kevniinvek do you have any links to
> their documentation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/2factorauth/twofactorauth/issues/1415#issuecomment-158074664
> .

## 

There are 11 types of people. Those who understand Gray Code and those that
don't.
