### ISSUE TITLE
Add Misfit to list

### ISSUE THREAD

**Issue by femaven** [2factorauth/twofactorauth#1416]
name: Misfit
      url: http://misfit.com/
      twitter: Misfit
      img: http://assets.misfit.com/assets/navbar/misfit_logo-7df40e70403439304350c2434330379e.png
      tfa: No

**Comment by fpigerre** [comment]
Hello @femaven,

Thanks for submitting this issue! :+1:
As soon as a contributor is able to, we will look into [Misfit](http://misfit.com) and add it to the repository.
If you would like Misfit to be added faster, you may also submit a pull request. Simple and easy to follow instructions may be found on [the wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_SITEhttps://github.com/2factorauth/twofactorauth/wiki/FAQ_New_SITE).
If you are new to GitHub, more information regarding forking and pull request can also be found on GitHub's [help page](https://help.github.com/articles/fork-a-repo/).

Thanks again,
psgs :palm_tree:
