### ISSUE TITLE
Please add BMO Canada

### ISSUE THREAD

**Issue by kraymitchell** [2factorauth/twofactorauth#1422]
Please add BMO in Canada.

**Comment by mxxcon** [comment]
what is BMO in Canada? Any links? What category?
If you'd like to, you can submit pull request. It's a simple yaml block with 32x32 png logo.

**Comment by kraymitchell** [comment]
BMO is a bank in Canada. I saw BMO Harris in the list already, but that is there American branches.

I will have to take a look at the code as I don't know yaml currently.

**Comment by Carlgo11** [comment]
#1639
