### ISSUE TITLE
Please add Merrill Edge (Supports 2FA)

### ISSUE THREAD

**Issue by klindek** [2factorauth/twofactorauth#1426]
https://olui2.fs.ml.com/security2/SafePassHelp.aspx

Supports codes sent via SMS or E-Mail.

**Comment by klindek** [comment]
What is an authorization code?

Authorization Code
An authorization code is a one-time number sent to you at log in to provide an extra level of security and help prevent unauthorized access. If you set your security preference to require an authorization code every time, you'll receive a code by text, phone call or email, depending on your preference. You may also be prompted for an authorization code when making certain types of high-risk trades.
You can visit the Security Center at any time to change your login security preference.

What is an authorization code?

Authorization Code
An authorization code is a one-time number sent to you at log in to provide an extra level of security and help prevent unauthorized access. If you set your security preference to require an authorization code every time, you'll receive a code by text, phone call or email, depending on your preference. You may also be prompted for an authorization code when making certain types of high-risk trades.
You can visit the Security Center at any time to change your login security preference.
How you obtain authorization codes

You can get an authorization code online or on a SafePass card.
 Obtain Authorization Code
If you set your security preference to require an authorization code at every login, after you enter your Password, you'll be prompted to send a code to your phone, email or text (depending on your preferred delivery method). You may also be asked to get an authorization code if you make certain types of high-risk trades.
After your service provider has delivered the code, you'll enter the code on the login screen. Codes expire after 10 minutes, but if you need a new one, select "Resend code."
Please note: If we don't have your contact information on file or if you've recently changed your information, you may not be able to request a code online. You'll need to call us for assistance.

I believe you can still obtain a Safe-Pass card as well for a one-time fee.

**Comment by mxxcon** [comment]
@klindek your link is behind a login. Is there some publicly accessible link?

**Comment by klindek** [comment]
I don't think so, I will look. That is why I copied and pasted the contents of the help page for the feature.

**Comment by jamcat22** [comment]
This issue has been resolved via #2275 and #2287.
