### ISSUE TITLE
PayPal 2FA information incorrect / inaccurate?

### ISSUE THREAD

**Issue by jwmann** [2factorauth/twofactorauth#1434]
I'm using Canadian Paypal but it does not seem to offer Software Tokens anywhere.

I do have the option for SMS and Hardware Tokens

Can anyone else confirm?
Thank you.

**Comment by mxxcon** [comment]
If I remember correctly, paypal uses Symantec's vip system. Can't you just install their app...and do some magic to add it?...(never used it so don't know how exactly it works.)

**Comment by Carlgo11** [comment]
I recommend talking to [@AskPayPal](https://twitter.com/askpaypal)

**Comment by jamcat22** [comment]
@jwmann I created a tutorial below for you to try. Let me know if it works so I can add it to #1026!
- First, sign in to PayPal, and go to your account security settings.
  ![screenshot_112715_091307_pm](https://cloud.githubusercontent.com/assets/1897053/11450056/a8e3c4c8-954b-11e5-9402-510ff5d612dd.jpg)
- Second, click "Edit" next to "Security key".
  ![screenshot_112715_091709_pm](https://cloud.githubusercontent.com/assets/1897053/11450069/3935dbba-954c-11e5-9214-6f0e80ce5669.jpg)
- Third, click on "Get security key".
  ![screenshot_112715_092005_pm](https://cloud.githubusercontent.com/assets/1897053/11450074/a19f461e-954c-11e5-80e7-60e8806ed968.jpg)
- Fourth, click the "Cancel" button.
  ![screenshot_112715_092149_pm](https://cloud.githubusercontent.com/assets/1897053/11450076/df97af88-954c-11e5-8934-16502e80694b.jpg)
- Fifth, click the "Activate" button under "Activate Security Key".
  ![screenshot_112715_092312_pm](https://cloud.githubusercontent.com/assets/1897053/11450083/10fca718-954d-11e5-9b25-fc19d1d6f0d0.jpg)
- Finally, follow the instructions to activate your software/hardware token.

**Comment by jwmann** [comment]
OH okay. Thank you @jamcat22 !

Well that's a very convoluted way / place in order to find that. Nice PayPal..
So it _can_ do Software Tokens but _only_ with the [Symantec VIP access](https://play.google.com/store/apps/details?id=com.verisign.mvip.main&hl=en) app.
I think that would be an important detail to add in your tutorial @jamcat22 for when it gets pulled into master.

Thanks again guys.
