### ISSUE TITLE
Please add Highside as a 2FA Developer

### ISSUE THREAD

**Issue by pieterkoenis** [2factorauth/twofactorauth#1443]
Dear Josh,

Thanks for the great overview of the 2FA landscape. This is really helpful and an eye opener.
We would like to be added as an Developer as we do 500.000 voice and SMS two-factor authentications per day.
See http://highside-telecom.net/two-factor-authentication/ for more information.

Thanks in advance.

Kind regards,
Pieter Koenis

**Comment by mxxcon** [comment]
You are welcome to submit a pull request with that addition.

**Comment by pieterkoenis** [comment]
Great and thanks for your quick reply.
I'll do that as soon as possible.

**Comment by RichJeanes** [comment]
@pieterkoenis Let me just clarify that we list sites that provide TFA as a security measure for the accounts on their own site. We do not list companies that provide services to enable TFA on other sites.
