### ISSUE TITLE
rename Google Auth to TOTP

### ISSUE THREAD

**Issue by hypatia** [2factorauth/twofactorauth#145]
Since it's a standard with widespread support across many clients and servers: http://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm

**Comment by RichJeanes** [comment]
That's a good point, though Google's authenticator app is the most commonly used for TOTP, especially as a mobile app.
There are a few other implementations listed on Wikipedia (http://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm#Client_implementations) 
@jdavis Your thoughts?

**Comment by jdavis** [comment]
I think it would be the most correct. However not the most understandable. Plus there are differences between Authy and Google Authenticator as they follow the standard but have additional features that aren't part of the standard.

**Comment by hypatia** [comment]
I also found it kinda odd to make Authy a top-level column given that it's got much less adoption than say the Symantec or RSA hard/soft tokens.

**Comment by jdavis** [comment]
We are working to add VIP by Symantec to be top level as #37 talks about.

**Comment by hypatia** [comment]
:+1: awesome. thanks for putting up with my nitpicking ^_^

**Comment by jdavis** [comment]
Non-sense!

**Comment by RichJeanes** [comment]
Someone has to worry about the details! Input is appreciated!

**Comment by hypatia** [comment]
glad to help :) my credit union (First Tech) uses VIP, i'll send in a PR for that once the dust settles

**Comment by RichJeanes** [comment]
Look forward to it!
With that I believe we can consider this issue closed?

**Comment by jdavis** [comment]
Yup, closing it is fine.

**Comment by hypatia** [comment]
works for me!
