### ISSUE TITLE
Information disclosure concern - "Tell them to support 2FA" option

### ISSUE THREAD

**Issue by litui** [2factorauth/twofactorauth#1450]
While it's a great idea in general, if a user were to only use this feature to notify their own sites it could easily translate to an inadvertent disclosure of a twitter user's affiliations.

Generally-speaking it would take some work to find out what banks a user might be registered with, whether they have cryptocurrencies, where their data is stored. Without at least a note about information disclosure here, this opens the door for a user to disclose that information to a potential attacker on their own. Knowing those sites don't support 2FA additionally reduces the difficulty threshold for a potential attacker.

**Comment by mxxcon** [comment]
How do you think this should be addressed?

**Comment by litui** [comment]
I would notify users of the potential disclosure risk in a note either when clicking the button to use the feature or at the top of the page. "Just a heads up before you do this thing"

**Comment by mxxcon** [comment]
At the same time nothing in the message says that you use that specific service and nothing prevents you from requesting 2fa from services that you do not use..

**Comment by litui** [comment]
Absolutely, which is why I'm not suggesting it be scrapped. The disclosure is about usage patterns and likely use-cases of the tool you have. Aware of your tool as I am, if I were a malicious person I would search someone's twitter history for any notices they may have sent out with your stock messages (which are fine). I'm going to guess it's likely that the average user will typically only opt to notify services they use.  ¯\_(ツ)_/¯  I can't say for sure, that's just what comes to mind as an attack vector.

Again I just suggest informing people of the risk.

**Comment by mxxcon** [comment]
I think this should be phrased very clearly, yet at the same time not so scary that it'll put off users from actually using the site to publicly shame companies.

**Comment by jamcat22** [comment]
I agree with @mxxcon, and also suggest it not be too serious. Maybe something like `"Heads-up! Posting to Twitter could potentially give other people clues to what accounts you have."`

I also think it should be an on-hover message, so it doesn't interrupt the flow of the posting process.

**Comment by Carlgo11** [comment]
Assigned @psgs to this issue as he's our html/css wizard :pray:

**Comment by RichJeanes** [comment]
**bump**

Is this still an issue we are concerned with?

**Comment by fpigerre** [comment]
I've added this issue to the [Site Changes](https://github.com/2factorauth/twofactorauth/projects/2) project and will work on it within the next few weeks 👍

**Comment by kmpoppe** [comment]
I dug up this rather dusty Issue and thought: Let's see what we can do about that 😉.
I've added an "Exception" box (thankfully, all the needed code as already there), to the twitter and facebook-links that has the wording as in @jamcat22 's comment from 14 Dec 2015.
My local jekyll build works just fine and both desktop- and mobile sites behave as expected.
Comments welcome!
// Kai
