### ISSUE TITLE
Abine.com - Blur

### ISSUE THREAD

**Issue by TraderStf** [2factorauth/twofactorauth#1455]
2FA compatible with Google Authenticator.

**Comment by mxxcon** [comment]
Does Blur and DeleteMe use the same account system?
Do you have links to docs about their 2fa implementation?

**Comment by TraderStf** [comment]
https://dnt.abine.com/#help/faq/faq-twoFactor

DeleteMe is only for paying user, can't answer.

**Comment by mxxcon** [comment]
Hmm, https://www.abine.com/deleteme/faq/ does not say anything about 2fa..

**Comment by jamcat22** [comment]
DeleteMe uses a different account system, which does not have 2FA. Same goes for MaskMe.

**Comment by TraderStf** [comment]
A problem for Blur?

**Comment by mxxcon** [comment]
@TraderStf I don't understand your question.

**Comment by jamcat22** [comment]
@TraderStf Nope. Right now Blur is fine, but DeleteMe and MaskMe don't support 2FA.

It might take awhile for a collaborator to add this site, but if you want to try it yourself, make a Pull Request. You can look at the [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE) for more info.

Thanks!

**Comment by Carlgo11** [comment]
Fixed in #1680

**Comment by jamcat22** [comment]
As noted above, this issue has been fixed by #1680 and will be removed from the backlog.
