### ISSUE TITLE
Add Huntington Bank

### ISSUE THREAD

**Issue by rosshashbarger** [2factorauth/twofactorauth#1456]
Please add Huntington Bank as a company that does not use two factor.

Here is their twitter:  https://twitter.com/Huntington_Bank

**Comment by jamcat22** [comment]
Hello @crewgooner!

It may take awhile to get to your issue, and add the site.
If you'd like, you can try adding it yourself by following the instructions on [the wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_SITE).

Have a great day!
