### ISSUE TITLE
Webfaction now supporting 2fa

### ISSUE THREAD

**Issue by gniemetz** [2factorauth/twofactorauth#1462]
Hi!

Webfaction recently added 2fa, look at their documentation at https://docs.webfaction.com/user-guide/control_panel.html#two-step-login

Thanks,
best regards
Gerd

**Comment by mxxcon** [comment]
@gniemetz Feel free to add this site. It's just a simple yaml block.

**Comment by gniemetz** [comment]
@mxxcon the site is already added, but now webfaction supports 2fa with softtoken (since a few days)

**Comment by mxxcon** [comment]
well, then update it with correct info :)

**Comment by gniemetz** [comment]
Did my first pull request, but saul was faster :)
Sorry for the noise
Thanks
