### ISSUE TITLE
List of software/apps for 2FA

### ISSUE THREAD

**Issue by TraderStf** [2factorauth/twofactorauth#1465]
A separate list of (main/famous) software on several platforms to manage 2FA.
Free - Freemium...

'Type' of 2FA supported (don't know if it is my mistake, will check later, yandex uses (OAuth 2.0) does not work with Authy

Google Authenticator - free
Authy (100/month)

You get the idea.

Thanks,

**Comment by Carlgo11** [comment]
Hi @TraderStf,
we used to have a list of TFA providers but decided to remove this.
See #1177 and #1173
