### ISSUE TITLE
Please add electronic medical records (EMRs) and associated web services to the Health section

### ISSUE THREAD

**Issue by brianpierce** [2factorauth/twofactorauth#1474]
Many EMRs are now web based and almost all of them have web portals for patients to communicate with their medical providers.  Few of these seem to offer 2FA and a list for comparing and pressuring them to improve would be very helpful.

https://www.elationemr.com/ does not support 2FA except during the initial signup for its portal http://www.elationpassport.com/

**Comment by mxxcon** [comment]
@brianpierce would you like to create a pull request adding these sites?
