### ISSUE TITLE
RBC Bank (Canada) does use 2FA

### ISSUE THREAD

**Issue by StephenKladich** [2factorauth/twofactorauth#1478]
Hi,

RBC does use 2FA, but it is an optional security measure on a user-by-user basis for both web and mobile. Not sure how to indicate this in the list.

Love this site!

S

**Comment by mxxcon** [comment]
do you have any links to their documentation?

**Comment by StephenKladich** [comment]
Yup here: https://www.rbcroyalbank.com/onlinebanking/signin/signinprotection.html

Basically you have to answer a question after you authenticate with username and password...or am I missing the point on 2FA?

**Comment by jamcat22** [comment]
@StephenKladich That's not two factors. Basically, possible factors are something you know (password), something you have (phone), and something you are (fingerprint).

A password and security questions are both things you know, so it's not 2FA.

**Comment by StephenKladich** [comment]
Ah ok, sorry...I took two factor to mean 2 steps but now I understand each step has to be a different type (have, know, are)

Happy New Year!

**Comment by wangkesen** [comment]
This is actually extremely surprising and ridiculous.

**Comment by wangkesen** [comment]
RBC does not offer 2FA for starts, and also RBC CANADA/US are two different banks.
