### ISSUE TITLE
Please add IBM Bluemix

### ISSUE THREAD

**Issue by Stwissel** [2factorauth/twofactorauth#1482]
They belong into the cloud platform category

PaaS: http://www.bluemix.net/

_(Edit: Removed Softlayer request) by - @Carlgo11_

**Comment by mxxcon** [comment]
softlayer is already there
You are welcome to add bluemix.

**Comment by Carlgo11** [comment]
Added in #1706

**Comment by Carlgo11** [comment]
Added in #1706
