### ISSUE TITLE
PayPal 2FA correction

### ISSUE THREAD

**Issue by ElPumpo** [2factorauth/twofactorauth#1483]
It states that PayPal 2FA is only supported in the US, and some other countries. But it works here in Sweden too. (SMS) Doesn't seem like I can chose other options.

**Comment by jamcat22** [comment]
See #1026, #1434, and try the [guide](https://github.com/2factorauth/twofactorauth/issues/1434#issuecomment-160247325) if you want to enable Software/Hardware 2FA.

**Comment by Carlgo11** [comment]
Can confirm paypal TFA in Sweden does in fact work now. :+1: 

(even though there's a 50% chance the page to add TFA loads)

**Comment by ElPumpo** [comment]
I donno, just wanted to point things out.
