### ISSUE TITLE
Please add MercadoLivre.com.br

### ISSUE THREAD

**Issue by UnderEu** [2factorauth/twofactorauth#1484]
Add http://mercadolivre.com.br bidding website, it belongs to 'Retail' category.

Supported: Software token (via Authy app)

**Comment by stephengroat** [comment]
https://www.mercadolibre.com/ shows a list of a bunch of seperate mercadolivre sites for different countries.

Do all countries share accounts and have the same software support?

**Comment by sailenicolas** [comment]
Yes @stephengroat, is all the same site. Only shows different articles from country to country. But is all the same in the security section... authy.
