### ISSUE TITLE
Add incapsula.com

### ISSUE THREAD

**Issue by TraderStf** [2factorauth/twofactorauth#1489]
incapsula.com
Email, GA, SMS

**Comment by jamcat22** [comment]
Hello @TraderStf! If you'd like to, you can make a pull request (PR) for this website. Just follow the instructions on the [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE).

For future reference, it looks like the best `doc` link is: https://incapsula.zendesk.com/hc/en-us/articles/204795664-Incapsula-s-Password-Policy

**Comment by TraderStf** [comment]
nope :) not enough time, sorry,don't blame me, it's my wife
few more
http://help.seagm.com/customer/portal/articles/571328-what-is-2fa-pin-and-how-to-set-it-

**Comment by jamcat22** [comment]
That's ok @TraderStf. At some point in the future, another collaborator will make a PR for Incapsula.

SEAGM's implementation looks to be just a second password, not another factor of authentication. If this site is added in the future, it will be marked as not supporting 2FA.

**Comment by TraderStf** [comment]
zonomi.com free dns host
TOPT (google auth)
https://zonomi.com/app/cp/twofactor.jsp

Zonomi lets you enable two-factor authentication on your account by requiring a password on login, as normal, plus an RFC6238 compliant Time-based One Time Password (TOTP) token.

**Comment by mxxcon** [comment]
@TraderStf please open a separate issue for each site otherwise things will get lost.
