### ISSUE TITLE
Blizzard Authenticator Token? (Key icon)

### ISSUE THREAD

**Issue by nelsonjchen** [2factorauth/twofactorauth#150]
While scrolling down the page I saw no services that have WP, Android, and iOS _and_ a physical token available. It's usually `or`.

Wait, I'm pretty sure Blizzard does. I was just about to add it and after a few moments of googling, I realize this:

All the links to Blizzard's store to purchase the authenticator are dead. It's still supported but a link to purchase one isn't available.

Any thoughts? Should this be added at all? If so, what should it link to?

**Comment by RichJeanes** [comment]
On the page describing the Authenticator: https://us.battle.net/support/en/article/battlenet-authenticator
The first paragraph under "Basics" provides a live link to purchase a physical authenticator token.

**Comment by RichJeanes** [comment]
But that's a good point. Their physical authenticator token is missing from the page. I'll make sure and add that. Thanks for the spot! :thumbsup:

**Comment by nelsonjchen** [comment]
Hah, that's a trip. If you select `Physical`, you won't get a working link. Good spotting.

**Comment by RichJeanes** [comment]
Didn't even notice that! Seems like Blizzard is getting a little sloppy with maintaining their older support pages! And they sell it from the Blizzard Gear site, but not in the Battle.net shop. Maybe it's just a bit of a relic from non-smartphone days and they just haven't been paying attention to it.

**Comment by nelsonjchen** [comment]
Anyway, thanks. When the authenticator came out, people have joked that the security was "better than my bank".

**Comment by jdavis** [comment]
I'm pretty sure this has been taken care of. I'm closing it to clean up a bit.

**Comment by nelsonjchen** [comment]
Hmm? I still don't see the token authenticator represented.

**Comment by nelsonjchen** [comment]
The Blackberry version is there though.

**Comment by jdavis** [comment]
Ah, I apologize, I thought it was there. I added it now with d3a135493691f96859cc72762f0aa21c7e911e31, is that better?

**Comment by nelsonjchen** [comment]
Looks good to me.

**Comment by jdavis** [comment]
Awesome. Sorry for the confusion.
