### ISSUE TITLE
Spideroak does support 2FA

### ISSUE THREAD

**Issue by vendion** [2factorauth/twofactorauth#1507]
I would say that saying Spideroak doesn't offer 2FA at all is wrong.  While their client doesn't make use of it, their web site does support it.

The way it's implemented via the web is also a bit odd, if you opt in, you have to request a token from https://spideroak.com/tokenrequest which will trigger a SMS with a six digit token that you then append to your password.

TL;DR: Spideroak kind of supports 2FA, while not perfect and needs a lot improvement saying the company doesn't support it is wrong IMO.  May Be cases like this should have something to indicate partial 2FA support?

**Comment by Carlgo11** [comment]
We'd discussed this with SpiderOak before and come to the conclusion that we don't think it qualifies as TFA if it's only available on some clients.

**Comment by mxxcon** [comment]
@vendion You can search our issues for historic discussions of spideroak support..

**Comment by vendion** [comment]
@mxxcon The only issue I found that has anything of value is #1052 where you state `That blog post is 4 years old...are they "still" working on 2fa in other regions? :-1:` not very informative and also a reason why I suggested adding something to mark partial 2FA support.

**Comment by Carlgo11** [comment]
https://github.com/2factorauth/twofactorauth/pulls?q=Spideroak
