### ISSUE TITLE
Please update Pogoplug

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#1508]
According to http://support.pogoplug.com/hc/en-us/articles/204553760-What-s-the-difference-between-Pogoplug-Business-Backup-and-Pogoplug-Personal-or-Family-Backup-

> Pogoplug Business Backup is purpose-built for business and includes additional security measures like 2-factor authentication, business-focused performance improvements and prioritized support.

However, I have been unable to find any more detailed info on what exactly their 2fa features are. I'm contacting their support to see if they have anything else.

**Comment by Carlgo11** [comment]
Just out of curiosity, did they ever reply?

**Comment by mxxcon** [comment]
Pinged their support again..

**Comment by mxxcon** [comment]
This is the reply I got

> Thank you for your feedback.
> Such inputs are important as we strive to consider users suggestions while developing future versions, services and products.
> This is now being forwarded to our product development team.

A non-answer answer. :confused:. I'll give them a chance to respond again.

**Comment by gingerbeardman** [comment]
This page http://blog.pogoplug.com/?p=3460 (I had to use [google cached version](http://webcache.googleusercontent.com/search?q=cache:blog.pogoplug.com/%3Fp%3D3460&num=1&client=safari&rls=en&strip=1&vwsrc=0)) states:

> This is why we and many other companies have started offering two-factor authentication that sends a secure code to your phone every time you log in

most likely SMS, but not definitive.

**Comment by Carlgo11** [comment]
#2355 closes this issue.
