### ISSUE TITLE
Programmatic Access

### ISSUE THREAD

**Issue by fpigerre** [2factorauth/twofactorauth#1520]
Hello!

In the future, making separate category based .json files accessible, each containing the website data located on [twofactorauth.org](https://twofactorauth.org), might improve programmatic access as well as helping in creating options for users who disable JavaScript.

Such a system could easily be implemented through Jekyll once the new layout has been merged with the `master` branch.
Do you think adding such files to the website would be a welcome enhancement? Could this perhaps be expanded into some form of API without the need for a back-end?

Thankyou,
psgs :palm_tree:

**Comment by mxxcon** [comment]
what kind of use-case would you see with API access?

**Comment by fpigerre** [comment]
Hello @mxxcon,

In some cases, third party websites recommending a certain service may want to display the status of two factor authentication from a reputable source. Otherwise, individual developers or open source projects may want to manipulate the data used on the site in other ways, for example, providing a command-line lookup service of websites supporting two factor authentication.

Furthermore, the implementation of an API could allow us to make other data more accessible, related to information security in general or completely different data, such as the language a website uses (as part of the ongoing internationalisation process).

**Comment by jdavis** [comment]
So this was actually implemented at a very primitive level but nuked with #1575. `data.json` was at least a simple way to access the data programmatically.

**Comment by Carlgo11** [comment]
Oh... Guess we'll revert that then. @jdavis are there any other files we should have kept?

**Comment by jdavis** [comment]
No, I think the JSON file is the only one :smile:
