### ISSUE TITLE
Bank of America correction -- SMS not hardware token

### ISSUE THREAD

**Issue by client9** [2factorauth/twofactorauth#1525]
Thanks for a great project.

Doing a quick scan of banking, I think BOA needs an update.

https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/safepass.go

Appears to the SMS based, not hardware token.

I'm not a BOA user, so I'll let someone else verify.

regards,

n

**Comment by jamcat22** [comment]
Hello @client9,

Bank of America supports the SafePass Card, a credit card sized code generator.

Check their [FAQ](https://www.bankofamerica.com/privacy/faq/safepass-faq.go) under "Do I need to have a Mobile Phone to use the SafePass service?"

Thanks!
