### ISSUE TITLE
HTTP Headers

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1527]
It would be great if we could add HTTP headers such as `X-XSS-Protection`, `X-Frame-Options`, `Public-Key-Pins`, `Content-Security-Policy` etc for twofactorauth.org.
I'm not sure if we're able to do that with gh-pages. Maybe @github/services could answer that?

//@carlgo11

**Comment by mxxcon** [comment]
Can we do it with CloudFlare?

**Comment by Carlgo11** [comment]
I don't think so. I just searched for it. If @github/services says it isn't possible I'll try and contact Cloudflare as well.

**Comment by Carlgo11** [comment]
**Update:** CloudFlare only supports custom HTTP headers for their Enterprise customers and @Github/Services still hasn't replied.

**Comment by jamcat22** [comment]
The email I got from GitHub:

> Hello Jacob,
> 
> > Is there any way to set HTTP headers for a GitHub Pages site?
> 
> Currently we don't support this level of control over Pages sites as Pages was never intended to be fully customisable.
> 
> I can add it as a feature request though and it may become possible in the future.
> 
> Regards,
> Daniel
> @danayel
> GitHub Support

**Comment by Carlgo11** [comment]
Okay closing this Issue then.

**Comment by nitrocode** [comment]
Interesting. I was just about to post [securityheaders.io results](https://securityheaders.io/?q=https%3A%2F%2Ftwofactorauth.org&followRedirects=on) as a separate issue when I saw this issue. I didn't realize that github pages don't set these kinds of headers by default.

**Comment by mxxcon** [comment]
Well, the original issue was over 2 years ago. Perhaps since then things improved.
