### ISSUE TITLE
Transportion companies

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1534]
This is more a list for myself than anything but if anyone wants to add a company then feel free to edit this doc.

Transportation-related companies to add:
- [x] American Airlines
- [x] Amtrak
- [x] British Airlines
- [x] Norwegian
- [x] SAS
- [x] Air France
- [x] EasyJet
- [x] RyanAir
- [x] Lufthansa
- [x] DB

**Comment by jamcat22** [comment]
Not all of these companies have been added. I'm going to reopen the issue, until all of the specified companies are added.

**Comment by Carlgo11** [comment]
Thank you very much Jacob! :dollar:

**Comment by Carlgo11** [comment]
All requests done! :smile:
