### ISSUE TITLE
Add A Few Sites

### ISSUE THREAD

**Issue by whatinthenameofgod** [2factorauth/twofactorauth#1541]
Finance - Partners Federal Credit Union - https://partnersfcu.org/
Sadly, they don't support anything.

Gaming - Xbox Live - they support whatever Microsoft account supports

Security - AirVPN, Express VPN, and BolehVPN

Social - Pocket

**Comment by jamcat22** [comment]
Hello @whatinthenameofgod!

Feel free to make a PR yourself if you'd like. Help for this is available on our [wiki](https://github.com/2factorauth/twofactorauth/wiki), and we ask that you only submit one site per PR.

If you don't want to make a PR, another collaborator will make one for you. This could take some time, as we have a long list of backlogged sites at the moment.

Thanks!

**Comment by whatinthenameofgod** [comment]
Thanks! Never used github before, so this was a new adventure. I realize now what you mean by submitting sites per PR. I submitted four in one which I shan't do again now that I know what I'm doing. Any advice on what I did wrong or should change for next time would be helpful! Thanks!

**Comment by fpigerre** [comment]
This issue is affected by issues #1554 and #1553.
