### ISSUE TITLE
Patreon now DOES support 2FA via Google Authenticator

### ISSUE THREAD

**Issue by Hudzen10** [2factorauth/twofactorauth#1545]
currently shows as not supported in list.

**Comment by mxxcon** [comment]
Do you have any links with documentations?

**Comment by fpigerre** [comment]
Hello,

There seems to be documentation mentioning Google Authenticator on [Patreon's Help Center](https://patreon.zendesk.com/hc/en-us/articles/206538086-How-Do-I-Set-Up-2-Factor-Authorization-).
I shall submit a pull request shortly.

Thankyou for opening this issue @Hudzen10! :+1:
