### ISSUE TITLE
Category Sorting Logic?

### ISSUE THREAD

**Issue by whatinthenameofgod** [2factorauth/twofactorauth#1558]
Is there any logic as to the order the categories are sorted? 

Wouldn't alphabetical sorting make more sense?

**Comment by mxxcon** [comment]
It is alphabetical...but vertically... :sweat_smile:
Perhaps we should figure out if it can be made sorted horizontally, @psgs?

**Comment by whatinthenameofgod** [comment]
Ahhhh, that makes sense! But yeah, horizontal sorting would be nicer!

**Comment by fpigerre** [comment]
Hello!

I shall take a look and see if I can ensure that the categories are sorted alphabetically in a horizontal fashion. :+1:

**Comment by jamcat22** [comment]
If they are sorted horizontally, that should also fix the sorting on mobile.
