### ISSUE TITLE
Netcup (Hosting & Domains) supports 2FA

### ISSUE THREAD

**Issue by mipapo** [2factorauth/twofactorauth#1570]
via Softwaretoken
https://www.netcup.eu/
https://netcup.de

**Comment by Carlgo11** [comment]
Hello @mipapo,
I need some more information about what kind of 2FA system they use.

When you say software, what kind of software are we talking about? Google Auth?
Is there some kind of documentation page for setting up 2FA that you could link me to?

**Comment by mipapo** [comment]
@Carlgo11 Of course:
A german instruction is available at http://www.netcup-wiki.de/wiki/Stammdaten_CCP#Zwei-Faktor-Authentifizierung_.282FA.29 

"Softwaretoken" was the wrong word. You just activate the 2FA and get the 2FA Token which you can add to every 2FA app.

**Comment by Carlgo11** [comment]
@mipapo Danke!

Time to take out the little German I know ;)
