### ISSUE TITLE
Duplicate Entries Display on Search

### ISSUE THREAD

**Issue by whatinthenameofgod** [2factorauth/twofactorauth#1571]
Not sure why, but some sites display doubled-up entries when searching?

![etsy_double](https://cloud.githubusercontent.com/assets/16806414/12724758/3f531b24-c8c4-11e5-9967-3e63ea090a3e.png)
![ebay_double](https://cloud.githubusercontent.com/assets/16806414/12724766/47439250-c8c4-11e5-9151-4aef09f547b7.png)

**Comment by mxxcon** [comment]
It seems like only `Retail` category is affected?

**Comment by whatinthenameofgod** [comment]
I think so. I tried to replicate it with other sections, but retail seems to be it for some reason...
