### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#1575]
Hello,
I looked through the files of this repo and found some that I think aren't used anymore. 
I'd like @psgs to confirm this.

**The files are:**
1. [restrictions.html](https://github.com/2factorauth/twofactorauth/blob/master/restrictions.html)
2. [international.html](https://github.com/2factorauth/twofactorauth/blob/master/international.html)
3. [data.json](https://github.com/2factorauth/twofactorauth/blob/master/data.json)

**Comment by fpigerre** [comment]
Hello @Carlgo11,

None of the files you listed above are being used in the current version of the website.
Would you happen to know why [restrictions.html](https://github.com/2factorauth/twofactorauth/blob/master/restrictions.html) was originally created? Was it intended as a centralised list of 2FA exceptions?

Thankyou,
psgs :palm_tree:

**Comment by Carlgo11** [comment]
Okay.
No I have no idea why.
Maybe @mxxcon or @jdavis can answer that?

**Comment by mxxcon** [comment]
For 1password and similar?

**Comment by Carlgo11** [comment]
But how is that different from the exceptions list?

**Comment by mxxcon** [comment]
hmm, seems like `restrictions.html` a vestigial file from something Josh was planning. https://github.com/2factorauth/twofactorauth/commits/master/restrictions.html
I guess it's ok to nuke it

**Comment by mxxcon** [comment]
@psgs 👆

**Comment by jamcat22** [comment]
I'm going to guess that restrictions.html was originally why `link: Yes` was planned. If you added `link: Yes` to an exception, I think it'd link to the page of exceptions.

**Comment by Carlgo11** [comment]
I removed the files and made a branch however it looks like I didn't push it to my fork so I'll have to do that once I get back home.
