### ISSUE TITLE
Self-Hosted Sites

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#1592]
I think we should take care of the issue of self-hosted websites and software.

There are multiple tools that website owners use that support 2FA natively (like Joomla and XenForo), and many that don't (like phpBB). Some have unofficial plugins (like WordPress), but these can be confusing.

Personally, I think we should provide information to website owners about what software natively supports 2FA for it's users, and link to documentation. I also think we should both encourage software that doesn't natively support it to do so, and perhaps also link to available plugins with a disclaimer stating that they are unofficial.

Below is a prior poll:
![Prior Poll](https://cloud.githubusercontent.com/assets/1897053/13025066/d4283e68-d1bc-11e5-8eab-385298f7055c.png)

**Comment by mxxcon** [comment]
What if there are multiple plugins for a given software, such as wordpress, are we going to list them all? What if those plugins have different capabilities, how are we going to list that?

**Comment by jamcat22** [comment]
@mxxcon I was thinking that if we could use another page style for self-hosted sites, then we could have a self-made doc link for those with plugins. It'd explain that the service doesn't natively support it, but link to a page to search results for a plugin, for example.

**Comment by ZacharyDuBois** [comment]
@mxxcon @jamcat22 I was thinking we only display it if the software has it in the core code.

**Comment by mxxcon** [comment]
@ZacharyDuBois So then we'd be punishing projects that by design leave it to external plugins to implement? Why do you think a project with 2fa baked in is better than the one that uses plugins/modules?

**Comment by jamcat22** [comment]
@mxx Most software that only allow plugins on purpose, provide a way for them to hook into the main core (like WordPress or Dokuwiki) officially, as an authentication provider or method. The trouble with plugins is that they're unofficial. For a ton of services, the only plugins available are put behind a pay wall. You also might have malicious plugins.

**Comment by mxxcon** [comment]
@jamcat22 and we list services that provide 2fa only on paid accounts...

**Comment by ZacharyDuBois** [comment]
@mxxcon @jamcat22 That is the issue I see as well. Since they are unofficial and most plugins for MFA become inactive, it is most sensible to punish the creator. For WordPress' case, why is MFA allowed on the .com version but not the .org (self-host) version. Same for ownCloud except IIRC, both versions to not have MFA which is an issue since it is storing possibly sensitive information.

**Comment by Carlgo11** [comment]
Wordpress.com isn't the same as the Wordpress.org organization. Wordpress.com have a completely different authentication system and does provide 2FA.

**Comment by Carlgo11** [comment]
While I personally am against listing self-hosted services on 2fa.org I would also opt for the later option, listing only official extensions or built in factors, if I must choose.

I feel like listing self-hosted products is against the core concept of twofactorauth.org.
If it now comes to listing these sites then we need to have thought through policies on what's allowed and not.
Who wants to make a draft?

**Comment by mxxcon** [comment]
So if a project decides to externalize its authentication modules to plugins they should be punished for that? Coming back to what list, in that case 1pass should be punished as well...

**Comment by jamcat22** [comment]
@mxxcon @Carlgo11 is explaining that the plugins should only be listed if they're official. 1Password isn't really a self-hosted website, as it's app syncs using Dropbox or iCloud, not a central service or a sync engine included with the product. As for 1Password's Teams feature, I think it's up for further scrutiny, especially because [their website](https://teams.1password.com/security/) states that their "Account Key" system is "Better than Two Factor". This entry wouldn't go under a self-hosted sites section though.

I would like to stress that "self-hosted" doesn't include locally run applications, that do not have an account system and aren't designed for other users. That would be another issue for another time.

My main argument for listing self-hosted websites is that it would help site owners make better decisions on how to protect their users, and would allow for the public shaming of the products that don't. This could also help mitigate our issue of listing smaller websites or forums, as people could refer to what software the website is running.

Of course, I do see the argument of not listing those products, as the original aim of this project wasn't specifically to help website owners support 2FA, but I think it might be a useful resource to add.

If the majority of people working on this project don't like the idea, I'm fine with just closing this issue and moving on, but I feel like we need to at least deal with how to handle these cases, instead of just ignoring or rejecting all of them.

**Comment by mxxcon** [comment]
Well, I don't think 2fa implemented as a plugin is such a big negative. It very much depends on a structure of a project. IF we are going to list such apps, I think simply indicating if it's baked in or needs a module/plugin is a better approach.
But then we need to decide what type of apps/projects qualify to be listed, what categories we'd have, etc.

**Comment by RichJeanes** [comment]
> Of course, I do see the argument of not listing those products, as the original aim of this project wasn't specifically to help website owners support 2FA, but I think it might be a useful resource to add.

Isn't this what we tried with listing 2FA providers and ended up killing that page because we were just getting products pitched at us by sales-people? What makes this any different?

**Comment by jamcat22** [comment]
Since it's been over three months, and the general consensus is that we shouldn't list self-hosted sites, I'm going to choose this issue.

**Comment by ZacharyDuBois** [comment]
Aw :(

**Comment by jancborchardt** [comment]
Sorry for commenting on this old thread again – but it just feels a bit off cause Two-Factor Authentication is about security, and so are open source projects you can self-host. (These projects for example also often offer encryption.)

Since wordpress.com and joinmastodon.com are listed, am I right to think that it would actually be fine for every Nextcloud _hoster/provider_ who offers 2FA to be listed? cc @ChristophWurst @Gomez @pierreozoux

**Comment by Carlgo11** [comment]
@jancborchardt wordpress.com also provides other services than blog hosting but yes, I assume a NextCloud provider could be accepted if a company runs it.

I can't give any definitive answer here as there are other criteria we'd have to take in to consideration but feel free to make a PR and we'll take a closer look at it.

As our lists are growing larger and larger it means it's harder for us to maintain them. Therefore we put up criteria such as this one to try and keep a reasonable size to the lists.
With our new rule of at least 200k ranking on alexa.com this self-hosting rule could possibly be removed as I guess that would work just as well as this one. However I feel like this is a topic for a new issue. 

Regarding joinmastodon.org, that site shouldn't be listed here under our guidelines. I'll make a PR to remove it. Thanks for pointing that out!

//Carl

**Comment by jancborchardt** [comment]
@Carlgo11 thanks for the info! I understand the criteria problem from running some directory-type sites as well.

Of course it’s a bummer in this case cause it excludes all of self-hosted open source which does not (or can not) provide a big hosted instance, so it would be cool to maybe adjust the criteria for that specific case and accept the main _project_ site (instead of _product_ site).

**Comment by rugk** [comment]
Despite seeming to have this "unofficial" rule, you did not really document it anywhere: https://github.com/2factorauth/twofactorauth/pull/3550

Also, there are many open questions around the topic anyway. IMHO it just makes not really much sense. See the discussion in the PR for that.
The module thing can be discussed, but IMHO it's easy enough: obviously it has to be somewhat "official", if not maybe just add a orange triangle warning, as you do for others…
