### ISSUE TITLE
Easy/Hard/impossible to reset 2FA

### ISSUE THREAD

**Issue by moviuro** [2factorauth/twofactorauth#1593]
Hi,

I just found this project by pure chance, and it looks like it could also benefit from a new information for each site, being:
- Easy to reset the 2FA settings (press a button, re-configuration is trivial) (Facebook, Google)
- Hard to reset the 2FA settings (you have to de-activate it and re-activate it) (Amazon.com)
- Impossible to reset the 2FA (e.g. OVH.com requires you to enter an app-generated OTP to reset the app-generated OTP; that's physically impossible if you wiped your phone)

Just my 2 cents.
Cheers

**Comment by Carlgo11** [comment]
#1348
