### ISSUE TITLE
Additional sites

### ISSUE THREAD

**Issue by ptretter** [2factorauth/twofactorauth#1603]
Please add WestJet, Air Canada, and Rogers Communications to your list.

**Comment by Carlgo11** [comment]
Hello @ptretter,
could you give us some more detail about the sites or make a pull request yourself?
More details on what's required can be found on [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) or [url wiki](https://github.com/2factorauth/twofactorauth/wiki).
