### ISSUE TITLE
Guidance question: where to put VoIP providers?

### ISSUE THREAD

**Issue by tvierling** [2factorauth/twofactorauth#1607]
Internet telephony / VoIP providers aren't currently anywhere here, and I don't know whether it would be preferred to put them under "Utilities" or "Communication".

It seems like "Utilities" fits the bill better, but given those are all currently more conventional companies such as wireline and wireless carriers, I don't know if the project would prefer VoIP providers to go elsewhere.

(Examples: Callcentric, voip.ms, Vonage, ...)

**Comment by RichJeanes** [comment]
I would say Utilities if they are intended as a landline replacement service (eg. Vonage, Obihai, Ooma).
If they're more in the line of an online service (eg. Skype, Google Voice), then communications.

**Comment by tvierling** [comment]
Hm. Well, it's fuzzy there. Callcentric and voip.ms, for instance, are popular online services that are frequently used with software phones -- but they also provide configuration ability for analog telephone adapters (ATAs) which make the service just like a Vonage or Ooma. (Obihai and others like Grandstream are ATA hardware manufacturers, not service providers, and they connect to VoIP providers at the choice of the user.)

Hence this issue, I'm really not sure what to do with these services.

Maybe the dividing line should be services which fundamentally integrate with the PSTN, such as providing the ability to register E911 service? GVoice is ostensibly a tightly PSTN-integrated service even if it has a rich online interface, but it (like Skype) provides no E911 service. In this case, the qualitative difference could be whether the service _can_ be used directly as a landline substitute (whether by supplied or third-party hardware).

**Comment by mxxcon** [comment]
Lives won't be at risk if you put it in one or the other category..☺

**Comment by tvierling** [comment]
Yeah I know, but I have a handful of these I'd like to propose adding, and as an 'outsider' I'd like to do whatever best fits the spirit of the project.

**Comment by mxxcon** [comment]
It's a very arbitrary decision. As long as info is accurate, either of these categorizes will work.

**Comment by tvierling** [comment]
Thank you, I think this is good enough advice.
