### ISSUE TITLE
Schwab Bank

### ISSUE THREAD

**Issue by Harshmage** [2factorauth/twofactorauth#1611]
Please add Schwab Bank (https://www.schwab.com/) to the list, with Hardware Token as the option.

Note that it must be requested by calling 800-435-4000.

SchwabSafe page that states this is here: http://www.schwab.com/public/schwab/nn/legal_compliance/schwabsafe

**Comment by Carlgo11** [comment]
Hello @Harshmage,
Charles Schwab is already listed on twofactorauth.org.

**Comment by Harshmage** [comment]
Thanks @Carlgo11

Schwab has an investing arm (which is where it's listed now), and a banking one, which is branded Schwab Bank.  But if it's listed already, I'll do a pull and add some notes to its existing entry to reflect the banking aspect and link the docs.
