### ISSUE TITLE
007names.com supports software token 2FA

### ISSUE THREAD

**Issue by dkossenko** [2factorauth/twofactorauth#1624]
Can use Google Authenticator or any other authenticator app

**Comment by mxxcon** [comment]
Would you like to submit a pull request adding it?

**Comment by dkossenko** [comment]
I'd love to.  How do I do that?

**Comment by Carlgo11** [comment]
Hello @dkossenko,
thank you for your interest in our project!

If you want to add the site yourself I can recommend reading our [contribution.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites) file or [our wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE) on the topic.

**If you need any help don't hesitate to ask!**

If you wish not to add this proposal yourself we try and add the sites ourselves however note that we get a lot of requests and the backlog is very big and it could therefor take between one month to up to a year before your proposal is addressed.
Therefor we recommend that everyone who can try and make a PR themselves
