### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by clemenzo** [2factorauth/twofactorauth#1625]
After migrating a Joomla site (3.4.8.) to a new server I cannot use 2FA any more. When trying to enable 2FA the server returns error 500. Help is much appreciated.  Any idea how to fix this?

**Comment by Carlgo11** [comment]
Hello @clemenzo,
This is twofactorauth.org. We are not in any way affiliated with Joomla.
I suggest you contact Joomla's support team instead.
