### ISSUE TITLE
Fitbit supports Google Auth

### ISSUE THREAD

**Issue by anjohnson** [2factorauth/twofactorauth#163]
At least, that's how I login to their site and apps.

**Comment by jdavis** [comment]
Great point. Would you like to do the honors? ;)

**Comment by computmaxer** [comment]
Hmm do you mean Google Auth as in logging in via OAuth like this: ![screenshot](http://content.screencast.com/users/max.peterson/folders/Jing/media/59fd8e81-76d2-44f8-9409-8cdd6f1663b7/00001058.png) or actually two-factor authentication with Google Authenticator? It can be easy to get them confused.

**Comment by jdavis** [comment]
It's just OAuth.

**Comment by jdavis** [comment]
Since this is the case, it isn't actually Fitbit 2FA.
