### ISSUE TITLE
Citibank Australia supports 2FA

### ISSUE THREAD

**Issue by aersida** [2factorauth/twofactorauth#166]
With SMS.  They may also have custom stuff for Android and iThingy by the looks of it.

**Comment by RichJeanes** [comment]
Is it a separate system from the Citibank already listed on the site?
@jdavis This is the second issue I've seen opened for sites outside the US (the other being #147). Not sure what your thoughts are on the internationalization of the site.

**Comment by aersida** [comment]
Hi Rich,

It is a separate system from the US one.  Citibank largely functions as a proper multinational, so each operation in each country has their own system.

Which means that i8n is very much an issue for the site.

I'm assuming that the little key icon means something like an RSA token?  In which case most of the business bank accounts in Australia would show that.  And that raises another question for you, in that a lot of "Business" accounts get higher levels of protection that general "Retail" accounts.  I know that particular distinction is important for me as a small business owner, i.e. I don't care about a bank's Retail accounts, but I do care whether their Business accounts are sufficiently protected.

Regards,
Lee Humphries
lee@md8n.com
+61 411 475 950

**Comment by RichJeanes** [comment]
I think we've added other sites that are specific to certain countries (a recent influx of Canadian banks, I think), so I don't think there's any reason to keep this one of the list.
Anyone care to put together a PR?

**Comment by fpigerre** [comment]
Given that the majority, if not all, of Citibank subsidiaries support Two Factor Authentication through the use of a one-time-pin, accessible either through a mobile application or SMS, it may be worthwhile simply maintaining one Citibank entry on [twofactorauth.org](https://twofactorauth.org).

As can be seen below, Citibank possesses [59 subsidiaries](https://en.wikipedia.org/wiki/Citibank):
![Citibank Subsidiaries List](https://cloud.githubusercontent.com/assets/3946887/10536965/5dafbc80-7432-11e5-9fb2-dbcac8696de0.PNG)

More information regarding Citibank's TFA solutions can be found below:
[Citibank Australia OTP](http://citibank.com.au/otp/)
[Citibank Singapore OTP](https://www.citibank.com.sg/gcb/otherservices/cbpre_2factor.htm)
[Citibank Privatebank Security Token](https://www.privatebank.citibank.com/security_token.htm)
[Citibank UK OTP](https://www.citibank.co.uk/personal/banking/Citibank-Online-Demo/otp/otp-text-guide.htm) (Citibank UK only seems to request a token when performing certain actions, not when logging in, which conflicts with [twofactorauth.org](https://twfactorauth.org)'s [definition of TFA](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions).

**Comment by Carlgo11** [comment]
Closing this ticket as per #1627.
