### ISSUE TITLE
Everlaw Listing (in Other) Incomplete

### ISSUE THREAD

**Issue by aflevin** [2factorauth/twofactorauth#1666]
In #1505, Everlaw was added to the "Other" category. It is listed as offering only email TFA, but the site also offers Software Token authentication. What is the best way to update this? Should I make a PR, or is that something that you would handle on your end?

**Comment by Carlgo11** [comment]
@aflevin Please make a new PR with a `software: Yes` under Everlaw.

**Comment by jamcat22** [comment]
Closing due to #1670.
