### ISSUE TITLE
Add Asana

### ISSUE THREAD

**Issue by aph3rson** [2factorauth/twofactorauth#1669]
Asana (www.asana.com) does not support 2FA, short of using Google to sign in (where your Google account is 2FA enabled).

They can be reached on twitter at @asana.

**Comment by jamcat22** [comment]
Hello @aph3rson!

The fastest way to get a website added is to make a PR. You can find instructions for this on our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_SITE), and we ask that you only submit one site per PR.

If you don't want to make a PR, another collaborator will make one for you after evaluating if it fits the [criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) for a non-2FA website. This could take some time, as we have a long list of [backlogged](https://github.com/2factorauth/twofactorauth/pulls?q=is%3Aclosed+is%3Apr+label%3Abacklog) and [requested](https://github.com/2factorauth/twofactorauth/labels/please%20add%2Fupdate%20site) sites at the moment.

Thanks!
