### ISSUE TITLE
Add Thexyz

### ISSUE THREAD

**Issue by ptoone** [2factorauth/twofactorauth#1671]
Someone emailed me asking to add Thexyz which now supports 2FA. How can I go about adding this? Thank you,

Some links:

http://blog.thexyz.com/2016/02/thexyz-adds-support-for-fido-u2f-and.html

**Comment by mxxcon** [comment]
You can create a new pull request adding your site.
See https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md

**Comment by ptoone** [comment]
Thanks, I think I added it but says I don't have permission to upload thexyz.png file.
