### ISSUE TITLE
Nationwide UK Does Support Hardware Based Auth

### ISSUE THREAD

**Issue by HexChaos** [2factorauth/twofactorauth#1677]
It's now required as part of the internet banking system.

**Comment by Carlgo11** [comment]
Hello @St0rmDev!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefore, we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.
