### ISSUE TITLE
Origin supports some form of custom 2FA

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#169]
I was directed to this website by @OriginInsider: http://help.ea.com/en/article/origin-login-verification-information/

**Comment by joshsleeper** [comment]
Same here. They do email auth for new location logins. Not perfect, but better than nothing.

**Comment by RichJeanes** [comment]
So it's the same as Steam Guard?

**Comment by RichJeanes** [comment]
Looks like this got handled in #179.
