### ISSUE TITLE
Update Skype exception text?

### ISSUE THREAD

**Issue by Xezient** [2factorauth/twofactorauth#1691]
Skype's 2FA is completely pointless, if you sign up with a Microsoft account you just get a Skype account that you can sign in with Microsoft (using 2FA) however you can always still sign in with Skype, which doesn't support 2FA. So even if you have 2FA on your Microsoft account, people can still sign in without 2FA on your Skype account making it pointless. So please remove it from your list.

**Comment by mxxcon** [comment]
I disagree. I think it should still be listed with the caveat that we already have there. Perhaps reword it a bit stronger...

**Comment by jamcat22** [comment]
It is possible to require 2FA by signing up with a Microsoft Account and not creating a Skype password or linking to an existing Skype Name.

That being said, we should definitely reword the notice to make it clearly understandable.
