### ISSUE TITLE
Add link for Fidelity

### ISSUE THREAD

**Issue by jrc** [2factorauth/twofactorauth#1700]
https://www.fidelity.com/security/soft-tokens/faqs

**Comment by mxxcon** [comment]
@jrc does this link cover similar information? https://twofactorauth.org/notes/fidelity/

**Comment by jrc** [comment]
Yes, but isn't it good to include a link to the source?

**Comment by Carlgo11** [comment]
Generally yes but not when we've specially crafted a page describing how their TFA setup works.

**Comment by jamcat22** [comment]
@jrc In addition, that link only mentions the software token, not the hardware one you can get by calling them. I'll go ahead and add the link to their FAQ page on our notes page just for good measure.

Thanks!
