### ISSUE TITLE
Discover Card no longer offers 2FA

### ISSUE THREAD

**Issue by gptril** [2factorauth/twofactorauth#1705]
Please update site.

**Comment by RichJeanes** [comment]
I have a message in to Discover support (I am a card holder) and will update when I hear back, but this appears to be true for the moment. Just logged in to a computer I have never used before without a second factor.

**Comment by RichJeanes** [comment]
This is the response I got from Discover:

> Thank you for the recent question you left on our website regarding your Discover account. I understand your concern and will be happy to provide additional information.
> 
> We currently still utilize a two-factor authentication process which prompts for an identification code that can be sent via email, text message, or phone call.
> 
> The identification code will be used on occasion to verify your identity when your account is accessed online. When you log in to your account, you may be prompted to enter an identification code to verify your identity. You will also find that you may be prompted to enter this code while performing certain tasks online.
> 
> We consider many factors when asking customers to complete the extra authentication step before login. Factors such as the internet connection and IP address are taken into account when deciding whether or not additional authentication is required.  We are unable to disclose all the factors involved for security reasons. Discover continually monitors the security of the credit card environment and will implement various measures to protect our customers and our company.

So they apparently only prompt for a second factor when they think the login attempt might be suspicious and also employ two factor verification.

Correct me if I'm wrong, but we've previously said that if it only sometimes prompts for second factor at login, that does not count as 2FA, right?

**Comment by Carlgo11** [comment]
Yes, that's more of a two step authorization

**Comment by digital-marketing-engineer** [comment]
Is this already resolved?
