### ISSUE TITLE
Teamviewer.com supports 2fa

### ISSUE THREAD

**Issue by fatalicus** [2factorauth/twofactorauth#172]
Teamviewer.com supports 2fa with Google Auth, Authy and others: https://www.teamviewer.com/en/help/399-Welche-Apps-kann-ich-verwenden-um-einen-Sicherheitscode-f-uuml-r-die-Zwei-Faktor-Authentifizierung-zu-erstellen.aspx (no idea why they have that on a german link...)

i'm new to this whole Github thing, so if anyone could add it, that would be nice.

**Comment by RichJeanes** [comment]
Being addressed in #177.
