### ISSUE TITLE
HipChat does support 2FA

### ISSUE THREAD

**Issue by markstos** [2factorauth/twofactorauth#1761]
They support it by allowing Google logins, and Google supports 2FA

**Comment by mxxcon** [comment]
This is not what we consider to support 2fa.
If a service supports login through other services that opens whole other can of worms such as SSO, SALM, other types of federation.
This is something that perhaps we should tackle, but haven't yet. Feel free to search previous issue to see similar discussions.

**Comment by markstos** [comment]
Thanks for the reply. Closing.

**Comment by kaidl** [comment]
I wonder what it means for Loopia for instance, as they "support" 2FA through BankID (swedish login solution). If they are listed, then everyone supporting BankID should be listed as supporting 2FA.

**Comment by Carlgo11** [comment]
@kaidl BankID is a TFA company. Letting people use Google, Facebook, Twitter, Microsoft/Xbox accounts is not TFA as that is not integrated with the site's main login service.
This ticket is assuming that Google-, Facebook-, Twitter-, LinkedIn- logins are the same as Transakt, Authy, "Finansiell ID-Teknik BID AB" (BankID) integrations.

And you're correct, all sites supporting BankID should be listed as supporting TFA. Feel free to make a PR with any additional sites supporting BankID that aren't yet listed on twofactorauth.org.

**Comment by markstos** [comment]
Google has world class security. I don't consider them a second-class login solution to BackID or Authy. 

I have found that I can't consider this 2FA site as a reasonable shopping list of projects that support 2FA, now that I know sites listed on may have a 2FA login option even whey are listed as "No 2FA" here.   A new besides "Yes" and "No" would be helpful to clarify: "Third-party 2FA".

**Comment by kaidl** [comment]
@Carlgo11 thanks for the clarification. I have wondered for a long time. 

Is it only "Mobile BankID" that is counted as 2FA or is "Desktop BankID" also considered 2FA?

**Comment by jamcat22** [comment]
@markstos The issue with your argument, is that most websites that support logging in with Google or Facebook also allow logging in with a password. In this case, 2FA through the 3rd party provider can be easily bypassed, simply by either logging in with a password which has been set, or by resetting the password for an account that has no password set. This is the case with most websites, including your HipChat example. As evidenced by their own [documentation](https://confluence.atlassian.com/hipchat/add-users-from-google-apps-776823485.html), which a screenshot of is attached below, users must create a password, and 2FA isn't enforced through that entry point.
![image](https://cloud.githubusercontent.com/assets/1897053/15622726/111c7cd0-2429-11e6-8281-1a2dd595fb70.jpeg)
For sites that only allow 3rd party login, or give the ability to only login with a 3rd party provider without the ability to reset a password (like HealthVault or signing up for Skype with a Microsoft Account) we list them as having 2FA.

Thanks!
-- Jacob

**Comment by Carlgo11** [comment]
@kaidl I'd say it qualifies.

**Comment by markstos** [comment]
I realized that HipChat only allows Googe logins on their website.

Hipchat is heavily used on mobile, and at least on Android there is _No_
option to login with Google on the Android app.

Considering that using a mobile app with HipChat is normal and expected,
there's therefore _No Option_ to for a user to protect all their HipChat
logins with 2FA, much less for admin to require 2FA-only logins.

Thanks for the discussion. I'm changing my position now to agree that
HipChat should not be included in the list.

On Sun, May 29, 2016 at 5:40 PM, Carlgo11 notifications@github.com wrote:

> @kaidl https://github.com/kaidl I'd say it qualifies.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/2factorauth/twofactorauth/issues/1761#issuecomment-222384440,
> or mute the thread
> https://github.com/notifications/unsubscribe/AABk5ZLFELZxSks-6Bis-2vH6a90IIJTks5qGgfSgaJpZM4IoFVR
> .

## 

```
Mark Stosberg
Senior Systems Engineer
RideAmigos
```

**Comment by Carlgo11** [comment]
@markstos so I can close this ticket?

**Comment by markstos** [comment]
@Carlgo11 This ticket is already closed.

**Comment by Carlgo11** [comment]
oh how stupid of me :smile:
