### ISSUE TITLE
Using Twitter API for travis-ci

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#1812]
I was wondering if there's been any thought in using the Twitter API for the travis ci checks?

I know that when I've been adding sites, my capitalization of twitter names has been severely off at times. There's a pretty easy to use [twitter ruby gem](https://github.com/sferik/twitter) that can return the correct capitalization name for a given twitter user.

The biggest problem would be the API key and OAuth tokens, but I think that those could be taken care of in the travis CI env variables.

My ruby is subpar (to say the least), so this is almost sudo code

``` ruby
twitter_client = Twitter::REST::Client.new do |config|
  # TWITTER* are env variables in travis ci
  config.consumer_key = TWITTER_CONSUMER_KEY
  config.consumer_secret = TWITTER_CONSUMER_SECRET
  config.access_token = TWITTER_ACCESS_TOKEN
  config.access_token_secret = TWITTER_ACCESS_TOKEN_SECRET
end

....
twitter = website['twitter']
begin
  twitter_fetched = twitter_client.name(twitter)
rescue Twitter::Error::NotFound => e
  error("Twitter user #{website['twitter']} not found")
end

if twitter_fetched != twitter && twitter.downcase = twitter_fetched.downcase
  error("#{website['twitter']} is incorrectly capitalized, should be #{twitter_fetched}")
end
```

**Comment by stephengroat** [comment]
Was looking and it seems likes there's no easy way to support travis ci env variables with pull requests and keep them secure (https://docs.travis-ci.com/user/environment-variables/). If anyone has any bright ideas, let me know.

Would be a nice feature to have

**Comment by fpigerre** [comment]
Hello @stephengroat!

Using the Twitter API to check on submitted Twitter handles is an awesome idea :smile:. In the past, we have also looked into providing visualizations of the tweets that have been sent out using [twofactorauth.org](https://twofactorauth.org), but we haven't been able to find a way to access the Twitter API securely, whilst at the same time hosting the website using GitHub Pages.

Perhaps it might be possible to encrypt the necessary API keys so that only Travis CI is able to decrypt and utilize them using Travis CI's [encryption feature](https://docs.travis-ci.com/user/encryption-keys/), however, I don't think this would result in a complete solution encompassing all use cases for the Twitter API.

**Comment by stephengroat** [comment]
If you're looking at client-side options, there's always [embedded search timelines](https://dev.twitter.com/web/embedded-timelines/search). That could be a good start.

Is there any good way to implement travis ci checks that are only accessible by 2factorauth members? Could that be involved in the push to "master?"

**Comment by fpigerre** [comment]
:smile: I had no idea embedded search timelines existed. They do seem like a good way to lookup two factor authentication tweets without requiring an OAuth token or API key. If we combine embedded search timelines with an encrypted API key for Travis CI, we should be able to implement the features we wish to implement that require access to the Twitter API.

**Comment by stephengroat** [comment]
If anyone else wants a preview, here's what it could possibly look like - https://twitter.com/settings/widgets/new/search?query=%23SupportTwoFactorAuth&ref_src=twsrc%5Etfw

**Comment by hassankhan** [comment]
This seems to have already been implemented, should the issue be closed?

**Comment by jamcat22** [comment]
@hassankhan yep! We implement this feature through our CircleCI checks. Thanks for letting us know! I'll close this one out.
