### ISSUE TITLE
Make "Tell them to support 2FA" tweets more constructive

### ISSUE THREAD

**Issue by troy** [2factorauth/twofactorauth#1813]
The current "Tell them to support 2FA" button, which sends a tweet, has a few problems. It:
- implicitly assumes that Web apps have either never heard of 2FA or would benefit from one more otherwise-unrecognized person saying it would be valuable. For nearly all Web apps, that's not the case. Either (a) they've considered 2FA and prioritized it (possibly based on information that the user isn't aware of, like how hard it is to handle edge cases like lost 2nd factor devices), or (b) they're not familiar with 2FA and are so clueless as to be a lost cause (and the person reading their tweets isn't going to change that).
- encourages thinking of the Web app operators as enemies (a "them") to be talked at, rather than as collaborators who are equally concerned about security. The current flow encourages fire-and-forget one-way tweets, not useful two-way conversations.
- puts quantity above quality, because people click many of the buttons - including many services they don't personally use. Example screenshot below. If getting 2FA was as simple as mass-sending the same tweet to every Web service, it would already be implemented 😄  A user sending 25 or 50 canned tweets is the advocacy equivalent of a stereotypically rant-y comment on a local newspaper's comment section: it's someone making themselves feel better.
- omits what would actually be useful: a user's own personal story why 2FA in that app would be particularly helpful to them. In any even halfway-clued company, someone has considered or is considering 2FA. However, it's possible that the product manager is underestimating the impact or overestimating the work, and personal stories, not form-letter tweets, are what would reveal miscalculations ("Oh, I never considered that use case").

So, proposed improvements:
- change the button label and default tweet text to something which invites a two-way dialog. For example, a "Learn more about their plans" button which drafts "Hey, I noticed Service doesn't support 2FA. Could you tell me a little about your thoughts on 2FA?"
- discourage clicking all the buttons. Possible implementations: cap the # of uses of the button per browsing session and/or require the user to type a portion of each tweet (like finishing a sentence) and/or change the button to say "I use Service" so it's clear that the button is meant to be used a few times, not 25 times
- encourage personal anecdotes. This could be an empty portion of a sentence that the user is expected to complete: "I use Service and.." Of the different ways to trade less quantity for more quality, this is my favorite because anecdotes (a) have more impact than canned tweets ever can, and (b) share information (use cases) which might make the Web app re-examine how they prioritized 2FA.

Here's an example of how the current button gets used. This is one of many pages of tweets from the same person:

![tweets](https://cloud.githubusercontent.com/assets/9222/16027849/73f46472-318e-11e6-927e-43a1f0798265.png)

**Comment by fpigerre** [comment]
Hello @troy,

Thanks for the suggestions and for pointing out some of the issues with [twofactorauth.org](https://twofactorauth.org). We shall start re-wording the default tweet text, and working towards encouraging better user interaction with companies. If you have some time and would like to help out, please feel free to submit a pull request :+1: 

Thankyou!
psgs :palm_tree:

**Comment by troy** [comment]
@psgs: My pleasure, and can do. PR sent as #1816.

**Comment by gingerbeardman** [comment]
My thoughts FWIW

I agree that the language could be a lot better, for the reasons Troy mentioned in the OP. 
However, I don't think expecting the user to complete the text of a tweet is going to happen.

I'd be happy to take this on if people think it's a worthwhile endeavour?

How I'd approach it: either A) we have a number of phrases, variations on a theme, and one is picked at random; or B) we generate the text using a small number of rules and changeable words.  I've written a similar generator before, based on an early 1950s computer algorithm: https://github.com/gingerbeardman/loveletter/

Having a variety of phrases ticks a couple of important boxes for me: 1) it avoids overfamiliarity with the tweet text. If everybody tweets @ company the same phrase they're just going to tune out and not even read them after a while; and 2) it will make the tweets appear to be more human.

I'd still need help with translations, if/when required.

**Comment by mxxcon** [comment]
@gingerbeardman If this can be achieved within the constraints of our static hosting environment of github-pages, I personally would like to see that.

**Comment by davchana** [comment]
@mxxcon it can be done via javascript array of phrases / phrase-parts; & choosing/building one out of that at random.
