### ISSUE TITLE
Paypal has 2FA support but NOT in the Netherlands

### ISSUE THREAD

**Issue by renini** [2factorauth/twofactorauth#182]
Paypal and Ebay works with Symantec VIP Access 2FA, but unfortunatly PayPal Netherlands does not support this.

I have been frustrated by this for a while already, PayPal is a company that imho should support 2FA. So maybe this should be added as a sidenote that they don't allow 2FA from all countries. :(

**Comment by Techbrunch** [comment]
+1 Same thing in France.

**Comment by jdavis** [comment]
We're working on international in #241 so I'll flag it there.

**Comment by renini** [comment]
Oke perfect! Thanks :+1:

**Comment by jdavis** [comment]
Okay right now I have it fixed to only show Paypal SMS 2FA support for the US. Let me know if this is wrong.

Cheers.

**Comment by renini** [comment]
They have 2fa by means of the hardware key and symantec vip app (ios)

Both of which are not working in .nl
No ability to enable, i have contacted them multiple times...
