### ISSUE TITLE
Please add DKB and Mittwald

### ISSUE THREAD

**Issue by malteschlueter** [2factorauth/twofactorauth#1835]
Hello,

i have 2 new companies to add.

Banking --> https://www.dkb.de/
Hosting --> https://www.mittwald.de/

Kind regards
Malte

**Comment by Carlgo11** [comment]
Hello Malte!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by Jawshy** [comment]
I would like to have a go at adding these sites via PRs, but I will need some more information. 

@malte-schlueter: 
Does the bank and hosting site support [two-factor authentication](https://en.wikipedia.org/wiki/Two-factor_authentication)? 
If they do, what type of 2FA do they support (software or hardware token, SMS, email, and/or phone call)?
