### ISSUE TITLE
Add transferwise

### ISSUE THREAD

**Issue by RichyHBM** [2factorauth/twofactorauth#1840]
[Transferwise](https://transferwise.com/) currently only support 2fa via proxy (if you sign in via google/facebook) not if you sign in via an email/password

**Comment by Carlgo11** [comment]
Hello @RichyHBM!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.
