### ISSUE TITLE
Strava does not appear to support 2FA

### ISSUE THREAD

**Issue by jani** [2factorauth/twofactorauth#186]
I suppose this one is for the "Health" section.

I am a Strava user, and have not found any documentation nor settings for Strava that would indicate that 2FA is possible.

I have not found any plans to enable it.

See www.strava.com or app.strava.com.

Their engineering team's Twitter user is @StravaEng and they appear to respond to at least some tweets.

**Comment by jdavis** [comment]
I love Strava. Would you be able to grab a 32x32 icon and add the info? If not, I will get around to it.. Eventually.

**Comment by jani** [comment]
I'm not familiar with Yaml, sorry, and my round tuits are few and far between, which means that my "eventually" is likely to be further into the future than yours, if you meant anything by stating "create an issue on GitHub".

I'm not sure if manipulating this icon:

http://d3nn82uaxijpm6.cloudfront.net/assets/website/mobile/icon-ios-app-525b77fcc05fed032b8379a512bbf974.png

by e.g. making it circular, reducing the colors to 2 instead of 7 and reducing the size, will be considered fair use under US copyright regulations.
