### ISSUE TITLE
Sonic Has Two-Factor Authentication

### ISSUE THREAD

**Issue by matthewmspace** [2factorauth/twofactorauth#1880]
Sent in a pull request a few days ago, but thought I'd send it in as an issue as well. Sonic, the ISP/utility, has two-factor authentication in the style of a code generator, sms, and voice calls: https://wiki.sonic.net/wiki/2-Step_Verfication.

**Comment by mxxcon** [comment]
@matthewmspace You sent a pull request in your own repo rather than this one.. :)

**Comment by matthewmspace** [comment]
Oh. Sorry, I have no idea how to use Github, as I can't code.
