### ISSUE TITLE
Wells Fargo does not support software tokens

### ISSUE THREAD

**Issue by chittti** [2factorauth/twofactorauth#1882]
I am aware of #1582 . Wells Fargo does support Text, Call and RSA SecurID hardware token. But it **does not** support software tokens. I am pretty sure. Anyone who knows how to get 2FA codes using a software token, please show us how to do so. If you look closely at #1582, nowhere does it show an option for software token. 

Thanks.

**Comment by mxxcon** [comment]
Addressed by #1900
