### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by awnumar** [2factorauth/twofactorauth#1883]
Apparently amazon.com has 2fa, while (as far as I can tell) amazon.co.uk does not. There was a suggestion in another issue that 2fa can be enabled by enabling it on AWS, but this isn't clear. Also, a distinction should be made between Amazon US and Amazon UK.

**Comment by mxxcon** [comment]
I'm not sure if distinction should be made between US and UK since both sites use the same accounts.
However, I do see the need for an 'exception' to mention that 2fa can be enabled (only?) from `.com` site and not `.uk`(or all others)

**Comment by awnumar** [comment]
So apparently 2fa can be enabled on amazon UK by logging into amazon US and enabling it there.
