### ISSUE TITLE
Open Classifieds

### ISSUE THREAD

**Issue by neo22s** [2factorauth/twofactorauth#1893]
Using google authenticator.

**Comment by Carlgo11** [comment]
Hello!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by stephengroat** [comment]
should be closed, already includes yclas. See #1899 for details

**Comment by neo22s** [comment]
Hello,

Open Classifieds is a FOSS php script that you need to host yourself, like wordpress.org. Where Yclas its a SaaS that has 2FA for customers to login to use their sites (that also have 2FA), llike wordpress.com.

Not sure if I explained myself properly xD, so yes 2 different stuff ;)

regards
