### ISSUE TITLE
Network Solutions *does* offer 2-factor authentication support

### ISSUE THREAD

**Issue by billcurnow** [2factorauth/twofactorauth#190]
Network Solutions offers 2-factor authentication support via Symantec's VIP Access app.  However, you must contact customer service to get support for 2FA added to your account.  Once you've jumped through the hoops it works quite well.

**Comment by jdavis** [comment]
Awesome. However, to be "green" on 2FA.org, I think it's important that there be no "hoops" to jump through. Security shouldn't be hidden by loops.

**Comment by billcurnow** [comment]
I agree that their implementation is terrible, and that they do not advertise their support of 2FA anywhere on their website, but the fact remains they do support it.  Saying otherwise is just disingenuous.  

If you were to flag their record appropriately there'd be 3 red Xs followed by a green "Call Support" under the custom option.  This should be more than sufficient to demonstrate that they're doing their own thing, which should please the NetSol haters out there.

**Comment by RichJeanes** [comment]
I feel like that would be us going out of the way to support their poor policies. I agree with @jdavis on this one. I think we're better off having a link to Tweet at them until they're more transparent on their practices. Since they already have the system in place, all we'd need to see is some public facing documentation of it. Just a support page. That's it. I don't think that's too much to ask of them.

**Comment by jdavis** [comment]
We've had to make this stand a few different times and we'll stay in the same position: unless a customer can turn on 2FA without contacting support, they won't be in the green on 2FA.org. Most users won't contact support.

Being disingenuous goes both ways here: if the company cares about their users, they'll do all they can to provide adequate security without the "hoops". Having a "hoop" is disingenuous to the progress that customer's deserve and expect.

**Comment by rublon-mw** [comment]
Generally I believe that adding Network Solutions the way that @billcurnow described it would benefit the visitors of TwoFactorAuth.org. Maybe this way we could make some Network Solutions clients aware that they can protect their account with two-factor authentication, even if it's so hard to set up. In the end it's just a custom 2FA solution. On the other hand, there seems to be no official information about this on their website. In that case there is no easy way to check the status of 2FA support at Network Solutions. Like @RichJeanes said, there should be public documentation available for any site that we add to the list.

In the beginning of this year Network Solution introduced some kind of WebLock program:
https://www.networksolutions.com/blog/2014/01/weblock-security-program-information/
http://domainnamewire.com/2014/01/21/network-solutions-auto-enrolls-customer-into-1850-weblock-service/

**Comment by fleish** [comment]
Just an update, Network Solution does *NOT* offer 2FA anymore. From their support department: 

> Sorry to report that the github thread, while correct in 2014, does not reflect our current situation... at this time, we do not offer the 2 factor authentication service.  You may, however, wish to consider our WebLock service -- details are here:  http://weblock.web.com/

It sounds like they want you to pay them to provide their own version of multi-factor authentication. I wouldn't trust this at all. Their website doesn't even have proper HTTPS support (https://weblock.web.com redirects to https://websitedevelopment.com).

**Comment by mxxcon** [comment]
@fleish would you submit a PR updating the current entry?

**Comment by fleish** [comment]
@mxxcon I'm not sure there's anything to update. The current entry shows they don't support it which seems correct.

**Comment by mxxcon** [comment]
oh, so then we are all set 😅 👍

**Comment by billcurnow** [comment]
FWIW, I'm still prompted to enter a 2FA token when I log in to my Network Solutions account.  Now I suppose its possible that I'm grandfathered in or that they're only making this service available to their VIP accounts.

**Comment by fleish** [comment]
@billcurnow I'm not sure if this news makes me hate netsol more or less

**Comment by berksoylu20** [comment]
kaliteli Vip [gold escort](https://www.goldescorthatun.com/)

**Comment by fleish** [comment]
<img width="324" alt="Screen Shot 2021-06-30 at 12 39 52" src="https://user-images.githubusercontent.com/2106430/124021370-5476d200-d9a0-11eb-9d11-fd02538cd6ba.png">

It seems Network Solutions has updated things to at least allow for SMS-based 2FA. Attached screenshot from https://www.networksolutions.com/my-account/account-center
