### ISSUE TITLE
Ebay and Paypal support Verisign VIP

### ISSUE THREAD

**Issue by depasseg** [2factorauth/twofactorauth#193]
https://m.vip.symantec.com/wheretouse.v

![image](https://f.cloud.github.com/assets/3201827/2462393/fc2efd30-af80-11e3-92f3-d9f8ad5270bc.png)

**Comment by sudeepkodavati** [comment]
@depasseg  You can contribute over here #37

**Comment by RichJeanes** [comment]
This is mentioned in #162 but his commits aren't ready to be merged in. If you want to update the site to show this, feel free to submit a PR! Otherwise it will be gotten around to eventually.

**Comment by depasseg** [comment]
I'd love to contribute, but the process is beyond my comprehension right now.

**Comment by jdavis** [comment]
I've updated the [README](https://github.com/jdavis/twofactorauth/blob/master/README.md#new-sites) to show the field for Verisign. @depasseg All you need to do is add the `verisign: Yes` line to any sites that have Verisign VIP and it'd work!

**Comment by sudeepkodavati** [comment]
If we enable verisign: Yes, do we still have to point to the play store and app store?

**Comment by jdavis** [comment]
For the Verisign VIP app? Is that what you mean?

**Comment by sudeepkodavati** [comment]
@jdavis Yes for Verisign VIP app.

**Comment by jdavis** [comment]
Nope, since there is a column for it, the apps shouldn't have to be linked
to.

**Comment by authsecure** [comment]
All references to Verisign should be changed to Symantec.  Symantec purchased the authentication assets of Verisign years ago.  It is now Symantec VIP.

**Comment by gboudreau** [comment]
Made a PR (#213) just to enable VIP for Paypal.

+1 about the name change from VeriSign (Identity Protection) to Symantec VIP (Validation & ID Protection). Might submit a PR for that a soonish.

**Comment by zach-taylor** [comment]
@gboudreau go ahead and submit a PR. closing this one now.

**Comment by gboudreau** [comment]
Of note: my PR was only for Paypal. I don't use 2FA with eBay, so I'm unsure if it is really supported there too.

**Comment by zach-taylor** [comment]
Sorry, I was referring to changing it from Verisign VIP to Symantec VIP

**Comment by gboudreau** [comment]
Yes, I know. I was just mentioning that because this issue was about both Paypal and eBay supporting VIP, and that seemed only half-resolved by my PR (unless someone else changed the eBay data to enabled verisign there too).
