### ISSUE TITLE
Entrust (SSL Vendor) supports 2FA

### ISSUE THREAD

**Issue by billcurnow** [2factorauth/twofactorauth#194]
Entrust, a SSL vendor, requires users of their Certificate Management Service to use  Multifactor Authentication via their app or a pre-printed e-grid.  I believe this service is optional for non-CMS customers.

Details: http://www.entrust.net/certificate-services/cms-authentication.htm

**Comment by ilyakatz** [comment]
@billcurnow would you be able to submit a pull request? let me know if you need any help

**Comment by mxxcon** [comment]
I'll add it.

**Comment by Carlgo11** [comment]
@mxxcon any updates?

**Comment by mxxcon** [comment]
oh my. missed this one :)
