### ISSUE TITLE
Add Weebly

### ISSUE THREAD

**Issue by nathanielbroughton** [2factorauth/twofactorauth#1966]
If you could add Weebly (weebly.com), that would be great! :smile: if you need any more info, please don't hesitate to let me know. :laughing:

**Comment by Carlgo11** [comment]
Hello Nathan,
sure! It might take some time for us to add it though.

We're all volunteers and do this on our spare time and adding suggested sites sometimes takes a very long time (anything from a day to a couple of years).

We therefor encourage people to make the additions themselves in a pull request. More information on how to add a site to the list can be found on our [wiki](https://github.com/2factorauth/twofactorauth/wiki) or [contributing.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).

If you don't want to add a pull request and instead still want us to add it we'll need a little more information.

Does Weebly support two factor authentication?
If so, what kind of 2FA? software? hardware? SMS? email?
If not, do they provide customer support via twitter? If so, under what handle?
And if they don't provide any customer support via twitter, do they have a facebook page or support email address?

//Carl
