### ISSUE TITLE
Box shows up 3 times

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#198]
I think this might have to do with the lowercase stuff that @mpdavis did.

@mwww pointed it out.

**Comment by mpdavis** [comment]
Yeah, this is due to how I am matching names to websites.  Liquid's string manipulation leaves something to be desired.  I'll see if I can figure something out.

**Comment by jdavis** [comment]
Hahha, yup. Liquid is great, it just isn't great for the kind of voodoo that we are doing without using a real plugin.
