### ISSUE TITLE
Blizzard and Google Authenticator

### ISSUE THREAD

**Issue by grawity** [2factorauth/twofactorauth#199]
Blizzard is an interesting one. It has its own authenticator app, but actually uses OATH TOTP behind the scenes. The soft-token signup process has been reverse engineered and you can use the `bna` tool to set up a token, then input the seed key into any OATH TOTP app.

However, it uses 8-digit codes instead of the usual 6-digit, so Google Authenticator doesn't work... But some other apps do – I'm happily using FreeOTP right now. (The standard allows any length, but unfortunately most apps hardcode 6.)

So it has OATH TOTP, but not Google Authenticator. Time to rethink the site's listings?

**Comment by RobFreiburger** [comment]
Way too many steps for most people to deal with. It's easier to encourage Blizzard to allow third-party 2FA apps.

**Comment by jdavis** [comment]
We tried to address issues like this with the new changes in #333.

**Comment by budafuko** [comment]
it wouldn't have been too many steps for me. lol does this still work? i want to limit the amount of authenticators i need lol

**Comment by beerisgood** [comment]
> it wouldn't have been too many steps for me. lol does this still work? i want to limit the amount of authenticators i need lol

take a look at https://github.com/andOTP/andOTP/wiki/Shared-secrets#battlenet
