### ISSUE TITLE
Add coinbase

### ISSUE THREAD

**Issue by bsdlp** [2factorauth/twofactorauth#20]
Coinbase supports:
- [x] authy
- [x] google authenticator
- [x] SMS

I had difficulty finding docs for coinbase 2fa tho.

**Comment by zach-taylor** [comment]
Hi @fly Coinbase was added in this commit: 672c7fbb42a69b43a99c4bb67df1c97a6c418022

**Comment by bsdlp** [comment]
womp, didn't see that :|
