### ISSUE TITLE
Handelsbanken doesn't offer 2FA

### ISSUE THREAD

**Issue by jfjallid** [2factorauth/twofactorauth#2022]
Handelsbanken doesn't implement any kind of 2FA. You can choose to either login via a hardware token or username and password but not the combination.

**Comment by Carlgo11** [comment]
I'm assuming you need to enter some sort of username (such as SSN) to let the system know which hardware token validate.
In this case the SSN would be the 2nd factor (something you know).

**Comment by jfjallid** [comment]
Well you need to enter your person number but since it is a public record I don't think that counts as something you know since everyone knows it or could atleast easily find out
