### ISSUE TITLE
Paypal only offers 2FA for business accounts

### ISSUE THREAD

**Issue by jfjallid** [2factorauth/twofactorauth#2023]
Just got a message from Paypal support that they are only offering 2FA for business accounts and not all accounts. I propose that Paypal should be marked as not offering 2FA with a notice that they do offer it for business accounts.

**Comment by RichJeanes** [comment]
Except I have SMS 2FA on my PayPal account, which is most definitely not a business account. Availability is dependent on where you live, what site you sign up through, etc. You can check out #1026 for an example of the history of what we've tried to deal with in regards to PayPal.

**Comment by jfjallid** [comment]
@RichJeanes Okey, might be that 2FA is not enabled for non-business accounts in Sweden.

**Comment by Carlgo11** [comment]
Can confirm Paypal's SMS 2FA works; Even in Sweden.
