### ISSUE TITLE
CompTIA

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2038]
So, https://www.comptia.org does not have 2FA.

I want to see if https://certification.comptia.org has 2FA, but I haven't gone down the CompTIA rabbit hole (and really don't want to, one worthless piece of paper from (ISC)2 is enough for me).

Can anyone help me confirm that CompTIA doesn't have 2FA? Their help page on their certification website for profile management (https://certification.comptia.org/help/profile-management) doesn't show anything, but I'd like some confirmation from an actual user if possible

**Comment by thegeekkid** [comment]
I have 3 CompTIA certs.  They do not have 2fa, and even something as simple as changing your password is almost impossible to find in their portal.  (It's under "demographics"... I had to search the FAQ to even find it the first time I wanted to change my pw!)

**Comment by stephengroat** [comment]
Thanks for the info @thegeekkid. Do you want to add CompTIA or should I start the shaming?

**Comment by thegeekkid** [comment]
Haha.  Sure... I can add it.  :)
