### ISSUE TITLE
SpiderOak does NOT support 2 Factor Authentication

### ISSUE THREAD

**Issue by sumocomputers** [2factorauth/twofactorauth#204]
SpiderOak does NOT support 2 Factor Authentication.

They rolled it out I think in 2011, and that is one of the reasons why I went with them.  They very soon revoked support for 2FA, and as of my communication with them on March 2014, they still have not reactivated it.  Shame really.

**Comment by RobFreiburger** [comment]
They seem to only support 2FA in the US according to the blog comments.

**Comment by sumocomputers** [comment]
I am in the US.  Here is a response I got from SpiderOak just a few days ago (note the part about 2FA being offline "...at the moment...".  It has actually been offline since 2011:

"This is Adam from SpiderOak support. Thanks for contacting us. 2-factor
authentication is still evolving. The developers are working to make this
accessible to all users (not just those in the US and Canada as at present) and
one of the solutions they are looking at is Google Authenticator. We haven't
been given a timeline when this will be implemented though. The 2-factor system
is offline at the moment, which is why you didn't receive a token. I would
suggest disabling 2-factor authentication for now so you don't get locked out
of your account. If you need help doing that please let me know.

We're very sorry for any inconvenience this has caused you.

Thanks,
Adam"

**Comment by computmaxer** [comment]
This was fixed in #211
