### ISSUE TITLE
torguard.net supports 2FA

### ISSUE THREAD

**Issue by yield65** [2factorauth/twofactorauth#2049]
TorGuard supports 2FA for accessing the client area  on it's web site.
I'm using Authy as the OTP.
https://torguard.net/

**Comment by Jawshy** [comment]
@yield65, do they have any documentation regarding their implementation of 2FA? I briefly checked their [FAQ page](https://torguard.net/faq.php), but I could not find anything.

**Comment by yield65** [comment]
No, they just added a new security section dedicated to their 2FA configuration, when logged in, one can go there select enable 2FA, then the wizard begins showing the QR code and a recovery code.
Very straight forward.
Now, when I log in, I type my username, password and then I'm presented with a text box to enter the code generated with the app, in my case, Authy.
In this page there is a banner sugesting the user to enable 2FA
https://torguard.net/serverstatus.php
