### ISSUE TITLE
Add german bank "Sparkasse"

### ISSUE THREAD

**Issue by beerisgood** [2factorauth/twofactorauth#2058]
Please add the german bank "Sparkasse" to the list with contact stuff like the other banks.
https://www.sparkasse.de
http://www.facebook.com/sparkasse
http://www.twitter.com/sparkasse

**Comment by Jawshy** [comment]
Hi, @beerisgood. Does this bank support 2FA? If yes, could you please link to their documentation.

**Comment by beerisgood** [comment]
Until now i doesn't found 2FA on their documentation so i don't think they support 2FA now.
But maybe they support it if many people contact them.

**Comment by Jawshy** [comment]
Thanks. I will submit a pull request to add this bank.

**Comment by beerisgood** [comment]
Thanks.

**Comment by beerisgood** [comment]
I wonder why i can't find the entry on the homepage, even after ther pull request is finished.

**Comment by stephengroat** [comment]
@beerisgood we have to merge `master` with `gh-pages` to publish, happens every week (or so). it'll be up relatively soon!

**Comment by beerisgood** [comment]
"Sparkasse" is still missing :(

**Comment by stephengroat** [comment]
@beerisgood it's being worked on. since this is a side project for everyone involved, it sometimes takes a little time for us to get the site updated. don't worry, it'll happen

**Comment by beerisgood** [comment]
Alright, thanks! :+1:
