### ISSUE TITLE
Add SmarTrip

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2084]
```
name: SmarTrip
img: wmata.png
url: https://smartip.wmata.com
tfa:no
twitter: wmata
```

![wmata](https://cloud.githubusercontent.com/assets/1159138/19171883/edbfc69e-8bd3-11e6-8a81-8dee4fc2cc20.png)

**Comment by Carlgo11** [comment]
Any reason for not making a PR?

**Comment by stephengroat** [comment]
Made a PR on master, was trying to avoid moving it and hope it would be merged soon.

AKA laziness

**Comment by Carlgo11** [comment]
`git cherry-pick`?

**Comment by stephengroat** [comment]
i know, i was literally trying to avoid opening a new PR since they're tied
to branches. again, never underestimate my laziness

**Comment by kartik95** [comment]
PR #2108 @Carlgo11
