### ISSUE TITLE
Add Zazzle

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2087]
```
name: Zazzle
url: http://www.zazzle.com
img: zazzle.png
tfa: No
twitter: zazzle
facebook: zazzle
```

![zazzle](https://cloud.githubusercontent.com/assets/1159138/19197402/8088f424-8c6e-11e6-9eba-f0515eb8cee4.png)

**Comment by Jawshy** [comment]
www.zazzle.com.au and www.zazzle.co.uk support HTTPS, but www.zazzle.com redirects to HTTP. :confused:

**Comment by Carlgo11** [comment]
What category?

**Comment by stephengroat** [comment]
I was thinking retail? it's basically the same thing as etsy

**Comment by kartik95** [comment]
Added Zazzle to retail.yml
PR #2107
