### ISSUE TITLE
Add Rally

### ISSUE THREAD

**Issue by XSchelin** [2factorauth/twofactorauth#2092]
Site: https://www.rallydev.com/
Status: does not support 2FA
Twitter: https://twitter.com/cainc

**Comment by mxxcon** [comment]
It says that rally is now part of ca technologies. What's going to happen to their login system then?

**Comment by kartik95** [comment]
In which category should I place this company? @Carlgo11

**Comment by kartik95** [comment]
Also, can't find 32X32 image of Rally.

**Comment by stephengroat** [comment]
I think that there's still a question if Rally should be included or if CA Technologies should be included in its place

**Comment by kartik95** [comment]
Since, CA Technologies acquited Rally, I think we should go with CA Technologies imo. @stephengroat
