### ISSUE TITLE
Add northern tool

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2094]
```
name: Northern Tool + Equipment
img: northerntool.png
tfa: No
twitter: NorthernTool
facebook: northerntool
```

![northerntool](https://cloud.githubusercontent.com/assets/1159138/19241968/f0c1c79e-8ec5-11e6-8bb6-d867fb9a2d84.png)

**Comment by mxxcon** [comment]
That's a pretty obscure site...I'd be hesitant to list it.

**Comment by stephengroat** [comment]
Ranks [7,764 on alexa](https://www.domaintally.com/www/northerntool.com)

**Comment by mxxcon** [comment]
Ya...I personally feel there are more higher profile sites to list before we to alexa rank 7764 😄

**Comment by stephengroat** [comment]
I think there probably eventually has to be some sort of automated eval. Look at [Dutch Bros](https://www.domaintally.com/www/dutchbros.com), [Usabilla](https://www.domaintally.com/www/usabilla.com), [Lazada](https://www.domaintally.com/www/lazada.com), etc. the list keeps going (obviously)

having a metric to evaluate sites would make it easy to determine. maybe an override if the site is a dev or admin site that has more power than it seems (dns admin sites, web apis, etc)

**Comment by kartik95** [comment]
Added NorthernTool. PR #2105
