### ISSUE TITLE
Add my.vanguardplan.com

### ISSUE THREAD

**Issue by krogius** [2factorauth/twofactorauth#2096]
Vanguard outsources handling some plans to a different website (without 2fa unfortunately). Not sure if this qualifies as a separate site or a note under vanguard.

**Comment by stephengroat** [comment]
Can you setup TFA like [this doc](https://personal.vanguard.com/us/insights/article/Account-security-092015) explains?

**Comment by krogius** [comment]
No - vanguardplan.com uses its own account database. No 2fa of any kind.
