### ISSUE TITLE
How do I add U2F dongle?

### ISSUE THREAD

**Issue by peca23** [2factorauth/twofactorauth#2097]
Hello,

I haven't found any way how to add a dongle itself. Only services / websites. Is that possible please? I would like to add TREZOR (http://doc.satoshilabs.com/trezor-user/u2f.html).

Thank you for advice and wish you beautiful day!

**Comment by mxxcon** [comment]
This is not what this website is for. We only list services that (don't) use 2fa.
Too many "dongle" manufacturers were abusing our website as nothing but free advertising platform, so we removed them all.

**Comment by RichJeanes** [comment]
@peca23 There is a derivative site based on this site that focuses on hardware dongles, perhaps they would be interested in adding this info to their site.
http://www.dongleauth.info/
http://www.dongleauth.info/providers/

**Comment by peca23** [comment]
Thank you, I have noticed yesterday already I submitted the pull request to the wrong repo:) Sent to them..
