### ISSUE TITLE
Add Any.do

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2114]
```
name: Any.do
url: https://web.any.do/
img: anydo.png
tfa: No
twitter: AnyDO
facebook: Any.DO
```

![image](https://cloud.githubusercontent.com/assets/1159138/19364240/3940852c-9142-11e6-8d77-d5f373420934.png)

**Comment by moritzsternemann** [comment]
To which category should I add it? I didn't find the perfect fit 😄

**Comment by stephengroat** [comment]
`other` sounds good to me
