### ISSUE TITLE
Backup and Sync: AeroFS: Update doc link

### ISSUE THREAD

**Issue by Jawshy** [2factorauth/twofactorauth#2134]
The [`doc`](https://blog.aerofs.com/two-factor-authentication-for-hybrid-and-private-cloud/) link for [AeroFS](https://www.aerofs.com/) returns `ERR_EMPTY_RESPONSE`. 

Need to find the latest documentation link then update [backup YAML file](https://github.com/2factorauth/twofactorauth/blob/4eeca58ec11f73154c50aa133602879c66a58981/_data/backup.yml).

**Comment by stephengroat** [comment]
`gh-pages` and `master` out of sync
