### ISSUE TITLE
Filter for sites that support Google Authenticator

### ISSUE THREAD

**Issue by febLey** [2factorauth/twofactorauth#2148]
I'd love a filter to just display sites that support the Google Authenticator.

Related to this one:

https://github.com/2factorauth/twofactorauth/issues/521

**Comment by RichJeanes** [comment]
There is no way to do that with 2FA.org. We do not distinguish between different software implementations. So while many of the sites listed with a Software check mark support Google Authenticator (more broadly, TOTP), many of those sites are also limited to other software based services, such as proprietary applications or commercial products such as Authy.
