### ISSUE TITLE
Fidelity has added SMS two-factor authentication

### ISSUE THREAD

**Issue by isidle** [2factorauth/twofactorauth#2154]
Well, they call it "two-factor" but it's more "two-step" - to quote their [page](https://www.fidelity.com/security/how-two-factor-authentication-works)

> You will get a security code to verify your identity when you **perform** _highly sensitive transactions_ such as setting up new bankwire instructions or changing your contact information

So, you don't need it to get into the account but when you are doing something "sensitive" it kicks in.

I'm new to this community, so I'm not sure if this would quality or not.

**Comment by fpigerre** [comment]
Hello @isidle,

Thanks for finding that documentation link! :+1: 
It seems that Fidelity's current implementation of two factor authorization wouldn't qualify as two factor _authentication_ on twofactorauth.org, but we shall definitely update the notes regarding Fidelity, which can be found at https://twofactorauth.org/notes/fidelity.
