### ISSUE TITLE
1password 2FA Info

### ISSUE THREAD

**Issue by jpartain89** [2factorauth/twofactorauth#2162]
So, I don't quite understand how exactly you'd expect 1password to implement 2FA within the confines of the proper standards. Especially when the app itself is oftentimes what I use for, at least, my 2 step verification setups for other websites. 

At the same time, they also have [their own rendition of 2FA](https://support.1password.com/understanding-account-key/) that specifically works with their encryption systems. 

So, asking them to try to implement 2FA systems in the long run is a great idea. I, personally, wouldn't see it happening soon. 

Also, with 1password having a supremely [robust user forum](https://discussions.agilebits.com/), that should honestly be included on your main page for submitting requests. They truly utilize their forum and their users for ideas constantly.

**Comment by Carlgo11** [comment]
Hello @jpartain89,
As described in #2048 1Password lets the user authenticate both when decrypting his/her vault and when syncing the vault to AgileBits' "cloud". We think at least the later one should be fairly easy to implement 2FA on.
That's also the reaction we get when talking to some of the AgileBits employees.

As of right now we feel that the only thing stopping AgileBits from implementing 2FA is the board not prioritizing it.
1Password has always been a bit of a controversy in the 2FA community but the majority of us, the members of @2factorauth, felt that it was time to add them again.

As for the forum, there are currently no way for us to link to that as we only support requests via email, Twitter and Facebook. Custom links might be something we implement in the future but it's not on the road map as of right now. (If enough people ask for it we will probably add it 😉 )

I hope that satisfies your questions. If not then please continue the discussion over at #2048 to keep everything 1Password-related in one place.

//@Carlgo11
