### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#2182]
Only supports SMS verification.

**Comment by Jawshy** [comment]
Hello, @Kevin-C-Bell. Does Affinity Federal Credit Union have a page that explains their implementation of two-factor authentication? If yes then could you please link to the page? If not then could you show us their implementation of 2FA (I.e. with screenshots)? 

If you feel up to it then you can add the site via a pull request (see [FAQ_New_TFA_SITE](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE)).

**Comment by Kevin-C-Bell** [comment]
It does not. Even the help links on the 2FA page canʻt be opened in a
new tab or window, I tried. Currently, they only support SMS 2FA. Wish
they supported FIDO U2F, as I have a key.

Screenshot below shows the 2FA challenge screen that appears (I
obfuscated my phone number) as I have enabled it on my account
(https://www.affinityfcu.org):

**Comment by Jawshy** [comment]
I cannot see any screenshots. You may have to login to GitHub to attach them.

**Comment by Kevin-C-Bell** [comment]
I found the support link with the information about 2FA:

https://www.affinityfcu.com/tips-and-tools/security-center/keeping-you-safe.aspx

**Comment by Kevin-C-Bell** [comment]
Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/13326415/20460458/0a7827ae-aeb1-11e6-8827-d2015cbb19e9.png)

**Comment by stephengroat** [comment]
closed by #2522
