### ISSUE TITLE
Twitter does not support software 2FA

### ISSUE THREAD

**Issue by Kenya-West** [2factorauth/twofactorauth#2192]
Twitter does not support software 2FA, I didn't find it, and every news article on Internet says the Twitter doesn't have this.

**Comment by gingerbeardman** [comment]
done #2256

**Comment by stephengroat** [comment]
It's hidden, but it's still there

In the Twitter Android App, Settings->Account->Security->Login code generator. I'm assuming the same is available on the iOS app according to [this](https://support.twitter.com/articles/20170409#login-code-generator)

**Comment by gingerbeardman** [comment]
Nice find! Yes it's there in iOS.

**Comment by Kenya-West** [comment]
@stephengroat no, there's no software 2FA feature in Twitter app for Windows. I checked that Lumia 1520 and laptop.
If I tap Settings->Account->Security, it just opens Twitter's web page containing security section without 2FA.

**Comment by jamcat22** [comment]
@Kenya-West, please see the [comment](https://github.com/2factorauth/twofactorauth/pull/2256#issuecomment-267513882) I placed on #2256 for more information on how to use a TOTP app for Twitter's 2FA.

**Comment by Kenya-West** [comment]
@jamcat22 OK, found how to do this. 

First, activate 2FA via SMS
Second, activate TOTP, you'll see the button. Same steps with VK for example.

Good, thanks for help.
