### ISSUE TITLE
Mailfence

### ISSUE THREAD

**Issue by Hillside502** [2factorauth/twofactorauth#2193]
Email privacy | Mailfence protects your mail privacy
https://mailfence.com/

Two-factor authentication
https://mailfence.com/c/mailfence/more/totp.jsp

**Comment by stephengroat** [comment]
thanks for the suggestion @Hillside502!

**Comment by MSalmanN** [comment]
The issue has been closed, and site has been reviewed #2194. But it's not included yet in the current repository! @stephengroat

**Comment by Jawshy** [comment]
That PR just needs to be merged then `gh-pages` synced with `master`, @MSalmanN.

**Comment by jamcat22** [comment]
@MSalmanN You can learn more about our merging process on the [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge). 😄

**Comment by MSalmanN** [comment]
Thanks @jamcat22, I was not aware of this.
