### ISSUE TITLE
please add  Schwyzer Kantonalbank

### ISSUE THREAD

**Issue by ulrichard** [2factorauth/twofactorauth#2196]
Please add https://www.szkb.ch/  to the list of banks
They only support SMS

**Comment by stephengroat** [comment]
do you have any links to documentation @ulrichard?

**Comment by ulrichard** [comment]
It's in German:
https://www.szkb.ch/pub/ueber-die-szkb/servicezentrum/e-services/sicherheit

**Comment by stephengroat** [comment]
thanks!

we have a `lang: de` tag we can use to target the site to german users!
