### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by netik** [2factorauth/twofactorauth#22]
This site says that Amazon has no 2FA. This isn't true. 

Amazon supports 2FA in IAM on Amazon AWS. 

If you've enabled it there, you'll also get asked for 2FA on user accounts. 

I think the Amazon issue needs to be greatly clarified.

**Comment by jdavis** [comment]
Interesting.

While that's great that it works like that, I still think it would be disingenuous to say that Amazon proper _has_ 2FA. Until I can enable 2FA (without AWS) from the amazon.com "Your Account" page, I think it should still be listed as a no.

Possibly a link in the `doc:` section of the main.yml could clarify it?

**Comment by ralfharing** [comment]
AWS probably deserves a listing separate from generic Amazon. [Here](http://aws.amazon.com/iam/details/mfa/) is their relevant support page.

**Comment by RichJeanes** [comment]
Considering the discussion  topic of this thread, should Amazon Payments in the "Payments" section be considered to fall under the Amazon in the "Retail" section?

**Comment by jdavis** [comment]
This might go with #35 regarding the duplicate entry of Amazon.

Regarding the possibly issue with clarification, I'm closing it as my previous comment made it clear where I stand.

**Comment by clex25** [comment]
Amazon.com now has 2 factor authentication. Go to change account settings - advanced security settings.
