### ISSUE TITLE
SMS should no longer be used in two-factor authentication (2FA)

### ISSUE THREAD

**Issue by Hillside502** [2factorauth/twofactorauth#2210]
FYI, excerpt from:-

NIST’s new password rules – what you need to know – Naked Security
https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/

"SMS should no longer be used in two-factor authentication (2FA).

There are many problems with the security of SMS delivery, including malware that can redirect text messages; attacks against the mobile phone network (such as the so-called SS7 hack); and mobile phone number portability.

Phone ports, also known as SIM swaps, are where your mobile provider issues you a new SIM card to replace one that’s been lost, damaged, stolen or that is the wrong size for your new phone.

In many countries it is unfortunately far too easy for criminals to convince a mobile phone store to transfer someone’s phone number to a new SIM and therefore hijacking all their text messages."

Hope this helps!

**Comment by RichJeanes** [comment]
This update by NIST was made a little while ago and has been discussed internally. While SMS may have flaws as a factor, those flaws are really only an issue in the case of targeted attacks (such as spear phishing). We have agreed that it is still better than nothing in that it provides protection against the most common account hijackings (usually password dumps from other sites).

**Comment by Hillside502** [comment]
> has been discussed internally

@RichJeanes  If you mean #1983 that was hardly a discussion --- brief mentions in the comments about adding VyStar.

You're a bit quick off the mark to close this!

As I said, "FYI".

**Comment by RichJeanes** [comment]
No, when I say "internally" I mean the team of collaborators that is dedicated to this project had a private ("internal") discussion over what the NIST recommendation meant for us and for TFA.org as an ongoing project.

Any objections with my wording and statement from @2factorauth/core?

**Comment by Hillside502** [comment]
> @2factorauth/core

gives a 404 error --- "Team members are private"

**Comment by Carlgo11** [comment]
@Hillside502 that's because it wasn't intended towards you but as a ping/poke to us, the core members of @2factorauth.

Internal = not publicly visible.

And +1  on the wording @RichJeanes.
