### ISSUE TITLE
Skype 2FA "useless" not topical anymore

### ISSUE THREAD

**Issue by Ascendor** [2factorauth/twofactorauth#2217]
The mouseover text of skype currently reads: "Two-factor authentication is available only when logging in using a Microsoft account. If you have setup your account using a Skype password, 2FA through Microsoft is essentially useless."

This is not true anymore, because now you can disable the login via the old skype.com-Account in your Microsoft account now. See https://community.skype.com/t5/Security-Privacy-Trust-and/Link-to-quot-baidu-quot-website-sent-to-all-of-my-contacts/m-p/4515175#M64836

**Comment by mxxcon** [comment]
Hmm..I can't replicate this. My skype.com account is not listed on that page, yet I can still login with it. 😕

**Comment by mxxcon** [comment]
Actually, I managed to get it to work. I'm not sure what kind of hoops I had to jump through but eventually when I logged in w/ my skype account it asked me if I want to link it to my MS account(even thought I've already done that before). And now my skype account did show up on that page and I was able to disable direct login with it. 😵

**Comment by Carlgo11** [comment]
Wait so it's possible to enable 2FA on skype accounts without linking it to a Microsoft account?

**Comment by mxxcon** [comment]
I don't know about that, and I'm not sure if I can even check it now since my skype account is linked to MS account.

**Comment by Ascendor** [comment]
@Carlgo11 No, it's not. You still have to link to a Microsoft account. But now you can then actually switch off the Skype.com account, leaving only the (2FA protected) MS account open.
Before, BOTH authentication ways were open, basically making the attack vector larger than smaller.

**Comment by mxxcon** [comment]
I'm thinking maybe still leave the exception with a note of this nuance?

**Comment by djrarky** [comment]
I think what he's trying to say is that it now isn't possible to create a new skype account, new signups through Skype are Microsoft accounts.

**Comment by Ascendor** [comment]
No, what I'm trying to say is: 2FA is no longer useless in Skype. No matter what kind of account you have.

- MS account only: 1. Switch on 2FA. => You're fine.
- Skype account: 1. Link to MS account. 2. Switch on 2FA. 3. Switch off old Skype authentication method. => You're fine.

Step 3 was not possible before, thus the statement on the website "2FA is useless". This is the change here.

**Comment by kmpoppe** [comment]
Obsolete through #3225.
