### ISSUE TITLE
Hitbox has two step authorization 

### ISSUE THREAD

**Issue by Zander490** [2factorauth/twofactorauth#2239]
You can find it under Account > Security. 

http://help.hitbox.tv/customer/portal/articles/2434122

**Comment by Carlgo11** [comment]
Hello @Zander490!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by Jawshy** [comment]
I had already started and committed the change, @Carlgo11. :sweat_smile:

**Comment by Carlgo11** [comment]
@Jawshy it's just a standard comment 😉 
![screenshot](https://cloud.githubusercontent.com/assets/3535780/21127231/c09ae95c-c0f1-11e6-990f-28231f642f0b.png)
