### ISSUE TITLE
Add labanquepostale.fr

### ISSUE THREAD

**Issue by Amaury-DB** [2factorauth/twofactorauth#2258]

**Comment by mxxcon** [comment]
Would you like to help us by submitting a pull request with relevant data?

**Comment by Amaury-DB** [comment]
Hello,

Yes. 

LBP is à french bank.

They do not provide 2fa.

**Comment by fpigerre** [comment]
Bonjour Amaury!

Merci pour vous avoir intéressé au site de twofactorauth.org.
Autant que nous aimerions bien ajouter tous les sites proposés nous mêmes, malheureusement nous n'avons pas le temps. Donc, nous comptons sur des bénévoles pour ajouter des sites en utilisant le système de "Pull Request" (PR) fourni par GitHub. Les informations nécessaires pour ajouter un site a la liste twofactorauth.org [peuvent se trouver ici](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
Si vous auriez besoin d'aide pour créer un Pull Request ou si vous avez des questions, n'hésitez pas a demander!

Si vous ne vouliez pas créer un Pull Request, veuillez l'indiquer pour qu'un autre volontaire puisse retourner a ce ticket et remplir un Pull Request. Ceci peut prendre assez de temps, par contre, puisse que nous sommes tous volontaires et maintenons ce site web dans notre temps libre. 🌴
