### ISSUE TITLE
Update ProtonMail with 2FA

### ISSUE THREAD

**Issue by amdelamar** [2factorauth/twofactorauth#2265]
Service: Mail
Name: ProtonMail
Site: https://protonmail.com

Only a few weeks ago, ProtonMail added 2FA via TOTP on their email service. Read more: https://protonmail.com/blog/protonmail-v3-6-release-notes/

**Comment by Jawshy** [comment]
Thanks for the report, @amdelamar, but this has already been done: https://github.com/2factorauth/twofactorauth/pull/2259. The [changes](https://github.com/2factorauth/twofactorauth/commit/d22e5f7b9a00d21a5d637cdc723c273fa823e789) will go live the next time `master` is merged into `gh-pages`. Please search before submitting a new issue.

**Comment by amdelamar** [comment]
Ah yep. Sorry about this. I searched but did not see it earlier.
