### ISSUE TITLE
Merrill Edge now supports 2FA

### ISSUE THREAD

**Issue by gregforcey** [2factorauth/twofactorauth#2275]
I couldn't find any documentation on the site about it. To activate it go to 

Help & Support > Personal Information > Security Center.

Only SMS 2FA for now. You can either have it send a code at every login or only for unrecognized devices. 

![screen shot 2016-12-22 at 6 14 21 pm](https://cloud.githubusercontent.com/assets/1922423/21443390/c3fb4d2a-c872-11e6-8f68-3450a0de2314.png)

**Comment by Carlgo11** [comment]
Closed due to #2287
