### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by andrewdski** [2factorauth/twofactorauth#2295]
I can't find anywhere that defines the difference between between the various 2FA methods. Ok, SMS, phone call, and email, are obviously straightforward, but what is the difference between software token and hardware token? For example, is Google Authenticator hardware or software?

I think this should be explained somewhere on the website.

**Comment by Carlgo11** [comment]
Every authentication method that is running through a program or an app is considered software while hardware authentication can be things like an RSA securID, Yubikey or a paper scheme.
For more on hardware tokens see https://en.wikipedia.org/wiki/Security_token#Physical_types

**Comment by Jawshy** [comment]
This is briefly explained on the [FAQ Categories](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Categories) wiki page. Please let us know if that could be expanded, @andrewdski.

**Comment by jamcat22** [comment]
This issue appears to be resolved, and unless a reply is received within 3 days, I'll go ahead and close this issue.

Thanks!
