### ISSUE TITLE
BofI Bank does support 2FA

### ISSUE THREAD

**Issue by justinharris1986** [2factorauth/twofactorauth#2298]
I think BofI Bank is incorrectly listed as not supporting 2FA. Please take a look at the screen shot. They support SMS and phone call authentication methods.

![screenshot at jan 09 11-53-12](https://cloud.githubusercontent.com/assets/7268384/21774984/629f7cba-d662-11e6-9b96-442b84a0f431.png)

**Comment by Jawshy** [comment]
Thanks for the report and screenshot, @justinharris1986. Do you know if they also have any webpage documentation about their verification procedure?

**Comment by justinharris1986** [comment]
Yeah, take a look at: [https://www.mybankofinternet.com/tob/live/usp-core/static/help.html#login_security](https://www.mybankofinternet.com/tob/live/usp-core/static/help.html#login_security)

Apparently they also support email as well.

**Comment by Jawshy** [comment]
Fantastic. Would you like to submit a pull request with the changes? If not, then a member will do so when they have the time.

**Comment by divayprakash** [comment]
@Jawshy  Working on it!
