### ISSUE TITLE
Dropbox & DigitalOcean support Authy

### ISSUE THREAD

**Issue by trampish** [2factorauth/twofactorauth#23]
Dropbox and Digital Ocean support Authy, I use it for 2FA on both services.

**Comment by zach-taylor** [comment]
Dropbox fixed in #36

**Comment by trampish** [comment]
Why close this issue before fixing Digital Ocean too? Just wondering, thanks!

**Comment by jdavis** [comment]
I think it might have just been a mistake. But don't worry, there are now two issues open for the DigitalOcean Authy support: #122, #109

**Comment by benjaminchait** [comment]
+1 DO has Authy support for the main account

**Comment by mpdavis** [comment]
I do not see Authy support in my DO account:

![](http://content.screencast.com/users/mikedavis.webfilings/folders/Jing/media/b4f59f03-7727-4d3d-90da-0d47a5bbfab5/00000470.png)

**Comment by trampish** [comment]
IIRC, one just sets up authy using the QR code they supply for Google Authenticator... screenshot:

![photo1](https://f.cloud.github.com/assets/1093422/2453985/ba945164-aee4-11e3-94c3-9a78adc3f05d.jpg)

**Comment by RichJeanes** [comment]
I think this ties in to our discussion on #145 a bit in that both Google Authenticator and Authy support the same TOTP standard but tack on additional features. I think the safe bet is to stick with whatever the site states they support for the purposes of twofactorauth.org though maybe contact DO support to get their take on the situation.
