### ISSUE TITLE
Add mbconnectline.com

### ISSUE THREAD

**Issue by JohannesRegner** [2factorauth/twofactorauth#2301]
Please add mbconnectline.com under Remote Access. Link for Help is:
DE: http://www.cc-onlinehelp.com/de/#index/verwaltung/benutzer/authentifizi/authentifizi.html
EN: http://www.cc-onlinehelp.com/en/#index/administrati/users/authenticati/authenticati.html

MB connect line are experts for remote maintenance solutions.

In our portals we use 2FA with Password + SMS and Password + Google Auth Code.

**Comment by jamcat22** [comment]
This issue is superseded by PR #2309.
