### ISSUE TITLE
Please add Prey, Inc. (supports 2FA)

### ISSUE THREAD

**Issue by stbxxl** [2factorauth/twofactorauth#2306]
Prey Inc. supports 2FA through software (Google Authenticator). I can't find any related documentation or instructions though. Here's the [link for the related 2FA settings](https://panel.preyproject.com/settings/two-step) (you need to have an account with them)

Attached are two screenshots for "proof". 

![prey1](https://cloud.githubusercontent.com/assets/19540455/21946221/4c1f8964-d994-11e6-8c5f-96b3047190f6.jpg)

![prey2](https://cloud.githubusercontent.com/assets/19540455/21946220/4c1dc64c-d994-11e6-88b9-da99217ad6c7.jpg)

Take care.

PS: Prey is a cross-platform, open source security solution that will let you track and potentially recover your devices in case of loss or theft (from their [help page](http://help.preyproject.com/article/185-overview-what-is-prey): )

**Comment by Carlgo11** [comment]
Hello @stbxxl!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.
