### ISSUE TITLE
Editing section icons & adding new sections

### ISSUE THREAD

**Issue by Stevoisiak** [2factorauth/twofactorauth#2338]
Is there a standard process for adding new categories? For instance, if I wanted to add a Productivity Tools category for sites such as Adobe, Autodesk, IFTTT, Office 365, Pastebin, and Todoist. I tried looking, but I couldn't find any icon files for each category in the source code.

**Comment by RichJeanes** [comment]
You are more than welcome to submit a PR with a new `productivity.yml` file with appropriate entries (removing them from other categories as necessary), as well as an accompanying `img` directory.

**Comment by Carlgo11** [comment]
https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sections

**Comment by jamcat22** [comment]
Additionally, we currently use [Semantic UI](semantic-ui.com), which includes Font Awesome icons. A complete list of icons (which would replace `icon-class` in the `icon: icon-class` line when following the directions in the [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sections) file) can be found [here](http://semantic-ui.com/elements/icon.html).

**Comment by Stevoisiak** [comment]
Ah, I hadn't noticed that section before. Thanks for the clarification. Closing the issue.
