### ISSUE TITLE
Merge Capital One and Capital One 360

### ISSUE THREAD

**Issue by Stevoisiak** [2factorauth/twofactorauth#2353]
As of 2017, the [old site for Capital One 360](https://home.capitalone360.com/) redirects to the main Capital One website, as both account types use the same webpage to login now.

Since both services have been merged together, I propose merging/removing the entry for Capital One 360.

**Comment by jamcat22** [comment]
While Capital One 360 and Capital One's main pages have been merged, when visiting the [login page](https://www.capitalone.com/sign-in/) there appear to be different login pages and accounts for [Capital One](https://verified.capitalone.com/sic-ui/#/esignin?Product=Card) and [Capital One 360](https://secure.capitalone360.com/myaccount/banking/login.vm).

**Comment by stephengroat** [comment]
i think that the logins are still run off of different systems. close the issue?
