### ISSUE TITLE
Telegram 2FA is password based - Phone/SMS is primary.

### ISSUE THREAD

**Issue by galaxyeden** [2factorauth/twofactorauth#2365]
EDIT - I had somehow overlooked that Telegram *does* have 2FA, and I just turned it on. However, unlike what is listed, the second factor is password. The phone/SMS is the primary factor. Is there a way to make note of this or to list "password" as a second factor?

Telegram is listed as supporting phone/SMS "two-factor authentication", but it isn't truly 2FA. From the definition at: https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md -

"For the purposes of this site, Two Factor Auth is defined as any service provided as a redundant layer for account authentication."

Telegram doesn't provide this, as the phone call/SMS is the only layer of authentication. No username, password, or any other authentication is needed. Thus, at least in my view, it isn't two-factor authentication by any definition. It just happens that its primary authentication is a scheme widely used by others for two-factor authentication.

**Comment by mxxcon** [comment]
What about https://telegram.org/blog/sessions-and-2-step-verification? You set a password there..

**Comment by galaxyeden** [comment]
Wow! *embarrassed* - somehow I missed this despite using Telegram for ages.

However, there's still an issue in how this is portrayed. In Telegram's case, phone/SMS still isn't the redundant layer - a password is. Phone/SMS is the primary authentication.

As out of the norm as it seems, in this case password really should be listed as the 2FA type.

P.S. *THANK YOU* - just got it turned on in Telegram!

**Comment by mxxcon** [comment]
Their approach is different to where password is the first factor. It there's no requirement for any given factor to be a primary one..
One things I'm not clear on is this:

>  It allows you to set up a password that will be required every time you log into your account from a new device – in addition to the code you get in the SMS.
>Be careful though: if you forget this password, you won't be able to access your messages from other devices. 

So does it mean you'll still be able to login, but just won't have access to chat history or what?

**Comment by galaxyeden** [comment]
> Their approach is different to where password is the first factor. It there's no requirement for any given factor to be a primary one..

I agree totally, I had missed this - it definitely is 2FA. I just mean in the list, it really should list "password" (which isn't an option now) and have a tick there, instead of for phone/SMS. As the primary is phone/SMS.

> So does it mean you'll still be able to login, but just won't have access to chat history or what?

I would imagine that you could still use the phone number to wipe it and start over. Since your account is your phone number, imagine getting stuck with an old re-used phone number where the person had turned on 2FA, but you weren't able to activate Telegram. Thus, there needs to still be an option to clear the history but still use the number.

I like Telegram, but this rabbit trail shows all the reasons I hate the phone-number-as-account method used by Telegram, WhatsApp, etc...

**Comment by mxxcon** [comment]
True, we don't have `password` category. But I'd imagine telegram is in a vast minority of services which are setup like that. I personally think modifying our site to handle these few cases would needlessly complicate things for us :)
