### ISSUE TITLE
Please add NS1 to the Domains Page

### ISSUE THREAD

**Issue by stuffcarlcodes** [2factorauth/twofactorauth#2378]
Hi there, Carl from NS1 here - a mutual customer has let me know that despite the fact that we offer 2FA as a standard option on our service that it was not listed here. Can we get that added?

https://ns1.com/articles/enabling-2-factor-authentication

We have a logo available for use that meets the size criteria, but I don't have the ability to push to the repo.

**Comment by mxxcon** [comment]
Feel free to submit pull request adding it. It's just a yaml block and 32x32 logo file.
You can make all the changes directly on github.com website.
Fork this repo into your account, create a branch in your fork, make needed changes in that branch, submit pull request back to us from that branch.

**Comment by jamcat22** [comment]
This issue is resolved via #2379.
