### ISSUE TITLE
Please add nitrado.net

### ISSUE THREAD

**Issue by serious-scribbler** [2factorauth/twofactorauth#2383]
They Support Google Authenticator and U2F security keys.

**Comment by Carlgo11** [comment]
Hello @serious-scribbler!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by BirknerAlex** [comment]
Hello @serious-scribbler,

I've seen your issue here. We've created a PR #2384. I hope this helps you.

Regards,
Alexander 
Nitrado.net Team
