### ISSUE TITLE
VyStar Credit Union has MFA Support

### ISSUE THREAD

**Issue by gregforcey** [2factorauth/twofactorauth#2385]
Vystar Credit Union supports multi factor authentication as described on their website. Either via an SMS message, phone call, or challenge question. 

> As Intelligent AuthenticationTM builds the access signature over time, various patterns and attributes are learned by the system. Just like it takes time for you to recognize another person’s face, IA also takes time to learn each user as they access their accounts on their computer. Until a reliable access signature can be built, any user will likely be challenged when they log in. Even then, a strong IA system will still occasionally challenge the user—especially if their behaviors, usage patterns or devices change or are updated. The challenge is typically a code sent via text or voice call to your mobile phone (something you have) and is the second factor in the MFA process, which helps us verify your identity. Other options are available, but this code is the most common method. - See more at: https://www.vystarcu.org/Online-Services/Internet-Banking-Access/Intelligent-Authentication#accordion1-collapse3

This isn't strictly 2-factor authentication because it does not require you to authenticate with 2 factors every time you log in. Rather only if the system does not recognize you, does it require 2-factor authentication to log in. 

Whether or not this justifies updating the website, I leave to the admins to decide.

**Comment by brycx** [comment]
When comparing the above with what is discussed in #1811 it seems as if VyStars options also wouldn't qualify for `tfa: Yes`. Is that correct?

**Comment by gregforcey** [comment]
Vystar's authentication system works like Chase's: Whenever you login with a new or unrecognized device, you are required to use 2-factor authentication. If you login with a recognized device, the second authentication is not required. 

Since the website shows Chase as offering true 2FA, I'm not sure why Vystar is not listed since it works the same way.
