### ISSUE TITLE
Please add www.signnow.com by Barracuda

### ISSUE THREAD

**Issue by user8446** [2factorauth/twofactorauth#2394]
Contract & e-signature service. Definitely needs 2FA as contracts and personally identifiable information is used and stored.

**Comment by Carlgo11** [comment]
Hello @user8446!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by user8446** [comment]
The PR is outside of my skillset but wanted to contribute by having a sensitive data site added, so someone else would have to come back to this. Thanks so much to all of the volunteers!
