### ISSUE TITLE
Please add HackerRank.com to education

### ISSUE THREAD

**Issue by jacenrkohler** [2factorauth/twofactorauth#2395]

**Comment by stephengroat** [comment]
FYI, HackerRank does not have TFA

**Comment by jacenrkohler** [comment]
Yes, I'm aware of that, but so do a lot of other services listed here.
I thought listing them might help encourage them to implement 2FA.

**Comment by stephengroat** [comment]
Yup, just writing on note for whoever wants to implement.

Thanks for letting us know! It's easy to contribute if you want to take a shot

**Comment by jacenrkohler** [comment]
Once I have a better handle on Jekyll, I'll try it.
