### ISSUE TITLE
Please add Lockheed Georgia Employees Community Credit Union

### ISSUE THREAD

**Issue by lrsatlanta** [2factorauth/twofactorauth#2411]
Please add Lockheed Georgia Employees Community Credit Union.  They do not have 2FA support at this time, but as they are my primary banking institution, I'd love for them to add it.

**Comment by schwartzadev** [comment]
Can you provide the following information?
1. Do they have a Twitter account?
1. Do they have a Facebook account?
1. Do they have a contact email address?
1. What is the link to their website?
1. What is a link to an icon?

Cheers!

**Comment by lrsatlanta** [comment]
1) https://twitter.com/LGEccu
2) https://www.facebook.com/LGECommunityCreditUnion
3) not sure
4) www.lgeccu.org
5)https://www.lgeccu.org/img/head_logo_lge_hires.png

**Comment by kmpoppe** [comment]
Closed by #2954
