### ISSUE TITLE
Adult/Social?

### ISSUE THREAD

**Issue by GregoryGHarding** [2factorauth/twofactorauth#2412]
not sure if this would go under social category or a separate adult one, but because of the cloudflare issues lately, the adult cam website www.chaturbate.com has introduced 2fa on their accounts by text, voice, software tokens, and hardware keys. their twitter is @chaturbate and link to 2fa setup is: https://chaturbate.com/security

**Comment by mxxcon** [comment]
maybe "other" category?

**Comment by Carlgo11** [comment]
I don't think this is the place to link to pornsites. Trying to appeal to the general public I wouldn't feel comfortable encouraging minors (or schools) to use our website. We might even get blocked by school internet-filters for linking to that.

**Comment by RichJeanes** [comment]
Yeah, solely on the basis of avoiding being blocked by parental/school/corporate internet filters, I think we should avoid linking to sites that are primarily hosts to adult content.

Thank you for your interest in the project, though, and feel free to suggest or contribute other sites that you would like to see listed.
