### ISSUE TITLE
What does "supports Authy" actually mean?

### ISSUE THREAD

**Issue by robn** [2factorauth/twofactorauth#245]
I haven't actually used Authy, but their website isn't entirely clear on exactly how they work. I get the feeling though that among things their client is a standard TOTP client.

If that's true, it explains why eg Google can claim Authy support, since I don't see Authy mentioned anywhere in Google's 2FA docs.

If that's true, it means everything that gets a tick for Google Authenticator should also get one for Authy, right?

If that's not true, then please explain what the difference is :)

**Comment by zach-taylor** [comment]
Hi @robn please see the discussion on #30. I think we are still working on how to handle that.

**Comment by robn** [comment]
Ahh, sorry. I searched but didn't see that one. Thanks!
