### ISSUE TITLE
ebay

### ISSUE THREAD

**Issue by ghctim** [2factorauth/twofactorauth#2455]
ebay no longer supports 2fa.  All links to register are dead.

**Comment by stephengroat** [comment]
eBay now support 2fa over SMS only, no longer uses the Symantec VIP soft token

not the best source, but a source (https://tamebay.com/2017/03/ebay-to-switch-to-mobile-2-factor-authentication-instead-of-paypal-key.html)

**Comment by ghctim** [comment]
How do you enable it? All instruction links don't work

**Comment by stephengroat** [comment]
they seem pretty worthless at documentation.

I've [tweeted at them](https://twitter.com/stephengroat/status/843855195717099520), hopefully they'll show us some documentation soon!

I'll try to update this thread with whatever they tell me!

**Comment by ghctim** [comment]
@stephengroat that article references a link for the UK, doesn't work with ebay.com....

**Comment by stephengroat** [comment]
try this

http://rover.ebay.com/rover/1/710-53481-19255-0/1?campid=5335837209&customid=&toolid=10001&mpre=http%3A%2F%2Fsigninalert.ebay.com/sgninalrt/twofa/onboard

**Comment by ghctim** [comment]
signed up! That is sweet! Thank you. Recommend updating the site doc for this....

**Comment by stephengroat** [comment]
from [AskeBay](https://twitter.com/AskeBay/status/844014526492303362?refsrc=email), new 2fa users currently can't turn on the feature.

do we want to update ebay with 2fa pending status @2factorauth/collaborators?

**Comment by melvynm** [comment]
Since that link works, and it's being emailed around by eBay and 2FA enthusiasts, why "Pending"? 

eBay now supports 2FA by SMS.

**Comment by stephengroat** [comment]
@melvynm Only works for existing 2fa users. Users who didn't have the feature before won't be able to turn it on

**Comment by ghctim** [comment]
I didn't and I was able to turn on

**Comment by ideologysec** [comment]
Worked for me as well, and I have never had 2FA on eBay enabled.

**Comment by ohheyrj** [comment]
Same for me, never had 2FA on my account enabled and it is now working.

**Comment by gingerbeardman** [comment]
I just turned this on for the first time and it's working just fine for me

**Comment by ghost** [comment]
@stephengroat Your link works fine even with eBay Italy; just replace both instances of ebay.com with ebay.it in the URL. Thanks!

**Comment by gingerbeardman** [comment]
@fturco I used the .com link to switch on 2FA for my .co.uk account so I don't think it even matters?

**Comment by gregforcey** [comment]
I was able to sign up for 2FA and I didn't have it enabled previously. I can't believe they make it so hard to find the link to do it.

**Comment by gingerbeardman** [comment]
I've made the changes. Awaiting review.

Pull request https://github.com/2factorauth/twofactorauth/pull/2545

**Comment by RichJeanes** [comment]
While setting up 2FA may work, if it is completely undocumented and requires some convoluted link to set up that must be shared around and is not easily accessible to a normal user, I would be hesitant to list the link publicly in case eBay decides to kill the feature completely or makes changes in the back-end that could potentially break this "not officially supported" feature.

**Comment by gingerbeardman** [comment]
@stephengroat where did you get the link?

**Comment by stephengroat** [comment]
@gingerbeardman https://github.com/2factorauth/twofactorauth/issues/2455#issuecomment-287804435

https://tamebay.com/2017/03/ebay-to-switch-to-mobile-2-factor-authentication-instead-of-paypal-key.html

I'm closing this for now. Whenever SMS officially supported, we can revisit it

**Comment by gingerbeardman** [comment]
also see: https://betanews.com/2017/03/23/ebay-sms-vs-token-two-factor-authentication/
