### ISSUE TITLE
Please add CircleCI

### ISSUE THREAD

**Issue by SamGJohn** [2factorauth/twofactorauth#2457]
Can you please add circleci (https://circleci.com/) to this list. They really need to get it together and start using 2fa. Thanks.

**Comment by jamcat22** [comment]
@SamGJohn, I'm not sure I understand. It appears CircleCI uses either GitHub or BitBucket to login, both of which offer 2FA. Is there a sign in process that only uses an email and password?

**Comment by Carlgo11** [comment]
Closing as CircleCI only provides authentication with GitHub or BitBucket
