### ISSUE TITLE
Please add WaveApps

### ISSUE THREAD

**Issue by user8446** [2factorauth/twofactorauth#2461]
WaveApps is online accounting software which includes banking connectors, receipts, invoicing, credit card processing and payroll (Intuit QuickBooks competitor). It definitely requires 2FA. Could someone please add?

www.waveapps.com
twitter: https://twitter.com/wavehq
facebook: http://www.facebook.com/waveHQ

**Comment by Carlgo11** [comment]
So they currently don't support 2FA?

**Comment by user8446** [comment]
No. I reached out to the security team and they only said it's on the roadmap with no eta.

On Mar 24, 2017 5:49 PM, "Carlgo11" <notifications@github.com<mailto:notifications@github.com>> wrote:

So they currently don't support 2FA?

**Comment by stephengroat** [comment]
closed by #2520
