### ISSUE TITLE
RedHat IPA / FreeIPA

### ISSUE THREAD

**Issue by briantopping** [2factorauth/twofactorauth#2469]
Hi there, I was sent to this site by @AuthyHelp regarding use of Authy with FreeIPA (aka RedHat IPA). Seems that FreeOTP works with these apps but Authy does not, and it's not clear why. Yesterday I was able to get SHA1 to work and synchronize, but today it's not working. Other algorithms don't even synchronize.

FreeIPA is trivial to install on CentOS 7 and fixing it would provide a lot of access to a lot of different corporate environments. Probably worth figuring out!

**Comment by fpigerre** [comment]
Hello @briantopping,

At the moment, [twofactorauth.org](https://twofactorauth.org) doesn't list FreeIPA as a service that supports two-factor authentication, so we have no idea whether FreeIPA's implementation of 2FA is currently working, or has ever worked in the past.

Would you by any chance be able to provide screenshots of the page through which you have added FreeOTP as a 2FA client?
It does seem that FreeIPA provides some sort of [standard OTP](http://www.freeipa.org/page/V4/OTP) (one-time password) support, however, it's unclear whether this implementation is well supported by various clients.

Thanks,
psgs 🌴

**Comment by briantopping** [comment]
Hi @psgs,

<img width="293" alt="identity_management" src="https://cloud.githubusercontent.com/assets/158115/24327823/32948b7a-1198-11e7-819f-61b7d78c2f18.png">

The URL that generates is otpauth://totp/brian@XXXX:XXXX?digits=6&secret=XXXX&period=30&algorithm=SHA1&issuer=brian%40XXXX

I assume that's what you are looking for and not an actual QR code with the URL in it or the secrets for it. The QR code is obviously pretty mechanical and it loads properly into Authy and FreeOTP, but I don't know enough about the encodings here to know if it's safe to share the actual values.

This is why I was saying someone on your team should just boot a VPS with CentOS on it and generate an OTP. 

Does that all help justify that this is an actual problem instead of just someone that doesn't know what's in play here? What else can I provide?

Thanks, Brian

**Comment by mxxcon** [comment]
@briantopping I think you misunderstood purpose of this site. We do not provide technical support for problems with totp. @authyhelp sent you to our site to see which, if any, sites that you use support 2fa.
If you are having problem FreeIPA and Authy implementation, you should contact them for help, we have nothing to do it with it.

**Comment by briantopping** [comment]
@mxxcon Thanks for straightening me out on the bad guidance. I'll correct them on Twitter.

My *misunderstanding* was that Authy was a tool that I wanted to use. I appreciate you helping me see that I was mistaken. I'll look elsewhere.

**Comment by briantopping** [comment]
@mxxcon: I see, the Authy tech support was just trying to get rid of me. This site is just about marketing that OTP is available and which sites support it, so they sent me here without thinking. 

It might be a good time to let them know that such redirections aren't welcome. It was unclear that you are not related to Authy until after posting the comment I just deleted.

Cheers

**Comment by Carlgo11** [comment]
@briantopping No I think they simply misunderstood you and thought you talked about a site supporting 2FA. The Authy guys are great people.

The problem you are having is however not related in any way to twofactorauth.org or Authy. Authy gives support for people using THEIR implementation of two factor authentication. You're using FreeOTP which ISN'T their software.
I suggest you contact the FreeOTP people instead.

Furthermore it is IMO pretty clear that we are not related to Authy as we don't promote any of Authy's products or services on our site.

**Comment by briantopping** [comment]
@Carlgo11 So are you saying there are multiple implementations of https://tools.ietf.org/html/rfc6238?

Someone has their implementation wrong.

**Comment by Carlgo11** [comment]
@briantopping Yes. Thousands.

**Comment by briantopping** [comment]
Yes, of course there are thousands. s/implementation/interpretations. Sorry I wasn't precise

**Comment by mxxcon** [comment]
from https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm
>  RFC 6238 allows different parameters to be used, the Google implementation of the authenticator app does not support T0, TI values, hash methods and token lengths different from the default. It also expects the K secret key to be entered (or supplied in a QR code) in base-32 encoding according to RFC 3548.

However, I personally never used Authy nor FreeITP, so I can't tell you if either of them are sticking strictly with Google Authenticator compatible implementation or support more various parameters.

**Comment by Carlgo11** [comment]
Authy supports multiple TFA software solutions (TOTP and non-TOTP) they also support phone calls and SMS.
However as far as I know they only give developer support for their own TFA implementation so if you're using RFC6238 you should probably seek help elsewhere.

**Comment by Carlgo11** [comment]
Locking this issue as it's invalid.
