### ISSUE TITLE
RFE: Compatibility Matrix

### ISSUE THREAD

**Issue by briantopping** [2factorauth/twofactorauth#2470]
#2469 discusses a misunderstanding that arose from an unfortunate divergence between https://tools.ietf.org/html/rfc6238 and implementations that should be compatible. Hopefully some good can come from that misunderstanding.

It seems that a very beneficial value add on what this site already provides is a compatibility matrix between authenticator implementations such as Google Authenticator, Authy and FreeOTP and actual implementations *and* deployments (deployments which may well be site-specific in the case of large sites but may be implementation specific in the case of products like FreeIPA). 

There was a reference there to T0, TI values, for instance. I thought those were included in the URL that is described at https://github.com/google/google-authenticator/wiki/Key-Uri-Format and coded into QR, but maybe I continue to be mistaken. If so, I can imagine it will be incredibly easy for others with less experience to also be mistaken. This issue is about avoiding future misunderstanding via this RFE.

This is written in the spirit of industry advancement toward universally compatible OTP authenticators. Hopefully it starts a valuable discussion on this critical component of emerging 2FA.

**Comment by briantopping** [comment]
So that it's said, the general behavior on #2469 is pretty weak. While I wrote this, I did not have time to come back and apologize for the misunderstanding created by Authy support. Regardless, it's a relevant issue. Whether this team chooses to address it or not is really none of my business and I'll leave it at that.

**Comment by Carlgo11** [comment]
This has already been discussed in https://github.com/2factorauth/twofactorauth/issues/1832 https://github.com/2factorauth/twofactorauth/issues/1844 and https://github.com/2factorauth/twofactorauth/issues/2148

**Comment by briantopping** [comment]
Great, closed.

**Comment by briantopping** [comment]
@Carlgo11: So it's noted, I am quite sure that none of the issues you referenced are duplicates of what I have written here. Or that this is an arm's length site from Authy instead of a front for it (i.e. #1832). 

IMO, the best anything anyone can do is ignore Authy and this site. I see why people don't like Authy now and am grateful for the education.

**Comment by mxxcon** [comment]
@briantopping If you don't find https://twofactorauth.org useful that's obviously your decision 😃
However, people that do contribute and visit it, do find it as a useful resource.

**Comment by briantopping** [comment]
@mxxcon Never disputed. I'm sure the people that contribute find it as a useful resource. That said, there is at least one visitor that did not find it useful, so your statement is not entirely accurate. And I do appreciate art, in all forms.

It doesn't make it any more of a duplicate though. It's not. And when it eventually gets implemented, it's really to the benefit of the site that does so.
