### ISSUE TITLE
Tresorit

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#248]
Tresorit is a backup/sync service much like SpiderOak's "no knowledge" policy but does not appear to support 2FA.

**Comment by Ritchie007** [comment]
Hi,

Received this mail from tech support 

---

Myke (Tresorit Customer Service)
Mar 20 13:52

Dear Richard,

Thank you very much for contacting us and for taking the time to share your feature request with us.

We are exactly on the same page and please let me tell you that this feature is totally on our roadmap, hopefully it will be added to our clients in the close future.

Thank you very much for your cooperation, your understanding and your patience.

Should you have any further questions, feedbacks or remarks, please do not hesitate to contact us again.

We hope you like Tresorit and wish you a great day.

Best regards,
The Tresorit Team

**Comment by ghost** [comment]
That's awesome, thanks for the heads up.

**Comment by jdavis** [comment]
I'm just doing some clean up, thanks for bring this up.

**Comment by RichJeanes** [comment]
Don't mean to zombie, but should we add this page as a status link for Tresorit so they won't get Tweeted at about it?

**Comment by jdavis** [comment]
Yeah, this link would work: https://github.com/jdavis/twofactorauth/issues/248#issuecomment-38165041
