### ISSUE TITLE
Improvements for healthcare section

### ISSUE THREAD

**Issue by MalMcWil** [2factorauth/twofactorauth#2490]
I'd like to see improvements made for health insurance providers to enable 2fa, I think it's important with patients access to medical records. Blue Cross blue shield, kaiser, Delta dental, VSP, UHC and UHC dental to name a few. 

Alternatively, if anyone has any good GitHub for dummies guide I'll learn to do it myself. Seriously, I'm looking to broaden my IT skillset anyways, and have zero foundational knowledge of github, but am able/willing to learn.

**Comment by mxxcon** [comment]
Check out https://try.github.io as a basic start.

If you have relevant info for these providers, you could also give a try to a form that I created https://docs.google.com/forms/d/e/1FAIpQLSfFQV0QPp0cSSKEx0rYXb46aXRBBOvelrEPfVV_Qhfm_DDOGw/viewform

**Comment by MalMcWil** [comment]
Awesome, thank you! I'll absolutely look into it. I'll be back!
