### ISSUE TITLE
"Custom" field

### ISSUE THREAD

**Issue by bsdlp** [2factorauth/twofactorauth#25]
The custom field currently displays a big red X if the service does not provide a custom 2fa solution. However, it shouldn't be considered a negative, as google auth, sms and authy support is Good Enough™.

I propose that the custom field be blank if N/A or otherwise more neutral.

**Comment by zach-taylor** [comment]
I agree. We need a way to signify that it's acceptable. I would suppose a site not having Authy support isn't the end of the world either. This will need some discussion.

**Comment by computmaxer** [comment]
Yes, I agree. We need a neutral state/color.

**Comment by computmaxer** [comment]
Here's my first stab at it:

![neutral](http://content.screencast.com/users/max.peterson/folders/Jing/media/af567f77-73fe-4fe4-aec4-abe961e13dab/00001057.png)

**Comment by computmaxer** [comment]
@jdavis any thoughts on this?

**Comment by jdavis** [comment]
Ahh, I wasn't aware of this issue. Sorry about that. Let me take a look now.

**Comment by jdavis** [comment]
I completely agree. One candidate is the icon from Semantic that is called 'Minus': http://semantic-ui.com/elements/icon.html

We could make it grey and the td white like your image, Max. I really like how it looks. I will work on it now.

**Comment by computmaxer** [comment]
I have the code I can just submit a PR if you want.

**Comment by jdavis** [comment]
Oh awesome, is it using the minus icon? Feel free to submit it.

**Comment by bsdlp** [comment]
New custom field looks great. thanks guys! :shipit:
