### ISSUE TITLE
CBT Nuggets

### ISSUE THREAD

**Issue by ohheyrj** [2factorauth/twofactorauth#2503]
Hello,

Looking for some advice here. I've made the addition of CBT Nuggets to my own fork and wondered if people think I should put a pull request in. I think the site fits the criteria and notice that there are already education sites similar to it on the site (Udemy, edX). CBT nuggets is an online IT on-demand training provider. You subscribe for a year and have access to all their online training. I'd like to add it in as I think it falls into the criteria of data but I'm not sure.

**Comment by Carlgo11** [comment]
@rj175 What kind of sensitive data do they store?

**Comment by ohheyrj** [comment]
They hold your payment details to renew each month/year. Also you can have
a 'team' account so an administrator account could contain username,
emails, names. In addition an administrator can add additional users
resulting in extra costs.

**Comment by Carlgo11** [comment]
Then yeah, go for it.

_Btw, when you reply to a thread on GitHub via your email, remember to delete the quoted history._

**Comment by ohheyrj** [comment]
Oops sorry about that.
