### ISSUE TITLE
easyJet Image Update

### ISSUE THREAD

**Issue by ohheyrj** [2factorauth/twofactorauth#2506]
I was looking at the transport section and noticed that the easyJet image seemed to standout more than the others (not just because its orange). I had a play around with it and this is the outcome:
Original image currently in use:
![easyjet-original](https://cloud.githubusercontent.com/assets/5339261/25066987/a970ee3c-222d-11e7-98c6-a519608e69e8.PNG)
Image that I've come up with:
![easyjet-new](https://cloud.githubusercontent.com/assets/5339261/25066988/a9737db4-222d-11e7-86a4-e8ef1783a521.PNG)

I was going to put this in as a pull request straight away but thought I might ask first to make sure what I'm doing is ok.

**Comment by Carlgo11** [comment]
@rj175 looks like a clear improvement. Go for it! 😉

**Comment by jamcat22** [comment]
Closed via #2507.
