### ISSUE TITLE
Walgreens now supports 2fa

### ISSUE THREAD

**Issue by ghctim** [2factorauth/twofactorauth#2525]
Walgreens just rolled out 2fa and called it pin code sign in.  to enable to go to Walgreens account and click on security enable pin code login.  they will text you a code

**Comment by stephengroat** [comment]
This is actually only 1 factor authentication, since you don't need the password when you sign in with the texted PIN code.

Too bad that Walgreens didn't do it right!

**Comment by mxxcon** [comment]
There's still regular login process...https://www.walgreens.com/login.jsp So texting pin to the phone would be 2nd factor, no?

**Comment by stephengroat** [comment]
i don't have to use my password when i login with the texted code.

have you tried enabling the service?

**Comment by mxxcon** [comment]
I don't have account with them, so can't test :)

**Comment by jamcat22** [comment]
Sadly, I can confirm that this is the case. 
![Walgreens Security Settings](https://cloud.githubusercontent.com/assets/1897053/26527186/5fe16398-434b-11e7-8eb5-7528ce8c9704.png)
