### ISSUE TITLE
Add Meraki

### ISSUE THREAD

**Issue by smarthero** [2factorauth/twofactorauth#253]
Meraki (acquired by Cisco) is a cloud based networking hardware solution plus a free mobile device management solution. Supports TOTP (Google Authenticator & Authy) and SMS. 

https://meraki.cisco.com/blog/2011/08/swing-into-security-with-the-two-factor-two-step/

**Comment by RichJeanes** [comment]
The link shows SMS. Can you provide documentation for TOTP?

**Comment by smarthero** [comment]
https://kb.meraki.com/knowledge_base/using-google-authenticator-for-two-factor-authentication

**Comment by RichJeanes** [comment]
Looks good. It'll go on the to-do list unless you just want to add it yourself.

**Comment by smarthero** [comment]
Have at it, thanks

**Comment by mxxcon** [comment]
@smarthero So did they retire SMS or it's both?
What category would you put them in?

**Comment by smarthero** [comment]
Fairly certain it's an either/or thing. You can set it up for SMS or TOTP (which Google Auth and Authy [the app, not their 'product'] both support)

As for a category, probably Other for now, or maybe a new category of Networking?
