### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by andrewhilts** [2factorauth/twofactorauth#2531]
Hi there, I'm wondering if you would be interested in assistance in internationalizing twofactorauth.org?

I work on a project called Net Alert (https://netalert.me) and we're making a comic about two-factor authentication that's intended to be translated into a few languages. We want to link to twofactorauth.org but since it's only in English we can't really do that consistently.

I used Jekyll for the Net Alert website, and specifically employed [jekyll-multiple-languages-plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin).

If I were to make a pull request for an i18n version of the site, would this stand a chance of making it to the web?

Thanks!

**Comment by mxxcon** [comment]
What about 2fa's website do you think would need translation? Category names?

I'm personally not against internationalization if somebody has a good way of handling it, but just wondering if it's really necessary at all..
I could be wrong, but I think our terminology is pretty basic for most internet-aware people to understand what "SMS" or "email" are no matter what language they speak.
I'm fluent with English so it's hard for me to judge such usability.

**Comment by fpigerre** [comment]
Hi @andrewhilts,

We've talked about translation a bit in issues such as #2510, but haven't come up with a broad solution yet. You might be interested in taking a look at the issues tagged with the ['international' tag](https://github.com/2factorauth/twofactorauth/labels/international).

At the moment, we haven't really found a great way to determine:
* What should be translated
* How it should be translated

However, we would be really interested any suggestions you have.
If you'd like to submit a pull request, I would definitely suggest that you go for it and give it a shot 😄 

Thanks,
psgs 🌴

**Comment by Carlgo11** [comment]
Moving to #6166
