### ISSUE TITLE
Bank of America 2 factor is a bit of a stretch

### ISSUE THREAD

**Issue by CTDragon** [2factorauth/twofactorauth#2532]
It's a bit of a stretch to say Bank of America has 2 factor auth. When you turn it on, you will notice that it never asks you for anything besides your password when you log in. The only time it really seems to ask for the second factor is when you try to add a new transfer account (and possibly other times). I did a quick google search and it says it will also do it for "higher value" transfers, but I've transferred thousands without having to enter the a text auth, so mileage may vary for "higher value" transfers.

It almost deserves an asterisk or something.

**Comment by mxxcon** [comment]
What if you delete all your cookies and try to login again, will it prompt you for 2fa?

**Comment by CTDragon** [comment]
I just tried this to make sure I was not mistaken with my claim. The only thing it does is ask a security question. There is no option to use sms, e-mail, phone, or app 2 factor auth for logging in. The only time mobile auth is used is when performing certain actions within the site.

**Comment by mxxcon** [comment]
Hmm. Looks like that's true. https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/safepass.go
This is 2-factor authorization, not 2-factor authentication, so should be `tfa: no`.

**Comment by CTDragon** [comment]
Agreed. I would however like it if they added it. I contacted them when I first set it up and they seemed confused what I was asking and why I would want that.

**Comment by mxxcon** [comment]
@CTDragon if you want to, submit a PR to fix boa's entry?

**Comment by jamcat22** [comment]
In BoA's security center, there's an option to require an extra security code at every sign in.
![Screenshot of Security Center demo video](https://cloud.githubusercontent.com/assets/1897053/26535788/bbd51224-43ed-11e7-8e28-df2230998656.png)

This is shown in the Security Center tour video [here](https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/security-center.go).

By enabling this option, you can force 2FA at every login.

**Comment by CTDragon** [comment]
@jamcat22 I just enabled this and confirmed that it works. When I called and asked about it a few years back, they said they didn't have anything like that. I'm glad they have caught up a little bit. I will close this issue since nothing needs to be done for it.

**Comment by antsar** [comment]
@CTDragon I think this issue should be re-opened.

Bank of America recently (in the last few months) removed the ability to use "SafePass" (hardware token) for login. SafePass is still supported for authorizing transactions, but the only 2FA method still supported is Code-by-SMS/Code-by-Email.

SafePass *was* supported for 2FA. I recently disabled it, intending to re-enable it momentarily. There was no option to do that, only Code-by-SMS. Customer Service confirmed that SafePass is phased out for 2FA.

**Comment by bobcowles** [comment]
I agree. There is no hardware token support and there *is* an option for receiving an SMS code at login - so it is for authentication, not just for authorization.
