### ISSUE TITLE
Expansion of site with support for password lengths / password charsets?

### ISSUE THREAD

**Issue by nitrocode** [2factorauth/twofactorauth#2539]
From using a password manager and authenticators for the past year, I'd like to see which websites support the following

* ~2fa / mfa using Authenticators like Google Authenticator / Authy~ (found this https://github.com/2factorauth/twofactorauth/issues/2148)
* ~password length (some websites only support up to 20 chars)~ (found this https://github.com/2factorauth/twofactorauth/issues/376)
* ~password character sets (some websites only support alphanumerics where some support all chars)~ (found this https://github.com/2factorauth/twofactorauth/issues/376)

Edit: this was a failed question as I found most of the answers to the above bullets by reading closed issues. 

If the above isn't in the scope of 2fa.org, any idea of any projects that do catalog websites by password sets and length?

Thanks

**Comment by mxxcon** [comment]
I think there was a forked project that wanted to map out password strength/restrictions of various sites, but I don't remember its name.
Perhaps this is a project better suited for password managers themselves so that they know what is the maximum most secure password they can generate..

**Comment by zecanard** [comment]
Take a look at https://github.com/apple/password-manager-resources and see if that’s what you’re looking for.
