### ISSUE TITLE
Add a section for recently added sites

### ISSUE THREAD

**Issue by lopezg** [2factorauth/twofactorauth#2558]
Every couple of months I come to this site to see if there are any new places that I can add 2FA too.  This means I have to visit each section one by one and scan the list to see what's new.  I think it would be better if there was somewhere on the site where I can see what was recently added, with a filter that shows last 30 days, 3 months, 6 months.

**Comment by mxxcon** [comment]
Yes, it would be nice to have. Until we figure out how to implement that for a completely static site, in the mean time you could look at the commit history to see what was added.

**Comment by lopezg** [comment]
I don’t know anything about Jekyll, but would it be possible to insert a date added variable to the yml file, that could then be parsed by JavaScript? 

today() - facebook.dateAdded > 30

**Comment by lopezg** [comment]
Closing because I just realized this is a duplicate of issue #519.
