### ISSUE TITLE
lobste.rs supports TOTP 2FA

### ISSUE THREAD

**Issue by strugee** [2factorauth/twofactorauth#2562]
https://lobste.rs supports two-factor authentication via TOTP. Unfortunately I don't have a lot of time or I'd just PR this myself, but I wanted to at least file an issue so I don't forget :)

Thanks for maintaining this project <3

**Comment by stephengroat** [comment]
thanks for the info @strugee.

i submitted a request to get an account to confirm. once i do, i'll make the pr

**Comment by strugee** [comment]
Whoa, that was fast! Thanks @stephengroat :)
