### ISSUE TITLE
canadian banks

### ISSUE THREAD

**Issue by kurtseifried** [2factorauth/twofactorauth#257]
AFAIK none support 2fa properly, but for sure:
http://www.tdcanadatrust.com/ (TD Canada)
https://www.servus.ca/

**Comment by jdavis** [comment]
Hold tight with these guys, we'll try to add them once we do the international part in #241

**Comment by snaray** [comment]
FYI. CIBC currently shows as "in progress", but they went live this summer. No software implementation (ie. Google/MS Authenticator), email/text/voice-call options are there though.

**Comment by mxxcon** [comment]
@snaray feel free to submit pull request with corrections.
