### ISSUE TITLE
Please add Airtable

### ISSUE THREAD

**Issue by maax-imus** [2factorauth/twofactorauth#2577]
Hello! I just stumbled upon this project/page, and I think it's great.

[Airtable](https://airtable.com/) supports 2FA, here is their help doc about it: https://support.airtable.com/hc/en-us/articles/219409917-Setting-up-two-factor-authentication

If it matters: http://www.alexa.com/siteinfo/airtable.com

Thanks!

**Comment by stephengroat** [comment]
closed by #2586
