### ISSUE TITLE
Kraken supports fine-grained U2F 

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#2580]
Kraken supports U2F now for YubiKeys. (Hardware tokens)

They also support fine grained 2FA even after login, specific actions can now be locked down to use u2F.

**Comment by mxxcon** [comment]
We consider fine grained controls as "two factor authorization" and are not applicable to this site.

**Comment by RichJeanes** [comment]
For clarity, @mwgh84, does Kraken support U2F **on login** or **just** to authorize actions after login?

**Comment by ghost** [comment]
Yes it supports it at login.

**Comment by RichJeanes** [comment]
Is there any documentation available for this yet? I cannot find anything about it on their support site or blog.

**Comment by ghost** [comment]
https://support.kraken.com/hc/en-us/articles/203395513-How-do-I-set-up-two-factor-authentication-

It certainly does support it in their 2FA list of options.

**Comment by RichJeanes** [comment]
There is nothing about U2F on that page. Are you sure it isn't just Yubico OTP that they support? 

This would still be considered a hardware token, but it is definitely not U2F.

**Comment by RichJeanes** [comment]
Since that page explicitly mentions the Yubikey's HOTP, I would say that it is the Yubico OTP they support, not U2F.

(And as an amendment to their documentation, the Yubikey **does** support TOTP, but requires an additional application to do it).

**Comment by ghost** [comment]
You're right, my bad, it is just OTP (hardware HOTP).
