### ISSUE TITLE
Fine-grained list needed

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#2581]
The list of services supporting is pretty coarse grained between Hardware and Software tokens.

I think it should be more fine-grained and list specific protocols, for hardware this will be FIDO U2F and FIDO UAF and software it will be HOTP and TOTP.

**Comment by mxxcon** [comment]
We specifically switched so such broad and generic terms to simplify and speed up addition of sites.
If we start listing all the specific implementations, the list would grow infinitely long.

**Comment by jamcat22** [comment]
This issue has been addressed in multiple other issues, including #1369, #965, #852, #842, and #493. Ultimately, #333 was the PR which switched the site from focusing on specific methods, like Google Authenticator, Authy, and Verisign VIP, to more broad usage types, like software and hardware. I would suggest looking at the prior issues and PRs relating to this issue to understand the mentality behind the decision to not include specific providers. If you have a suggestion on how to tackle this problem that hasn't already been addressed, you're welcome to talk about it here.
