### ISSUE TITLE
Not all sites can be searched

### ISSUE THREAD

**Issue by MarkDarwin** [2factorauth/twofactorauth#2605]
I was going to submit Poloniex because it doesn't show up in the search but when I looked at the file cryptocurrencies.yml it's in there.  All information and formatting looks correct so I can't see why it's not showing up.

I've repeated the steps for searching in Chrome, IE, Edge and mobile browser and in each case I can't find the site.  Nor can I find it if I type in the end few characters which works for others.

This is the only one I've found so far like this.  Perhaps I'm missing something obvious?

**Comment by mxxcon** [comment]
The site was added to the code, but the updated code have not been pushed live yet.

**Comment by MarkDarwin** [comment]
Ok thanks.  That is helpful to know for next time.
