### ISSUE TITLE
Help update addiko bank

### ISSUE THREAD

**Issue by stephengroat** [2factorauth/twofactorauth#2615]
Need help updating the `doc` link for addiko

**Comment by jamcat22** [comment]
The updated version of the link we had posted before, which talks about the hardware token, is: https://www.addiko.hr/static/uploads/addiko_bank_uputa_za_koristenje_tokena_mtokena.pdf

A different doc, which talks about the software version of the token, is: https://www.addiko.hr/static/uploads/mtoken-uputa-za-koristenje.pdf

Not sure which we should use. I guess we could just keep the old doc about the physical token and update it with the new URL.
