### ISSUE TITLE
Please Update Coinbase To Indicate It Now Recommends Google Authenticator

### ISSUE THREAD

**Issue by sudleyplace** [2factorauth/twofactorauth#2625]
As per the following link

https://support.coinbase.com/customer/en/portal/articles/1658338-how-do-i-set-up-2-factor-authentication-with-authy-

Coinbase now recommends using Google Authenticator.  I didn't see any explanation of the difference between "Hardware Token" v. "Software Token", but I'm guessing that GA is in the Hardware Token class.

**Comment by jamcat22** [comment]
Coinbase is already listed on [twofactorauth.org](https://twofactorauth.org/#cryptocurrencies) as providing a software implementation (like Google Authenticator or Authy) of 2FA. For more information on categories, see our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Categories) page on the subject.

**Comment by sudleyplace** [comment]
Thanks for the info.  The first page I saw which mentioned Hardware and Software Tokens was https://twofactorauth.org/#cryptocurrencies.  It would be helpful if there were a link there which explains those terms, or perhaps a tooltip on mouse over on the header.

Thanks again for the explanation.

This is a very useful site!
