### ISSUE TITLE
Update: Backblaze

### ISSUE THREAD

**Issue by Gridonyx** [2factorauth/twofactorauth#2643]
Backblaze now supports authentication apps (Google Auth/Authy) in addition to their current SMS offering

Edit: Here is a link for verification https://www.backblaze.com/blog/two-factor-verification-via-totp/

**Comment by stephengroat** [comment]
Closed by #2636

**Comment by JamesMontour** [comment]
No change was made to Backblaze's listing, it still lists only SMS the Software Tokens should be checked now as well, not sure why this was closed with no change.

**Comment by stephengroat** [comment]
@JamesMontour sorry about not explaining the closure. 

#2636, which has been merged on master, has the changes. This project use master as a staging branch for production, which is gh-pages. Once gh-pages is updates with master, the changes will be live. It can take a few weeks, but I promise it'll happen. Again, sorry about that.

Sound good?

**Comment by Gridonyx** [comment]
@stephengroat No worries, I realized my mistake and removed my comment. I didn't notice the link to the issue that was opened prior to mine. Thank you for taking the time to explain though, it is appreciated.
