### ISSUE TITLE
Please add CBQ - Commercial Bank of Qatar

### ISSUE THREAD

**Issue by davchana** [2factorauth/twofactorauth#2651]
https://cbq.qa/EN/

**Comment by stephengroat** [comment]
hey @davchana! do you want to create a pull request to merge those commits on to master?

**Comment by davchana** [comment]
@stephengroat yes, I am learning, this is my first time with pull requests. I have already forked it into my github, now trying to do the travis build. Once done, will submit a pull request. :)

**Comment by davchana** [comment]
@stephengroat added pull request https://github.com/2factorauth/twofactorauth/pull/2652 Now waitinf for its Travis Build Success. The one on my github passed https://travis-ci.org/davchana/twofactorauth/builds/256435638
