### ISSUE TITLE
Total count

### ISSUE THREAD

**Issue by simplenotezy** [2factorauth/twofactorauth#2655]
Would be nice to see total count of sites that support 2FA and which ones they support (SMS, Phone, software, etc)

**Comment by conorgil** [comment]
It would be neat to create a "stats" page or something like that with some snazzy graphs showing some neat metrics. Ideas:
- Which categories have the most/least entries?
- Which category has the most/least support for 2FA?
- Which are the most popular forms of 2FA (sms, totp, push, U2F, etc)?

**Comment by mxxcon** [comment]
We do have https://twofactorauth.org/data.json so scanning all the entries to generate stats should be somewhat easy.

**Comment by Carlgo11** [comment]
@conorgil like this one https://carlgo11.github.io/twofactorauth-chart/?

**Comment by conorgil** [comment]
@Carlgo11 sure! I think that is a good start. I imagine there are tons of graphs and lists that would be super interesting to look at that can be added over time.

**Comment by Carlgo11** [comment]
Added in our API v2
