### ISSUE TITLE
CIBC 2FA (Text)

### ISSUE THREAD

**Issue by walk0080** [2factorauth/twofactorauth#2656]
CIBC under #banking supports 2FA via Text Messages at the moment.

**Comment by stephengroat** [comment]
thanks for the info @walk0080 

we've actually already gone over this is https://github.com/2factorauth/twofactorauth/pull/2153

> It is not because according to the [documentation](https://www.cibc.com/ca/legal/two-step-verification.html) the second step is for authorisation (of sensitive actions, as pointed out by @stephengroat) and not for account authentication (login) which does not meet [Two Factor Auth's definition](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions).
