### ISSUE TITLE
Persistent Table Header

### ISSUE THREAD

**Issue by brandoningli** [2factorauth/twofactorauth#2670]
A persistent table header or repeating the header every `x` rows would benefit the readability of the site, especially when the lists get long in some categories.

**Comment by Carlgo11** [comment]
ping @psgs

**Comment by kenman345** [comment]
I know this is old but perhaps bootstrap components could help with this. Maybe just something similar to what it can do with [affix](https://getbootstrap.com/docs/3.3/javascript/#affix)

**Comment by fpigerre** [comment]
This issue affects #3091.

**Comment by kenman345** [comment]
so I dont need to look it up again, I think my earlier suggestion of Bootstrap is silly. Why introduce another library to a project when we use Semantics already that has [Sticky](https://semantic-ui.com/modules/sticky.html)

**Comment by kmpoppe** [comment]
This was already accomplished, thus closing this issue.
