### ISSUE TITLE
Trion Worlds issue

### ISSUE THREAD

**Issue by Jelliol** [2factorauth/twofactorauth#2674]
Hi, juste a precision to add, you must use Trion Worlds mobile app for 2FA.
No Authy or other app support yet.

**Comment by stephengroat** [comment]
thanks for the info @Jelliol 

right now, our `software` tag counts any software/smartphone based auth systems (authy, duo, TOTP/HOTP, or custom).

if (or hopefully when) we get around to providing more detail (like a pop-up on the `software` checkmark talking about methods), we'll be sure to include this!
