### ISSUE TITLE
Update Wargaming

### ISSUE THREAD

**Issue by rakleed** [2factorauth/twofactorauth#2676]
name: Wargaming
url: https://wargaming.net/
img:
tfa: Yes
sms: No
email: No
phone: No
software: Yes
hardware: No
doc: https://eu.wargaming.net/support/kb/articles/775

**Comment by Carlgo11** [comment]
Hello @Rakleed,
I've made a PR with your suggested changes. You can view at over at #2678.


Have a good day!
