### ISSUE TITLE
Write Bot to scrape Twitter for new tweets

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#268]
Using the Twitter Streaming API filtering on the hashtag #SupportTwoFactorAuth.

**Comment by computmaxer** [comment]
Let me know if you want any help with this, sounds awesome! (Unless you're writing it in Ruby... ;) )

**Comment by jdavis** [comment]
Nope, it'll be Python. I still have to learn Ruby :P

**Comment by computmaxer** [comment]
:heart: Everything you just said there is perfect.

**Comment by zach-taylor** [comment]
Hey now.. Ruby is a nice lady.
