### ISSUE TITLE
Patreon supports software tokens 

### ISSUE THREAD

**Issue by carlosjeurissen** [2factorauth/twofactorauth#2689]

**Comment by RichJeanes** [comment]
Can confirm. I've had it set up for a while. I don't know why they don't have a support doc telling you how to set it up, but it even mentions that they support TOTP at the bottom of the currently linked SMS docs.

**Comment by jamcat22** [comment]
Please see #2480 for prior discussion on this topic. If we determine that `software` can now be enabled on a new account that has never had it enabled, or we change our decision, then we could update the entry.

**Comment by RichJeanes** [comment]
Oh. I guess it would help if I read the whole message. Or slept. Sleep would probably be helpful.
