### ISSUE TITLE
Looks like someone steal your work

### ISSUE THREAD

**Issue by beerisgood** [2factorauth/twofactorauth#2709]
See: https://www.2fa.jetzt/dienste/

**Comment by mxxcon** [comment]
Yes, they are stealing our work. 😞 
And it's not like our license is so restrictive https://github.com/2factorauth/twofactorauth/blob/master/LICENSE 👎

**Comment by beerisgood** [comment]
You should contact them.
I will open a reddit thread so maybe this get more publicity.

**Comment by fpigerre** [comment]
@beerisgood, Our licence permits this sort of copying intentionally.
We like people translating the website into other languages, it helps people access and learn about 2FA 😃

**Comment by mxxcon** [comment]
@psgs well, not exactly. our MIT license requires for them to keep our license file and give us credit, which was not done anywhere on their site.
To quote github's own tldr:

> A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

**Comment by beerisgood** [comment]
*push*

**Comment by mxxcon** [comment]
@beerisgood we contacted them. waiting to hear back

**Comment by jamcat22** [comment]
This issue is resolved by ecsec/2FA.jetzt#13.

**Comment by beerisgood** [comment]
Nice to hear!
