### ISSUE TITLE
Apple TOPT is not available for all

### ISSUE THREAD

**Issue by clawfire** [2factorauth/twofactorauth#272]
I think if you start acting like USA is the center of the world and reference some system that are US only available without mentioning it, like Apple or Paypal, it's sad.

So FYI, Paypal and Apple doesn't support SMS TOPT outside US :(

**Comment by RichJeanes** [comment]
We are discussing how to handle this in #241.

**Comment by jdavis** [comment]
Oh, well I apologize that Apple and Paypal were both started in the US. Maybe the rest of the world can step-up and start innovating for once.

Regardless, thanks for the PR @clawfire, I'm addressing this now.
