### ISSUE TITLE
gmx.com, gmx.net, mail.com in email

### ISSUE THREAD

**Issue by lpn25** [2factorauth/twofactorauth#273]
Gmx.com, gmx.net and mail.com in Email, all owned by United Internet. None of them supports 2FA. Gmx.net and .com are rather large email providers in Europe.

**Comment by jdavis** [comment]
Being that they are from Europe, that explains why I've never heard of them. Let's hold off on adding these until we get the International section done.

**Comment by lpn25** [comment]
Makes sense, although there are already some international services listed (fastmail in email, gandi in domains).

**Comment by jdavis** [comment]
Cool, we'll have to address those once we figure things out in #241

**Comment by dsoegijono** [comment]
Added with #684
