### ISSUE TITLE
Doesn't work with Mozilla firefox

### ISSUE THREAD

**Issue by theREALaltoid** [2factorauth/twofactorauth#2740]

**Comment by mxxcon** [comment]
What doesn't work?

**Comment by jamcat22** [comment]
The main portions of the site seem to be working on my end on 64-bit Firefox's Stable, Developer's Edition (Beta), and Aurora builds on my Windows 10 computer running the latest Insider build.

Would you please be more specific as to the issue you've encountered? Please also include which operating system you're using and the [version of Firefox you're running](https://support.mozilla.org/en-US/kb/find-what-version-firefox-you-are-using).
