### ISSUE TITLE
Paypal, do they really have software auth?

### ISSUE THREAD

**Issue by CrossBound** [2factorauth/twofactorauth#2741]
I've looked into this and don't see a way to setup a software token based 2 factor authentication. It seems like only SMS is supported (even the link on this site points to a page where it only talks about SMS). I'd suggest removing the checkbox for software token based authentication and the hardware based authentication. 
If someone knows how to set up PayPal with an TOTP app I'd love to know how to do it so I could use it. 

If no-one disagrees I'm happy to create a pull request

https://www.paypal.com/us/selfhelp/article/how-do-i-order-or-activate-my-paypal-security-key-faq634

![image](https://user-images.githubusercontent.com/11417093/30727296-03b1aa20-9f16-11e7-9049-bc0b03664a62.png)

**Comment by Carlgo11** [comment]
Hello @PSCapng,
you can read everything there is to know about PayPal's 2FA system here: #1026 

Have a great day! 😃

**Comment by CrossBound** [comment]
Fair enough, that works

**Comment by Sunit-Kulkarni** [comment]
https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fcgi-bin%2Fwebscr%3fcmd%3d_setup-security-key

Here is a hidden link that will let you setup 2FA with VIP app
