### ISSUE TITLE
Job sites

### ISSUE THREAD

**Issue by Nicos18** [2factorauth/twofactorauth#2752]
I have several accounts with jobs providers (such as clickworker, spare5, appen, lionbridge, etc.). These kind of sites enter in your site criteria? If yes, I would to add this sites in the list

**Comment by mxxcon** [comment]
We do have linkedin under social category and Monster.com under other.
If the site fits in our criteria at https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria and decently popular (along the lines of alexa top 250k), ya, why not add it.

**Comment by Rfosu2k2** [comment]
@Nicos18, all of the sites you listed above are well under the alexa 200k.  Since you have several accounts with the job providers (freelance companies), could you provide an update to each of the 4 listed if they have or support 2FA, and which type if they do?
