### ISSUE TITLE
Add Xmarks

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#276]
Hi,

Xmarks is another service of LastPass.  So if you decide to login with your lastpass account, you'll benefit from that account's 2FA.

Regards,

Richard

**Comment by Ritchie007** [comment]
Anyone working on this one ??

**Comment by zach-taylor** [comment]
Well, we have LastPass on the list. Does that suffice?

**Comment by jdavis** [comment]
I think it does.

**Comment by mxxcon** [comment]
But Xmarks is a separate installable app..does it actually support all the same 2factor auth features as LastPass proper?

**Comment by Ritchie007** [comment]
Actually, you can use your LastPass ID (with 2FA) to log in to XMarks, but you can also have a separate log in:password.  That's because XMarks used to be independent until LastPass bought it.
