### ISSUE TITLE
Add Feedly

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#277]
Feedly users can login from the following methods 
- Google
- Facebook
- Microsoft
- Yahoo!

Regards,

Richard

**Comment by jdavis** [comment]
Hey Ritchie, thanks for this info. The only thing I'm wondering about is the importance of 2FA for an RSS reader. While it is a great feature, I just can't imagine the kind of damage that could be done if compromised.

Also with the plethora or OAuth providers/login's available, I think there are plenty of options to keep Feedly secure.

**Comment by Ritchie007** [comment]
The more secure the better, I'd prefer that nobody could find what type of news I subscribe too.

On the case of Feedly, you can't create an account for Feedly per say, you have to use one of the 4 account services named previously.

**Comment by jdavis** [comment]
Oh, well that's even better if Feedly doesn't offer their own account creation. Thus it must use OAuth from other providers and still protectable through 2FA from the other providers, thus it is basically already documented on 2FA.org and doesn't need to be added again.

Sorry for shooting it down, I really appreciate your contributions. I just want to be selective about what we add now considering the attention the site is getting.

**Comment by Ritchie007** [comment]
Maybe adding a special table to list all those sites that use accounts through OAuth providers.

**Comment by migueldemoura** [comment]
Feedly allows you to create an account *without* using 3rd parties (OAuth). Although the damage in the event of a breach is low, I still think it is of value to add it to the list.

**Comment by RichJeanes** [comment]
This issue was closed over two years ago. Please do not create zombie threads. If you would like to see the addition of this site discussed, please open a new issue.
