### ISSUE TITLE
Feature Request: Show list of recently added sites

### ISSUE THREAD

**Issue by andmpel** [2factorauth/twofactorauth#2792]
It would be nice to be able to come to the site periodically and view what are the latest sites that have enabled 2FA. Or to get an email digest of the latest sites that have added 2FA support.

**Comment by stephengroat** [comment]
@AMP648 thanks for the suggestion!

i'm not closing this issue because i don't think it's a great idea, but we already have some discussion & code in #2159. if you have any more feedback, please just add it to that thread!
