### ISSUE TITLE
Add Wunderlist

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#281]
Hi,

GTD App on the Web and on iOS, www.wunderlist.com is not yet 2FA, but this reply to my request from Tech Support suggest by Year End

---

Dominic Mar 20, 2014 01:57PM CET
Hi Richard,

Thanks for getting in contact. 2 step-auth has already been discussed within the team, and is something we will likely implement later in the year after the release of our next major update, Wunderlist 3.

In the meantime, we also encourage all of our users to post their suggestions for future features and vote up similar suggestions on our UserVoice website, as we base our choices for future features on what our users most request. The link is:

http://wunderlist.uservoice.com/
Regards from Berlin,
Dominic

**Comment by jdavis** [comment]
Whoa, that's pretty cool. Do you want to add it to the list with another pull request?

**Comment by Ritchie007** [comment]
Josh, Being new to GitHub, I'm having some issues :

1) What tools on Mac OS X could I use to convert images to 32x32 png files ?
2) I can't find a way to add the files to my repository ?
3) How do I update my repository copy so that it syncs to be equal to the master before making a change and pushing it towards the master ?
4) I'm working directly off the web site for GitHub, maybe I should use a sotfware on the Mac ?

Cheers,

Richard

**Comment by mxxcon** [comment]
@Ritchie007 what category should this go to? I can add it.

**Comment by jdavis** [comment]
My vote is for Other, @mxxcon.

**Comment by Ritchie007** [comment]
Fine with me !

Cheers,

Ritchie

---

Richard Migneron
📩 : richard@migneron.com
☎ : +33 6 52 22 84 76
iMessages : richard@migneron.com
Skype : rmigneron
about.me/richardmigneron

**Comment by jdavis** [comment]
Closed by #318
