### ISSUE TITLE
Should an Exception or Note be Added to Norton?

### ISSUE THREAD

**Issue by Jawshy** [2factorauth/twofactorauth#2820]
During the setup process for adding two-factor authentication to a user's [Norton](https://my.norton.com/) account, Norton asks the user to enter their mobile phone number to which Norton will send a link to download their VIP Access app. 

Normally this would definitely be something to mention as an [exception](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#exceptions--restrictions). However, their VIP Access app can also be downloaded via [Symantec VIP - Two Factor Authentication Anywhere](https://idprotect.vip.symantec.com/). 

Should an exception or note be added to Norton that links to the download webpage?

**Comment by jellemdekker** [comment]
Is Norton's 2FA only supported through their own VIP Access app? It seems to me it's sort of a replacement for Google Authenticator or Authy etc. Or is the VIP Access app only used to secure Norton accounts?

**Comment by Jawshy** [comment]
This article has more information: [Two-factor authentication for Norton account](https://support.norton.com/sp/en/us/home/current/solutions/v100023155_NortonM_Retail_1_en_us).
