### ISSUE TITLE
Note: Namecheap's software token 2FA is only available through the Namecheap mobile app

### ISSUE THREAD

**Issue by ChillyHellion** [2factorauth/twofactorauth#2823]
Namecheap's software token 2FA is only available through the Namecheap mobile app (and not through a standard TOTP authentication app.  This should probably be noted as a restriction next to their entry in this list.

**Comment by jscott0** [comment]
Namecheap also offers it through SMS, although it is true that its software token is only through its mobile app and not through usual software authenticators like Google Authenticator.

**Comment by stephengroat** [comment]
Thanks for the info @ChillyHellion and @JohnScott623!

We currently don't differentiate between TOTP/HOTP based `software authentication` and other, proprietary types of auth (too much info for us to update right now!)

If we ever get around to it, we'll make sure to update it

**Comment by ChillyHellion** [comment]
Fair enough, thank you for the response, Stephen, and happy holidays!
