### ISSUE TITLE
Show whether sites will set up Google Authenticator *without* requiring a mobile number

### ISSUE THREAD

**Issue by unikitty37** [2factorauth/twofactorauth#283]
Evernote's setup process for Google Authenticator requires an SMS, thus excluding people who don't use mobile phones or who don't wish to provide their mobile numbers to businesses (in my experience, they all decide to spam you eventually).

Please could you indicate which sites actually do Google Authenticator _properly_, without requiring a mobile number (such as Dropbox and Github) and which ones are using it as an excuse to harvest mobile numbers?

**Comment by mxxcon** [comment]
Why would they do sms for google authenticator? afaik you can set it up by scanning a QR code or manually entering  relevant seed number..where does sms come into play here?

**Comment by RobFreiburger** [comment]
It's likely a backup solution in case if the Google Authenticator app data gets wiped or lost.

**Comment by jdavis** [comment]
We have taken off Google Auth from the list. Check out the new table. Feel free to open a new issue if this isn't satisfactory =]
