### ISSUE TITLE
Please add Microsoft To-Do

### ISSUE THREAD

**Issue by MashiroYae** [2factorauth/twofactorauth#2830]
- name: Microsoft To-Do
   url: https://todo.microsoft.com/
   tfa: Yes
   sms: Yes
   software: Yes
   doc: http://windows.microsoft.com/en-us/windows/two-step-verification-faq

**Comment by Jawshy** [comment]
Hello, @InoriHeart. Thanks for your interest in twofactorauth. Microsoft services are currently listed under several different categories. What [category](https://github.com/2factorauth/twofactorauth/tree/master/_data) do you think Microsoft To-Do should be listed under?

**Comment by MashiroYae** [comment]
Task

[Your Preview of Microsoft To-Do](https://www.wunderlist.com/blog/your-preview-of-microsoft-to-do/)
[Microsoft To-Do is a new app that replaces Wunderlist](https://www.theverge.com/2017/4/19/15357992/microsoft-to-do-app-wunderlist-replacement-outlook-office)
