### ISSUE TITLE
Please Add East Carolina University to the Education category for 2fa

### ISSUE THREAD

**Issue by cardassian-tailor** [2factorauth/twofactorauth#2838]
ECU has been working to implement 2fa and it is now available for use. Some documentation can be found here. 

http://www.ecu.edu/cs-itcs/office365/multi-factor-authentication.cfm  

Thank you. 

https://www.ecu.edu

**Comment by cardassian-tailor** [comment]
Is there anything I can do to help make this occur @Jawshy  ?

**Comment by mxxcon** [comment]
You are welcome to create a pull request to add it.

**Comment by cardassian-tailor** [comment]
@mxxcon @Jawshy  do i have to create the png image along with it? What size should i make the png image?

**Comment by mxxcon** [comment]
@cardassian-tailor you can use this image
![ecu](https://user-images.githubusercontent.com/847140/34808014-f31a75ac-f659-11e7-8fbe-59bbf55df630.png)
But in general logos should be 32x32 and under 2500 bytes in size.

**Comment by stephengroat** [comment]
closed by #2939
