### ISSUE TITLE
Yammer info slightly outdated

### ISSUE THREAD

**Issue by jnievele** [2factorauth/twofactorauth#2844]
Yammer does support 2FA if your company uses O365/Azure integration - in that case, the same authentication you use for example for O365 Webmail also applies for Yammer

**Comment by Carlgo11** [comment]
Hello @jnievele,
We don’t list third party authentication systems for sites. If we did, all sites using OAuth would be listed as supporting 2FA.

**Comment by jnievele** [comment]
Then Skype also shouldn't be mentioned. Yammer belongs to Microsoft, just like Skype...

**Comment by mxxcon** [comment]
But you can't login into Skype with anything but Microsoft account.

**Comment by jnievele** [comment]
You can't create new accounts anymore - but the old pre-Microsoft accounts still work AFAIK. At least consider adding a note to the Yammer entry that it does support 2FA when used with a Microsoft account...

**Comment by mxxcon** [comment]
See #2217 discussion regarding Skype.

Regarding yammer, is login page for MS account different from https://www.yammer.com/login ?

**Comment by jnievele** [comment]
Same as for the rest of O365 - you type in your email address, then the system realises that your domain is supported, and it jumps to the appropriate login page - for example for me, it will then check whether I'm connected to the corporate network directly (no 2FA necessary) or I'm on the Internet elsewhere (in which case I will get a phone call). I get the same login for OWA, OneDrive and Sharepoint Online.

**Comment by RichJeanes** [comment]
So it is just an OAuth scheme? Then it does not support native 2FA and it should be listed as such.
