### ISSUE TITLE
Add SAML/OpenID connect support for self-hosted 2FA

### ISSUE THREAD

**Issue by nowen** [2factorauth/twofactorauth#285]
SAML/OpenID connect would allow you or your organization to control the authentication server.  Google Apps allows this, for example.  

This provides some protection and far greater control.

**Comment by mxxcon** [comment]
There's now `Identity Management` section, so I imagine your WiKID would go there. Feel free to contribute accurate information. :)

**Comment by RichJeanes** [comment]
I feel like this has come up before but I can't seem to find the issue thread... @jdavis I seem to recall that you shot down the idea of listing services that allow you to host your own 2FA...
Please correct me if I'm wrong.

**Comment by mxxcon** [comment]
@RichJeanes service that support such integration is different from services that provide such integration.. I think SAML services that support 2FA are a good match for `Identity Management` section.
Don't you think so?

**Comment by jdavis** [comment]
Yeah, I don't agree with having self-hosted solutions that support 2FA on the site unless I heard a compelling argument in favor of it.

Hmm, I'm a bit ignorant of SAML and might have to read up more on it to decide.

**Comment by mxxcon** [comment]
Bumping this up again..With commits like #547 we should probably make a decision one way or the other when it comes to services that support SAML intergration.

**Comment by smholloway** [comment]
My initial reaction is that SAML integrations and SSO tie-ins are outside the scope of this site. Theoretically, any site could support third party authentication systems, but configuring a single sign-on then enabling 2fa feels very different than simply enabling 2fa. Perhaps the criteria is something like this: is 2fa part of the standard user login and can it be enabled in one step?

**Comment by ben-dearmond** [comment]
"Security is important, @RightScale. We'd like it if you supported two factor auth. http://twofactorauth.org  #SupportTwoFactorAuth"

It _is_ possible to implement a 2FA solution with SAML SSO on RightScale, as username/password authentication can be disabled, so the veracity of the twitter share "depends on what your definition of is is".

**Comment by mxxcon** [comment]
SAML is just a mechanism for a site to ask some designated destination if this user is allowed in or not. How that destination verifies that user is irrelevant to the site. In some cases it can be 2fa, in other it's a colonic map :wink:
It's up to the SSO provider to support 2fa.
@smholloway So I think a more accurate statement would be "any site that support SAML/SSO could support 2fa".

**Comment by jdavis** [comment]
I agree with @smholloway regarding this.

There's a bit of a grey area as well. If a site allows you to login using Google and Facebook, then those without a doubt offer 2FA. I've seen plenty of sites that right after you use Google/Facebook they ask for a password to finish creating your account.

Or even if a site adds Google/Facebook later on. The password login would still be there and not require 2FA while using Google/Facebook would.

My response is that SAML and SSO are great; but I don't think that's what we want to capture on the site. I am open to my position it if I hear a compelling argument and a way to represent these problems on the site.

I'll leave this open for a few days to get some responses and then close it.

**Comment by mxxcon** [comment]
I think SAML/SSO is a bit different than sites which allow google/facebook logins.
SAML completely replaces the login system, not amends it like social logins...at least that's what companies expect it to do.

**Comment by jdavis** [comment]
Ahh, you're totally right. I knew that SAML wasn't like social logins.

In the past I've heard people refer to those logins as being SSO's. I was reading the SAML Wikipedia page but didn't look at the [SSO](http://en.wikipedia.org/wiki/Single_sign-on) one.

Apparently other people had my issue as well:

> Other shared authentication schemes not to be confused with SSO include OAuth, OpenID, OpenID Connect and Facebook Connect, which require the user to enter their login credentials each time they access a different site or application.

**Comment by nowen** [comment]
If the idea is really that some services allow you to run your own server
or, more likely, your company control the access and keys, then it might be
best as another list.  One battle at a time perhaps, but I also wish it was
being 'done right the first time', but perhaps that's just my version of
right.  ;-)
ᐧ

On Mon, Jun 9, 2014 at 5:38 PM, Josh Davis notifications@github.com wrote:

> Ahh, you're totally right. I knew that SAML wasn't like social logins.
> 
> In the past I've heard people refer to those logins as being SSO's. I was
> reading the SAML Wikipedia page but didn't look at the SSO
> http://en.wikipedia.org/wiki/Single_sign-on one.
> 
> Apparently other people had my issue as well:
> 
> Other shared authentication schemes not to be confused with SSO include
> OAuth, OpenID, OpenID Connect and Facebook Connect, which require the user
> to enter their login credentials each time they access a different site or
> application.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jdavis/twofactorauth/issues/285#issuecomment-45547772
> .

## 

Nick Owen
WiKID Systems, Inc.
http://www.wikidsystems.com
Commercial/Open Source Two-Factor Authentication
http://twitter.com/wikidsystems | #wikid on freenode,net

**Comment by jdavis** [comment]
After looking at it closer, I still think it is outside the scope of the site, as @smholloway put it. I'm closing this for right now as in its current form, it wouldn't fit anywhere on 2FA.org.
