### ISSUE TITLE
Sprint needs updating

### ISSUE THREAD

**Issue by ntman1** [2factorauth/twofactorauth#2864]
Sprint now uses SMS to provide customers 2FA

**Comment by jellemdekker** [comment]
Please give us a link to this announcement or to an article with documentation of their 2FA options.

**Comment by ntman1** [comment]
A description is available here - SOLUTION: Sprint.Com Password Requirements -https://community.sprint.com/t5/Account-Billing-Payments/SOLUTION-Sprint-Com-Password-Requirements/ta-p/943334

I grabbed two screenshots (attached) to see it in action – including the SMS from my phone showing on the second screenshot via PushBullet.

![sprint 2fa screenshot-1](https://user-images.githubusercontent.com/33769104/33340924-5da42282-d44b-11e7-84cd-0a2c31adf1e0.JPG)

![sprint 2fa screenshot-2](https://user-images.githubusercontent.com/33769104/33340926-606d098e-d44b-11e7-9a33-22ad3f354c13.JPG)

[Edit by jamcat22: Cleaned up email.]

**Comment by jamcat22** [comment]
@ntman1, please use the GitHub website to upload screenshots. File and photo uploading is not supported by the email relay.

**Comment by ntman1** [comment]
OK - I corrected the posting. The screenshots are now embedded.

**Comment by Carlgo11** [comment]
Closed as per #3068
