### ISSUE TITLE
PNC Bank needs updating

### ISSUE THREAD

**Issue by thurm1nator** [2factorauth/twofactorauth#2877]
PNC Bank now supports 2FA via SMS. Hooray! https://www.pnc.com/en/customer-service/update-center/sign-on-changes.html

**Comment by jamcat22** [comment]
Thanks for letting us know @thurm1nator! The change has been merged and will be available on the live site soon. You can learn more about how changes are pushed to the live site on our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).
