### ISSUE TITLE
www.dhl.de supports 2FA by Email

### ISSUE THREAD

**Issue by Eastpak1984** [2factorauth/twofactorauth#2882]
Hi, could you please add DHL to your side? They support 2FA by Email.

Thank you!

**Comment by mxxcon** [comment]
is DHL.de separate login from other sites like dhl.com?

**Comment by Eastpak1984** [comment]
i Cant find any option to login at www.dhl.com. I meant www.dhl.de - there does my login work.

**Comment by Carlgo11** [comment]
Is it the same as [MyDHL](https://www.mydhl.dhl.com/)?

**Comment by Eastpak1984** [comment]
No, my login data doesnt work there. Seams to be different.

**Comment by kmpoppe** [comment]
@Carlgo11 @Eastpak1984 
MyDHL is a service for DHL Express, the business customer service, does not provide 2FA and is not Alexa-ranked.
DHL.com doesn't have logins, as you're being redirected to a country-specific page.
DHL.de (as in this Issue) has its own login-concept for private costumers (with email 2FA), that is not identical with MyDHL.
I think that would qualify for an entry.
