### ISSUE TITLE
Capital One 360 software 2FA is weak

### ISSUE THREAD

**Issue by scovich** [2factorauth/twofactorauth#2891]
Capital One 360 claims a push-based 2FA mechanism, but in order to use it you have to log into their mobil app on your device using normal username password. The mobile device thus remains as a weak link because anyone who compromises it can just access your account directly; why bother messing with the other 2FA-protected devices at that point?

**Comment by alecbw** [comment]
The explainer video on their splash [page](https://www.capitalone.com/identity-protection/swiftid/) implies 2FA is capable of being enabled on the webapp, though neither the instructions nor a service rep could describe how to actually set it up. At this time it appears 2FA only actually works for the mobile apps via sending an email code auth.

**Comment by ghost** [comment]
Agreed with @alecbw.  Spent 30 minutes on the phone with tech support and SwiftID would not work. Additionally the help desk, SwiftID is not available. The 2FA software is absolutely worthless if SMS and email codes cannot be disabled. It is up to the individual logging in how they want to receive the code, so of course an attacker would pick whichever they could easily control. I disagree with @scovich to an extent, the mobile device is MUCH better than SMS/Email (i.e. Google's 2FA push actually works and lets you disable all other 2FA methods after initial setup)

**Comment by ryancwalsh** [comment]
I agree. https://www.capitalone.com/identity-protection/swiftid/ feels like security theater. Probably useless. Very disappointing for a major bank to not take security seriously.

**Comment by Carlgo11** [comment]
>What about these verification methods? They seem to be used for logins as well.
https://www.capitalone.com/support-center/bank/what-is-otp
https://www.capitalone.com/digital/mobile-app-verification/
 \- @phallobst https://github.com/2factorauth/twofactorauth/issues/6170#issuecomment-936680085
