### ISSUE TITLE
Chase 2FA is unreliable and has a major security hole 

### ISSUE THREAD

**Issue by schwit61** [2factorauth/twofactorauth#2898]
https://github.com/2factorauth/twofactorauth/issues/1548
IMO 2FA needs to happen every time you login. Chase does 2FA the first time and never there after if it recognizes the source system. Chase says clearing cookies reenables 2FA. Not true. 

So, Chase 2FA won't help if your device is stolen or malware is running on your system.

Tested with IE11, Chrome 63, Firefox 52.2.2ESR and Firefox 57.0.2 on multiple systems.

**Comment by RichJeanes** [comment]
Please do not open new issues to reiterate on closed issues without new information or changes to the discussion. This does nothing but clutter the repo for no productive purpose.

If you read through that thread you linked to, solid points were laid out as to why Chase (among many other banking institutions) are listed as implementing 2FA. At this point, those arguments stand for listing criteria. I would suggest that you contact Chase to provide feedback about their implementation and maybe they will listen if they get enough customer engagement on the issue.
