### ISSUE TITLE
1Password has abandoned Two-Factor, but claims it is not needed.

### ISSUE THREAD

**Issue by alset333** [2factorauth/twofactorauth#2929]
Not to resurrect #2245, but a [support page](https://support.1password.com/authentication-encryption/) mentions the following:

> The 1Password apps don’t need two-factor authentication. 1Password accounts use Two Secret Key Derivation (2SKD) to make sure no one can access your data without both your Master Password and your Secret Key.

Not really sure how it should be listed on the 2FA website.

**Comment by mxxcon** [comment]
🤦‍♂️ 1pass has a pretty "unique" ideas of security.
If you search our issue history you'll see pretty extensive discussions on 1pass. 🙄
I'm of the mindset that they are `tfa:no`, but I don't know...

**Comment by jamcat22** [comment]
Have they removed the [Duo Security integration beta](https://duo.com/docs/1password) from their Teams product? Last I heard they still offered it, but it was in beta and only available to those with a Teams subscription.

**Comment by mxxcon** [comment]
It's gone.
<img width="812" alt="screen shot 2018-01-03 at 9 15 51 am" src="https://user-images.githubusercontent.com/847140/34523748-c8784660-f066-11e7-8fcf-815cbec3d62d.png">

  This is what it used to look like before
<img src="https://duo.com/assets/img/documentation/1password/1password-mfa-options_2x.png">

**Comment by Carlgo11** [comment]
Here we go again... 😒 
It's a clear `tfa: no` for me

**Comment by stephengroat** [comment]
closed by #3092
