### ISSUE TITLE
Facebook does not require SMS for 2FA

### ISSUE THREAD

**Issue by brycx** [2factorauth/twofactorauth#2935]
Hey!

I recently enabled 2FA on a Facebook account without the use of SMS. Required instead was: a 2FA app for the phone and a U2F security key. The warning on the [site](https://twofactorauth.org/#social) says SMS is needed for 2FA on Facebook, maybe instead it should say "Depends on two independent 2FA methods"?

**Comment by Jawshy** [comment]
Thanks for pointing out that inaccuracy, @brycx. Would you like to submit a pull request?

**Comment by brycx** [comment]
Gladly.

**Comment by brycx** [comment]
Fixed in #3217.
