### ISSUE TITLE
Misinformation in Steam warning

### ISSUE THREAD

**Issue by matt-t-jones** [2factorauth/twofactorauth#2936]
The warning next to Steam states that "It does not support multiple accounts on the same device." which is incorrect.

**Comment by Jawshy** [comment]
Thanks for pointing out that inaccuracy, @matt-t-jones. Steam does support multiple accounts on the same device and using the same phone number. Would you like to submit a pull request?

**Comment by brycx** [comment]
If you don't want to @matt-t-jones I have no problem picking it up.
