### ISSUE TITLE
GSBank rebranded to Marcus - and has 2FA

### ISSUE THREAD

**Issue by maxgrifka** [2factorauth/twofactorauth#2940]
GSBank.com no longer exists and has been rebranded to Marcus.  It currently supports both email and SMS 2FA.

**Comment by kmpoppe** [comment]
@maxgrifka Can you supply documentation to the 2FA from their website? As I can't have an account with Marcus Goldman Sachs, I can't use Register for a LogIn.
Thanks.

**Comment by maxgrifka** [comment]
@kmpoppe Sure - it's actually spoken about in the security center portion of the site.  https://www.marcus.com/us/en/banking-with-us/security-center

Multi factor is on by default (not opt-in) and supports SMS/Email currently.  

Multi-factor Authentication
Marcus uses multi-factor authentication to help us authenticate you. Multi-factor authentication is an additional layer of security to help protect your account from unauthorized access. You can conduct your online banking with confidence, knowing you are communicating only with Marcus.

**Comment by kmpoppe** [comment]
Checking with Marcus UK what they say about 2FA (https://twitter.com/kmpoppe/status/1133100645714726912).

**Comment by kmpoppe** [comment]
Closed by #3900
