### ISSUE TITLE
Missing GeoTrust Docs Link

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#295]
I can't seem to find any documentation that GeoTrust offers 2FA for account logins. Anyone able to sniff out some info for this? Also appears that RapidSSL is a subsidiary of GeoTrust and they share support and login systems, so one would apply to the other.

**Comment by jdavis** [comment]
Yeah, it does look like they are owned by the same company: http://stackoverflow.com/a/5062656. Shall we simplify a bit and just have Geotrust?
