### ISSUE TITLE
Contribution guidelines - Requiring HTTPS links if the site supports it

### ISSUE THREAD

**Issue by brycx** [2factorauth/twofactorauth#2955]
I think it would make sense to have a rule, or at least mention, that sites which support SSL should also be linked with HTTPS. Some sites automatically redirect to HTTPS and some don't. Not everyone forces HTTPS in their browser either. In any case I think it generally would be good practice to require SSL links when available.

Could such a rule/mention be added to `CONTRIBUTING.md`?

**Comment by mxxcon** [comment]
Seems logical to me. 👍
