### ISSUE TITLE
Please add OMOC.interactive for 2FA

### ISSUE THREAD

**Issue by omocinteractive** [2factorauth/twofactorauth#2974]
We support a 2FA for our login to the room-managment-system:

https://www.online-raumverwaltung.de/

(see "Demo" and " Anmeldung mit 2-Wege-Authentifizierung" in the Top-Menue ...

thx!

**Comment by Jawshy** [comment]
Hi, @omocinteractive. What [method](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Categories) is used for the second factor?

**Comment by omocinteractive** [comment]
Hi,

we use the software based google authenticator.

Kind regards, Andreas

**Comment by Carlgo11** [comment]
Closing this issue as per #3036.
