### ISSUE TITLE
2FA without staff recovery option can be dangerous/desired, warn/inform about it

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#2983]
When companies implement 2FA, they can choose between two philosophies:

- The user is a security&computer expert who is constantly under attack by extremely powerful adversaries. Someone activating 2FA needs to know the risk of irrevocably losing access to their account. If the user is not willing to deal with this risk, they should never activate 2FA.
- The user is not necessarily careful in what they do. We're dealing with a "normal" kind of computer user who likes the idea of 2FA but needs to ask for assistance when their phone is lost. Note: not "if" their phone is lost. **When** their phone is lost. Because this will certainly happen.*

There are services like iCloud that allow you to setup 2FA but do not offer a "last resort" way to restore access to the account. This explicitly includes the inability of staff helping you in any way to get access to the account. If you lose your "backup recovery codes", your account is permanently locked. No human can help you to solve this problem. If I remember correctly, GitHub behaves similarly.

When you lose your Google account's 2FA device, you can contact Google's support to regain access after proving your identity. Authy offers a similar process. This might include using a government-issued identification card.

For some very extremely paranoid people, the iCloud/GitHub solution might be desirable. However, when we want 2FA to become the normality, this philosophy suddenly fails in a very cruel way.

-----

*Sounds unlikely? Not if you take time into account. A young person registers a GitHub account and uses it until they die. If you are doing something for 80 years, it is quite possible that it will go wrong at least once.

**Comment by ghost** [comment]
Yes, I was right about GitHub:

"Warning: For security reasons, **GitHub Support may not be able to restore access to accounts with two-factor authentication enabled** if you lose your phone, don't have access to your recovery codes, or don't have an account recovery token stored. For more information, see 'Adding a fallback authentication method with Recover Accounts Elsewhere.'"

https://help.github.com/articles/about-two-factor-authentication/

This sucks for me. It's the reason I'm not using it here. @github

**Comment by Carlgo11** [comment]
Hello @ToBeFree,
thank you for your feedback!

We, the team, have had this discussion before and have come to the conclusion that it's better to keep the design of the site as clean as possible to make it easier for people that are completely new to 2FA to use the site.
If you could come up with a way to display this without adding another field to the list we'll certainly take another vote on the issue but as of right now our standpoint is that this won't be implemented.

Sorry I couldn't be of any more help! 😞 
//Carl

**Comment by ghost** [comment]
Hey, thanks!

Hmm. Maybe we shouldn't recommend these dangerous implementations to 2FA beginners? We could remove them entirely. ;)

Another idea: There is already a way to add a warning (red ⚠️ sign) to entries in the list. We could use it to add a general warning text about this issue wherever needed. Possible text suggestion:

"When losing your password and your 2FA token, staff might not be able to restore access to your account, not even if you can prove your identity. This is a strict security measure that can lead to unpleasant surprises."

**Comment by RichJeanes** [comment]
That's a rather large exception that would need to be added to a lot of websites. Typically services that operate in this fashion provide their own warning to users about this scenario.

Fastmail:
![image](https://user-images.githubusercontent.com/6753081/35922562-1eb52464-0bdb-11e8-9266-4e351decd832.png)

GitHub:
![image](https://user-images.githubusercontent.com/6753081/35922745-964fc8d0-0bdb-11e8-9d83-724cb7d07e1d.png)

I think it's fair to place a little onus on the user to read what they're going through when setting up 2FA on their accounts. I also think that once we start using more and more generic exceptions, they start to mean less to the end user. The whole point is for it to stand out which it can't really do if a considerable number of entries have an exception on them.

**Comment by Carlgo11** [comment]
Plus, most 2FA apps support some sort of syncing or backup of codes. Authy, Duo Security, 1Password.
Unless you use Google Authentication you pretty much don't have to worry about losing your codes.

**Comment by ghost** [comment]
I'm afraid that one day one of you will be in the situation I tried to avoid ;)

**Comment by ghost** [comment]
But yes, taking this specific suggestion any further is basically questioning the whole idea of recommending most 2FA services to beginners. Google does it in a newbie-friendly way that I can and will recommend to anyone, but GitHub and many others don't. We won't change this – this criticism would probably be better directed at the implementing companies. Closing the issue because it is not relevant if the project doesn't drastically change its main principles. :)
