### ISSUE TITLE
Thoughts on adding .travis.yml to list?

### ISSUE THREAD

**Issue by kenman345** [2factorauth/twofactorauth#2993]
https://github.com/2factorauth/twofactorauth/blob/365fc7b491d07dc51d3b5da14df03f0d075c6fb7/_config.yml#L13

Hey, Just wondering if a thought had occurred to include .travis.yml in the exclude tag. Trying to wrestle with doing it myself for our acceptbitcoincash/acceptbitcoincash fork.

**Comment by mxxcon** [comment]
what kind of problems is it causing? 🤔

**Comment by kenman345** [comment]
I just like cleanliness and figured I’d ask

**Comment by Carlgo11** [comment]
Exclude makes Jekyll not include any of said files on the public website. There's no reason for files like CNAME, Gemfile or Rakefile to be on the public facing site and so it's excluded from the build.

**Comment by Carlgo11** [comment]
Whops, I didn't read the entire issue. Sure, the travis file could be added there. I'll make a PR for it now.

**Comment by Carlgo11** [comment]
See #3029
