### ISSUE TITLE
Capital One WEBUI 2FA is flawed

### ISSUE THREAD

**Issue by schwit61** [2factorauth/twofactorauth#2994]
On the first login Capital One uses 2FA and identifies the source device via the browser’s user-agent. All subsequent logins using the same browser and device fail to use 2FA. I get the same results on multiple systems with multiple browsers. Clearing browser cookies does not help. The only thing that reenables 2FA is changing the browser’s user-agent and again only the first time you log in with that user-agent.

**Comment by mxxcon** [comment]
Unfortunately, many sites work like that where they don't prompt you for 2fa on every login. :(

**Comment by RichJeanes** [comment]
Please see my comment on #2898 and please do not open essentially duplicate issues for the same topic.
