### ISSUE TITLE
Add CSP and other headers to github pages

### ISSUE THREAD

**Issue by nitrocode** [2factorauth/twofactorauth#2995]
Noticed the [securityheaders.io scan results](https://securityheaders.io/?q=https%3A%2F%2Ftwofactorauth.org&followRedirects=on) gave this site a D due to these missing headers

* Content-Security-Policy - [enabled using meta tag](http://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog)
* X-Frame-Options - unsure if this is possible
* X-XSS-Protection - unsure if this is possible
* Referer-Policy - unsure if this is possible

Original issue closed when even fewer headers could be enabled on github pages: https://github.com/2factorauth/twofactorauth/issues/1527

**Comment by ghost** [comment]
None of these are possible with GH. You could use Cloudflare workers to add the headers at the edge but they cost money.
