### ISSUE TITLE
Fidelity - Kind of Two Factor Authentication

### ISSUE THREAD

**Issue by wooster11** [2factorauth/twofactorauth#301]
Fidelity's response to the tweets has been the following:

We have strong protections in place: http://go.fidelity.com/safe .  Customers can also request two-factor authentication.

Not exactly we're going to fix this but not exactly wrong either.

Although they don't support Two Factor Authentication in the purest sense - as a requirement for logging in - they do offer something similar called Transaction Security which requires a code sent via text to be entered before allowing a transaction to take place.

I don't know if there's a place on your site to indicate this or not, but it might be something worth mentioning.

The main problem with their implementation is that it still allows whoever is logged in to still see balances and holdings - and allows for access to lots of other stuff.

**Comment by jdavis** [comment]
Yeah, I'm aware of this. I got a GuerillaMail yesterday from someone saying the exact same thing.

However, this has come up in the last few days and I won't budge as I didn't in #190.
