### ISSUE TITLE
Twitter no longer requires SMS for 2FA

### ISSUE THREAD

**Issue by carlylemiii** [2factorauth/twofactorauth#3014]
Title.

This is listed as an exception, but this (thankfully!) isn't the case anymore.

**Comment by brycx** [comment]
If I take a look at the [docs](https://support.twitter.com/articles/20170388) it says:
> Note: In order to set up login verification, you need to have a phone number associated with your Twitter account. This requirement is in place for account recovery.

Is this not the case? If it is, maybe just rephrase the exception to something like "Phone number associated with account required for 2FA"?

**Comment by carlylemiii** [comment]
Sure, that would work. I guess I do still have a phone number attached to my account, but I don't have SMS enabled anymore, since they made the change in December:

https://www.androidpolice.com/2017/12/20/twitter-can-finally-two-factor-authentication-without-sms/
