### ISSUE TITLE
Add KLM or modify Air France

### ISSUE THREAD

**Issue by ocsi01** [2factorauth/twofactorauth#3031]
KLM and Air France has two separate website with different functionality, however the login methods are both tied to FlyingBlue accounts.
I would suggest to modify Air France to Air France/KLM ( Flying Blue) or create separate entries to:

- Air France ( already exists )
- KLM
- Flying Blue ( optional )

**Comment by mxxcon** [comment]
On KLM's website it says
https://www.klm.com/home/gb/en#/tab=hpTbIci&g_np_mya-overlay=1&mya-np=0
> log in with your KLM or Flying Blue account 

does it mean they have 2 login systems?

**Comment by Carlgo11** [comment]
@mxxcon they have 2 systems.
1. Flying Blue account
2. Booking code + family name.

Air France has both Flying Blue accounts and Air France accounts (because why just have one? 🤦‍♂️)
Both airlines also support login via social media (Facebook and LinkedIn)
