### ISSUE TITLE
T-Mobile

### ISSUE THREAD

**Issue by htmlarson** [2factorauth/twofactorauth#3033]
T-Mobile recently started supporting ***SMS-Only*** 2FA.

**Comment by stephengroat** [comment]
thanks for the info @htmlarson 

do you have any documentation or could you provide an edited screen shot?

do you know if it's requesting authentication to login or just for sensitive account actions?

**Comment by htmlarson** [comment]
<img width="774" alt="screen shot 2018-02-22 at 12 28 14 pm" src="https://user-images.githubusercontent.com/18153857/36562432-e0270ecc-17cb-11e8-885d-62a9b6b5caf8.png">
