### ISSUE TITLE
Generic columns headers need explanation/clarification

### ISSUE THREAD

**Issue by guntbert** [2factorauth/twofactorauth#3037]
The two generic headers (*hardware token*, *software token*) need a little explanation.

I suggest (to preserve screen real etstate) attaching an :information_source: icon and on hover showing a popup with a short explaining text and a few examples (non-exhaustive of course).

**Comment by mxxcon** [comment]
what kind of explanation text do you think it should have?

**Comment by guntbert** [comment]
Giving it a try:

- Hardware Token
  > A physical item you have to insert/attach
  > e.g. Yubikey, FIDO, ...
- Software Token
  > A program running on your phone, that will provide an additional code
  > e.g. Google Authenticator, Authy, ...

(The rationale: I had to think a little to understand the meaning of the column titles, and I am not new to security :smile_cat: )
