### ISSUE TITLE
Bank of America incorrect - no hardware MFA

### ISSUE THREAD

**Issue by jantman** [2factorauth/twofactorauth#3041]
Perhaps @jdavis who [originally added the info](https://github.com/2factorauth/twofactorauth/commit/4d8058e87560f6f01f4af2a9bc7fca694a1f28e9), or @swrobel or @urlicht who have made changes to the BofA information, know more about this, but the current Bank of America [document linked on SafePass](https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/safepass.go) says that it's SMS-based not hardware, and that it's "required in Online and Mobile Banking to authorize higher-value transfers" but doesn't say anything about overall opt-in.

I'm a BofA customer, and haven't been able to find any confirmation that they offer hardware 2FA.

**Comment by jantman** [comment]
I just wanted to see if I'm missing something before I cut a PR...

**Comment by swrobel** [comment]
All I did was remove software 2fa which they don't support. As for whether something counts based on there being exceptions to when it's required or other stipulations about when it can be activated, I'm already a persona-non-grata on this repo for a heated debate on that subject, so I won't weigh in. Good luck dealing with the maintainers...

**Comment by RichJeanes** [comment]
If you look at the [FAQ](https://www.bankofamerica.com/privacy/faq/safepass-faq.go) linked to in #1525, there is a hardware SafePass token available for purchase (though they make no mention of how to obtain one; presumably by calling customer service). This is stated under "How much does SafePass cost?" and "Can I use SafePass internationally?".

**Comment by jantman** [comment]
Ahh, interesting, thanks. That sure was buried way down in the docs... I guess they really don't want people doing that, but I suppose it does mean it's supported. Thanks.
