### ISSUE TITLE
Building a web extension, have some questions

### ISSUE THREAD

**Issue by designedbinary** [2factorauth/twofactorauth#3073]
HI There 2FA.org team.
	
My colleague (Conor) and I (Ray) are looking to make a web extension to help folks discover if a service has 2FA or not. I'm doing some initial user research on who (if any) might find this web extension useful, what their motivations are, and how we might make this more useful for them. We would be leveraging the data from twofactorauth.org (and of course attributing to all the right folks). So then,I was wondering if the team had any information on the demographics of folks who use twofactorauth.org? I'm particularly interested in:
	 
* What type of folks use this service? (mostly developers in a professional environment? Academics using this at home? Percentage breakdown if there are multiple significant groups?)
* Why do they use this service? 
* When/where do they use this service?  (do they use this to determine if they should create an account? Or maybe only to determine if a service they already use has 2FA they can enable?)
* What exactly are they looking for when they visit 2fa.org? Just existance of 2fa? Or more?
* How often do folks generally visit twofactorauth.org? 
	
Ultimately, our goal is to understand potential users so that we might better serve their needs. If you don't have this information, would it be acceptable for me to place a link here to a Google form to collect this information? 
	
Also, I was wondering if there might be anything we could do in particular with this web extension, that the community would find helpful? 
	
Thanks so much for any help anyone can provide!  Also, this is a great service. Thanks to all the folks who contribute!
Ray

**Comment by conorgil** [comment]
I'm the collaborator mentioned above. @designedbinary is a designer and I am a dev, so we hope to focus both on the UX and functionality.

I'll add that I am aware of https://github.com/2factorauth/twofactorauth/issues/2579 and the feedback in that thread.

I contacted the creator of that extension offline to ask about his plans for his extension and get his thoughts on what I have in mind to implement. He was super responsive and we had a good chat. I decided that I want to write the extension in TypeScript and take it in a specific direction in terms of the UX, so we are going to create a new extension for now. We are totally open to contributors, so there is definitely a chance to collaborate on an extension if others are interested.

**Comment by conorgil** [comment]
Hey everyone!

Today, @designedbinary and I released the extension that we have been working on.

Check out the site [2fanotifier.org](https://2fanotifier.org), [Twitter thread](https://twitter.com/conorgil/status/996835889010630656), and [HN thread](https://news.ycombinator.com/item?id=17086377).

We would love feedback from the community! Feel free to open issues on the [2FA Notifier repo](https://github.com/conorgil/2fa-notifier/issues) if you have comments/questions/bugs/etc.

Here is some of the beautiful illustration work that @designedbinary did to pique your interest if you're still on the fence:

<img width="640" alt="screenshot b 2x" src="https://user-images.githubusercontent.com/945571/40149659-e9db2648-5942-11e8-8a47-937cf08bc193.png">

<img width="640" alt="screenshot c 2x" src="https://user-images.githubusercontent.com/945571/40149667-f0709cfe-5942-11e8-919c-54dda951858e.png">

**Comment by kmpoppe** [comment]
@designedbinary @conorgil I just installed the Firefox Addon, and it looks nice :-)

**Comment by kmpoppe** [comment]
@conorgil Do you still need information from this project? As your extension is working fine in your own repo, I feel this Issue has no real need here anymore, right? If so, would you kindly ask @designedbinary to close this Issue?
