### ISSUE TITLE
Just following up on something

### ISSUE THREAD

**Issue by kenman345** [2factorauth/twofactorauth#3082]
https://github.com/2factorauth/twofactorauth/blob/master/_includes/desktop-table.html#L32

This line is just to indicate that load up with placeholder.png and then the other tags around it are for Javascript to insert the data-src value in its place afterwards, right?

**Comment by fpigerre** [comment]
Using the JQuery [Unveil plugin](http://luis-almeida.github.io/unveil/), the following line is used to replace placeholder.png images with the corresponding website logo.

```
<img src="/img/placeholder.png" data-src="/img/{{ section_id }}/{{ website.img }}" class="icon"
                   alt="{{ website.name }}">
```

This is done using the `data-src` tag. The tags that are presented using the curly braces, for example `{{ section_id }}` are [jekyll variables](https://jekyllrb.com/docs/variables/).

The tags around this line, for example, the line containing the `<noscript>` tags are for compatibility with users that don't currently have JavaScript enabled.

Thanks for your interest in the project,
psgs 🌴

**Comment by kenman345** [comment]
thanks! Wanted to make sure I didnt screw things up for our project which is a fork of yours where the code for that line came from. I like the worthwhile enhancement to initial page loading
