### ISSUE TITLE
Rage4

### ISSUE THREAD

**Issue by rage4** [2factorauth/twofactorauth#3086]
Please add rage4.com

**Comment by mxxcon** [comment]
According to alexa ranking, the site is too small to list. https://www.alexa.com/siteinfo/rage4.com
it's unfeasible for us to list every single site out there, so we tend to cut off at top 200k alexa ranking.

**Comment by rage4** [comment]
Rage4 is in top 5 fastest authoritative DNS providers according to https://www.dnsperf.com/, it would be nice to list it in domains category

**Comment by RichJeanes** [comment]
That's great and we hope that Rage4's business continues to be successful, but a service's performance does not influence Alexa rank. We would be happy to list Rage4 once the site becomes more heavily trafficked.
