### ISSUE TITLE
Add University of Colorado Boulder

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#3094]

**Comment by Carlgo11** [comment]
Hello @vsandrei.
thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by ghost** [comment]
@Carlgo11 Creating a pull request sounds fun! Though I'll save it for tomorrow since I'm working out problem sets tonight...if that's okay with you. :)

**Comment by Carlgo11** [comment]
Sure, do it whenever you feel like it.
If you need any help, don't hesitate to ask! 😄

**Comment by kmpoppe** [comment]
@indescribability It seems that you have already contributed to this repo since you opened this Issue. Alas I'd be willing to add the University I can't find the information for 2FA. They may only be available for alumni and students?
Maybe you could add these information yourself?

**Comment by kmpoppe** [comment]
@indescribability Could you please answer my question from January 27th? I've got no clue as to how 2fa may work at UCB, we'd need to check that. Can you supply screenshots? Do you want to add the Pull Request yourself?
I'll set this Issue to inactive as it has been over a year since you last wrote something here.

**Comment by kmpoppe** [comment]
Closed due to inactivity.
