### ISSUE TITLE
[IMPORTANT] Tidy up design

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#3095]
I think there are some ways we can improve the design of 2fa.org. Images attached for examples.

## Mobile Improvements

* Alignment is all weird
* Docs button is too large
* Social/email buttons look strange
* Icons aren't centered
* Other things that are too big:
  * Margins
  * Font size

[Mobile 1](https://user-images.githubusercontent.com/157801/38125015-1574a1c6-339b-11e8-80c6-d77080a404a7.png)
[Mobile 2](https://user-images.githubusercontent.com/157801/38125020-2674fd72-339b-11e8-9c27-49203c442e07.png)

## Desktop Improvements

* Things too large:
  * Margins
  * Font size
* Website icon not aligned with website title (minor)
* Simplify buttons. Should just be:
  * Tell them to support 2FA on: [twitz button] [fb button] [email button]

[Desktop](https://user-images.githubusercontent.com/157801/38125075-b0357604-339b-11e8-92d8-0f2aa879e705.png)

**Comment by mxxcon** [comment]
I personally like the current font sizes on both desktop and mobile. They are nice and readable. However, other aspects I agree could use some improvement.

**Comment by RichJeanes** [comment]
I agree on that point. I like the font size.

But on mobile, would it be possible to add commas to the list of supported methods on a site? I think seriously less savvy users could misunderstand a line that says "SMS Email", "SMS Phone Email", or "Hardware Software". Not great for readability in general.

**Comment by jdavis** [comment]
Yeah, the font size might just look worse with the size of the margins. Maybe it'll be fine if alignment, spacing is all adjusted.

**Comment by kenman345** [comment]
@jdavis just a note, you can use `!` before a link to an image to inline preview it(added a little formatting to make the mobile images side by side too):

Mobile 1 | Mobile 2
-----------|----------
![Mobile 1](https://user-images.githubusercontent.com/157801/38125015-1574a1c6-339b-11e8-80c6-d77080a404a7.png)| ![Mobile 2](https://user-images.githubusercontent.com/157801/38125020-2674fd72-339b-11e8-9c27-49203c442e07.png)

![Desktop](https://user-images.githubusercontent.com/157801/38125075-b0357604-339b-11e8-92d8-0f2aa879e705.png)



Also, linking over to the conversation going on in #3171

**Comment by Carlgo11** [comment]
@dsoegijono what's left on this list?

**Comment by dsoegijono** [comment]
I think my PR #3413 fixed the mobile issues (except maybe for margins). The desktop issues mentioned are still there:

1. Margins & font size too large: Need suggestions on what margin/size to use
2. Website icon not aligned with website title: I can try fixing this
3. Simplify buttons: I like the idea, might get rid of some rows with 2 row buttons

**Comment by dsoegijono** [comment]
<img width="1172" alt="screen shot 2019-01-16 at 10 59 20 pm" src="https://user-images.githubusercontent.com/867840/51247863-794e7900-19e2-11e9-9844-281251ef8d80.png">

Found another issue, we should clean up the In Progress rows. Maybe move the button to the right column?

**Comment by Carlgo11** [comment]
I say let's just remove them completely. We haven't changed a "In progress" status for years

**Comment by jdavis** [comment]
@dsoegijono 🙌🙌🙌

**Comment by kenman345** [comment]
Want to note that the mobile issue with the categories all being opened might have to do with the way the mobile/desktop tables are designed and separate. 

Would be nice to figure out exactly why and maybe make a unified table so the total page size is way smaller. and so we dont have Javascript checking the screen size to control opening the mobile or the desktop version of a category.

**Comment by Carlgo11** [comment]
No longer applies to the project
