### ISSUE TITLE
update steam icon

### ISSUE THREAD

**Issue by noammiz007** [2factorauth/twofactorauth#3100]
can you please update steam icon to the new one?
![default](https://user-images.githubusercontent.com/31467235/38200554-7d84ea28-369d-11e8-9d4c-1ccd6524e2c3.png)
to this one 
![default](https://user-images.githubusercontent.com/31467235/38200587-a1e9bc90-369d-11e8-9a0a-82b8cc601ced.png)
https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/2000px-Steam_icon_logo.svg.png

**Comment by mxxcon** [comment]
Their favicon and other logos are white/grey on black, not blue..

such as http://store.steampowered.com/favicon.ico 
and https://steamstore-a.akamaihd.net/public/shared/images/responsive/share_steam_logo.png

**Comment by noammiz007** [comment]
@mxxcon but this new logo comes with the software and looks much better

**Comment by mxxcon** [comment]
Is it new? Afair they always had blue gradient logo as well.

Yes, at 2000 pixels in size it looks great. But we use 32x32. How well will it look that small?
The other image you attached is 33x30. It's not square.
