### ISSUE TITLE
T-Mobile needs to be updated

### ISSUE THREAD

**Issue by etnguyen03** [2factorauth/twofactorauth#3101]
T-Mobile supports SMS two-factor authentication.

2FA is mentioned [here](https://support.t-mobile.com/docs/DOC-37078) but for whatever reason their [page on 2 factor authentication and login options is down](https://support.t-mobile.com/docs/DOC-2727)

Screenshots: 
![2fa toggle](https://user-images.githubusercontent.com/3579871/38219742-08e779da-36a5-11e8-80b1-0524552eb6c7.png)

![2fa screen 1](https://user-images.githubusercontent.com/3579871/38219804-60353628-36a5-11e8-96cc-7151355728ee.png)

![2fa screen 2](https://user-images.githubusercontent.com/3579871/38219792-4d5805ee-36a5-11e8-81fd-c456cd6aeaed.png)

**Comment by stephengroat** [comment]
thanks for the info @etnguyen03 

this has already been fixed by #3034, just hasn't been published yet! We're on our way to publishing, just takes time
