### ISSUE TITLE
Your Schema doesnt account for everything your HTML does

### ISSUE THREAD

**Issue by kenman345** [2factorauth/twofactorauth#3116]
https://github.com/2factorauth/twofactorauth/blob/44a27551a18669f3adc5b37ac57270268db89bc6/websites_schema.yml#L42

It would appear that you have the ability to also account for a mapping "link" for an excption, and even where its not either of those....https://github.com/2factorauth/twofactorauth/blob/44a27551a18669f3adc5b37ac57270268db89bc6/_includes/exception.html#L11

**Comment by stephengroat** [comment]
since we're currently not using it, shouldn't we just remove it? it's currently dead code

**Comment by kenman345** [comment]
On our repo we removed it and left it looping through the text tags in case
we had multiple. I can do the same tomorrow for you guys so it’s a bit
better suited to what the scheme allows you to do

**Comment by kenman345** [comment]
Happy to help pull back those orphaned html components.

**Comment by kenman345** [comment]
This issue is stale as hell. Do you want me to take a knife to the dead code in the layouts/includes? Otherwise let’s close this

**Comment by fpigerre** [comment]
Yeah, if the code is currently unused, removing it all and getting this stale issue out of the way would be awesome 👍

**Comment by kmpoppe** [comment]
This is addressed in https://github.com/2factorauth/twofactorauth/commit/70aed0008ab066268d19f290472fd1eb9f060ed5 (not yet in a PR).

**Comment by Carlgo11** [comment]
No longer applies to the project
