### ISSUE TITLE
Question: Marking complex setups or non-standard 2FA methods

### ISSUE THREAD

**Issue by MovGP0** [2factorauth/twofactorauth#3162]
It should be possible to mark websites as having implemented 2FA, but have a very complex method of setting it up, or requiring proprietary hardware or software, rather than a standardized method. 

What would be the best way to do so?

**Comment by mxxcon** [comment]
We have such here https://twofactorauth.org/notes/

**Comment by mporcheron** [comment]
Actually, I personally don't think a seperate page of notes is the right solution.
I'm coming from using 1Password 7, which pulls data automatically from twofactorauth.org (so 'notes' is not necessarily useful in this case). For me, 1Passsword alerts me that I haven't enabled 2FA for my bank (first direct), but of course I have but it's through their propriety app and not an open standard. It would be better if twofactorauth had the option to record software (open standard) and software (propriety app) as I’m sure many banks would fall into this latter category, and it preserves the meanginfulness of a searachable and machine-readable table

**Comment by mxxcon** [comment]
@mporcheron Separate notes page IS the right solution for situations where sites do not provide easy instructions on how to enable 2fa.
We previously listed all kinds of site-specific 2fa implementations but specifically decided to switch to broad generic categories for the simplicity of contribution, maintainability and readability.
It sounds like this is a limitations of 1pass where it can not handle use-cases where 2fa is enabled but not integrated into 1pass. They should have a setting where you can tell it that 2fa is enabled but used externally from 1pass.

**Comment by jamcat22** [comment]
Try adding the tag `2FA` to an item. It should exclude it from Watchtower’s Inactive 2FA section.

The problem we ran into before is that choosing which standards are “open” is hard to define, and it leads to additional complexity with how users can quickly understand our site. For example, Battle.net’s software 2FA asks that users use their own app, but the app itself uses an RFC 6238-compatible token that can be exported to another app (like Google Authenticator) either via an existing Android device or through an application like [WinAuth](https://github.com/winauth/winauth/blob/master/Authenticator/BattleNetAuthenticator.cs).

**Comment by jasonkarns** [comment]
I think that marking a site has having software support for 2fa when it requires a custom app is misleading. I would wager that the majority of users who happen upon this resource are expecting to be able to use authy/google authenticator/1password etc as their TOTP app of choice. Requiring a site-specific app does not meet those expectations.

My suggestion would be to have a "partial" value for the software column that more explicitly calls out the restrictions for a given site. That way tools like 1Password which use this data source to determine which sites support 2fa can behave more appropriately.

**Comment by maltfield** [comment]
@jasonkarns It's not only inconvenient to have to use some proprietary app instead of an open-source app that implements the TOTP standard -- it's downright unsafe.

If a service requires users to download some closed-source, proprietary app that implements their 2FA solution, then how can we audit that it's actually secure?

That sort of thing should be marked with a huge red flag so the users know it's not a trustworthy 2FA implementation.

**Comment by MovGP0** [comment]
> @jasonkarns to have to use some proprietary app instead of an open-source app that implements the TOTP standard

As long as you comply with the TOTP standard, the user can choose to either use an OOS application or an closed-source application. It will work either way.

**Comment by jasonkarns** [comment]
@MovGP0 Isn't this entire thread intended to call out precisely the non-standard implementations that _don't_ allow users to "bring their own TOTP app"? That was my understanding when commenting. Implementations that don't support the standard shouldn't be reported as compliant; and 'notes' is not sufficient to call them out as aberrations. Some extra "partial" or "nonstandard" flag would be desirable to more clearly designate nonstandard implementations.

**Comment by MovGP0** [comment]
Since there is now the 
![image](https://user-images.githubusercontent.com/83339/106378428-02a42e80-63a5-11eb-96eb-97d6c94d9963.png)
 symbol for propritary software tokens, I'll close the issue.
