### ISSUE TITLE
Exceptions & Restrictions also applies on Google 2FA

### ISSUE THREAD

**Issue by dominikconrads** [2factorauth/twofactorauth#3180]
Please add the following warning to all Google search results. It's not possible to set up 2FA without verifying with SMS or phone call exactly like amazon.com.

> Exceptions & Restrictions
> SMS or phone call required to enable 2FA. Enabling on Amazon.com activates 2FA on other regional > Amazon sites, such as UK and DE.

<img width="773" alt="screen shot 2018-05-06 at 18 58 58" src="https://user-images.githubusercontent.com/36445834/39675718-8f29d6da-515f-11e8-84dc-773934d1ac64.png">

**Comment by mxxcon** [comment]
How did you try to active 2fa here? From which url?

**Comment by dominikconrads** [comment]
Go to www.google.com, login, go to My Account → go to Sign & security → scroll to Signing in to Google → click on 2-Step Verification

https://myaccount.google.com/signinoptions/two-step-verification/enroll-welcome

**Comment by RichJeanes** [comment]
Hmm. I have 2FA set up but I don't have a phone number attached for it.

**Comment by dominikconrads** [comment]
Since when have you enabled this? It's Google guys, we all know this company for get as many private data as possible.

**Comment by onkarshinde** [comment]
Last month I setup my 2FA settings in google account from scratch and nowhere it asked me to setup SMS factory first. Perhaps this has changed since you last tried.

**Comment by dominikconrads** [comment]
I tested it with a second account and the only options given is security key, Google prompt (via an App) and text message or voice call. 

If you setup with a text message, you can change these later to other options like an Authenticator app and remove the phone number completely. 

But google forces you still to give them a phone number!

![screen shot 2018-12-20 at 22 06 53](https://user-images.githubusercontent.com/36445834/50310958-e504fb00-04a3-11e9-953a-eb44843acbae.png)

**Comment by RichJeanes** [comment]
> I tested it with a second account and the only options given is security key, Google prompt (via an App) and text message or voice call.

So you are not forced to give them a phone number with the option of the Google Prompt or Security key...

>But google forces you still to give them a phone number!

Is this on another screen or something? Because you're directly contradicting yourself here.

**Comment by dominikconrads** [comment]
If you sacrifice your smartphone to install the google app on it or you have bought a security key, yes you don't must give google your phone number. 

But if you don't have a smartphone, don't want to install googles app, or don't have bought a security key you have to give them your number. Is this so hard to understand? In the setup process it's the preferred option.
