### ISSUE TITLE
Huntington Bank Supports 2fA

### ISSUE THREAD

**Issue by annonman** [2factorauth/twofactorauth#3181]
The website is incorrect as it states Huntington does not support 2FA.

I receive a call to my cell every time I log in.   Email OTP is also available.

thanks

**Comment by mxxcon** [comment]
Do they have some documentation page explaining how to sign up for 2fa?

**Comment by jimsug** [comment]
A cursory look at the huntington site doesn't show two factor auth options for retail customers, but for small business there seems to be one: https://www.huntington.com/SmallBusiness/online-banking/information-and-reporting

Huntington could possibly be added with exceptions.

**Comment by kmpoppe** [comment]
No documentation could be obtained. PRs were subsequently closed. If ever there's a publicly available documentation, a new Issue/PR can be created.
