### ISSUE TITLE
Adding Coinroom to your list

### ISSUE THREAD

**Issue by Coinroomcom** [2factorauth/twofactorauth#3184]
Hello,

We are coinroom.com, a Polish cryptocurrency exchange. We also use 2FA via Google Authenticator, could you please add us to the list https://twofactorauth.org/#cryptocurrencies ?

Kind regards,
Pawel Zablotny
Coinroom team

**Comment by mxxcon** [comment]
Hello Pawel.
For now we are restricting to adding alexa top 200k sites. At this point in time your site is too low ranked to be added.
