### ISSUE TITLE
BoA doesn't seem to support hardware token

### ISSUE THREAD

**Issue by bobcowles** [2factorauth/twofactorauth#3185]
Following the documentation trail for Bank of America, I could not find any place describing the use of a hardware token.

**Comment by mxxcon** [comment]
Also looking at https://www.bankofamerica.com/privacy/faq/safepass-faq.go it says:
> SafePass is an extra layer of security that is required in Online and Mobile Banking to authorize higher-value transfers.

So that's two-factor _authorization_, not authentication...If this is the only type of protection they provide, then it should be outright changed to `tfa:no`.

**Comment by RichJeanes** [comment]
Bank of America has been a topic brought up many times. See: #3041 #2532 #1525 #43

Can we get verification on [this comment](https://github.com/2factorauth/twofactorauth/issues/2532#issuecomment-363857824) that was made on #2532 after it was closed?

**Comment by bobcowles** [comment]
The SMS code is supported for login. There is no hardware token support.
