### ISSUE TITLE
Allow Self hosted as well as SaaS products

### ISSUE THREAD

**Issue by kilasuit** [2factorauth/twofactorauth#3234]
Reason being these are still valid products and the whole point behind a site like this should be to include EVERY possible application as a single 1 stop place to be able to look at for what allows MFA

**Comment by mxxcon** [comment]
We do list saas products.

The problem with self-hosted entries are situations where multiple external modules/plugins/packages/addons/whatevers provide different/conflicting features. How would such be represented?
As an easy example: wordpress.org has 17 different 2fa plugins...

**Comment by kilasuit** [comment]
Well that's easily fixed by saying there additional installs needed using the below like I had to add to my PR #3210 

```exceptions:
       text:  "M/TFA is only available with additional Plugin installs"
```

It wouldn't add that much more but would be a reasonable expectation especially as a need for this site is to know **Where** MFA can be used not **How** its implemented - that can be found by other means and would negate declining PR's like #3219

**Comment by mxxcon** [comment]
What about situations where mutually exclusive plugins provide different features? What methods do we indicate? Indicating all of them could be misleading for any given plugin..

**Comment by kilasuit** [comment]
We don't indicate/suggest individual plugins - but more inform the users that they can find available plugins that will enable MFA to be used on which ever system it is - perferably linking to the underlying software provider's help pages (aka Wordpress)

**Comment by Carlgo11** [comment]
As of right now our stance is that we don't list self hosted sites and we don't list third party login systems.
We'll take note of your request and maybe in the future, if enough people request it, we'll add self hosted services.
For the moment however, I think a fork of the site would be better suited to list self hosted services.
