### ISSUE TITLE
How to be added as a contributor / team member

### ISSUE THREAD

**Issue by kilasuit** [2factorauth/twofactorauth#3235]
I **LOVE** this as an idea,

However in practice,

there are far too many PR's that are open and some that are being declined for various reasons, and that is lowering the barrier to being able to see this being a true single shop to be able to find any sites that implement MFA - TFA is technically an incorrect terminology and whilst it is widely known out there 

```
All two-factor authentication (2FA) is multi-factor authentication (MFA), but not all MFA is 2FA.
```

I would love to help out with getting this repo up to scratch and getting PR's approved and accepted and therefore added to the repo.

I have Ruby and Jekyll experience helping other community sites so I am versed with Travis for builds.

Let me know if/when I could be able to help further

**Comment by mxxcon** [comment]
At this point we don't have an official, codified process. When we see people who contribute to this repo in a meaningful way and without ulterior agenda, we invite them if they are interested in joining.
