### ISSUE TITLE
New Tab/Window

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#325]
Hi Josh,

It would be great, if each time we click on a link, it would open in a new tab or window instead of over the list.

Cheers,

RItchie

**Comment by RichJeanes** [comment]
Hey @jdavis, couldn't this be done with just adding `target="_blank"` to [line 94](../blob/master/index.html#L94), [line 99](../blob/master/index.html#L99), and [line 143](../blob/master/index.html#L143)?
On a semi-related topic, I feel like there's some redundancy there that could be optimized out... Or maybe there's something about the syntax that I'm not familiar with preventing that. Is that Jekyll handling that code?

**Comment by smholloway** [comment]
Yep, that should do it. `index.html` is standard HTML with [Liquid as the templating language](http://jekyllrb.com/docs/templates/).

What redundancy do you see?

**Comment by RichJeanes** [comment]
I was referring to the repetition of the img and url items but looking again I realize that it needs to be separated for the different styles (positive vs negative).
I see about getting those target references in there. Anything else that would need it other than url and img?

**Comment by jdavis** [comment]
Hmm. Should it open up in a new window though?

In my experience, I loathe all sites that by default `target="_blank"`. I think it should be up to the user to either Cmd + Click or Middle click. Whenever I come across a site that "assumes it knows best", it frustrates me.

Any thoughts on that?

**Comment by mxxcon** [comment]
I think internal links should open in-place, but links to external sites should open in a new tab/window since chances are you'll want to stay on the site to enable 2fa for your other accounts..

**Comment by jdavis** [comment]
How often do sites use _blank for linking to the outside though?

**Comment by Ritchie007** [comment]
It's become sorta the norm, you open a New Tab with to the linked page, you browse as you need (even changing pages a lot), then Close the tab and you are back to where you were WITHOUT reloading the page (saves internet bandwidth - very useful with heavily loaded pages (lots of pubs and other stuff)).

I definitely prefer this.

**Comment by Ritchie007** [comment]
Oups, I closed instead of Comment

**Comment by jdavis** [comment]
I don't necessarily agree in that it is becoming the norm. I can't think of a single website that opens outside links in tabs by default.

Like I've said, I don't think it's a very good decision from a usability standpoint.

**Comment by Ritchie007** [comment]
Some Forums work that way (even for internal links sometimes), Feedly too.

From a user experience point of view, I totally prefer it.  Otherwise, after the first click, I come back to the page and redo a <ctrl>-Click and select Open in New Tab all the time (but it's cumbersome).

As I said before, the advantage to this is that when you come back to the page you left, you don't have to reload it (fast & efficient).

**Comment by jdavis** [comment]
Sure, the key is that from **your** point of view. On the contrary, by assuming that no one wants a new window/tab, it satisfies both use cases. Because if a person wants to open it in a new tab, they just hold down a key or middle click.

While if the person doesn't want it to open in a new tab, they are forced to.

**Comment by jdavis** [comment]
I'm closing this because I don't agree with it =[

Sorry @Ritchie007.
