### ISSUE TITLE
Please add anycoindirect.eu

### ISSUE THREAD

**Issue by Speedliner** [2factorauth/twofactorauth#3253]
anycoindirect.eu supports 2FA via Google Authenticator - please see instructions (account required) below:

https://anycoindirect.eu/de/account/twofactorauthentication

**Comment by mxxcon** [comment]
I tried to add it in #2732, alas it wasn't committed. 🤷‍

**Comment by kmpoppe** [comment]
Was added with #3520, please close Issue.
