### ISSUE TITLE
Question: Duplicate Items in Different Sections

### ISSUE THREAD

**Issue by jadchaar** [2factorauth/twofactorauth#3258]
Hello 👋 ,

At 1Password, we use twofactorauth's data for our Watchtower service. I was looking through the parsed JSON we use and noticed that Vultr, for example, seems to have 2 entries on the twofactorauth repo, one under `hosting`, and another under `cloud`. Why is that? I am not sure if there are more similar cases, but if so, is this in error?

I am bringing this up because it is super hard to keep them in sync. The doc for vultr in our parsed version was a bit outdated because we parsed the hosting URL versus the new one (the 2 vultr entries are different and one seems to have a more up to date link).

**Comment by mxxcon** [comment]
I don't think we should have duplicate items for exactly this reasons..It'll be even bigger pain the butt to keep things consistent. I think each site should be in only one, most appropriate category.

Perhaps in the future if we'll figure out some other data layout structure we could support multi-categories.

**Comment by jadchaar** [comment]
Yeah I was thinking about that. Find some way to link categories, or "tag" entries with multiple categories.
