### ISSUE TITLE
Time to update data.json

### ISSUE THREAD

**Issue by jadchaar** [2factorauth/twofactorauth#3270]
Curious, how long does it take between a merge and an update of `data.json`? At 1Password, we like to update our 2FA list often so that users get the most up to date links, but our recent merges don't seem to be reflected in the `data.json` yet 😄.

Just wondering to have a timeline 👍 .

**Comment by Carlgo11** [comment]
Hi Jad,
information about or merge process can be found on [our wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).
Essentially, we push master to gh-pages (our live site) about once a month. (And sometimes longer depending on our workload)
This is to ensure that the information we display is accurate and that no commits break the build in any way that Travis-CI doesn't catch.

**Comment by jadchaar** [comment]
Ah ok thanks @Carlgo11! I should just check back to see when it is merged then.
