### ISSUE TITLE
Would be pleased to add commonly used software - like discourse - to be added

### ISSUE THREAD

**Issue by childnode** [2factorauth/twofactorauth#3290]
I would appreciate the site will list software that supports the 2FA methods, not even "cloud services".
e.g. https://github.com/discourse/discourse is a common forum software.

**Comment by mxxcon** [comment]
If I understand your request correctly, listing such software was discussed in #3234.

**Comment by childnode** [comment]
yes, that's it ... thanks for pointing out #close #revoke
