### ISSUE TITLE
Change call to action wording

### ISSUE THREAD

**Issue by kenman345** [2factorauth/twofactorauth#3292]
Viewing the site, its quite assertive in the Call to action:
`Tell them to support 2FA on Twitter`
`Tell them to support 2FA on Facebook`

I think instead we should have it say 
`Ask them on Twitter to support 2FA`
`Ask them on Facebook to support 2FA`

Or at least:
`Ask them to support 2FA on Twitter`
`Ask them to support 2FA on Facebook`

**Comment by mxxcon** [comment]
Yes, perhaps rephrasing that does make sense.

**Comment by kenman345** [comment]
I got a thumbs down on this? But no comment @quassy ...

Can you please explain your viewpoint? Otherwise I'd be interested in hearing from @mxxcon or others about their opinions on the new call to action wording so that I can make a PR for the change.

**Comment by mxxcon** [comment]
I'm not sure which one is more grammatically correct.😅

**Comment by brycx** [comment]
@kenman345 I like the current phrasing of it. I see no excuse for a company not to provide 2FA for their customers and you can't rely on passwords with breaches happening left and right. I think that the current call to action is appropriate, in a way nudging the user to reach out (kind of like a commanding). The more users that reach out, the faster those companies hopefully will implement 2FA.

**Comment by quassy** [comment]
> Can you please explain your viewpoint? Otherwise I'd be interested in hearing from @mxxcon or others about their opinions on the new call to action wording so that I can make a PR for the change.

Hey @kenman345, basically what @brycx said: In my opinion 2FA being available should be a standard for every place you need to login just like SSL/TLS has become standard for every website you visit. With more complex systems and more services people use, the days are gone were you could say "my data is not important enough to have hashed passwords / https / 2FA". Assertive language might help against sloppy security practices 😉

**Comment by phallobst** [comment]
The wording on the "call to action" should match the actual tweet. Currently it is
> Security is important, @TWITTERHANDLE. We'd like it if you supported two factor auth.

My guess is that "ask" fits better than "tell".

**Comment by dsoegijono** [comment]
#1813 similar issue

**Comment by Carlgo11** [comment]
Fixed in v3
