### ISSUE TITLE
webby 

### ISSUE THREAD

**Issue by BigGiantHeadsHighCommander** [2factorauth/twofactorauth#3293]
Other sites like

https://totp.app/

Would be a great addition.  Why carry a soft token when you can webby it? [rhetorical]

Sure, not the best idea, but 2FA for mostly disposable online services is met nicely by disposable 2FA tokens

**Comment by mxxcon** [comment]
I don't understand what are you asking to add?

**Comment by RichJeanes** [comment]
Heads up if you visit that site: They use you for crypto mining. They disclose it, but it starts as soon as you load the page and it's listed as the very last thing on the page.

**Comment by Carlgo11** [comment]
Just like @mxxcon I’m not sure what you’re trying to do here.
We don’t list 2FA providers anymore.
