### ISSUE TITLE
Add spotinst.com

### ISSUE THREAD

**Issue by vladholubiev** [2factorauth/twofactorauth#3296]
They support 2FA since summer of 2016 - https://blog.spotinst.com/2016/07/18/two-factor-authentication/

I just set it up so here is a proof:

![image](https://user-images.githubusercontent.com/3817380/42660558-3f42bb46-8634-11e8-8802-a86209a8faaf.png)

This is SaaS which utilizes spot instances on AWS/Azure/Google Cloud

The correct category would be "Cloud Computing"

**Comment by Carlgo11** [comment]
Closing as it's >200k on Alexa
