### ISSUE TITLE
Chase 2FA source

### ISSUE THREAD

**Issue by kevindj71** [2factorauth/twofactorauth#330]
I'm a Chase customer and not aware of this functionality, can you share your information source?

**Comment by jdavis** [comment]
Hey @kevindj71, a few people have actually asked this. Let me ping the guy that added it.

@jfocht, do you have a link to where Chase has documentation regarding 2FA?

**Comment by SJTirone** [comment]
http://fppad.com/2011/11/29/boost-your-online-security-with-two-factor-authentication/

**Comment by jdavis** [comment]
A source directly from Chase would be preferred... Although that site does say that they call it a Chase "Identification Code" which might help for Googling...

**Comment by SJTirone** [comment]
I will look for one. I just happened to be looking at that page recently,
and it was the first thing that popped in my head.

**Comment by SJTirone** [comment]
here we go: https://m.chase.com/#faqs-question-detail

sorry this is through email, but I'm on my android and don't have GitHub on
it

**Comment by jdavis** [comment]
Awesome, I'll open a new issue for it.
