### ISSUE TITLE
Volunteer to translate the site to Brazilian Portuguese

### ISSUE THREAD

**Issue by anciaes** [2factorauth/twofactorauth#3301]
I would like to volunteer myself to translate the site to Brazilian Portuguese. I understand that there are very few words to translate (column headers, category names, etc), since the majority of the site is made of site names and links, what makes the translation even more desirable (as the need for translation updates will be minimum). I can search for links to the portuguese version of the guides, too (when available).

I'm a native Brazilian Portuguese speaker.

I'm volunteering because the site is a fantastic resource and because it's all too common to find people here in Brazil that have never heard of TFA, even people that work in IT. This is why I think that translate your website would be a huge help.

I can give you some references of other volunteer translation works I made in the past, if needed.

**Comment by mxxcon** [comment]
You could update https://github.com/2factorauth/twofactorauth/blob/master/_data/languages.yml to add new language and update any existing Brazilian sites to utilize that.

Is there really a need for a full translation of the site? Is there terminology significantly different that people wouldn't understand current English words?

Right now the site is not really setup to support multiple languages beyond the snippets linked above. I'll let others chime in on what it would take to create such a version.

**Comment by anciaes** [comment]
Some categories are very similar when written in English or in Portuguese, but others are completely different, making it difficult for people that can't read English (example: Retail is Varejo in Portuguese). But there's more to the translation than the categories, like the links to the guides of each site (that could lead to the correct language instead of the English version).

I agree that for people that have at least some English knowledge it would be possible to just find the site they want, click on the link, arrive in the English version and then try to find the Portuguese one, but this is not true for people that don't speak English at all. If we add that up with the general ignorance about the 2FA itself, I believe we have a reason to translate.

On the other hand, I understand that the site doesn't support this right now. If you decide to do so in the future, please let me know. The same applies if you have some FOSS project where you think I could help with the translation to PT-BR.

**Comment by mxxcon** [comment]
Do we haveany sites listed right now which are primarily Brazilian but have docs link pointing to English version?

**Comment by anciaes** [comment]
Primarily in Portuguese, no. But there are several sites that have PT-BR versions (all the huge ones like GMail, Facebook, GoDaddy and such, and probably some smaller ones, too - I would need to check the sites one by one to see how many). It's a fact that a lot of them don't have portuguese translations, for their intended public doesn't include portuguese speakers.

I see your point, and I understand that you need to assess the trouble of implementing such multilanguage system and compare it with the benefits of offering other languages (not only portuguese).

**Comment by he7d3r** [comment]
See also https://github.com/2factorauth/twofactorauth/issues/2531 and other [international](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aissue+is%3Aopen+label%3Ainternational) issues.

**Comment by Carlgo11** [comment]
Moved to #6166
