### ISSUE TITLE
Add Navy Federal Credit Union

### ISSUE THREAD

**Issue by htmlarson** [2factorauth/twofactorauth#3312]
Supports in-app push authorizations and email support

**Comment by mxxcon** [comment]
are you referring to https://www.navyfederal.org/ ?

**Comment by htmlarson** [comment]
Yes

**Comment by mxxcon** [comment]
Do you happen to have any links to documentation that explain to users how to enable 2fa there? I tried looking through their site and haven't found much beyond them telling how to create secure passwords

**Comment by htmlarson** [comment]
Best I could find: 

https://nfcucloud.custhelp.com/app/answers/list/c/543
