### ISSUE TITLE
Add netcup

### ISSUE THREAD

**Issue by dt-flo** [2factorauth/twofactorauth#3318]
Hello,

please add ccp.netcup.net to the list. It supports two factor auth.

**Comment by Carlgo11** [comment]
Hello @florian2833z,
thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by dt-flo** [comment]
netcup was already added but the domain was wrong.

**Comment by Carlgo11** [comment]
Ah, right. then it would have qualified if it wasn't for the reason provided in #3319.
