### ISSUE TITLE
apache guacamole support

### ISSUE THREAD

**Issue by muratdogan1** [2factorauth/twofactorauth#3325]
2fa do settings . can you help me?

**Comment by Carlgo11** [comment]
Could you elaborate?

**Comment by mxxcon** [comment]
I think https://guacamole.apache.org/support/ is a more appropriate place for guacamole support.

**Comment by muratdogan1** [comment]
apache guacemole install and twofactorauth install 
http://localhost:4000 open page . not list guacamole

**Comment by mxxcon** [comment]
@muratdogan1 this is not Apache Guacemole support forum. Please go to https://guacamole.apache.org/support/

**Comment by Carlgo11** [comment]
@mxxcon maybe he means that his changes doesn’t show up on the local build of twofactorauth.

**Comment by mxxcon** [comment]
🤷‍♂️ maybe. not much details provided. But either way it's a self-hosted app, so for now we wouldn't be listing it.
