### ISSUE TITLE
Email Only Accounts

### ISSUE THREAD

**Issue by ohheyrj** [2factorauth/twofactorauth#3339]
Hello,

I wanted to reach out and ask this question, sorry if it sounds stupid!

I noticed that some of my accounts that I would like to add to the site do not have username/password combos but instead use a 'special' email link to allow you to sign in. For example (and not one that I was going to list on the site!) Laundrapp in the UK does not have a username or password for your account. To 'login' you give it your email address and you receive a link to allow the app to login.  Personally, I would not class that as 2FA (In fact, I would say its no where near secure) and therefore should be listed so. I checked the definition of what 2FA is for this project but wanted to reach out just to check so that I don't waste peoples time.

**Comment by mxxcon** [comment]
Correct, such a site would be `tfa:no` since there's only 1 factor of authentication.

**Comment by ohheyrj** [comment]
Thanks, just wanted to check before I submitted them!
