### ISSUE TITLE
NameCheap 2FA Clarification

### ISSUE THREAD

**Issue by braydenhouston** [2factorauth/twofactorauth#3344]
Name Cheap requires the use of their own custom app to use 2FA. The only other option is to use SMS.

Similar to the entry for Steam, I believe this should have a warning for this caveat.

**Comment by mxxcon** [comment]
It _requires_ their own app or it's an option with SMS?

**Comment by braydenhouston** [comment]
SMS is an option and functions like many other websites. You get a text with a code everytime you login.

If you want to use their token based 2FA method you **must**  use their app. You cannot use a standard app like Google Authenticator or Authy.

**Comment by braydenhouston** [comment]
Also use of the app must be tied to a phone number.

**Comment by brycx** [comment]
I think an exception that says something like "Software token can only be used through NameCheap's own 2FA app. This app requires a registered phone number." would be fitting here.

**Comment by RichJeanes** [comment]
Perhaps mirror the Steam exception to try to standardize the language a bit?
"Software Token requires the use of NameCheap's mobile app. SMS capable phone required."

**Comment by brycx** [comment]
Good idea @RichJeanes
