### ISSUE TITLE
Navy Federal Credit Union Now Supports 2FA via Email and Push Notification

### ISSUE THREAD

**Issue by aaronsentell-zz** [2factorauth/twofactorauth#3350]
Screenshots: https://m.imgur.com/a/ESukhfl

**Comment by Carlgo11** [comment]
Hello!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by aaronsentell-zz** [comment]
Hi - I think the request for Navy Federal to be updated was accidentally categorized as a new site. It’s currently on your site, but it is listed as not supporting 2FA.

**Comment by mxxcon** [comment]
Already addressed in #3314
