### ISSUE TITLE
Add Veterans Administration - US Government

### ISSUE THREAD

**Issue by swedeman** [2factorauth/twofactorauth#3356]

**Comment by Carlgo11** [comment]
Hello!
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by ninavizz** [comment]
I think the VA uses ID.me, which is a vendor providing auth services. FWIW.

**Comment by Archigos** [comment]
@ninavizz is correct, they use ID.me which although stated on your site, ID.me does support 2FA already and the information on how to set it up can be found here: https://help.id.me/hc/en-us/sections/115000551794-Securing-My-Account-with-2FA

**Comment by kmpoppe** [comment]
I changed ID.me to support 2FA with #3680.
I'm unsure how to proceed with the VA - as they support three different ID-services (ID.me, DS Logon and My HealtheVet). Even if it was only ID.me, how would this be representable in this project?

**Comment by Archigos** [comment]
Thank you for adding that... as far as the three different services, the
first thing that comes to mind is doing something like I put at the bottom
as three separate options so the user can select the one they use? If it's
not too much hassle having essentially duplicated do to their end.  I'm
unsure if it helps, but based on when I talked to someone from both ID.me
and the Vets tech support, a majority of the users use ID.me as the primary
for the site, so it may be as simple as using ID.me as the default with a
special note added somewhere explaining the other two options available but
not listed.

"VA [ID.me]"
"VA [DS]"
"VA [HealthVet]"
