### ISSUE TITLE
Sortable Tables

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#336]
As per an email I received.

**Comment by mxxcon** [comment]
This seems like a feature-creep request.
What would be the use of sorting tables? Just to group all sms 2FAs together?
To me this doesn't seem like a useful feature other than to play around with the site.
Just because this is a table, doesn't mean it should be sortable. :-1:

**Comment by smholloway** [comment]
What benefit is gained by sorting the tables? 

Perhaps the point of sorting is to see only sites that have 2fa or to show only the villains who do not. If that's the case, a filter or toggle might make more sense. I don't see that as a pressing need, but you could leave it open and see how many people request something similar.

**Comment by jdavis** [comment]
Good points guys, I'll close this for now.

**Comment by dsoegijono** [comment]
@jdavis I think sorting could be useful. For example, I would like to be able to group all SMS 2FAs together because I live overseas and SMS and phone calls don't always work. I usually ignore those options and only use 2FA through the other methods.

**Comment by jdavis** [comment]
Rather than actual "sorting", would it be more appropriate to consider "Filtering"? I prefer the filtering idea.

Would that satisfy your need @dsoegijono?

**Comment by mxxcon** [comment]
@jdavis if you are going with filters, then I think categories should be filters as well and have everything listed alphabetically.

**Comment by dsoegijono** [comment]
@jdavis Yes, filtering would be a great option.

**Comment by jdavis** [comment]
@mxxcon @dsoegijono K, I'll create a new Milestone for it.

I actually think filtering could solve our issues with the whole international specific page idea from #241 as well.
