### ISSUE TITLE
Basecamp SMS 2FA Removed

### ISSUE THREAD

**Issue by nbuuck** [2factorauth/twofactorauth#3364]
On [July 2nd](https://m.signalvnoise.com/protect-your-basecamp-login-with-googles-two-factor-authentication-c7c495e49292), Basecamp (categorized as a Communication app) removed their native SMS-based 2FA support. The only way to achieve 2FA on the platform now is by converting your account to use Google federated authentication and configure that Google account for 2FA. After reading the CONTRIBUTING document, I'm not sure if that meets this project's requirements, so I'm opening this issue so that a maintainer can decide how Basecamp's entry is updated.

**Comment by mxxcon** [comment]
So they still keep their native login, but also support federated login with google?
If they still keep their native login, then our records would need to be updated to be `tfa:no`.
If they completely switched to federated login then I think it would need to be removed since at this point in time we don't list sites with federated logins(saml or other type of sso).

**Comment by nbuuck** [comment]
@mxxcon Correct, Basecamp now has:

- Native authentication, no option for 2FA.
- Google federated authentication with the option for 2FA.

**Comment by Carlgo11** [comment]
I made an account on there just to understand what they've done.
I must say that I find it pretty funny how they brag in their blog post, that @nbuuck linked to, about how they've upped their security by removing 2FA for their native login system.
Even though we all know SMS based 2FA is bad it's still better than nothing... It was probably just a money thing 😒 

And just as @nbuuck  says, the only way to get 2FA now is by switching to a third party system and so it's indeed `tfa: No`.  

![screenshot](https://user-images.githubusercontent.com/3535780/47015454-51cee280-d14d-11e8-8fc5-92d2595e5c25.png)

I'll be making a pull request soon.
