### ISSUE TITLE
Add hostnet.nl

### ISSUE THREAD

**Issue by JaneX8** [2factorauth/twofactorauth#3373]
hostnet.nl sells hosting and domains. Supports software tokens (HOTP/TOTP).

**Comment by Carlgo11** [comment]
Hello @ElleshaHackett,
could you link to any documentation on how to enable 2FA on hostnet.nl?
Alternately, could you provide us with screenshots of the setup process or login process?  __(Remember to blur out or paint over any personally identifiable information if you send a screenshot)__
