### ISSUE TITLE
Tumblr just got 2FA !!!!

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#338]
News here --> http://www.engadget.com/2014/03/24/tumblr-two-step-authentication

Cheers,

Richard

**Comment by smarthero** [comment]
Just to add some info

Tumblr's 2FA supports SMS and OATH TOTP, so smartphone authenticator apps like Google Authenticator, Authy, Duo Mobile, etc will all work with it.

**Comment by jdavis** [comment]
#337 beat ya too it, Ritchie. Sorry mate!
