### ISSUE TITLE
US Bank needs update

### ISSUE THREAD

**Issue by theevilshiftkey** [2factorauth/twofactorauth#3405]
The following authenticators are available for customers of US Bank.

-One-time Passcode Via SMS
-ID Shield Questions
-Visual Pattern (app only)
-Fingerprint Scan (app only)
-Face ID (iPhone X only)

**Comment by Carlgo11** [comment]
Hello @theevilshiftkey,
thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by theevilshiftkey** [comment]
Thanks. I looked at https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md and have no idea what any of it means.

**Comment by mxxcon** [comment]
@theevilshiftkey would you happen to have a link documenting those authentication methods?

**Comment by theevilshiftkey** [comment]
See the top paragraph at https://www.usbank.com/online-security/mobile-security.html , specifically the last sentence. I'm a US Bank customer and I've successfully configured my online account to require SMS code in order to sign in. Better than nothing, we'd all prefer an auth app.

**Comment by mxxcon** [comment]
Fixed in #3477
