### ISSUE TITLE
Update PocketSmith

### ISSUE THREAD

**Issue by JAYSONHOOGY** [2factorauth/twofactorauth#3406]
The current entry for PocketSmith uses an old logo and the docs link goes to the original blog post when it should go to the updated doc article.

New logo: https://www.pocketsmith.com/favicon.ico
Docs link: https://learn.pocketsmith.com/article/167-two-factor-authentication-2fa-on-your-pocketsmith-account

**Comment by Carlgo11** [comment]
Hello @JAYSONHOOGY,
could you provide us with a PNG file? 32x32 pixels and smaller than 2.5KB.
