### ISSUE TITLE
Tumblr TFA

### ISSUE THREAD

**Issue by elliottcarlson** [2factorauth/twofactorauth#342]
Tumblr TFA is now available to the public: http://staff.tumblr.com/post/80583764030/the-smile-of-a-loved-one-your-childhood-blanket

**Comment by jdavis** [comment]
That's already taken care of: #274 #338 #337 

You guys must like Tumblr or something ;)

Edit: Oh, you work for Tumblr. In that case, I'm curious, was releasing my site last week just a coincidence? Or did it have a factor (haha, factor) in it?

**Comment by elliottcarlson** [comment]
D'oh, teaches me for just giving a cursory glance.

**Comment by jdavis** [comment]
Well, to be fair, I haven't pushed it to gh-pages yet. I'll do that now.

**Comment by jdavis** [comment]
@elliottcarlson Take a look now, it should be updated.

Also, I might think about adding some sort of indicator that shows that 2FA was added since the site was released. It'd be a cool visual. Referencing #320 for the future...

**Comment by elliottcarlson** [comment]
:+1: 

Oh and just noticed your edit as well - it's been an admin only feature for a while, this is just the public release - pure coincidence :) Though once I saw this site on HN I knew I would have to come and update you once we had released it.

**Comment by jdavis** [comment]
Very cool.
