### ISSUE TITLE
Add Mimecast (Email)

### ISSUE THREAD

**Issue by cphaynes** [2factorauth/twofactorauth#3421]
name: Mimecast
url: https://mimecast.com
img: mimecast.png
tfa: Yes
sms: Yes
email: Yes
software: Yes
doc: https://community.mimecast.com/docs/DOC-1913

![mimecast](https://user-images.githubusercontent.com/29051913/44881039-49454a00-ac7c-11e8-8758-ad39a3c183bd.png)

**Comment by Carlgo11** [comment]
Hi @cphaynes,
what kind of service is this?
Is this like Microsoft 365 Outlook or like MailChimp?

**Comment by cphaynes** [comment]
Hi @Carlgo11,

It's an email security company. It scans, archives, and keeps email flowing incase providers (like O365) have an outage.
