### ISSUE TITLE
HackerOne requires SMS for 2FA

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#3422]
HackerOne requires enabling SMS account recovery before enabling 2FA, as shown in the GIF below and explained in the [doc](https://docs.hackerone.com/hackers/two-factor-authentication.html) link. It doesn't support SMS for 2FA itself, nor as a backup method, but there must be a phone number attached to the account before enabling 2FA.
![GIF showing HackerOne's enable 2FA process](https://user-images.githubusercontent.com/1897053/44883346-fb2c4880-ac73-11e8-8db5-8e6df766668d.gif)

The phone number is only used to provide notifications about automated account recovery, which sends an email and SMS to your phone multiple times over a 24-hour period before removing 2FA from an account.

![Image showing HackerOne's account recovery process](https://user-images.githubusercontent.com/1897053/44883498-8efe1480-ac74-11e8-8e67-cb2484658fdf.png)

**Comment by mxxcon** [comment]
I guess this needs an exception text that sms is required?

**Comment by jamcat22** [comment]
Yep I just don’t have git on my computer right now and we’ve been opposed to making new branches on the base repo for web edits

**Comment by stephengroat** [comment]
any reason we don't want branches on the base repo? we could easily use something like this https://probot.github.io/apps/delete-merged-branch/ to automatically delete branches after merges. it allows us to centralize work and (hopefully) show people how the work should be done. since people have enough issues using git, i don't think we'll have too many issues of people forking off of non-master branches

**Comment by jamcat22** [comment]
I don’t think we want branches to auto-deleted, especially if we’re working on a major feature change. Everyone with permissions to create branches can delete branches even if they weren’t the original creator, so I don’t think it will be too much of a problem.

**Comment by stephengroat** [comment]
> I don’t think we want branches to auto-deleted

i think branches only get deleted once merged. we don't want merged branches deleted?

**Comment by jamcat22** [comment]
We wouldn’t want that if we merge branches to push changes made, but we’re still working on other changes in the branch itself. Otherwise everyone working in the branch has to remove the branch from their local machine, recreate the same branch title, and change back to the branch. This isn’t too big of a deal using Git, but the GitHub GUI apps get a little temperamental with this. Plus PRs already have the delete branch option at the end. I’m not sure it’s worth adding a bot to the repo for something that only adds another click after merging.

**Comment by stephengroat** [comment]
> We wouldn’t want that if we merge branches to push changes made, but we’re still working on other changes in the branch itself

how often does that happen in the repo? in a quick look through the history, doesn't seem to happen very often.

i'm just saying the restriction on not creating branches on the repo seems like it's not getting us much value. as long as the branches are cleaned up after merges, doesn't seem to be adding confusion to novice users (that usually don't find/work on branches other than `master` anyway) plus get us the ability to work from the web interface for minor, quick changes

just a thought!

**Comment by jamcat22** [comment]
Oh no I totally agree with you on not needing the restriction! I was just saying the only people who are able to create new branches on the repo are members of the @2factorauth organization, so I don’t think we need a bot to clean up stuff because everyone who’s creating branches as an admin of the repo should also know how to delete them.

**Comment by Carlgo11** [comment]
@stephengroat there are several reasons for the rule.
One is that it makes the process of adding/updating sites in the list should be the same for first time users and collaborators.
Another is that, by keeping the main repo to a absolute minimum of branches we reduce the amount of data required to fork the repo. Over a bad connection it can really make a difference if a repo is one branch or twenty branches.

And another pro of only having one branch is that new users can't accidentally make a PR for merging two branches (like has happened countless times before) however that isn't a reason for having the rule. Only a positive side effect.

This issue however isn't about whether or not that rule should be in place so I suggest we open a new issue if you feel we should consider changing this rule. Just remember to reference this issue number 😉
