### ISSUE TITLE
Please add Invoicera

### ISSUE THREAD

**Issue by amitbhardwaj080387** [2factorauth/twofactorauth#3453]
Hi,
I have done with the below steps to make list invoicera.com on your site (https://twofactorauth.org/).
1. fork github, clone repo on local
2. make an entry in _data/finance.yml file.
3. upload logo (32*32 png) in img/finance directory.
4. commit and push this change.
Our site is 15 years old. Our Alexa ranking is 2 lacs 78 thousand. I want to know the mandatory steps to list the site on twofactorauth.org. Please suggest

Thanks & Regards
Amit Bhardwaj
invoicera.com

**Comment by amitbhardwaj080387** [comment]
please update

**Comment by Carlgo11** [comment]
Hello Amit,
I looked at your profile and you don’t appear to have forked our repository.


I don’t quite understand what you mean by “2 lacs 78” but your Alexa ranking is above  378k and so it doesn’t meet our criteria of at or below 200k.
