### ISSUE TITLE
Citi Bank now supports 2-Factor Authentication

### ISSUE THREAD

**Issue by boktai1000** [2factorauth/twofactorauth#3467]
You are able to configure 2-Factor Authentication on Citi Bank. The best instructions / documentation I could find regarding this is here- http://www.citibank.com/tts/docs/2fa_nonenabled_clients_faq.pdf 

I am positive the option is available in accounts now. If anyone else would like to cross confirm before updating the site to list it as enabled, that's fine. I know that it at the very least supports SMS and Calling for verification purposes.

**Comment by gunr2171** [comment]
This information is correct, just enabled it myself.

**Comment by brycx** [comment]
Hi @boktai1000, thanks for the update. Would you like to add a PR that updates the entry?

**Comment by Carlgo11** [comment]
@boktai1000 the document you've linked to seems to only be for the 'Treasury and Trade Solutions' branch of Citi Bank. Have you tried on a normal banking/investment account?

**Comment by boktai1000** [comment]
It is setup on a normal Credit Card account currently. It's in the settings of my account, but I can't find any documentation on their site that mentions it - just that document. Maybe it's worth getting them to acknowledge via Twitter or something?

**Comment by boktai1000** [comment]
After talking to their Twitter Support account I received this site that has information that 2-Step Authentication is an option as well as includes a link that users can click to Enroll.

https://online.citi.com/JRS/pands/detail.do?ID=SecurityCenter&section=security_tools

**Comment by RichJeanes** [comment]
I can confirm. Just enabled this on my Citi credit card account. It's just as clunky as every other bank's solution (prompting you to select a method every time you log in and only supporting SMS and call), but it's there and required at _every_ login.
