### ISSUE TITLE
code.videolan.org support 2FA, based on GitLab

### ISSUE THREAD

**Issue by RussianNeuroMancer** [2factorauth/twofactorauth#3472]
VLC development site code.videolan.org now support 2FA, based on GitLab.

**Comment by Carlgo11** [comment]
Hello @RussianNeuroMancer,
we don't classify sites only supporting 2FA via third party logins as supporting 2FA.
Furthermore as code.videolan.org is a self-hosted version of GitLab it wouldn't be listed here.
