### ISSUE TITLE
Add SIMEX site in Authy apps

### ISSUE THREAD

**Issue by irazulkifli93** [2factorauth/twofactorauth#3473]
Please add the Singapore International Monetary Exhange (SIMEX) site in 2FA under bitcoin category for Authy apps.

**Comment by Carlgo11** [comment]
Hello @irazulkifli93,
as simex.global is ranked above 200k on [Alexa](https://www.alexa.com/siteinfo/simex.global) it doesn't meet our [guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) and therefore can't be added to our list.
Sorry for the inconvenience
