### ISSUE TITLE
Instagram only has SMS 2FA

### ISSUE THREAD

**Issue by GuillaumeRossolini** [2factorauth/twofactorauth#3478]
Even though their documentation says they allow for either SMS or an app [1] [2], they actually only allow SMS at the moment.

[1] https://help.instagram.com/566810106808145
[2] https://help.instagram.com/1582474155197965?helpref=faq_content

**Comment by jamcat22** [comment]
Hi @GuillaumeRossolini!

Instagram does support app-based TOTP 2FA, it's just being rolled out slowly in waves to all users. You can read about the roll out in Instagram's [blog post](https://instagram-press.com/blog/2018/08/28/new-tools-to-help-keep-instagram-safe/) on the feature. High profile accounts and those in the beta program were able to try this feature first. I was given access to this feature on one of my accounts last week, but a few friends of mine still don't have the option. You must use the Instagram app to turn on app-based 2FA, and ensure your app is up-to-date before trying to enable the feature.

Here's what my settings look like:
![Instagram App on iPhone X, Two-Factor Authentication Settings](https://user-images.githubusercontent.com/1897053/46557087-f9265c80-c8a5-11e8-900f-1f1af5248637.png)

Feel free to comment if there's something else I can help with!

Thanks,
Jacob
