### ISSUE TITLE
QR code is ok?

### ISSUE THREAD

**Issue by rafaelvannucci** [2factorauth/twofactorauth#3488]
Are you guys expect TOTP/FIDO or alternative solutions, like QR codes (WhatsApp Web) are also ok?

**Comment by Carlgo11** [comment]
I don't really understand what you're asking.
QR codes can't by themselves be 2FA. It has to link to something else like TOTP or OTP.

**Comment by Carlgo11** [comment]
I'm going to close this issue due to inactivity.
