### ISSUE TITLE
A way to represent cross-functional systems such as Google, Microsoft, Yahoo, etc

### ISSUE THREAD

**Issue by smarkwell** [2factorauth/twofactorauth#35]
The current category system doesn't really cover the breadth of larger cross functional authentication systems such as Google and Microsoft.  For example, should G+, Blogger and Gmail be separate systems or group in some other way?  As they all rely on Google's 2FA solution when enabled.

Same is true of Microsoft, but how that exactly works for each property is a little inconsistent.

**Comment by victorhaggqvist** [comment]
That could maybe be achieved by a "Corporations" section or something of that nature. Then adding a possibility to bind services to a corporation.

**Comment by jdavis** [comment]
I totally understand. I've been saying this to a lot of issues, but I need to think on it and let it sit in my head to see how to best represent it. I do think something needs to be done though.

**Comment by jdavis** [comment]
We're on our way to being able to represent this in #208. I'm closing this in favor of that one. Thanks for the suggestion.
