### ISSUE TITLE
ExpressVPN has two factor authentication now

### ISSUE THREAD

**Issue by Evernow** [2factorauth/twofactorauth#3521]
Hello! I just created my Github account! I just wanna say now when I try to login, every time I get a prompt to input the code sent to my email. I weirdly haven't seen an official announcement, but they do now have two factor authentication, email based anyways!

**Comment by Carlgo11** [comment]
Hello @Evernow,
could you send some screenshots of the login process and or setup process (with any personal information blurred out or painted over?)

**Comment by Evernow** [comment]
![proof of two2](https://user-images.githubusercontent.com/44484725/47571749-d7f6e000-d928-11e8-9372-1f8a547e3234.jpg)
![proof of two1](https://user-images.githubusercontent.com/44484725/47571750-d7f6e000-d928-11e8-8f00-c7b30d498083.jpg)
Of course! Here I include when the website is asking me and the email I receive!
