### ISSUE TITLE
Add a place for paid only

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#354]
Some TFA providers _cough_ Enjin, SecureSafe _cough_ only provide two factor authentication for people who pay for it. Maybe we could add a column to show if you have to pay to get TFA. (Maybe make the default no and then if they require a paid plan add a paid: Yes)

**Comment by smholloway** [comment]
I'm not sure how I feel about this. Do you have an example site using paid 2fa? I'd like to understand this better.

To avoid adding yet another column, perhaps the checkbox or docs icon could be replaced with a dollar sign icon. 

Playing devil's advocate: anyone coming to this site would be willing to pay for 2fa, so this may not be a big deal. Whether users are willing to pay or not, they can find out quickly by visiting the docs link.

**Comment by jamcat22** [comment]
Enjin (not currently on the list and I don't want to add it until Awesome 1.0 and the new format) and SecureSafe (also not on the list) both require a paid plan to activate TFA. I like your idea of adding a dollar sign symbol or something since not that many companies require paid plans for TFA. It might be a bit much to make a new column.

**Comment by jdavis** [comment]
I don't like that some sites paywall a feature like 2FA... Hmm...

**Comment by Donatzsky** [comment]
I like the idea of replacing the checkmark with a $. Unlike a separate column, this also allows for the case where one method may be free and another paid.

**Comment by jdavis** [comment]
Yeah, it's a good compromise having a dollarsign.

I'm still torn though because 2FA shouldn't be a paid only feature... I'd prefer if the sites were Tweeted at in hopes they'd change...

**Comment by jamcat22** [comment]
Maybe we could make it so that when you hover over the dollar sign it lets you click a link to tweet them.

Also, I think the rule should be that we only show the dollar sign if the website only offers paid TFA, not if it is just one method (like a hardware token) requiring payment and another method (like a software implementation) being free.

**Comment by Donatzsky** [comment]
The way I see it, paid = recurring fee/subscription. If it's just a one-time fee to get a HW token, then it should count as free. If the service only offers paid plans and 2FA is included in all of them, then it should count as free.

**Comment by smholloway** [comment]
Paid 2fa is still 2fa. I feel like this is getting too complicated. The logic is tricky for a relatively small gain. For example, the data files would need to change making it harder for people to update, and the logic would expand, increasing the chance for bugs. It would also clutter the UI--or at least fracture it.

How are people going to use this information? What problem does this (pointing out paid 2fa) solve?

**Comment by RichJeanes** [comment]
It's not so much that pointing it out solves a problem, but that it helps people stay informed which is basically (at least, IMO) the guiding principle of this site.

**Comment by smholloway** [comment]
How could we show that 2fa is paid without cluttering the interface or making it harder to add new sites?

Best I can come up with: add a new field for `paid`; if `paid` is `Yes` then show dollar signs instead of checkmarks. I immediately think of sites that have paid and free 2fa, which would break this scheme. So the fields (`email`, `sms`, `software`, etc) could be `Yes`, `No,` or `Paid`. I think that sucks for contributors and code maintainers. 

I'm also concerned that we'd need a legend to explain what the checkmark and dollar sign mean.

I'm open to ideas, but it doesn't seem worth it if it hurts the design or usability.

**Comment by jamcat22** [comment]
I think we should just add a green dollar sign icon next to their name instead of having it replace the checkmark. That way it doesn't add a new column, change the icons in the rows, or clutter the interface much. When you hover over the dollar sign it could say "This site only offers TFA on paid plans. Click the dollar sign to send a tweet asking them to make it free." or something similar. Maybe we could make it so when you clicked on the dollar sign it would tweet them asking them to make it paid if the `twitter:` tag was added.

We could also make it so that it defaults to no and it only shows the dollar sign if `paidonly: Yes` is explicitly added. That way the code doesn't get too cluttered with `paidonly: No` and `paidonly:` is only there if it needs to be.

As a side question, do things like `sms: No` need to be added or does it only need to be added when it is `sms: Yes`

**Comment by smholloway** [comment]
One only needs to add `Yes` where needed as `No` is the default. Here's a snippet from `index.html` as an example:

```
 {% if website.sms %}
      <i class="checkmark large icon"></i>
 {% endif %}
```

No truthy `sms`, no checkmark.

**Comment by jamcat22** [comment]
I think we should close this since we now have the amazing `exceptions:` option.

**Comment by jdavis** [comment]
:+1:
