### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [2factorauth/twofactorauth#3540]
I am saddened that the twofactorauth is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other)

**Comment by mxxcon** [comment]
This question came up a few times before.
Unfortunately it seems like we don't have enough people who would work on this feature to figure out all the nuances.

**Comment by Carlgo11** [comment]
It would also be extremely difficult to do that with our static site. Maybe with JS but that would probably mean all different versions would be added to the HTML = very long loading time.

**Comment by kmpoppe** [comment]
If I might add my two cents:

I think it would be absolutely fine, to generate localized versions of the HTML-page with English being the standard and then have some buttons to switch to the localized versions.

Of course, I'd volunteer for German translations of like everything, and I think there will be people one can find via twitter or anything, that will do the first complete translation of what is available.

For new additions to sites, CONTRIBUTIONS.md could say that at least English needs to be supplied, for additional categories all languages need to be supplied (which is easy af with Google Translate if you only need to translate one word). If no translation for other languages is provided, the localized pages could generate with the English text as a fallback.

The YAML for multiple language text could look like this:
```
exceptions:
  - lang: DE
    text: "Dies ist eine Ausnahme"
  - lang: EN
    text: "This is an exception"
  - lang: FR
    text: "Ceci est une exception"
```

**Comment by Carlgo11** [comment]
Moved to #6166
