### ISSUE TITLE
Can we add this? Aspire Financial Services (under investments)

### ISSUE THREAD

**Issue by ajar** [2factorauth/twofactorauth#3545]
_[Aspire Financial Services](https://www.aspireonline.com)_ is an investment management platform and financial record keeper, and also my employer. The only criterion not met is the global Alexa rating, north of 200k worldwide and around 50k within the United States. However, a good portion of our clients are still on an older platform accessed via another hostname from which we are migrating entirely this month.

I am ready to get the pull request in, but I wonder if this will be accepted considering the Alexa rating. Please review and let me know. We add two-factor authentication in our next release, and I want as many clients to use that as possible. Could an exception on this stipulation be made here? Lots of money involved. Thanks.

**Comment by brycx** [comment]
So the global rank seems to be dropping. And you said you're going to add 2FA in the next release, so it's not available yet. I don't think we should make an exception here, I see no specific advantage compared to other sites we have dropped for not being within the rating.

**Comment by Carlgo11** [comment]
If there's some other metric we can use (like social media following) then I don't see any problem with it being just below 200K. The site would however be listed as not supporting 2FA so that might not be something you're interesting in doing.

**Comment by ajar** [comment]
Sorry, should have mentioned that the next release was rolling out later that night, so 2FA features are live now. But considering that this is a fairly "private" service, meaning you either get an account through your employer or are yourself an employer or financial advisor, I see why it would not be a good fit.

My purpose in adding was to prompt 1Password alerts for 2FA, would like more of our clients to take advantage, but goes back to the relatively low traffic... scope of impact there would be next to nothing. Thank you for taking time to review this issue anyway! ✌️
