### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by ninavizz** [2factorauth/twofactorauth#3552]
Hello! I'm a UX practitioner, looking for excellent research on the usability of 2FA systems. I'm certain that Google and ID.me have done this, and I'm in touch with other orgs, too. I'd love to be able to make a public spot somewhere for other designers to also access this information, should orgs be willing to grant permission to open-source that knowledge. 

Might there be any interest in adding a "Usability" or "Research" section to the site?

(and by "Section," I mean a page with some links. Heh.)

**Comment by Carlgo11** [comment]
Hello @ninavizz,
I'm not quite sure what your asking. Is it to add some sort of advertisement on our site for another project? If that's the case then my response would be no.
If it's to access our 2FA data then it's already free for anyone to use under the MIT license.

**Comment by ninavizz** [comment]
No advertisements. Ever. 

User research. I'm looking for user research on 2FA interactions. I'm a UX'er, looking to guide a 2FA instance for a FOSS product. 

When you say "2FA data" what are you referencing? I see that the site content is licensed under an MIT schtick, but I don't see any user research on the site.

**Comment by ninavizz** [comment]
To be clearer: Currently your site has "Category" buttons, and upon clicking each a table for products within each category is revealed. Each table has columns for things—including support documentation. 

Each organization whose product is listed on the website either did or didn't do user research to validate the comprehension and usability of how they present their 2FA implementation to users. As a UX'er, I'd love to see artifacts of that research, from orgs willing to share. Mozilla seems like it'd be a great place to start, so I'll personally poke their UX team—but I'm sure 2FA user research must also exist, agnostic of any specific product... and it'd be great for the site to have a section for that stuff, should content come up.

**Comment by RichJeanes** [comment]
So are you suggesting we add another column to the table to link to research done on each site's specific UX implementation of their 2FA system? That doesn't seem like something that would be very common and probably not within the realm of educating the general user.

**Comment by brycx** [comment]
I have the same understanding of this as @RichJeanes.

I see one potential problem with listing UX information on various sites and companies. If we were to do this, users might not decide which service to use based only on what 2FA options are offered but also their UX "rating" as well. This could potentially put sites that don't have enough money or that haven't invested enough time in UX, at a disadvantage. Even if those sites offer better 2FA options compared to those with very good UX. I'd much rather "promote" a site offering all 2FA options with mediocre user-friendliness, compared to one offering only SMS but with the most user-friendly interface.

**Comment by kmpoppe** [comment]
Proposal to close due to inactivity and seemingly no fitting use in this project (as per @Carlgo11 @RichJeanes  and @brycx)
