### ISSUE TITLE
RunSignUp Supports Two-Factor Authentication

### ISSUE THREAD

**Issue by zecanard** [2factorauth/twofactorauth#3556]
Hello,

The fitness site [RunSignUp](https://runsignup.com/) recently added support for two-factor authentication using a software token (Google Authenticator/Authy). Setup is done via QR code (no manual entry with a seed code).

![screenshot 2018-11-15 at 23 16 10](https://user-images.githubusercontent.com/25799849/48599453-572a7300-e92d-11e8-8358-a812557cc111.png)

**Comment by brycx** [comment]
Hi @zecanard, would you be interested in making a PR to add this site yourself?

**Comment by zecanard** [comment]
Hey @brycx,

I don’t know what a PR is, but I’m not sure I’d be comfortable doing that. I haven’t done any programming or web development in 6 years.

**Comment by brycx** [comment]
That's no problem. Do you have a link for some documentation that describes how to setup 2FA here? If not, and it's only available to registered customers, I'd need a screenshot of it with personal information blurred out.

**Comment by zecanard** [comment]
I haven’t been able to find any documentation on this topic, so here’s a series of screenshots. Users should start from the account [Profile](https://runsignup.com/Profile) page.

Click **[MFA Disabled](
https://runsignup.com/Profile/MFA)** to start.
![screenshot 2018-11-20 at 12 11 52](https://user-images.githubusercontent.com/25799849/48795701-47ab8100-ecc3-11e8-8f78-5a877b0aeb1e.png)

Next, click **SET UP MFA**.
![screenshot 2018-11-20 at 12 12 03](https://user-images.githubusercontent.com/25799849/48794826-afac9800-ecc0-11e8-8de1-9181d30b04d9.png)

Then open your Authenticator app and scan the provided QR code (no manual seed entry available). Once that’s done, enter an authentication code provided by your app, then click **FINISH MFA SETUP**.
![screenshot 2018-11-20 at 12 12 14](https://user-images.githubusercontent.com/25799849/48794829-b0ddc500-ecc0-11e8-8d81-1a4b05cfc7c7.png)

If everything went well, you will get this confirmation screen:
![screenshot 2018-11-20 at 12 14 23](https://user-images.githubusercontent.com/25799849/48794830-b20ef200-ecc0-11e8-86f5-7c9e365b5a12.png)

Please let me know if you need any additional information. Thank you!

**Comment by brycx** [comment]
@zecanard That's plenty, thank you!
