### ISSUE TITLE
AppVeyor now supports 2FA

### ISSUE THREAD

**Issue by xt0rted** [2factorauth/twofactorauth#3571]
Their announcement https://www.appveyor.com/blog/2018/11/07/2FA-implementation/

**Comment by Carlgo11** [comment]
Hello @xt0rted,
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by xt0rted** [comment]
@Carlgo11 AppVeyor is already on the site https://github.com/2factorauth/twofactorauth/blob/51d977e7d77ffe3d9ab11892692b5b3ace3e4dba/_data/developer.yml#L26-L31

**Comment by Carlgo11** [comment]
Okay, still. Would you mind making a PR with the changes?

**Comment by onkarshinde** [comment]
Happy to pick this up if no one else is doing, once my pull request is merged (#3575).
