### ISSUE TITLE
CloudMQTT supports 2FA

### ISSUE THREAD

**Issue by metbril** [2factorauth/twofactorauth#3579]
CloudMQTT (cloudmqtt.com) supports 2FA.

https://www.cloudmqtt.com/blog/two-factor-authentication.html

You can use an TOTP token, but need to register a phone number for SMS first, that can be used to disable 2FA when needed. Which is not too secure, unfortunately.

**Comment by Carlgo11** [comment]
Hello @metbril,
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by metbril** [comment]
Today, the site does not comply to the required Alexa 200k ranking to be listed:

https://www.alexa.com/siteinfo/cloudmqtt.com

So I don't know if my pull request would be merged. I would only submit one if it has chance to be.
