### ISSUE TITLE
Pinterest does NOT have software token

### ISSUE THREAD

**Issue by Opt33** [2factorauth/twofactorauth#3586]
Pinterest does NOT have software token capability as indicated on the website. Only SMS at this time (per Pinterest website).

**Comment by Carlgo11** [comment]
@Opt33 is this outdated then? https://medium.com/@Pinterest_Engineering/two-factor-authentication-on-pinterest-238aa3dc92d1

**Comment by peevishvulcan** [comment]
Just checked today and on a US based account I was only offered SMS with no chance to connect an Authorization program.

**Comment by Carlgo11** [comment]
@peevishvulcan do you have Authy installed and registered to your number?

**Comment by peevishvulcan** [comment]
I have a similar program (1Password) that can issue one time passwords but I have no section to even add a 2FA program other than SMS.

![screen shot 2018-12-23 at 12 16 56](https://user-images.githubusercontent.com/46091720/50386854-be65e080-06ac-11e9-8e46-47eedcd3d85c.png)

**Comment by Opt33** [comment]
> 
> 
> @Opt33 is this outdated then? https://medium.com/@Pinterest_Engineering/two-factor-authentication-on-pinterest-238aa3dc92d1

@Carlgo11  I wouldn't say it's outdated, but I wouldn't say it's completely accurate either.  2FA (non SMS) is only available through Authy and not other OTP based apps (i.e. 1Password or DuoMobile). What's missing is Pinterest showing a QR code to scan using a password manager.

**Comment by Carlgo11** [comment]
If a site uses Authy as their 2FA solution they can use Authy's API to register the user by simply sending the phone number to Authy. If the user has registered to Authy they get a code with the app and if they don't have an account they get an SMS message with the code.
It's a proprietary system not using the RFC-6238 standard and thus you can't use 1Password or any other program other than Authy to generate the codes.

**Comment by Opt33** [comment]
> 
> 
> If a site uses Authy as their 2FA solution they can use Authy's API to register the user by simply sending the phone number to Authy. If the user has registered to Authy they get a code with the app and if they don't have an account they get an SMS message with the code.
> It's a proprietary system not using the RFC-6238 standard and thus you can't use 1Password or any other program other than Authy to generate the codes.

@Carlgo11 So what you're saying is IF a particular site is boxed into using one proprietary 2FA software token solution (i.e. Authy), THEN it's considered by the website as offering "2FA software token capability?"

If so, it'd be useful to discriminate between the 2FA software token types...especially for the layman or non-tech savvy determining if additional apps are necessary to make 2FA a reality for them.

**Comment by Carlgo11** [comment]
#3222
