### ISSUE TITLE
Add Azendoo in other

### ISSUE THREAD

**Issue by Ritchie007** [2factorauth/twofactorauth#361]
Azendoo is a Project ToDo website and iOS App (maybe Androïd soon).

They don't have plan to support 2FA in the near future.

Cheers,

Ritchie

**Comment by ilyakatz** [comment]
@Ritchie007 would you be able to create a pull request for this. Let me know if you need help

**Comment by jdavis** [comment]
In another PR, @Ritchie007 said he got a new job so he wouldn't be able to do pull requests. One of us might have to.

**Comment by ilyakatz** [comment]
got it, i assigned it to myself. initiative is punishable :)
