### ISSUE TITLE
misshosting provides 2FA

### ISSUE THREAD

**Issue by bugsse** [2factorauth/twofactorauth#3634]
Please update the site

**Comment by Carlgo11** [comment]
Hi @bugsse,
what kind of 2FA does Miss Hosting support? Could you provide a link to any documentation pages from Miss Hosting about how to add 2FA? If not, please attach a screenshot the setup process or login process _(with any personal information blurred out)_.

**Comment by bugsse** [comment]
Unfortunately, I can only access the misshosting controlpanel in Swedish, if I change to English I get redirected to their US portal, where I do not have an account. So the screenshot is in Swedish, I hope that's ok.

I can not find any documentation publicly available on their site, but once logged in to their customers portal, you can choose to activate 2FA on your account in a very easy and well explained process with just a few clicks. They recommend to use Google Authenticator but mention that other apps are supported as well.

The green button you see in the screenshot says "Click here to activate" and takes you to a very nice guide that helps you activate 2FA with QR-codes and everything.
As you can see in the red field, they even encourage you to activate it, and for some reason that text is still in English. 

Maybe I should point out that I am not in any way associated with misshosting, I'm just a very satisfied customer and I was a bit surprised to find them on your list since I've been using 2FA with them for quite some time now.

![misshosting2fa](https://user-images.githubusercontent.com/46709434/51234712-db20cb80-196d-11e9-9f63-2437c895d9ef.PNG)
