### ISSUE TITLE
Add consumercellular.com

### ISSUE THREAD

**Issue by ast96** [2factorauth/twofactorauth#3639]
I would really appreciate it if 2FA could be added for the Consumer Cellular mobile carrier website.

**Comment by onkarshinde** [comment]
@ast96 
Do you have a link to the documentation that mentions how the 2FA can be used?

**Comment by ast96** [comment]
@onkarshinde 
I am not sure what documentation you are referring to. As far as how the 2FA would be used, my hope is that it could be used to authenticate logins for people with Consumer Cellular accounts.

**Comment by Carlgo11** [comment]
@ast96 so they don't currently support 2FA?

**Comment by ast96** [comment]
@Carlgo11 to the best of my knowledge, that is correct - they don't currently support 2FA.
