### ISSUE TITLE
Open Links in a New Tab

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3643]
Please open all links in a new browser tab.
It is annoying when I open a documentation to set up 2FA and have to press "back" several times to get back to your Two Factor Auth List.

**Comment by RichJeanes** [comment]
This has been suggested before and I believe the current mentality is to leave that option to the user instead of forcing it to a new tab. If you middle click the link, it will open in a new tab (alternatively, right click -> Open in New Tab).

**Comment by OLLI-S** [comment]
OK, then close this issue.
But normally users click with the left mouse-button and the new page should normally open in a new tab.
I work as Usability-Engineer and UX expert.

**Comment by kmpoppe** [comment]
@OLLI-S I'm also always annoyed by websites linking away from themselves - twofactorauth.org seems to have no new-window-links at all (neither to GitHub, Josh's site and the other websites). I suggest you close this Issue, maybe there'll be a more clever idea to decide whether the user wants a new window or not in the future!

**Comment by OLLI-S** [comment]
Closed
