### ISSUE TITLE
Wells Fargo only accepts RSA SecurID hardware tokens (and not Yubikey, or anything else)

### ISSUE THREAD

**Issue by zoltan57** [2factorauth/twofactorauth#3644]
For Wells Fargo I suggest replacing the check mark under "Hardware Tokens" with "RSA SecurID only".

**Comment by zoltan57** [comment]
And Charles Schwab only accepts Symantec Hard Tokens and software tokens from the Symantec VIP Access app. I think it is important to push these vendors to a common standard where we consumers can choose the hardware token or MFA app of our choice, and indicating the limitations on your very informative website would be good start.

**Comment by RichJeanes** [comment]
We have left the columns as generic as possible for a reason. Having a separate column for each various 2FA implementation would quickly balloon and we never really settled on a good way to represent specific solutions within each column.

For the moment that leaves adding an exception to the site or implementing a solution that allows for a good, clean representation of specific implementations within columns. Discussion or Pull Requests on both ideas (or others) is absolutely welcome.
