### ISSUE TITLE
Local/CMS section

### ISSUE THREAD

**Issue by Terrance** [2factorauth/twofactorauth#365]
How about a section for enabling two-factor authentication on local installations of webapps and frameworks (for example, [Drupal](https://drupal.org/project/tfa) or [WordPress](https://wordpress.org/plugins/google-authenticator/) CMS)?

**Comment by jdavis** [comment]
Hmm. I'm going to vote to keep the fluff down. We are adding sites every day and I think if we were to add CMS sites, it would get a bit full.

**Comment by jdavis** [comment]
Closing this to clean up a bit...
