### ISSUE TITLE
Add site: Acclaim

### ISSUE THREAD

**Issue by burgatshow** [2factorauth/twofactorauth#3654]
The site Acclaim is not listed on the website but it support two factor auth.

https://www.youracclaim.com

Please add it to the list.

Thank you.

**Comment by kmpoppe** [comment]
Alexa Global Site Ranking is around 23k. Will add a change for this later.

**Comment by kmpoppe** [comment]
Solved by #3663, please close Issue.

**Comment by Carlgo11** [comment]
@kmpoppe in the future, if you add a text like `fixes #3654` or similar then GitHub will automatically close the issue when your PR is merged. Just a nifty little feature 😄

**Comment by kmpoppe** [comment]
@Carlgo11 I wrote "regarding issue #3654" in the CI comment - that was not enough ;-) Thanks for letting me know the correct syntax ;-)

**Comment by Carlgo11** [comment]
@kmpoppe list of the accepted phrases: https://help.github.com/articles/closing-issues-using-keywords/
