### ISSUE TITLE
Paypal uses only SMS

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3660]
In the Two Factor Auth List I see that PayPasl offers 2FA coes by
- SMS
- Hardware Token
- Software Token

When I open the linked docs (https://www.paypal.com/us/webapps/mpp/security/security-protections) I can see that PayPal only supports SMS (at least in Germany).
When I open my PayPal account and go to the settings, I also read only SMS.

**Comment by kmpoppe** [comment]
I can second that, my German PayPal Account also only shows SMS support for two factor authentication.
@OLLI-S, can you try to find out, what countries support which methods, so that we can update the warnings here?

**Comment by OLLI-S** [comment]
@kmpoppe I have no idea how to find that out, because I don't have foreign PayPal accounts.
In my German account I just went to the settings and saw, that only SMS is available.
But I have no idea how to find out if an US or UK for example allow software tokens.

**Comment by kmpoppe** [comment]
@OLLI-S I just saw that there already is a warning in the data "2FA is only available in a few countries. Contact PayPal on twitter for an up to date list of available countries." - I think we're not going to get any more specific than that. 

BTW: There is a long thread about how stupid PayPal is about only having SMS in Germany:
https://www.paypal-community.com/t5/Kontosicherheit/Standard-Zwei-Faktor-Autorisierung/m-p/1365875

I'll go forward and try to find a way to get something going about that sh**, but I guess this Issue could be closed, as twofactorauth.org is already warning about problems, right?

**Comment by OLLI-S** [comment]
Oops, I have overseen the warning.
But believe it or not: I have no twitter account (so I wrote an email to the PayPal Support).
Yes, with the warning the topic can be closed.

**Comment by kmpoppe** [comment]
You'd need to close the Issue yourself, I can't :-)

**Comment by OLLI-S** [comment]
Closed

**Comment by mxxcon** [comment]
Can you use this link? https://www.paypal.com/webscr?cmd=_setup-security-key

**Comment by kmpoppe** [comment]
With that link my German account can exactly either
a) add SMS as a security method or
b) activate the hardware token you received ... yet you can't order one.

**Comment by OLLI-S** [comment]
Same here.
I would like to sue an authenticator app (my password manager Enpass)

**Comment by Carlgo11** [comment]
For consistency, let's try and keep everything related to PayPal's 2FA in #1026

**Comment by OLLI-S** [comment]
OK
