### ISSUE TITLE
Please add Cabify

### ISSUE THREAD

**Issue by ubidragon** [2factorauth/twofactorauth#3662]
The site Cabify is not listed on the website but it support two factor auth.

https://cabify.com

Please add it to the list.

Thank you.

**Comment by kmpoppe** [comment]
It seems cabify.com is not listed on the Alexa Global Site Ranking.

**Comment by Carlgo11** [comment]
@kmpoppe 72k on Alexa. https://www.alexa.com/siteinfo/cabify.com

**Comment by kmpoppe** [comment]
Must've been really blind yesterday, so yeah... Will add site later.

**Comment by kmpoppe** [comment]
@ubidragon I just registered with cabify.com, yet the only Code Challenge-Response I get is when I register to add a mobile number which then sends me a text. I don't get 2FA for login, yet I cannot check whether it's needed to call a ride.
Can you elaborate what they auth-service they offer?

**Comment by kmpoppe** [comment]
bump @ubidragon, please review what I wrote, thanks!

**Comment by kmpoppe** [comment]
@carlgo11 I couldn't confirm, that cabify uses 2fa and OP doesn't respond. Please add the `inactive` label, thx.
