### ISSUE TITLE
Additional categories "Professional" and "Logistics"

### ISSUE THREAD

**Issue by kmpoppe** [2factorauth/twofactorauth#3664]
I'd like to propose 3 new categories:

"Leisure" for hobbies and spare time things. Things like postcrossing (currently in Other) and geocaching (not yet in list) don't really fit in "Social".
"Professional" for things that are supposed to boost your personal working life. That MIGHT include Xing and LinkedIn (currently in Social) and YourAcclaim (Pull Request to add to Other).
"Logistics" for things like Post- and Parcel-Services (UPS, DHL, RoyalMail, ...)

What does everyone think?

**Comment by jakejarvis** [comment]
I do like Professional (or maybe "Office"). Seems like it would take a big chunk out of the Other category, namely:

- Airtable
- AngelList
- BasisCode Compliance
- Cisco
- Cosmolex
- Everlaw
- Findmyshift
- Formstack
- Freelancer
- IEEE
- Indeed
- Jitbit
- Kayako
- Mathworks
- Monster
- Office 365
- Promoter
- Repairshopr
- SignNow
- SmartSimple
- UpWork
- Usabilla
- WageWorks
- Yclas
- YourAcclaim

Logistics stuff would probably fit well under Professional too if it's not deemed worthy of its own category... even though UPS/Fedex are consumer companies, I'm guessing the only people who bother setting up 2FA on them (besides people like us) are the businesses doing the shipping.

I could make the PR if others agree?

**Comment by mxxcon** [comment]
Just the terminology of "logistics" might not click with people.

"Professional" and "Office" also sound a little....awkward(?).. While I can see that being a good candidate for a new category, perhaps we can come up with a different name?

**Comment by jakejarvis** [comment]
Business maybe? 

Also, the tiny Legal category could definitely be folded into this new category IMO.

**Comment by kmpoppe** [comment]
My initial idea behind Logistics were (mostly) parcel services, and - at least in Germany - many of them have consumer logins so that one can have additional services around your parcel. Deutsche post/DHL has a shitload of stuff you can do.
What about "Postal services" with the `shipping fast` icon?
For "Business" the `briefcase` icon would be an idea, even more so, when #3694 gets merged with the health icon being changed.
@jakejarvis If we come to a decision for both categories (Leisure currently makes no sense) here, you could do the PR as I'm away until Saturday.
//Kai

**Comment by Carlgo11** [comment]
@kmpoppe how about `box` icon for logistics?

**Comment by kmpoppe** [comment]
@carlgo11 I saw in #3694 that `box` was your choice for logistics, but I am unsure whether that the "movement of stuff" associated to post and parcel services is sufficiently represented with just the plain box. 🤔

**Comment by dsoegijono** [comment]
How about "Productivity"? Seems a more common category for apps/websites.

**Comment by Carlgo11** [comment]
bump @kmpoppe

**Comment by kmpoppe** [comment]
So we are in agreement for **Productivity** with `briefcase` and **Logistics** with `box`?

**Comment by Carlgo11** [comment]
Yes?
But we can make a final decision when there's a PR.

**Comment by kmpoppe** [comment]
Obvs., I'll do a PR soon, what about the list of Jake (https://github.com/2factorauth/twofactorauth/issues/3664#issuecomment-460384837), do you agree that they should go into the **Productivity** upon launch of the category?

**Comment by phallobst** [comment]
Category "Post and Shipping" has been added by PR #5140.
