### ISSUE TITLE
Site Ranking revisit

### ISSUE THREAD

**Issue by kmpoppe** [2factorauth/twofactorauth#3674]
As sites are not included here if they have an Alexa ranking below 200k, what shall happen is a page drops out of that range?
If one were to check every entry regularly (say once a month), sites with fallen rankings could be flagged.
Thoughts?

**Comment by mxxcon** [comment]
We keep them for now.
The work have already been done to review and merge so no point deleting.
The reason we restrict to alexa200k is otherwise we'd be flooded with fly-by-night sites simply using this as spam referral.

**Comment by kmpoppe** [comment]
Thanks for the heads up!
