### ISSUE TITLE
Travis checks for Pull Request is broken

### ISSUE THREAD

**Issue by kmpoppe** [2factorauth/twofactorauth#3677]
My PRs #3675 and #3676 are blocked because Travis died after it ran into a HTTP 503?
Bump @Carlgo11 @mxxcon @stephengroat 
Regards
Kai

**Comment by kmpoppe** [comment]
Need to revisit the logs, there's something gone horribly wrong

**Comment by mxxcon** [comment]
#3675 passed travis test and you closed #3676... 🤷‍♂️

**Comment by kmpoppe** [comment]
Yes, I was being an idiot, because I checked the .2 result first I saw the 503. Obvs. this was a result of the .1-check failing and that alluded me 🤷‍♂️. My brain seems to need sleep. Thanks!
