### ISSUE TITLE
paypal-Info-URL is not correct any more

### ISSUE THREAD

**Issue by Eastpak1984** [2factorauth/twofactorauth#3687]
The paypal-Info-URL is not correct any more

**Comment by Carlgo11** [comment]
Is this any different from #3688?

**Comment by Eastpak1984** [comment]
Of course. One is for the How To-Url, one for the missing function.

**Comment by mxxcon** [comment]
@Eastpak1984 you need to elaborate and explain what you mean by your pickets. 5 words is not enough to understand you.

**Comment by Eastpak1984** [comment]
Oh, Paypal fixed it - now the URL to the Docs is fine again. Ticket can be closed.
