### ISSUE TITLE
paypal "Hardware Token"  & "Software Token" is not available

### ISSUE THREAD

**Issue by Eastpak1984** [2factorauth/twofactorauth#3688]
Paypal stopped their support for token 2FA.

They only support SMS-2FA  now.

**Comment by kmpoppe** [comment]
@Eastpak1984 #1026 has a lengthy discussion about PayPal. There is a written exception in banking.yml already that says, that 2FA might not be available in specific countries, so, to keep workload off the project I'd propose to close this Issue.

**Comment by kmpoppe** [comment]
Closing Issue for now, as Software 2FA has returned per April 2019 policy changes
