### ISSUE TITLE
Game "Ashes of Creation" supports 2FA (Software Token)

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3689]
The game "Ashes of Creation" (https://ashesofcreation.com/) supports 2FA by Software Token.
If you create an account and log-in then you can add "Two Factor Auth".

Here a screen shot where I have to enter the code:

![ashes_of_creation_2fa](https://user-images.githubusercontent.com/8037790/52162552-20672c00-26d6-11e9-8288-e332fbaa7564.png)

**Comment by mxxcon** [comment]
Does the site save payment info?

**Comment by OLLI-S** [comment]
This is a MMORPG (in development) and I can buy different game packages to get early access.
When I add a package to my chart and check out, a popup from Xsolla opens, so the payment is done by a 3rd party company (a vendor).
In my profile I don't have fields to store payment information.

Why are you asking @mxxcon ?

**Comment by mxxcon** [comment]
Just wondering how/if it would qualify for our https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria

**Comment by OLLI-S** [comment]
Well, I don't have this game yet.
But I know that you can buy Ember (in-game marketplace credits where you can buy stuff).
So I pay real money to get in-game money that is used to buy stuff.

In my eyes this fits to **criteria 3** (Money: Any site that deals with money)

**Comment by OLLI-S** [comment]
@mxxcon I saw that you already have some game-related entries in this list.
You have companies like Epic and Uplay but also single games like Elder Scrolls Online and Eve Online.
I don't understand why you asked if Ashes of Creation matches the criteria (it seems like the other games fit these criteria?)

**Comment by OLLI-S** [comment]
Thank you for adding Ashes of Creation
