### ISSUE TITLE
Ubisoft/Uplay - Add note that 2FA is not for the Website

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3690]
I added 2FA at my uPlay account.
When I start the **uPlay desktop app** then the **2FA code is required** (as expected).
When I open the **German uPlay website** (https://uplay.ubisoft.com/de-DE) then the **2FA code is not required** (I can login by username and password).

This is in my eyes very dangerous because after logging in at the uPlay website I can deactivate 2FA.
So if my uPlay account gets hacked the hacker can login without 2FA and then deactivate it.

**Comment by Carlgo11** [comment]
I can confirm it doesn't prompt for any 2FA codes, even when editing security options.
As this undermines 2FA completely it would probably be best to mark uPlay as not supporting 2FA (`tfa: No`)

**Comment by kmpoppe** [comment]
Would that case qualify for adding an exception text for "fake 2fa"?

Am Mo., 4. Feb. 2019, 04:08 hat Carlgo11 <notifications@github.com>
geschrieben:

**Comment by Carlgo11** [comment]
@kmpoppe with `tfa: No` there's no need for an exception. Plus, I don't think exceptions even work with `tfa: No`.

**Comment by jamcat22** [comment]
Could someone please provide screenshots of the management system for accounts you’re able to access without 2FA? The only management system for 2FA I can find is https://account.ubisoft.com/ which requires 2FA even if you’re already logged in to uplay.ubisoft.com, club.ubisoft.com or store.ubi.com

**Comment by OLLI-S** [comment]
@jamcat22 I go to https://uplay.ubisoft.com/de-DE and click on the profile image at the top-right corner.
Then the following page is shown:

![uplay_login_01](https://user-images.githubusercontent.com/8037790/52240790-317c8c80-28d2-11e9-9f76-c3150cd6b131.png)

Here I enter my username and my password and then I am logged in.
No 2FA code required.
Then I go to my account settings and have to confirm that it is me (by clicking on "Continue"):

![uplay_login_02](https://user-images.githubusercontent.com/8037790/52240798-39d4c780-28d2-11e9-8193-cf586e68aa9e.png)

Then I scroll down and click on the Security Settings:

![uplay_login_03](https://user-images.githubusercontent.com/8037790/52240805-3e997b80-28d2-11e9-92ab-a827617b92fe.png)

Here I scroll down to "Manage my Twp-Factor-Authentication":

![uplay_login_04](https://user-images.githubusercontent.com/8037790/52240825-4eb15b00-28d2-11e9-8bd5-66ba1c55ba01.png)

And then I can deactivate 2FA;

![uplay_login_05](https://user-images.githubusercontent.com/8037790/52240836-57a22c80-28d2-11e9-8464-8fb0909d1adb.png)

Now I see a question "Do you really want to...?" and I click on "Yes".

![uplay_login_06](https://user-images.githubusercontent.com/8037790/52240970-c54e5880-28d2-11e9-8881-48e35e57fb67.png)

Now an wait animation is shown **for several minutes**...
I keep you updated with the results.

**Comment by OLLI-S** [comment]
Now after 10 minutes the animation is still shown.
One reason could be: yesterday I contacted the Ubisoft Support and this morning I received an email where they asked me to confirm my account and then they will remove 2FA.
So maybe this is the reason why I can not remove 2FA here.
But it is shocking that I can log in without 2FA and also update my profile settings...

**Comment by OLLI-S** [comment]
I also reported the issue to the German Computer Magazine called **c't**
They contacted Ubisoft and **now the issue is solved**:
When you log into the website there is still no 2FA Code required, **but** as soon as you go to the account settings you have to enter your password again **and also the 2FA Code**.

**Comment by Carlgo11** [comment]
> and not **the issue is solved**

what?

**Comment by OLLI-S** [comment]
> > and not **the issue is solved**
> 
> what?

Sorry, my fault (typo): **now** the issue is solved.
I updated my posting.
Thank you for reporting.

**Comment by kmpoppe** [comment]
@olli-s so ... The Issue could be closed?

**Comment by OLLI-S** [comment]
Yes, the issue can be closed.
