### ISSUE TITLE
Twitter "Software Token" Does not work any more

### ISSUE THREAD

**Issue by Eastpak1984** [2factorauth/twofactorauth#3693]

**Comment by Eastpak1984** [comment]
Etwas ist aus technischen Gründen schiefgelaufen.
![unbenannt](https://user-images.githubusercontent.com/3694647/52210499-8cd55d00-2887-11e9-96ac-a15db48594ad.JPG)

**Comment by jakejarvis** [comment]
Seems to still be an option for me. Maybe it's a regional change?

![Screen Shot 2019-02-04 at 2.45.25 PM](https://user-images.githubusercontent.com/1703673/52232971-e475c780-288b-11e9-8c51-1eb0c0e1ea58.jpg)

**Comment by Eastpak1984** [comment]
This part you show works perfect. I get the QR Code, generatore the TOTP Codes, but these dont work for the Login - there i get the error above. Only the SMS Codes work.

**Comment by Carlgo11** [comment]
@Eastpak1984 I think you're better of contacting Twitter support first. If they confirm that RFC-6238 is unavailable then we'll take it from there.

**Comment by kmpoppe** [comment]
I have removed TOTP from my Twitter account, signed off, signed on and re-added TOTP (all in German as well as @Eastpak1984) without any problems.
I think this might either have been a temporary problem or there is something wrong with the account, alas this shouldn't be an Issue here.
Proposal to close.

**Comment by conorgil** [comment]
Agreed that it sounds like this can be closed.
