### ISSUE TITLE
Please add tokopedia.com

### ISSUE THREAD

**Issue by rifqire** [2factorauth/twofactorauth#3695]
Tokopedia is one of the popular online marketplaces in Indonesia and is the only one that supports 2FA via Google Authenticator. Users can enable it in the Account Settings menu.

https://www.tokopedia.com
![24198](https://user-images.githubusercontent.com/30471081/52280211-efb11c00-298d-11e9-84d8-fcb571984240.jpg)

**Comment by kmpoppe** [comment]
Closed by #3720
