### ISSUE TITLE
Please add MasterOf13FPS.de

### ISSUE THREAD

**Issue by timxllr** [2factorauth/twofactorauth#3696]
**Page: **https://masterof13fps.de/
**Types: **Email & Software Token
**Setup for 2-FA: **https://masterof13fps.de/forums/account/two-step

**Comment by kmpoppe** [comment]
Site is below 200k Global Alexa Ranking and bloating with ads. My recommendation is to not add this page.

**Comment by Carlgo11** [comment]
@RealFantaCoke,
Unfortunately as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.
