### ISSUE TITLE
Please add Datto.com

### ISSUE THREAD

**Issue by pm17788** [2factorauth/twofactorauth#3697]
Please consider adding Datto (datto.com) to the list of hosts providing 2FA.

The setup instructions are here:

* https://kb.datto.com/hc/en-us/articles/360021169311-Getting-Started-With-Two-Factor-Authentication-2FA-in-the-Datto-Partner-Portal
* https://kb.datto.com/hc/en-us/articles/360016176791-How-Do-I-Enable-Two-Factor-Authentication-For-My-End-Users-

Supported 2FA methods are:
* SW Token (Authy)
* SMS

**Comment by kmpoppe** [comment]
References #3707

**Comment by pm17788** [comment]
Datto has a number of products under its umbrella, but they're not stand-alone services. The users interface through a single, unified portal, or through dedicated and fully separate portal for that product. This may change in the future, but currently, the "services" model proposed in #3707 does not seem to be applicable.
