### ISSUE TITLE
Please add AutoTask.net

### ISSUE THREAD

**Issue by pm17788** [2factorauth/twofactorauth#3698]
Please consider adding AutoTask (aka Datto RMM) (autotask.net)

The setup instructions are here: https://help.aem.autotask.net/en/Content/2SETUP/Users/TwoFactorAuthentication.htm

Supported auth methods:
* SMS
* SW Token (TOTP)

**Comment by kmpoppe** [comment]
References #3707 because autotask is a service of #3697 (datto.com).

**Comment by pm17788** [comment]
While AutoTask is part of the Datto umbrella, the authentication backends aren't currently connected. It would not be accurate to think of Datto AutoTask products as a service under a unified Datto authentication system at this time. This may change in the future, but currently, the "services" model proposed in #3707 does not seem to be applicable.
