### ISSUE TITLE
ID.me

### ISSUE THREAD

**Issue by kistanovdev** [2factorauth/twofactorauth#3700]
ID.me does not have Two-Factor authentication setup in the account settings.

**Comment by kmpoppe** [comment]
@kistanod I have just recently added id.me to support 2fa, because the help section says that you can secure your va.org or Cali DMV account with 2fa.
That led myself and others to believe that 2fa was provided through the id.me account.
Could you get any deeper into what you wrote?

**Comment by mxxcon** [comment]
Is this info not accurate? https://help.id.me/hc/en-us/sections/115000551794-Securing-My-Account-with-2FA

**Comment by kistanovdev** [comment]
When going into the direct settings of an account of id.me website, there is not an option to add any type of two factor authentication. 

Other sections on the image do not provide any 2FA opt-in options. 

<img width="932" alt="screenshot 2019-02-07 20 39 21" src="https://user-images.githubusercontent.com/38178976/52459302-38e1a700-2b19-11e9-8aec-7d73ed6602c5.png">

**Comment by kmpoppe** [comment]
https://help.id.me/hc/en-us/categories/360001435974 clearly shows how ID.me accounts can be set up for 2-factor-authentication, therefore I'm closing this Issue as invalid.
