### ISSUE TITLE
Google Auth support =/= Authy support

### ISSUE THREAD

**Issue by joshsleeper** [2factorauth/twofactorauth#371]
Please feel free to correct me if I'm wrong, but a number of sites in this list that claim to support Authy are incorrectly labeled. They implement Google Auth., which Authy can _manage_, but they don't actually implement Authy-based codes. 

Google Services (Google+, Gmail, etc.), Facebook, and Outlook are all examples of this. Humble Bundle is one of the few that actually implements Authy properly.

It'd be nice to only show an Authy check for sites that actually implement Authy-based codes.

Thoughts?

**Comment by jdavis** [comment]
Great point, we are actually dealing with this now in #333. The idea is that we will no longer show specifically what is used, instead just list IF they have 2FA.

Since you are pretty knowledgeable, we'd love to hear your feedback on that issue.

**Comment by joshsleeper** [comment]
I actually saw #333 just after I posted this haha. Whoops~
At a glance it didn't occur to me that it would be relevant to my specific concern, but it looks like it's being worked on in some fashion.

Since the focus of the site is really to present a simple view of who supports 2FA at all, my wants may be more of an edge case haha. That said, the one thing I'd still love to an easy way to see who all supports certain software auth methods.

I think that's exactly what you were referring to here:
https://github.com/jdavis/twofactorauth/pull/333#issuecomment-38404420

For example, I personally use Authy, Google Auth, and Duo Security (as well as SMS and Email auth where that's the only option), but I'd love to use Authy-based codes or Duo Push where I can e.g. not just as a frontend for a 6-digit Google Auth code. I think that may be hard to see at a glance with the new layout.

Some sort of mouseover bubble for the software token section is one option, but that still makes comparing sites tedious since you have to mouse over every site individually.

Another option might be an advanced/expanded view. This could be a checkbox or toggle button at the top of the page that, when checked/selected, does one of two things:
1. It swaps the checkboxes that are checked in the Software Implementation column with a number of unique icons representing the specific software tool that site/service supports. Ex. A Google Auth icon, a Toopher icon, and an Authy icon, each (if possible) linking to a support page on that site about them, although that's just icing on the cake. ;)
2. It swaps out the entire Software Implementation column with a unique column for each service, similar to how Google Auth and Authy are shown now. I prefer this idea, since it'd be nice and clean and wouldn't force anyone to have to recognize two different types of column notation. However, it's definitely less mobile friendly, so there's that haha.

I'm sure there are other solutions, and if you've got feedback please let me know! I'm actually a UI/UX developer where I work, but I work more on the code side of things, so don't expect any mock-ups from me better than whatever I could make in MS Paint. XD

**Comment by jdavis** [comment]
Hey @joshery420. I like your idea and have had a similar vision of an Advanced and Simple view.

We finished up #333 which definitely addressed the short term concerns but I think this is a valid long term one.

**Comment by jdavis** [comment]
I'm closing this for now but Advanced/Simple will return to this if/when we add Advanced/Simple views.
