### ISSUE TITLE
Please add feuerwerk-forum.de

### ISSUE THREAD

**Issue by Eastpak1984** [2factorauth/twofactorauth#3717]
https://www.feuerwerk-forum.de does support 2FA with email and App.

**Comment by Eastpak1984** [comment]
ah, its not only this forum. The Forum provider supports it:

Forum software by XenForo™ © 2010-2019 XenForo Ltd.
https://xenforo.com/community/threads/two-step-verification-and-security-improvements.99881/

**Comment by mxxcon** [comment]
how would this forum fit in our site criteria?

**Comment by Carlgo11** [comment]
Self hosted products aren't listed on twofactorauth.
