### ISSUE TITLE
PayPal listings are incorrect

### ISSUE THREAD

**Issue by joekir** [2factorauth/twofactorauth#3722]
https://github.com/2factorauth/twofactorauth/blob/f9e85f1db516766f0ff41d621384f0ef5388f766/_data/payments.yml#L103

They have SMS and that's it :(
They call SMS their "security key"

They don't have TOTP/HOTP (what the app refers to as software)
They don't have U2F (what this app refers to as hardware)

**Comment by kmpoppe** [comment]
@joekir #1026 lists every problem this community has with PayPal and it not providing a real 2FA. There are exceptions listed in the PayPal entry.

**Comment by joekir** [comment]
First I laughed, then I cried. I'll close this issue
