### ISSUE TITLE
Please add Gamesplanet.com (does not support 2FA yet)

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3728]
Please add the website https://gamesplanet.com to your list.
It is a store where you can buy computer games.

The games you bought are listed in your account where you can also see the Steam keys.
So if you take over the account you can also take over the steam keys (if they are not yet activated in Steam).
You also can pay-in money (like from a paysafecard) to your wallet so if you have some money in your wallet this can be used to buy games.
This fits perfectly your criteria!

Up to now they don't offer 2FA.
At the support site (https://gamesplanet.com/support) you see their Facebook and Twitter page.
I sent an email right now to the email address listed in the support website (hilfe@gamesplanet.com).
I have a German OS, to the email address is a German address.

**Comment by kmpoppe** [comment]
Closed by #3805

**Comment by OLLI-S** [comment]
Thank you for adding Gamesplanet!
