### ISSUE TITLE
How do I upload an image?  I can't tell from the Contributing.md page.

### ISSUE THREAD

**Issue by myuseraccount** [2factorauth/twofactorauth#3742]
I am new to Github, excuse my ignorance of common practices.

If I try to upload an image to the img folder, it tells me Push access to the repository is required.  Does this mean that the only way to upload is to...
1. clone the repository
2. add the file to my "fork"
3. commit my changes
4. wait for a maintainer with higher access to push the changes into the main tree

I don't see anything on the contributing page that suggests this.  It just talks about what format is preferred for the icon.  I was able to modify the Internet category data file directly from the web interface, so I just want to add the icon for the entry I added.

**Comment by mxxcon** [comment]
fork this repo
(optional but recommended) make a new branch in YOUR forked repo
commit your changes, including file upload.
create a new pull request here from your branch into our `master`.
we'll review it and take care of the rest.

You should be working and making changes only in your forked repo. once all your changes are complete, then you create a pull request(ie you are asking us to "pull" a set of changes from your repo into ours)
