### ISSUE TITLE
US Social Security website allows 2FA via E-Mail as well

### ISSUE THREAD

**Issue by Sea-Worker9552** [2factorauth/twofactorauth#3757]
Update per title.

**Comment by Carlgo11** [comment]
Hello @dmo580,
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by Sea-Worker9552** [comment]
I apologize that I'm not saavy enough to create a pull request. My comment/request here wasn't to add a new site but to correct a mistake

![Screenshot](https://user-images.githubusercontent.com/1091670/55042146-82b11e80-4fed-11e9-95e7-dc65b2c18aa7.png)

**Comment by kmpoppe** [comment]
@dmo580 I cannot read the documentation for the 2fa options at present, maybe because the service just went into maintenance shutdown. I will take a look at a later time and then create the PR so that you don't have to.
