### ISSUE TITLE
Add password information

### ISSUE THREAD

**Issue by lukekim** [2factorauth/twofactorauth#376]
The site is called 'two factor auth' but we are only listing one of the factors.

Let's add an additional column for basic password information (the first factor) the for most being maximum password length, and a twitter message to say 'please consider increasing your maximum password length'.

I am happy to submit a pull request with the change if we can get agreement we should add this extra column.

**Comment by jdavis** [comment]
Hey @lukekim,

Thanks for the suggestion. I am a bit hesitant to add that though because while I agree that having a max length for the passwords is silly, I just don't know how useful people would find it.

I must say I care a lot about security yet I have never sought out websites that have better support for longer passwords. That may just be me though...

**Comment by lukekim** [comment]
If you use any type of password manager with long and complex passwords, then you run into this thing all the time.

The main benefit would be the Twitter button providing some public pressure I think. I considered making a fork of the site just for passwords, which may be a better way to go, because I like the format.

**Comment by RichJeanes** [comment]
Actually a maximum password length in some cases is not silly, but a limitation on the password hash algorithm that is being used. While most good hashed allow for longer passwords (I know bcrypt can take something like 50 character password), there's no way to actually know what hash a site is using to call them out on it.

**Comment by jdavis** [comment]
I think the first factor is pretty well supported (considering the length issue and everything @RichJeanes mentioned from above). I really appreciate the input though, @lukekim.
