### ISSUE TITLE
Tumblr and Hover 2FA works also with Authy 

### ISSUE THREAD

**Issue by davidmenzel** [2factorauth/twofactorauth#378]
I found two mistakes. The 2FA for Tumblr and Hover works also with Authy.

**Comment by jdavis** [comment]
Hey @davidmenzel. Thanks for the heads up.

The good news is that #333 will make Authy/Google Auth obsolete. We're switching to just categorize things as Software, Hardware, SMS, Email, Phone. This should fix the problem you see.
