### ISSUE TITLE
Add virustotal.com

### ISSUE THREAD

**Issue by rakleed** [2factorauth/twofactorauth#3784]
Please add [VirusTotal](https://virustotal.com) to the Security section. I did not find on their [support page](https://support.virustotal.com) for information about 2FA, but in [Settings](https://www.virustotal.com/gui/settings) there is an opportunity to enable 2FA using a software token.
<details><summary>Screenshots:</summary>

![screenshot-www virustotal com-2019 04 06-02-20-23](https://user-images.githubusercontent.com/19418601/55661492-bde4f600-5814-11e9-9a31-67631860c153.png)

![screenshot-www virustotal com-2019 04 06-02-22-41](https://user-images.githubusercontent.com/19418601/55661496-c63d3100-5814-11e9-805e-7378ecb1d456.png)

</details>

But I am not sure if it is suitable for [Site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria).

**Comment by kmpoppe** [comment]
I _think_ this could fit the `Security` category, but am also unsure. @Carlgo11 ?

**Comment by jtagcat** [comment]
I'd agree on Security, if not, then Other

**Comment by Carlgo11** [comment]
Yes Security seems fine.
When it comes to the site criteria, what can I do with an account on VirusTotal? I've only ever used it without an account.
Depending on what an account has access to it could potentially qualify under section 1 and 2.

**Comment by JackThursby252** [comment]
An account enables you to gather reputation points with a sample. A way to identify more trusted users to speed up av siganture updates on unknown samples with some av vendors.

And you get access to a pretty cool api. Security sounds reasonable.

**Comment by kmpoppe** [comment]
Closed by #4005
