### ISSUE TITLE
Network Solutions 2FA?

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#379]
Network Solutions is in Domains as tfa: No but verisign: Yes (now software+hardware: Yes). Any one know the correct answer?

**Comment by jdavis** [comment]
I thought I remembered Network Solutions: #190 and then #216 updated it to be a `Yes`.

**Comment by smholloway** [comment]
I vote to drop the `software` and `hardware` and make `tfa: No` for Network Solutions. Sources say that [Network Solutions does not support 2fa](https://konklone.com/post/protect-your-domain-name-with-two-factor-authentication). It looks like [VeriSign bought Network Solutions in 2000](http://money.cnn.com/2000/03/07/deals/verisign/), but I can't find any confirmation about them offering 2fa. There's also no docs link.

Also, we don't have to be perfect--if Network Solutions does have 2fa available, anyone can make the change and submit a pull request--with the proper docs link.

**Comment by jdavis** [comment]
Yeah, I second that as well.

**Comment by RichJeanes** [comment]
Sounds like a consensus. Will update for cleanliness.
