### ISSUE TITLE
Add cp.blacknight.com please

### ISSUE THREAD

**Issue by thecivvie** [2factorauth/twofactorauth#3790]
An Irish hosting and domain seller have added 2 FA to their customer login at the control panel. They use Software Tokens for 2FA, don't require a telephone number

**Comment by kmpoppe** [comment]
Hi!

Could you provide an URL with a description on blacknight's page of how 2fa
can be setup ?

Kai

thecivvie <notifications@github.com> schrieb am Mo., 8. Apr. 2019, 22:17:

**Comment by thecivvie** [comment]
Only page I can see is [https://blacknight.blog/secure-your-account-with-2-step-verification.html](url)

**Comment by thecivvie** [comment]
Sorry, new to this :)

**Comment by thecivvie** [comment]
Sorry there is a better explanation showing how to use SMS or Software Tokens
[https://help.blacknight.com/hc/en-us/articles/360001358517-Two-Step-Verification](url)
