### ISSUE TITLE
Wikipedia Only offers 2FA On Accounts with a certain Seniority

### ISSUE THREAD

**Issue by jamesnelmore** [2factorauth/twofactorauth#3792]
The database lists Wikipedia as giving a software token, but it only gives that to certain people.

**Comment by kmpoppe** [comment]
@admiral-ackbar This project already lists an exception that describes the current "state of affairs" with Wikipedia 2FA.

There's currently no other means of displaying this, so there's nothing we can do about this at this point in time.

^KMP

**Comment by kmpoppe** [comment]
Yes, it does. That's why the exception information is there, that tells you
it only gives 2FA to specific people.

This is the current way of handling these types of things.

^KMP

Am Mi., 10. Apr. 2019 um 02:14 Uhr schrieb admiral-ackbar <
notifications@github.com>:
