### ISSUE TITLE
Add warning to n26?

### ISSUE THREAD

**Issue by jtagcat** [2factorauth/twofactorauth#3806]
N26 has bad security background, maybe consider adding a warning?

**Comment by kmpoppe** [comment]
As N26 currently doesn't support 2FA, the `exception`-field would not be displayed. Additionally, I wonder if this project would be fitting for security issues like this.

**Comment by RichJeanes** [comment]
I believe that would be outside the scope of this project.

**Comment by kmpoppe** [comment]
Closing this Issue for now.
