### ISSUE TITLE
Navy Federal does not support software tokens

### ISSUE THREAD

**Issue by jensenja** [2factorauth/twofactorauth#3813]
Hi,

Not sure how to phrase this, but here goes:

Navy Federal only supports 2FA via Email, SMS, and a Notification Push to the Navy Federal app (I've confirmed this via iOS but I don't have an Android device to test). You cannot use TOTP software (ie 1password, Google Authenticator, etc) and a QR code to use 2FA with Navy Federal. I'm not sure if this fact should preclude the Navy Federal website from having "Software Token" checked in that column.

Thanks.

**Comment by Carlgo11** [comment]
Hi @jensenja,
No, push notifications from an app still counts as software 2FA. We currently don’t make any distinction between the different types of software 2FA.
If you want it to not show up on 1Password I recommend you contact AgileBits, the creators of 1Password, directly.
They can blacklist specific domains.

**Comment by kmpoppe** [comment]
Hi @jensenja,
In case you're using 1Password, you can add the tag "2FA" do make it stop whining about you not having add a TOTP key, when this project says that the site has software tokens.
This is a rather bizarre procedure, but I needed to use it for e.g. Wikipedia.
// Kai
