### ISSUE TITLE
Update moniker which now supports email & software token

### ISSUE THREAD

**Issue by fleish** [2factorauth/twofactorauth#3821]
I can't find their documentation, but per the attached screenshots they now support Google Authenticator & email OTP

<img width="796" alt="Screen Shot 2019-04-20 at 7 41 14 AM" src="https://user-images.githubusercontent.com/2106430/56458849-7d22cc00-6340-11e9-8dce-ae654e3c20ac.png">
<img width="835" alt="Screen Shot 2019-04-20 at 7 41 58 AM" src="https://user-images.githubusercontent.com/2106430/56458852-801dbc80-6340-11e9-9ff4-2799cec8fa8b.png">

**Comment by kmpoppe** [comment]
Found documentation in the FAQ, PR is created, thanks for your contribution, @fleish !
// Kai
