### ISSUE TITLE
Website: Freeze title cells to top of screen when scrolling through list of sites

### ISSUE THREAD

**Issue by platinumtach** [2factorauth/twofactorauth#3828]
When looking through longer lists of sites on the website, it would be helpful to have the column titles stay at the top of the screen so you do not have to keep scrolling back up to remember what column is what. Freezing those cells to the top of the screen would be very helpful as a UI improvement to the site and make the data easier to digest at a glance. 
THANKS!

**Comment by dsoegijono** [comment]
@2factorauth/collaborators what do you guys think about having a set max height for tables, so tables are scrollable and headers are viewable, but also allows easy access to close or move to a new category? I can take a stab at it and see if it works.

**Comment by Carlgo11** [comment]
Fixed in 5c7403b
