### ISSUE TITLE
I'm locked out of my original gmail and yahoo a

### ISSUE THREAD

**Issue by OrlandoHerreraIII** [2factorauth/twofactorauth#3831]
Hi my name is Orlando Herrera I recently had my SIM card stolen out of my phone and got drugged by 2 individuals.  I can no longer remember my gmail password to swrtya715 and my yahoo mail are both locked with 2 factor identification.  I tried contacting yahoo and was given a hard time. My new phone number is **_removed for data protection reasons_** can someone please help me.  It would be greatly appreciated.  Blessings and praise.

**Comment by kmpoppe** [comment]
Hello @OrlandoHerreraIII, this project gladly provides you with information about two-factor-authentication, yet it is by no means connected to any provider.
If you do not have the backup-codes that Google and Yahoo provide to you in case you lose your device, you will have to contact their support to prove your identity by other means and regain access to the accounts.
There is nothing we can do for you regarding this matter.
I regret that I can't accomodate you.
I will close this issue now.
