### ISSUE TITLE
Password Managers

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#384]
I'm going to add Dashlane (supports 2FA) but now that we have a Security section, I feel like password managers fall into that category (right now, LastPass is in Other).
Thoughts?

**Comment by smholloway** [comment]
I wondered where LastPass should fit in. I like the idea of moving it to Security.

**Comment by jdavis** [comment]
I think Security is a good place for it, good call.

**Comment by zach-taylor** [comment]
I like the idea of moving LastPass to Security. Okta would probably need to move there since it is very similar, just focused on enterprise. I wonder if an Identity Management section would make sense if we could come up with a handful?

**Comment by jdavis** [comment]
Now we have 3.

**Comment by mxxcon** [comment]
I think there are sufficient number of players(more than 3), it is a distinct and important enough category that it deserves a separate section...or at the very least upgraded from "Other" :)

**Comment by jdavis** [comment]
Yup, I agree with @mxxcon.

**Comment by clsy** [comment]
Create section called "Identity/Password Management"? There are at least a dozen legitimate players in that space.

**Comment by jdavis** [comment]
I'm going to close this as we added the Identity section in #384. Feel free to add Dashlane or anything else, @RichJeanes.

**Comment by RichJeanes** [comment]
Will do. Sorry I haven't been contributing. Been busy between Startup Weekend now and LA Hacks next weekend.

**Comment by jdavis** [comment]
Real life should come before open source :smile:
