### ISSUE TITLE
Update Ubiquiti

### ISSUE THREAD

**Issue by JackThursby252** [2factorauth/twofactorauth#3843]
Ubiquiti meanwhile supports otp 2fa (no u2f tho)
Pls update :)

**Comment by kmpoppe** [comment]
Hello @Square252 and thank you for your contribution. From what I see in our files, Ubiquiti Networks (ubnt.com) is listed as `software: Yes`, which essentially mean OTP/TOTP via any reasonable software implementation, we have no support for u2f (or `hardware:`) listed.
Could you please clarify what entry you mean?
// Kai

**Comment by JackThursby252** [comment]
uhm, strange. On the website it shows no support for 2fa at all. Other sites with otp like PhraseApp got the `otp: Yes` entry additionally as far i can see.

**Comment by Carlgo11** [comment]
@Square252 refresh your cache or something. 
Ubiquity is displayed as supporting software 2FA.(see screenshot below)
Furthermore, there’s no `otp` tag in our repository. The valid tags are `phone, sms, software, hardware`.
![D3EDEE1C-3631-4C93-918A-24B8F5120A9C](https://user-images.githubusercontent.com/3535780/57496906-9da5cc80-72d5-11e9-91f5-5043badd6dac.jpeg)

**Comment by JackThursby252** [comment]
Uhm, strange....
Cleared chaches etc, tried incognito mode... Still shows:
![image](https://user-images.githubusercontent.com/898298/57535249-1e9aad80-7342-11e9-9270-c5c693bdbc10.png)

**Comment by Carlgo11** [comment]
@Square252 that screenshot is not from our site. This repository is for twofactorauth.org. Check the url that you’re using. It’s probably a fork of some kind.

**Comment by JackThursby252** [comment]
Ups. thats embarrassing :rofl: 
I was on dongleauth.info, which seems to be a quite outdated one....

Sorry for the inconveniences^^
