### ISSUE TITLE
2fa that isn't any of the categories?

### ISSUE THREAD

**Issue by olikami** [2factorauth/twofactorauth#3848]
I have a question concerning one specific bank: Zurich Cantonal Bank (ZKB).

As far as I can tell most of the data is wrong. While they require every customer to use 2fa for online banking, it's neither through SMS, Phone Call, Email, Hardware Token or Software Token (at least the way I know it).

Basically how the system works:
1. Login uname & pwd
2. Scan a "photoTan" on the screen with an authenticated device (mobile phone or dedicated device).
3. Enter the TAN (transaction authentication number) in the ebanking.

If you have done all of the above succesfully, you are then logged in.

For me the definition of software token would probably be the closest, but the system is completely different from most other software tokens I know. And I assume it would also mess with 1Password, since they except software tokens to be TOTP.

What should we do here?

**Comment by kmpoppe** [comment]
Hello Oliver @olikami,
what you describe is the _authorization_ process for any transaction of literally every bank in the D-A-CH area. 2FA in the sense of this repository and site, however, is _authentication_, the difference of which is described here: https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions
So, as long as you're not able to add a second method of authentication for the login, the bank would be considered as `tfa: No` in this repository.

**Comment by olikami** [comment]
I can only say this for the 2 banks I have used in Switzerland (ZKB being
one of them), but you have to enter these security features on login, so
according to the definition you linked that would qualify for 2fa.

I guess it should be mentioned that sometimes you need to also
authorize payments through the same method. (So every time on login and
sometimes on payments).

**Comment by olikami** [comment]
Here's the [relevant part of their website](https://www.zkb.ch/de/pr/pk/efinance/ebanking/login-verfahren.html):

> Das eBanking verwendet zum Login und zur Freigabe von Zahlungen photoTAN: via photoTAN App mit Hilfe Ihres Smartphones oder Tablets sowie via photoTAN Lesegerät. Entscheiden Sie selbst, welche Variante Ihren Bedürfnissen entspricht. Beide sind schnell, einfach und bieten dieselbe erhöhte Sicherheitsstufe. 

And here it is in english (non-professional translation by me):

> eBanking uses photoTAN to login and approve payments: via photoTAN App with the help of your smartphone or tablet as well as via photoTAN Reader. Decide for yourself which option meets your needs. Both are fast, simple and offer the same increased level of security.

**Comment by kmpoppe** [comment]
Hi Oliver, 
as I'm from Germany, I'm perfectly able to read the German version ;-)
I seem to have skimmed over the "If you have done all of the above successfully, you are then logged in." part of your text.
So, in essence, they use a hardware-device (the photoTan scanner) or a software-authenticator (the banking app) as the second factor.
From the experiences I had so far, the Members of this repository have so far opted for seeing these variants as `software` and `hardware`.
@Carlgo11 @RichJeanes Do I remember correctly that we have had entries like this so far (software and hardware authentication via proprietary devices/programs)?

**Comment by olikami** [comment]
@kmpoppe I assumed that you speak German from the DACH abbreviation, but I thought maybe if other people want to weigh in as well

So from what I understand this should then be correct?
```
    - name: Zurich Cantonal Bank (ZKB)
      url: https://www.zkb.ch/
      img:  zkb.png
      tfa: Yes
      software: Yes
      hardware: Yes
      doc: https://www.zkb.ch/de/pr/pk/efinance/ebanking/login-verfahren.html
```

**Comment by kmpoppe** [comment]
@olikami Yep, apart from the superflous space in the `img:`-line that would be correct. Would you create a pull request?

**Comment by olikami** [comment]
@kmpoppe Thanks for you help, I have just done so.
