### ISSUE TITLE
Collapsible Sections

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#385]
Perhaps a stop gap for the never ending lists would be collapsible sections. Eg. Click on the grey header bar for the table and it folds up, maybe has a little arrow indicator next to it. Y'all know what I'm talking about.

**Comment by joshsleeper** [comment]
Why close this, @jdavis?
Seems like a good idea to me, unless you've already got something better in the works.
Or maybe I missed an announcement about holding off on enhancements like this haha.

Edit: Or I'm just silly and don't pay attention when things change. -_-
The nav at the top works just fine.
Although, for the record, when you select a category, it actually hides the grey section header under the green nav header with it's current positioning. Maybe it'd be nice to adjust that so the header for the section they were intending to go to is initially visible?

Reorganized my comment, so it's clear what order I was saying things.

**Comment by jdavis** [comment]
I agree with showing the header (I wanted to fix that when I was creating 2FA.org but it would have required a few HTML tricks like a hidden item or something).

The list is getting long but I feel that collapsing the divs would be a pain in the butt. Okay, so all the divs are closed when you select one from the menu? Well what if you want to scroll again? Do you have to uncollapse them all?

I don't mind scrolling and think it's good in this case (but am willing to hear arguments from the other side).

**Comment by joshsleeper** [comment]
nonono, don't misunderstand haha.
Collapsing divs isn't a bad idea (although all of your usability concerns are valid), but I like the current  drop-down implementation as well.
Both good ideas, but only one is really needed.

The grey header being hidden seems like a bigger deal to me right now, although small in the grand scheme of things.
I'm sure there are more important enhancements to focus on than that.

**Comment by jdavis** [comment]
Gotcha. I'll add an issue for the links to #id elements.
