### ISSUE TITLE
Add adguard.com

### ISSUE THREAD

**Issue by GauthierPLM** [2factorauth/twofactorauth#3860]
[AdGuard](http://adguard.com) supports 2FA to protect accounts. I am not sure about the category, but I guess Security would be the right one.

**Comment by rakleed** [comment]
In progress in https://github.com/2factorauth/twofactorauth/pull/3825.

**Comment by kmpoppe** [comment]
As Rakleed pointed out, there is already a Pull Request for this. Closing this issue now.
