### ISSUE TITLE
GMX and Web.de introduced 2FA Authentication by App

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3870]
I read at heise.de that GMX implemented 2FA authentication by authenticator apps.
The service is available from the 5th of June and will affect 18 million users.
Later this month 2FA will also available for Web.de (this will affect 15 million users).

Here the article at heise.de:
https://www.heise.de/newsticker/meldung/GMX-fuehrt-sichere-Anmeldung-mit-Zwei-Faktor-Authentifizierung-ein-4439558.html

**Comment by kmpoppe** [comment]
Hi @OLLI-S, I've read the article this very morning and have since activated 2FA, works like a charm.
I'm away for a week, if you fancy, just make your own Pull Request with the changes, if you don't, I'll do it next week.
// Kai

**Comment by raffisweb** [comment]
2FA at GMX is working.

**Comment by kmpoppe** [comment]
The problem I see is, that we have gmx.com as the website for GMX (even though it being first built in Germany) and I don't see an English help page for 2FA. Has anyone found one?

**Comment by OLLI-S** [comment]
> Hi @OLLI-S, I've read the article this very morning and have since activated 2FA, works like a charm.
> I'm away for a week, if you fancy, just make your own Pull Request with the changes, if you don't, I'll do it next week.

@kmpoppe I never did this before and I also have no idea how to do this.
So I would be pleased if you do it (whenever it is).
Thank you!

**Comment by raffisweb** [comment]
> The problem I see is, that we have gmx.com as the website for GMX (even though it being first built in Germany) and I don't see an English help page for 2FA. Has anyone found one?

Absolutely, @kmpoppe is right. There seems to be a difference between GMX.com and GMX.de - so the german site activates 2FA but we have to check the .com!

**Comment by kmpoppe** [comment]
@OLLI-S, @GeileHirnbude was so nice to create a Pull Request, that split GMX net and com so that we can list them with and without 2FA.
Could you please close this Issue and create a new one, once Web.de announces 2Fa as well? I myself don't use web.de so I'm bound no to get the information.
// Kai
