### ISSUE TITLE
HSBC add (another) exception

### ISSUE THREAD

**Issue by dkwo** [2factorauth/twofactorauth#3872]
Their (US NA) hardware token policy is that one can still login and perform certain operations with only user/pwd.

**Comment by Carlgo11** [comment]
Hi @dkwo,
could you be a little more specific on what operations are available without 2FA?

**Comment by dkwo** [comment]
Basically everything except for Wire Transfers to a new payee, see https://www.us.hsbc.com/online-banking/logon-options/#services
More generally, they either ask for user/pwd or user/token, so I would not even call this 2fa.

**Comment by Carlgo11** [comment]
@dkwo so when you log in you don't actually need to enter a code from the security device?
Could you try and log in using private/incognito mode on your browser and see if it still let's you log in without it?

**Comment by dkwo** [comment]
Of course, that's what I'm saying.
I use incognito by default.
