### ISSUE TITLE
Search by type of security

### ISSUE THREAD

**Issue by seekheart** [2factorauth/twofactorauth#3876]
Please add the ability to search by type of security i.e. please let me be able to get answers to the following questions:

- [ ]  What sites implement software tokens?
- [ ] What sites implement hardware tokens?

**Comment by WORMSS** [comment]
Yes, the hardware token search would be much appreciated. I did think of just web-scraping the website and building my own front end to their data. From the look of the issue count, it might be faster

**Comment by Carlgo11** [comment]
`https://twofactorauth.org/data.json` has a list of all sites. You can use that to get sites that support hardware or software 2FA.
#3908 is another way to get it.

**Comment by Seegras** [comment]
Yes please. Because having SMS in there is quite useless without being able to filter it out. 

https://thehackernews.com/2016/07/two-factor-authentication.html

**Comment by RichJeanes** [comment]
@Seegras Believe me, we've had many discussions over the inclusion of SMS, but we've collectively come to the agreement that for most lay-people, SMS is better than nothing, so we still want to list it.

**Comment by Seegras** [comment]
I consider it worse, as it is a violation of privacy as well. In any case, it's not about the inclusion, it's about being able to filter.

**Comment by Carlgo11** [comment]
@Seegras if you create a PR with a filter ability to the search tool we'll certainly take a look at it.

**Comment by phallobst** [comment]
Closed by #4584
