### ISSUE TITLE
Tumblr has a "Software Implementation" for 2FA

### ISSUE THREAD

**Issue by davidmenzel** [2factorauth/twofactorauth#389]
Hi Josh, I just have seen the updated website and have to say that it looks very good. I noticed only one mistake: The software implementation for Tumblr is no longer displayed.

**Comment by jdavis** [comment]
It has been updated, it just hasn't been merged yet into the `gh-pages` branch: https://github.com/jdavis/twofactorauth/blob/master/_data/social.yml#L67

I'll push out the new changes soon though =]
