### ISSUE TITLE
Add Wuala

### ISSUE THREAD

**Issue by Donatzsky** [2factorauth/twofactorauth#390]
"Secure cloud storage", without 2FA :(
Should go in Backup and Sync.

```
  - name: Wuala
    url: https://wuala.com/
    twitter: Wuala
    img: wuala.png
    tfa: No
```

![wuala](https://cloud.githubusercontent.com/assets/4938390/2585410/7de7a0e6-b9ec-11e3-9f21-cb30a81e99f4.png)

**Comment by jdavis** [comment]
You're half way there! Make a pull request, haha.

If you don't, one of the collaborators will eventually get around to this =]

**Comment by Donatzsky** [comment]
Done :)
Just didn't have Git installed on this computer.
