### ISSUE TITLE
Please add Bitvavo

### ISSUE THREAD

**Issue by belle-de-jour** [2factorauth/twofactorauth#3906]
Hi,

Bitvavo (cryptocurrency exchange) supports 2FA by Authenticator/Authy app (see 
https://support.bitvavo.com/l/en/article/q7kl06gojd-two-factor-authentication-2-fa )

**Comment by kmpoppe** [comment]
Hi @belle-de-jour and thanks for your contribution.

Unfortunately, bitvavo.com does not rank within the top 200k of the Alexa site ranking, so according to our [Contribution Guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) we cannot add this site to the repository.

If the ranking ever changes or if you have any other sites to recommend, feel free to come back any time!

I'm sorry if this causes you any inconvenience!

// Kai

**Comment by kmpoppe** [comment]
[](url)
