### ISSUE TITLE
Please add BankID 

### ISSUE THREAD

**Issue by hstokset** [2factorauth/twofactorauth#3913]
"BankID Norge" is the secure login solution used by all the banks in Norway. Please add a "tell them to support U2F" message.

They offer a number of other second factors ranging from cards with one time codes on them to hardware one time code generators to one time passphrases sent to to a cellular phone. I would love if enough people encourage them to add Yubikey/U2F support as well.

Webpage: https://www.bankid.no/privat/
U2F support: No
OTP support: Yes
Twitter: https://twitter.com/bankidnorge
Facebook: https://www.facebook.com/BankIDNorge/

**Comment by Carlgo11** [comment]
Hei Henrik!
We removed 2FA providers from twofactorauth.org back in June 2015. As BankID is a 2FA service I'm afraid it can't be listed here any more.

P.S. as they're a 2FA provider I'm fairly certain that they won't support another 2FA provider like Yubikey however I do agree that it would be nice if they did :wink:
