### ISSUE TITLE
Patreon supports software tokens

### ISSUE THREAD

**Issue by jcobleigh** [2factorauth/twofactorauth#3915]
I've seen #2480 where Patreon's doc said that SMS would be the main way of authentication going forward. That was in 2017. I've never had 2FA on my Patreon account and just added TOTP. It looks like Patreon should be listed as supporting software tokens again.

Here's their [support page](https://support.patreon.com/hc/en-us/articles/206538086-How-Do-I-Set-Up-Two-Factor-Authorization-).

**Comment by kmpoppe** [comment]
Hello @jcobleigh, thank you for your contribution!
I just checked my Patreon page and could confirm, that software/TOTP works. I had 2FA on via SMS, it seems to me, that TOTP must have been added recently because I'd otherwise used that over SMS.
I'll just create a PR for that, thank!
