### ISSUE TITLE
eclipso Mail & Cloud supports 2FA - Please add to list

### ISSUE THREAD

**Issue by eclipsoDE** [2factorauth/twofactorauth#3919]
First of all: We are new in the Github world, please forgive us if we make mistakes.

eclipso Mail & Cloud introduces Two-factor-authentication by App: [https://www.eclipso.de/blog/2019/06/12/eclipso-fuehrt-zwei-faktor-authentifizierung-ein/](url)

Documentation: https://www.eclipso.de/zwei-faktor-authentifizierung/

**Comment by Carlgo11** [comment]
Guten Tag!
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo/eclipso.de) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.
