### ISSUE TITLE
Add Standard Notes

### ISSUE THREAD

**Issue by pawelostr** [2factorauth/twofactorauth#3926]
Not really a website, but notes app. E2EE, software 2FA, open source. Not really sure about category

**Comment by Carlgo11** [comment]
What kind of 2FA? By just looking at the app on the App Store I can’t see a centralized login system for the app. Local authentication isn’t a part of our coverage on twofactorauth.org.

**Comment by pawelostr** [comment]
There's more on the website https://standardnotes.org/help/25/how-do-i-enable-two-factor-authentication-for-my-account. I forgot all the names of types of 2fa, but I believe it's OTP, the one that google authenticator uses. It's currently only in paid plan, but I'm sure the dev will give you it for free for verification if you'd email him or wirte on slack

**Comment by Carlgo11** [comment]
The documentation seemed familiar and so I did a search here on GitHub. Apparently this app have been brought up before but haven’t been added as it haven’t reached 200k on Alexa yet. 
It’s currently ranked <300k and so still not able to be listed.
Sorry about that!

**Comment by Jawshy** [comment]
[Standard Notes](https://standardnotes.org/) is currently [ranked](https://www.alexa.com/siteinfo/standardnotes.org) in the top 200,000 on Alexa. See https://github.com/2factorauth/twofactorauth/pull/3778 and https://github.com/2factorauth/twofactorauth/pull/3800.

**Comment by phallobst** [comment]
Alexa rank is over <strike>9000</strike> 200,000 again...
