### ISSUE TITLE
Launchpad.net incorrectly listed

### ISSUE THREAD

**Issue by KnnNike** [2factorauth/twofactorauth#3931]
Launchpad.net is listed as supporting hardware and software tokens. However, there is no place on the website to actually enable these.

**Comment by Carlgo11** [comment]
@KnnNike have you followed the linked documentation?
https://help.ubuntu.com/community/SSO/FAQs/2FA

**Comment by kmpoppe** [comment]
Closing this issue as OP never came back to this and hence I suspect that adding 2FA actually worked.
