### ISSUE TITLE
Please add SkautIS

### ISSUE THREAD

**Issue by marekdedic** [2factorauth/twofactorauth#3942]
Please add SkautIS at https://is.skaut.cz.  Probably under "other"

It supports mobile app like Google authenticator and also e-mail

Help link: https://napoveda.skaut.cz/skautis/prihlaseni

**Comment by kmpoppe** [comment]
Hello @marekdedic, thank you for your contribution, yet we will currently do not add sites to the repository, that do have an alexa site ranking below 200k, skaut.cz is currently at under 500k.

I hope for your understanding as I will have to close this issue.

// Kai
