### ISSUE TITLE
New Categories!

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#395]
We are starting to blur the line on a few places. So I think it'd be great to introduce a few new categories to keep the clutter down.

Here are a few of my ideas:
- Banking: To remove some of the banks from finance. Finance would remain one that deal with personal finance.
- Investing: Investment sites
- Hosting/VPS: this would split up Domains/Developer a lot more
- Cloud Services possibly
- Project Management (Trello, Wunderlist, etc)

Any other ideas? Those are the two largest categories along with Domains which I'm not sure what to do with.

**Comment by seanmcelroy** [comment]
The banking-finance distinction would be hard for some of the very large financial institutions that offer both services under one login.  I'm all for the Hosting/VPS separation.

**Comment by RichJeanes** [comment]
Though it's like you said before, a lot of domain registrars also offer hosting (eg Namecheap).

**Comment by jdavis** [comment]
Yup, in that case, we could go by what they are most known for and/or started with. Like Namecheap is domains, and then Dreamhost would be hosting.

Maybe..? Hmm.

**Comment by mxxcon** [comment]
Maybe then somehow allow cross-linking of categories?
It will become harder for contributors to find the "source" file, but for the users a site will be listed in all relevant categories.

**Comment by jdavis** [comment]
What do you mean by cross-linking categories, @mxxcon?

Do you mean like having a section for "Hosting", a section for "Domains", and then "Hosting + Domains"? Or do you mean having a site listed multiple times?

I have some time now that I want to play a bit with the categories so any feedback would be great.

**Comment by mxxcon** [comment]
Let's take Godaddy as an example. They offer a mile long list of services. It is obviously not a good idea to duplicate godaddy in every single category where they fit. It will be pita to update. Perhaps implement a system of tags that will automatically put each entry into appropriate category?

**Comment by jdavis** [comment]
In addition to the commit above, I broke them up into other sections:
- Added a Project/Task Management section: 0aad2ef699cffdb466150e7ab6f7538594d22b6e
- Broke up Finance into Personal Finance, Investing, Banking (it actually worked nicely): 45b7bcefb68197c42d32eef9b29fa94ad37b5234
- Added a Hosting/VPS section: 2df32cdf32ce5ba1a5935e98cba8a53276316647

In the case of sites like GoDaddy and DreamHost. I left GoDaddy in the Domains section because while they do do hosting, their <title> is regarding Domains. I put DreamHost in the hosting, because the name implies hosting even though they do offer domains.

**Comment by mxxcon** [comment]
@jdavis, everybody have opinions, and like ...holes all of them stink ;)
Here's mine:
maybe you are splitting hair a bit too much?
I think our current 6 columns work pretty well and saves us(and hopefully visitors) the headache of figuring out all the specifics of 2FA implementations.
Perhaps it should be similar with categories?
For example what about Chase or other similarly large entity that have investment services, personal banking, institutional banking, retirement, etc... Where would you put it?
We also have informational/reporting sites like Mint and CreditKarma, where would you put those?

Financial section is long, but does it really needs splitting? I think it's simple enough to figure out that a site relates to financial industry and just look there, rather than specific type of finance industry.

We could add Hosting section, but then we'll continue to have ambiguity of deciding where to put an entry - hosting or domains..
Maybe combine Hosting/Domains and keep other esoteric entries in Developer?

Project/Task management is ok, but I feel beyond that it would be too nuanced.

Don't look at it all negatively, just trying to figure out the mindset.

**Comment by mxxcon** [comment]
I also noticed commit 30faf62 which I also think is complicating this situation.
Datapipe has their own physical hosting but partners with AWS for cloud hosting, so perhaps it sould not included in Cloud Hosting section.
Rackspace meanwhile offers both and their current Cloud services are probably as big as physical/dedicated hosting, so it deserves to be in both sections?

**Comment by jdavis** [comment]
The list of categories isn't and shouldn't grow to be that big though. Rather think about it as essentially a [clustering](http://en.wikipedia.org/wiki/Cluster_analysis) problem. We don't know how many clusters there should be, yet we want to minimize the average linkage (how similar two sites are) between all the sites in a cluster (depending on the k that we choose).

The reason for wanting to expand the categories is because two sites that do completely different things shouldn't be next to each other.

GitHub shouldn't be next to AWS. If someone wants to see what Cloud services implement 2FA and to pick between them, I want them to easily be able to see alternatives and competitors.

Our job isn't to accurately categorize a site based on **_all_** the services that it provides. Rather we should put websites where an average user would expect it to be.

Rather than think about the changes I'm proposing, let's take a look at Dreamhost. Right now it is in the Domains section. Yet just given the name and what they primarily started off as, I'd expect them to be next to the other solutions that offer Hosting. Most of those are in the Developer section.

Of course some people will use it's Domain registrar capabilities without using their hosting. But I bet the majority of people use it and know of it for its hosting abilities.

If a person comes to 2FA.org and wants to see what sites they can use to manage their finances, they shouldn't have to look through a list of credit unions, investment firms and banks for that. I'd much prefer them to look through sites like Check Inc, TurboTax and Kiva.

**Comment by jdavis** [comment]
I do think the Project/Task Management section is a bit much. I'm going to remove that one.

**Comment by jdavis** [comment]
Take a look now, @mxxcon and let me know. I realize you want to keep the number of Categories to a minimum and I totally agree. I think we just need to find a balance.

And apparently you are the only Contributor left that is paying attention =] So thanks for that.

**Comment by mxxcon** [comment]
Where exactly am I looking?
Perhaps then it's worth revising the idea of tags or maybe even taxonomy? An entry can be in multiple categories and a user can filter on them?
