### ISSUE TITLE
Rebrandly only supports 2FA on paid accounts

### ISSUE THREAD

**Issue by JyeGuru** [2factorauth/twofactorauth#3957]
My account page shows "Add an extra layer of security with two-factor authentication. Contact us" instead of the Enable 2FA button. When contacting them, was advised that 2FA is only available on paid plans, and that I need to upgrade.

Screenshots of support emails can be provided if required.

**Comment by dsoegijono** [comment]
> Screenshots of support emails can be provided if required.

@JyeGuru That would be helpful, thanks.

**Comment by JyeGuru** [comment]
![image](https://user-images.githubusercontent.com/5215014/64840905-6444eb00-d640-11e9-83d9-56c71139ab2b.png)

As part of the support ticket, they agreed to enable it for free "on request" - after I asked them to confirm in writing that they are limiting standard security options behind a paywall. Apparently the original consultant didn't know this was possible.

![image](https://user-images.githubusercontent.com/5215014/64840967-a5d59600-d640-11e9-9450-302103bda7ec.png)

**Comment by JyeGuru** [comment]
There may have been more developments in this since, as I have not followed to know if it's now more widely available, but at the time this was logged the information was accurate.

**Comment by Carlgo11** [comment]
So it's not actually only for paid accounts?
I'm a bit confused on what you want us to do here.

**Comment by Carlgo11** [comment]
Closing as the issue seems to have resolved itself.
