### ISSUE TITLE
Update MBNA Canada

### ISSUE THREAD

**Issue by acidpandas** [2factorauth/twofactorauth#3959]
MBNA now supports 2FA via SMS and Phone Call.

See 2FA FAQ page: https://www.mbna.ca/help-centre/credit-cards/two-step-verification-faq/index.jsp

**Comment by Carlgo11** [comment]
Hello @acidpandas,
Thank you for your interest in twofactorauth.org.
While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this on our spare time.

**Comment by kmpoppe** [comment]
@bobmatyas you committed 8a3f1aa, yet you've not create a pull request yet, would you be so kind as to do so?
// Kai

**Comment by bobmatyas** [comment]
The change is included in this PR: https://github.com/2factorauth/twofactorauth/pull/4017/commits/446af56b62c78d8ed22a866abd92f45fd6913668

**Comment by kmpoppe** [comment]
@bobmatyas Thanks, I didn't see that. Strange day, today :-D

**Comment by kmpoppe** [comment]
Closed by #4017.
