### ISSUE TITLE
Bank of America does support HW tokens

### ISSUE THREAD

**Issue by geoffb1723** [2factorauth/twofactorauth#3962]
Call Cust Service, it's $15, it's called a Safe Pass Token Card. RSA type token card. You cannot order it via the web site. The documentation on the web site is very obscure and confusing.

**Comment by dsoegijono** [comment]
> The documentation on the web site is very obscure and confusing

@geoffb1723 Do you have a link? Is it behind login?

**Comment by geoffb1723** [comment]
The websites is wrong and useless, the way I found out was to call BofA and ask specifically for a “SafePass hardware card”, the agent had no
idea what this was and had to get a supervisor, they evidently order them 1 by 1 from the supplier, took about 10 days to get one.

**Comment by dsoegijono** [comment]
So I looked up a couple articles that confirms the card can be purchased, but it looks like SafePass is only used to authorise higher transaction amounts, not for authentication. 

From BofA's SafePass [page](https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/safepass.go), it's for transferring funds:
> SafePass uses a 6-digit one-time code sent in a text message to your mobile phone to help verify your identity before authorizing the transfer of funds from your account.

[This article](https://go.forrester.com/blogs/bank-of-america-lowers-security-removes-one-time-passwords-at-payee-add-change/) also says the same thing:
> SafePass (the SMS or email or optional, $20 2FA token-based  OTP 2FA) is only used for authorizing “higher value” transactions. No definition of “higher value” is immediately available

**Comment by geoffb1723** [comment]
Well, to be precise, it’s almost useless, as the only transactions it comes in to play for are:

it’s a Gemalto SafeNet OTP (OATH TOTP) based card, but they only use it for:

create new payee in 'pay to’ account management
wire transfers over a limit you set
moving money via other means over a certain limit.

Pretty weak, as login auths are still 2FA via SMS or a phone call. So for account
auth and everything else, useless.

**Comment by Carlgo11** [comment]
@geoffb1723 see https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions
