### ISSUE TITLE
Login.gov Docs link goes to the wrong help page

### ISSUE THREAD

**Issue by eefedor** [2factorauth/twofactorauth#3964]
The login.gov Docs link goes to a page that is security-related but says nothing about how to set up 2FA. Should perhaps link instead to:

https://www.login.gov/help/changing-settings/how-do-I-set-up-an-authentication-app/

(It's currently going to https://login.gov/help/privacy-and-security/how-does-logingov-protect-my-data/)

**Comment by Carlgo11** [comment]
Thanks for the suggestion @eefedor! 😄 

I've made a pull request and as soon as it's been merged you should be able to see the new link on our site.
