### ISSUE TITLE
LinkedIn supports Software Token

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3968]
At your website I saw that for LinkedIn only SMS is supported.
So I logged into LinkedIn, went to the settings and wanted to activate 2FA via SMS.
But here I was able to choose between **SMS** or **Authenticator App**.

I selected **Authenticator App** and in the next step I see the instructions.
Here I read that I should use an Authenticator App like the Microsoft Authenticator.

I also see the QR code that I have to scan with my Authenticator app (and also the 2FA key that I can insert in the authenticator app instead of the QR Code).

Here the URL of the 2FA setup:
https://www.linkedin.com/psettings/two-step-verification

So LinkedIn now supports the software token.

**Comment by dsoegijono** [comment]
Done in https://github.com/2factorauth/twofactorauth/pull/3981
