### ISSUE TITLE
American Funds does support 2FA

### ISSUE THREAD

**Issue by gjmarkovich** [2factorauth/twofactorauth#3972]
American Funds does supports 2FA - Data needs to be corrected.

**Comment by Carlgo11** [comment]
Hello @gjmarkovich,
thanks for the info!

Could you please provide screenshots of the 2FA setup process and/or the login process with any personal information blurred out?

Also, could you describe what kind of 2FA that American Funds supports?

**Comment by kmpoppe** [comment]
Bump @gjmarkovich, please take a look at @Carlgo11 's comment.

**Comment by kmpoppe** [comment]
Bump @gjmarkovich, please take a look at @Carlgo11 's comment. I've set this Issue to inactive and will close it after 2 weeks if we can't get any further information on this.
Thank you for your understanding!
// Kai
