### ISSUE TITLE
MeisterTask + MindMeister support Software Token

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#3978]
The task manager MeisterTask (https://www.meistertask.com) and the mind mapping tool MindMeister (https://www.mindmeister.com) are both from the same company.
If you create an account for one of these tools, you also can log into the website of the other tool.

In the settings of my account I saw that they support two factor authentication (you have to be logged in):
https://www.mindmeister.com/account/email_password

Here is a documentation:
https://support.mindmeister.com/hc/en-us/articles/218901367-Personal-Info

There you see that they support authenticator apps:

> Supported Two-Factor Authentication Applications: Google Authenticator, Authy 2-Factor Authenticator, PW 2-factor Authenticator.   

So please add MeisterTask and MindMeister to your list of supported apps.
Thank you!

**Comment by rakleed** [comment]
Documentation for MeisterTask — https://support.meistertask.com/hc/en-us/articles/207318670-Change-Your-Personal-Info

**Comment by kmpoppe** [comment]
Closed by #4028

**Comment by OLLI-S** [comment]
I can see MeisterTask but not MindMeister in https://twofactorauth.org/
Yes, I did reload the page (delete the complete browser cache before reloading).
Both tools are from the same company but have different URLs you should add two entries:
* MeisterTask (https://www.meistertask.com) 
* MindMeister (https://www.mindmeister.com)

**Comment by kmpoppe** [comment]
Hello Olli.

We decided that, since MindMeister and MeisterTask integrate into the same
login (tried that myself), that we only add MeisterTask now. We might
change the name to MeisterTask (MindMeister) later.

// Kai

OLLI-S <notifications@github.com> schrieb am Sa., 5. Okt. 2019, 11:21:

**Comment by OLLI-S** [comment]
This is true (sam login) but when people search for "MeisterTask" they find an entry and if they search for "MindMeister" they find nothing,
So you really should change the name now to "MeisterTask and MindMeister" or "MeisterTask/MindMeister".
