### ISSUE TITLE
Add mineplex.com

### ISSUE THREAD

**Issue by kmpoppe** [2factorauth/twofactorauth#4023]
Can you add mineplex.com since it has email 2fa authenticater app, and backup codes.

_Originally posted by @karson111 in https://github.com/2factorauth/twofactorauth/pull/3894#issuecomment-514940197_

**Comment by Carlgo11** [comment]
I don’t think a Minecraft server is within our scope.

**Comment by kmpoppe** [comment]
Closed as the site is not within what twofactorauth.org will list.
