### ISSUE TITLE
Add OVH to the list of websites

### ISSUE THREAD

**Issue by Mrgove10** [2factorauth/twofactorauth#4031]
OVH supports SMS 2FA

**Comment by kmpoppe** [comment]
Bonjour @Mrgove10, OVH is contained in the "Hosting/VPS" category since 2015 (2FA methods added with #1079).
Is there anything wrong with the information currently listed here?
// Kai

**Comment by Mrgove10** [comment]
I think it should also be in "Domains" since they are also selling domain names.

**Comment by kmpoppe** [comment]
Ok, now I see what you mean. #3707 is an Issue that asks for extending the schema, so that sites can be added in multiple categories. I created a possible solution in #4034 - until this is approved, we will keep this Issue open and then move the entry into multiple categories later.
// Kai
