### ISSUE TITLE
Add Precious Metal Dealers

### ISSUE THREAD

**Issue by ItsMattL** [2factorauth/twofactorauth#4036]
I would be interested in adding or seeing added information about precious metal dealers to the website. These sites traffic in buying and selling high value assets: gold, silver, platinum, etc. Due to the financial volumes involved, they're logical choices to support 2FA, but not all of them do.

Examples:
apmex.com
jmbullion.com
providentmetals.com

Would these fit under an existing category (Investing)? Or a new category?

**Comment by phallobst** [comment]
I think "Investing" should be okay right now.

If a new category is needed, "Precious Metals" as the name might be too restrictive. Maybe "Commodities" is better, which would include trading oil, coffee, paper, corn, rubber etc.

**Comment by phallobst** [comment]
Since PRs are now created for these three websites, we can close this issue now.
