### ISSUE TITLE
Yandex uses their own authenticator app

### ISSUE THREAD

**Issue by jchevali** [2factorauth/twofactorauth#4037]
Yandex has a further restriction in that it uses their own authenticator app, not Google Authenticator or compatible.

Their app is called Yandex Key and I believe it outputs an 8-figure alphabetic key instead of 6-digit numeric.  It is also possible that it requires a PIN at the time of code generation besides the secret token loaded into the app.

**Comment by kmpoppe** [comment]
Hello @jchevali, thanks for your information, which I could verify using the documentation we link.

This would be a classic case for #4015, where the new tag "proprietary" would come in to play. We will keep this issue open until we can update the site to this standard.

**Comment by kmpoppe** [comment]
Hello @jchevali, the first entry (Yandex.Disk) was already corrected by #4122, we will update the Yandex.Email entry with the complete category update.
I'll therefore close this Issue.
Thanks for your contribution!
// Kai
