### ISSUE TITLE
President's Choice Financial Has some options

### ISSUE THREAD

**Issue by LukeAbellSmith** [2factorauth/twofactorauth#4045]
They support SMS, Phone call and email.
They have "forwarded the suggestion" of supporting authenticator apps/software tokens "to the correct department"

**Comment by kmpoppe** [comment]
@LukeAbellSmith Could you please provide a documentation link for PCF's 2FA support or, given the documentation is behind a login wall, provide screenshots on how to enable 2FA?
Thanks!
// Kai

**Comment by LukeAbellSmith** [comment]
This page says that they have it, but not much in the way of detail.
https://www.pcfinancial.ca/en/security

This is the best thing I could find. 
![image](https://user-images.githubusercontent.com/842506/65880327-da3e9700-e34e-11e9-82ce-f4cde15ae9d4.png)

**Comment by Carlgo11** [comment]
@LukeAbellSmith and this is used for signing in and not just for certain actions like transferring money?

**Comment by LukeAbellSmith** [comment]
It seems to be for signing in on a new device.
