### ISSUE TITLE
Remove the need to put sites in name-alphabetical order from Travis

### ISSUE THREAD

**Issue by kmpoppe** [2factorauth/twofactorauth#4054]
During my work on #4034 (Issue #3707), I found that we could very well use Jekyll's internal functions to order the websites by name when displaying them.

I trust that nobody uses the alphabetical order in the YAML-files to actually look for an entry when editing but rather goes for a string-find.

I think the Travis CI rule to order the sites alphabetical within each YAML could, therefore, be scrapped.

What's everyone's take on that?

**Comment by Carlgo11** [comment]
I think it's pretty standard to organize YAML content alphabetically.
Plus, it makes it easier to navigate in the YAML files and since we have so many YAML files I think we should use any chance we get to make it easier for us.
