### ISSUE TITLE
Fidelity now supports 2FA by text or call

### ISSUE THREAD

**Issue by VictorYing** [2factorauth/twofactorauth#4073]
https://www.fidelity.com/security/extra-security-login

The previous feature to use a smartphone app from Symantec is still available, but the ability to set up 2FA for logins without downloading a special app or needing to call Fidelity is new.

Also, it's not clear to me but the note on notes/fidelity/ about the old "transaction security" feature might be out of date. I'm not able to find any clear documentation on any still-existing distinction in how to set up 2FA for logins and identity verification for sensitive transactions at Fidelity.

**Comment by kmpoppe** [comment]
Hi @VictorYing, there's already a Pull Request that addresses Fidelity (#4098), yet it only speaks of SMS, not calls. Could you clarify?

**Comment by VictorYing** [comment]
Thanks for the ping, I made some comments at #4098
