### ISSUE TITLE
Add equifax.com

### ISSUE THREAD

**Issue by Return-4Leaky-Insure-Lethal** [2factorauth/twofactorauth#4083]

**Comment by kmpoppe** [comment]
Hello,
thank you for your interest in twofactorauth.org 😃 

While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you don't want to make a pull request, please provide the following information about the site:
- Site name
- Main URL of the site
- Category which the site would be in.
- What kinds of 2FA authentication the site supports.
- When the site asks for 2FA.
- Link to any documentation on how to enable 2FA on the site. If no documentation is available, please provide screenshot(s) of the setup process and/or login process. __Remember to blur or crop out any personal information linked to you.__


You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by Return-4Leaky-Insure-Lethal** [comment]
Site name - Equifax
Main URL of the site - https://www.equifax.com/personal/
Category which the site would be in. - Finance or Identity Management
What kinds of 2FA authentication the site supports. - other, ask questions
When the site asks for 2FA. - not sure if questions would meet the 2FA need
![equifax user-password](https://user-images.githubusercontent.com/56308540/67161552-48a8c080-f321-11e9-995f-40b89d889d28.jpg)

**Comment by Carlgo11** [comment]
@kmpoppe you stole my GIF! 😕

**Comment by Carlgo11** [comment]
@WreckDiving are you familiar with 2FA ([MFA](https://en.wikipedia.org/wiki/Multi-factor_authentication))?

The MFA factors are:
* Something you know - (password, SSN, security questions etc)
* Something you have - (phone, bank card, RSA device, Yubikey)
* Something you are - (fingerprint, face, iris, voice)

So the questions are *something you know*. Are any of the other factors available?

**Comment by Return-4Leaky-Insure-Lethal** [comment]
I am not a programer, just a user of 2FA and companies not giving me an option to protect my information is driving me nuts.  What I do not understand is how companies like this can treat people's (Equifax Data Breach 147 million people) information with so little protections (https://www.equifaxbreachsettlement.com/).   Not sure if asking a few questions goes far enough.   I will let you decide how and what you want to do with this request.  I would prefer an option of Authy type of app, but as a person held hostage by these companies I get no say so.

**Comment by Carlgo11** [comment]
I understand what you mean but I doubt 2FA would be the answer here. Sounds more like a job for GDPR. Nonetheless we can classify Equifax as not supporting 2FA.

There’s a lot of other active  issues right now but I’m sure someone will get around to making a PR to fix this issue.
