### ISSUE TITLE
Add Experian.com

### ISSUE THREAD

**Issue by Return-4Leaky-Insure-Lethal** [2factorauth/twofactorauth#4085]

**Comment by kmpoppe** [comment]
Hello,
thank you for your interest in twofactorauth.org 😃 

While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefor we rely on people's pull requests(PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you don't want to make a pull request, please provide the following information about the site:
- Site name
- Main URL of the site
- Category which the site would be in.
- What kinds of 2FA authentication the site supports.
- When the site asks for 2FA.
- Link to any documentation on how to enable 2FA on the site. If no documentation is available, please provide screenshot(s) of the setup process and/or login process. __Remember to blur or crop out any personal information linked to you.__


You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by Return-4Leaky-Insure-Lethal** [comment]
Site name - Experian
Main URL of the site - https://www.experian.com/freeze/
Category which the site would be in. - Finance or Identity Management
What kinds of 2FA authentication the site supports. - SMS
When the site asks for 2FA. - after username password screen
![experian user-password](https://user-images.githubusercontent.com/56308540/67161676-5f034c00-f322-11e9-9eb3-1c1374e67cb3.jpg)

![experian 2fa](https://user-images.githubusercontent.com/56308540/67161681-6165a600-f322-11e9-83bf-01a5517258eb.jpg)

**Comment by Carlgo11** [comment]
I can't even view the main page.
![oAhBHZSgG7](https://user-images.githubusercontent.com/3535780/67165878-8857c280-f38a-11e9-9707-a96cd4685dfa.png)

**Comment by Return-4Leaky-Insure-Lethal** [comment]
Link worked for me.
try https://www.experian.com
![Experian website](https://user-images.githubusercontent.com/56308540/67166906-89bcc700-f359-11e9-8da7-3dac763a7d88.jpg)

**Comment by Carlgo11** [comment]
Found the problem.
![CTWRZGtuRm](https://user-images.githubusercontent.com/3535780/67251954-3e95d780-f471-11e9-9324-e4e6fbc4c838.png)

Probably not a site we want to list if their encryption is so bad.
