### ISSUE TITLE
Alphabetized list?

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#410]
With constantly increasing list and having some ambiguity about where a given site belongs, perhaps it makes sense to also have an alphabetized list/index of all the sites?
That way visitor can simply click on a relevant letter and see if their site is listed there...rather than figuring out if their idea of a category matches with ours..

**Comment by jdavis** [comment]
Yeah, I would support that. Or even just a simple search field that does a really simple filter.

**Comment by thebigmunch** [comment]
To add to this, the category list should be alphabetized as well in the dropdown and the display.

**Comment by jdavis** [comment]
I agree, @thebigmunch. The categories should be alphabetized. Although I might leave Social at the top for relevance sake.

**Comment by thebigmunch** [comment]
Please don't. Frankly, I, and probably many others who even understand what two-factor authentication is, probably wouldn't put social sites at the top of our relevance list. I also don't think any amount of relevance would justify disrupting the sort order. It'd just be an eyesore.

**Comment by jdavis** [comment]
Good point, I just changed it.

**Comment by jdavis** [comment]
Closing this in favor of #521.
