### ISSUE TITLE
change.org dose not use 2FA 

### ISSUE THREAD

**Issue by vampireanarchy** [2factorauth/twofactorauth#4116]
[change.org](https://www.change.org/)[Twitter](https://twitter.com/Change)

**Comment by kmpoppe** [comment]
Hello,

Thank you for your interest in twofactorauth.org.

While we'd love to add all sites to the list we simply don't have enough time to do so.
Therefore we rely on people's pull requests (PR). The requirements for pull requests can be found [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).

If you need help making your PR or have any questions regards the PR requirements don't be afraid to ask us!

If you do not wish to make a PR please tell us so and someone will come back to this ticket in the future and make a PR. However please note that this can take a long time as we're all volunteers and do this in our spare time.

Additionally, I may note, that this issue lacks any information in what category you think the new page you want to add belongs to and any other data that's listed in the Contribution Guidelines. If you want to rely on others to add a PR for this issue, you'll need to more information.
