### ISSUE TITLE
Update needed for Wiki

### ISSUE THREAD

**Issue by Rfosu2k2** [2factorauth/twofactorauth#4172]
With the recent PR #4090 merge , the twofactorauth [wiki](https://github.com/2factorauth/twofactorauth/wiki) doesn't correctly reflect [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)

The 2 pages that should be updated are:

1. - [X]  [FAQ-New-2FA-Supported-Site]( https://github.com/2factorauth/twofactorauth/wiki/FAQ-New-2FA-Supported-Site)
2. - [X] [FAQ-New-Site](https://github.com/2factorauth/twofactorauth/wiki/FAQ-New-Site)

The 1 page that may or may not need updated:
1. - [X] [FAQ-Categories](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Categories) does not contain:

    **proprietary, totp, u2f** 

The attached files have the suggested changes to better reflect the new format of sites with and without 2FA.
[FAQ-New-2FA-Supported-Site.txt](https://github.com/2factorauth/twofactorauth/files/3759205/FAQ-New-2FA-Supported-Site.txt)
[FAQ-New-Site.txt](https://github.com/2factorauth/twofactorauth/files/3759206/FAQ-New-Site.txt)

**Comment by Carlgo11** [comment]
Now open for everyone to edit

**Comment by Rfosu2k2** [comment]
I have updated the 2 pages for having 2FA, and not having 2FA.

-How should we incorporate proprietary, totp, & u2f on the categories page if at all?

**Comment by kmpoppe** [comment]
Hi @Rfosu2k2 and thanks for your changes. I changed some minor details - and added a Footer that reflects what TwoFactorAuth.org says :-)
I'd say, yes please, if you would add prop, totp and u2f to the categories, that would be great!

**Comment by Rfosu2k2** [comment]
I have updated the Categories wiki, and would like some additional eyes on it to ensure it is what should be stated. @kmpoppe 
@Carlgo11 - from your template #4309 it appears you included WebAuthn(FIDO2).  Should this be added to the categories?

**Comment by phallobst** [comment]
The word "category" is used in two ways, which could be confusing for new users. In the wiki, it describes the 2FA variant that is supported, in the markdown docs it's the name for the area under which the website is listed. That ambiguity should be fixed, I think.

**Comment by Rfosu2k2** [comment]
> The word "category" is used in two ways, which could be confusing for new users. In the wiki, it describes the 2FA variant that is supported, in the markdown docs it's the name for the area under which the website is listed. That ambiguity should be fixed, I think.

How would you suggest that be implemented/corrected?

**Comment by phallobst** [comment]
I am not a native English speaker, so there may be people more qualified than me in this regard. My suggestions would be:
- Use "Category" for the areas the websites are listed under.
- Use "Method", "Type" or "Style" for the different 2FA variants.

**Comment by Rfosu2k2** [comment]
Per your suggestion:

Change wiki page title "Categories" to `2FA Types`
update the wiki page to reflect the types of 2FA, and remove the usage of category(ies) from that wiki page.

Would this work per your suggestion @phallobst

**Comment by phallobst** [comment]
Sounds good to me.

**Comment by Rfosu2k2** [comment]
This has been updated accordingly.  Once another reviewer has confirmed the changes are accurate and no other modifications are needed I will resolve this issue.

The Home,  New 2FA supported site, and New Site pages have been updated to correctly link to the new page name.  I added some text rather than just 2FA Types on the home page.  I removed the line that links to FAQ 2FA Types from New Site page as that is only needed for a supporting site and didn't properly reflect an unsupported site.

Review requested by @kmpoppe and/or @Carlgo11

**Comment by Bitcofreeway** [comment]
> With the recent PR #4090 merge , the twofactorauth [wiki](https://github.com/2factorauth/twofactorauth/wiki) doesn't correctly reflect [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
> 
> The 2 pages that should be updated are:
> 
> 1. * [x]   [FAQ-New-2FA-Supported-Site](https://github.com/2factorauth/twofactorauth/wiki/FAQ-New-2FA-Supported-Site)
> 2. * [x]  [FAQ-New-Site](https://github.com/2factorauth/twofactorauth/wiki/FAQ-New-Site)
> 
> The 1 page that may or may not need updated:
> 
> 1. * [x]  [FAQ-Categories](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Categories) does not contain:
>    
>    **proprietary, totp, u2f**
> 
> The attached files have the suggested changes to better reflect the new format of sites with and without 2FA.
> [FAQ-New-2FA-Supported-Site.txt](https://github.com/2factorauth/twofactorauth/files/3759205/FAQ-New-2FA-Supported-Site.txt)
> [FAQ-New-Site.txt](https://github.com/2factorauth/twofactorauth/files/3759206/FAQ-New-Site.txt)
