### ISSUE TITLE
image for WiKID

### ISSUE THREAD

**Issue by nowen** [2factorauth/twofactorauth#418]
![wikid](https://cloud.githubusercontent.com/assets/264677/2634154/3d2d70b4-be77-11e3-9d7f-d481759645e8.png)

**Comment by jdavis** [comment]
I'm just closing this in favor of #417.

**Comment by nowen** [comment]
thanks and sorry to be extra work.

**Comment by jdavis** [comment]
There's no need to apologize! As long as you are learning then that's all that matters =]

**Comment by mxxcon** [comment]
it took me a few tries to figure out the workflow for my commits as well. :)
btw, if you are not using it already, consider using http://www.sourcetreeapp.com/ client. It's a pretty nice visual git(and mercurial) client. Using it try to get your commits nice and clean and then once you have that, just send pull request direct from github site.
Contributions here are relatively simple, just yaml and images, if you screw up, it's not that much work to blow everything away and restart from scratch. :+1:
