### ISSUE TITLE
Date of last change

### ISSUE THREAD

**Issue by phallobst** [2factorauth/twofactorauth#4266]
I stumbled upon issue #519 and wondered whether an additional `date:` property would nice to have, regardless of it being displayed or used in some other way (right now).

I hacked a little Lua script to sift through the `git blame` output for the yml files, which adds the date of the last change as something like `date: 2019-11-03` at the end of the respective block. _However_, due to commit https://github.com/2factorauth/twofactorauth/commit/9a6981a43e1f72f7b9a058845d90479353aa5f48 all entries would get a date no earlier than 2019-10-10.

Is this useful? Or should a `date:` property be added manually whenever possible?

**Comment by Carlgo11** [comment]
I don’t think another YAML tag is a good solution for this.
It’s possible that we can display this using GitHub actions when that comes out of beta.

**Comment by phallobst** [comment]
Don't get me wrong, I'm not thinking about the developers here, but the users. I think it's beneficial to know whether the information presented is up-to-date, especially if some website does _not_ support 2FA according to the list.

**Comment by Rfosu2k2** [comment]
#2159 would also be affected with this.

**Comment by Carlgo11** [comment]
@phallobst right but I think there are better ways than doing it through YAML tags. Especially when git natively logs contribution dates.

**Comment by phallobst** [comment]
Okay, but there should probably still be some way to express "the information on this entry is still valid as of ..." without having to do a dummy change in git.

**Comment by Carlgo11** [comment]
The validity of the site status is entirely different from what you proposed in the original comment of this issue. IMO that's not something a last change date can fix. There are sites that haven't been touched since 2014 that display correct information and then there are some sites edited the last couple of weeks that need to be updated again.
