### ISSUE TITLE
Entries for "Crowd Funding" sites

### ISSUE THREAD

**Issue by phallobst** [2factorauth/twofactorauth#4273]
I had a look at the "Other" category and found eight entries for crowd funding sites (there may be more, maybe even in different categories).

- Should these go to "Social" instead?
- Do they deserve a category of their own? To be honest, I haven't found a decent icon yet (that wasn't already taken).

**Comment by kmpoppe** [comment]
From the [Semantic UI Hands & Gestures](https://semantic-ui.com/elements/icon.html#hands--gestures) list, I'd go for the `handshake` icon, if we added a new category.
How many crowdfunding pages did you find?

**Comment by phallobst** [comment]
Weirdly enough, I went for "handshake" for my local tests as well, but thought it wasn't "quite there yet". But it is reassuring that I wasn't far off.

The 8 crowd funding sites that I recognized/checked are:
1. Crowd Supply
2. GoFundMe
3. Indiegogo
4. JustGiving
5. Kickstarter
6. Patreon
7. Ulule
8. Pozible
