### ISSUE TITLE
Corner Icons

### ISSUE THREAD

**Issue by phallobst** [2factorauth/twofactorauth#4275]
According to https://semantic-ui.com/elements/icon.html#corner-icon it is possible to combine two icons (of different sizes) into one.

Do you see a way to incorporate this? The set of (base) icons doesn't cover all categories properly. There are some that would benefit by combining two icons, however.

**Comment by Carlgo11** [comment]
If corner icons are supported in Semantic 2.3 then I guess it could be set by just adding "corner" before any icons in sections.yml.

Font Awesome 5.0.8 is also supported.

**Comment by phallobst** [comment]
I found no mention of _Font Awesome_ yet, but I added this to the page header:
> `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/fontawesome.css">`

After that, the _Font Awesome_ icons could be referenced.

However, I was not able to get a proper `corner` icon combination, especially with the `circular` tag, which preferably should apply to the combination itself, but not to the components. Please share if you have a working example.
