### ISSUE TITLE
Hint Health now offers software token 2FA

### ISSUE THREAD

**Issue by brianpierce** [2factorauth/twofactorauth#4282]
Please update that entry.

**Comment by Carlgo11** [comment]
Hello @brianpierce,
thanks for letting us know.

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by brianpierce** [comment]
Individual user 2FA settings are at:  https://provider.hint.com/user/security
More importantly, the settings to mandate 2FA on employee users are at:  https://provider.hint.com/admin/team

**Comment by brianpierce** [comment]
![Hintshot](https://user-images.githubusercontent.com/16437077/68476887-e8bc8000-0223-11ea-95e2-46122aacef84.png)

**Comment by phallobst** [comment]
Strangely enough, I found a support page via Google search only, but no link on the website. (see PR)
