### ISSUE TITLE
Bank of America supports a custom 2FA

### ISSUE THREAD

**Issue by jhawkwind** [2factorauth/twofactorauth#43]
Bank of America supports a custom 2FA, where they mail you a physical token, which they call SafePass.
As part of Bank of America but a separate site and entity, Merrill Lynch also has 2FA.

**Comment by nikolay** [comment]
Confirmed. I'm using the physical token, too, as I can't use SMS abroad (or at least, not for free).

**Comment by jhawkwind** [comment]
https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/safepass.go
The option in the box on the right show you their SafePass card option.

"You can generate SafePass codes from a card. It’s the same size as a credit card and fits conveniently in your wallet. There’s a one-time fee of $19.99 for the SafePass card."

**Comment by jdavis** [comment]
Very cool. I'll update the BoA data and let you know.

**Comment by jdavis** [comment]
K, I added it with that last commit. Let me know if I should update anything.
