### ISSUE TITLE
[Feature Request] Is it possible to have section for sites that have been newly added to the list?

### ISSUE THREAD

**Issue by QUItURNE** [2factorauth/twofactorauth#4301]
So the user can easily identify sites they use that have recently implemented 2FA without having to check every page

**Comment by zecanard** [comment]
This would be great. Right now I just watch the repository for all new tickets, and that’s definitely far from ideal.

**Comment by dsoegijono** [comment]
I think this is a duplicate of #521 and #519 part of [Filtering milestone](https://github.com/2factorauth/twofactorauth/milestone/4)
