### ISSUE TITLE
Maintaining language declaration on site update

### ISSUE THREAD

**Issue by Rfosu2k2** [2factorauth/twofactorauth#4304]
The `lang` field is being removed when a site is updated from not having 2FA to one that does implement it.  It seems that maintaining the language once it is declared should stay with the site even after being updated to implementing 2FA, and not removing it just because it now supports 2FA.

This shows on [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) under New_Sites but only as a site that does not support 2FA.

As an example #4240 removes the language when adding 2FA.  Should we not be maintaining the language when adding or updating a site?

**Comment by Carlgo11** [comment]
The language tag is used for tweets and emails. If the site supports 2FA then there’s no reason for tweeting the site hence no reason for the language tag.

**Comment by Rfosu2k2** [comment]
> The language tag is used for tweets and emails. If the site supports 2FA then there’s no reason for tweeting the site hence no reason for the language tag.

Should that information be added to [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) so that future contributors understand the full reasoning behind adding the `lang` field?

**Comment by Carlgo11** [comment]
I don’t think that’s essential information for creating a PR. The wiki is probably a better place for that.

**Comment by Rfosu2k2** [comment]
That seems like a great place to document that.  I will update accordingly and resolve this PR.  Thank you.
