### ISSUE TITLE
Backblaze, Kickstarter, Mercado Libre

### ISSUE THREAD

**Issue by victorh800** [2factorauth/twofactorauth#4312]
please add to Exceptions & Restrictions:
[**Backblaze**](https://help.backblaze.com/hc/en-us/articles/217666588-Two-Factor-Verification): SMS-capable phone is required for software token.
**Kickstarter**: A verified phone number (SMS or call) is required for software token.
**Mercado Libre**: Mercado Libre own app, SMS, or Authy. Authy requires a phone number.

**Comment by phallobst** [comment]
Backblaze and Kickstarter are covered now. For Authy (Mercado Libre), I don't really see the need for an exception text, otherwise very many "proprietary" entries would need one. That would defeat its purpose.

**Comment by ApCoder123** [comment]
Closing, as these issues were resolved by: 
Backblaze - #4863
Kickstarter - #5579
Mercado Libre - as mentioned in the comment above, Authy doesn't justify a phone number exception
