### ISSUE TITLE
Allows mandatory two-factor authentication

### ISSUE THREAD

**Issue by edwardabraham** [2factorauth/twofactorauth#432]
I am interested in who allows mandatory two-factor authentication for all the people in an organisation. For example, google apps premier allows you to enfore 2FA for all the people with your company email. This is great. 

On the other hand, Github have 2FA but don't allow you to enforce it for all the people in your organisation. A pattern we see is that the most security minded people also have 2FA, whereas the people who don't really care about these details in life don't bother. They may well be the same people who have one password for every circumstance. It is a pain to have to go through the lists of teams and ask people to switch it on. I want to encourage services that have a concept of an organisation, to allow mandatory 2FA as an organisation setting.

Really appreciate your list, and am just raising this as a potential feature.

**Comment by jdavis** [comment]
Yeah, I understand your point. It would be nice to know from an organization standpoint where you can enforce it.

I see it being a niche need/concern though and don't know how we could represent it on the site as such.

**Comment by edwardabraham** [comment]
Fair enough. First get sites to use 2FA, than get them to allow you to make it mandatory ...

**Comment by jdavis** [comment]
Thanks for opening the issue though.

And I'm sorry about shooting down your idea because obviously it would help you out. I guess decisions like this come with being a [BDFL](http://en.wikipedia.org/wiki/Benevolent_Dictator_for_Life) of a project :frowning:
