### ISSUE TITLE
Differentiate between different types of software tokens 

### ISSUE THREAD

**Issue by jtl999** [2factorauth/twofactorauth#4324]
It would be useful to be able (at a glance) to know what kind of "software token" a given service uses. For example OATH/Google Authenticator might be acceptable to someone but a mobile application might not be.

A few things to note:

1)  If I were designing a mockup for this I'd probably have a mouseover for the "Software Token" checkmark, similar to how the exceptions are done. Maybe I'll try later.
2) It would need to be kept updated if/when services change.

**Comment by Carlgo11** [comment]
That's on the roadmap. In the meantime, the API displays totp or proprietary software implementations.
