### ISSUE TITLE
Distinction between Open and Proprietary Software Token

### ISSUE THREAD

**Issue by iancynk** [2factorauth/twofactorauth#4329]
A lot of people may be interested in whether the software token of a certain service (e.g. a bank) is proprietary (like a banking app) or open like a TOTP token that I could use with any app of my liking.

This seems a very important distinction for privacy-oriented people who are looking for a new favorite bank or other service.

**Comment by kmpoppe** [comment]
Same as #4324. That's on the roadmap. In the meantime, the API displays totp or proprietary software implementations.

**Comment by Stevoisiak** [comment]
@kmpoppe If visually separating software & proprietary 2fa is on the roadmap, shouldn't this issue stay open until it has been implemented?
