### ISSUE TITLE
Evernote Update

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4382]
(1) Even on the free account, SMS 2FA can be used by selecting "I need help getting a verification code." when prompted for an authenticator app code.

(2) As a corollary to the above, SMS can be used to bypass software method.

To cover both, I suggest updating the exceptions/restrictions text: "Software method can be bypassed with SMS."

**Comment by Carlgo11** [comment]
@djfredalert feel free to make a PR with the changes that you want done.

**Comment by leggomyinfo** [comment]
Hi @Carlgo11 - I would have but the readme didn't give directions on how to request edits to sites already posted (unless I missed it/misread it). Could you let me know how to make a PR for a change to a site already listed? I'm a Github newb, sorry for the extra work on your end.
