### ISSUE TITLE
Adobe URLs

### ISSUE THREAD

**Issue by Calorion** [2factorauth/twofactorauth#4390]
1Password, of course, uses twofactorauth to determine whether a particular login has 2FA available. 

However, there are various possible URLs for Adobe logins, and the fact that twofactorauth lists https://accounts.adobe.com/ means that if the Adobe URL you have in 1Password is, say, https://account.adobe.com/, or https://adobeid-na1.services.adobe.com/renga-idprovider/pages/login (which is what they all resolve to), 1P won't notify you that 2FA is available.

A possible solution is to use https://adobe.com/account/sign-in.adobedotcom.html, which presumably will trigger 1P's notification for any subdomain that is saved.

**Comment by Carlgo11** [comment]
We generally advise anyone using our API to ignore subdomains.
That said, since the current URL is just a login page it shouldn't be the URL for Adobe ID. Just having `https://adobe.com/` seems like a good solution.

I'll make a PR with the change.
