### ISSUE TITLE
Update software tags

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#4410]
All the categories needs to have their software 2FA tokens replaced with our API 2 software tags.
So far these categories have been updated:
- [x] Backup
- [x] Banking
- [x] Cloud
- [x] Communication
- [x] Cryptocurrencies
- [x] Developer
- [x] Domains
- [x] Education
- [x] Email
- [x] Entertainment
- [x] Finance
- [x] ~Food~
- [x] Gaming
- [x] Government
- [x] Health
- [x] Hosting
- [x] ~Hotels~
- [x] Identity
- [x] Investing
- [x] ~IoT~
- [x] Legal
- [x] Other
- [x] Payments
- [x] Remote
- [x] Retail
- [x] Security
- [x] Social
- [x] Task
- [x] Transport
- [x] Utilities
- [x] VPN

**Comment by phallobst** [comment]
In the works:
- [x] banking
- [x] betting
- [ ] developer
  - aTech Media has insufficient documentation
  - Phacility is lacking documentation
- [x] domains
- [x] education
- [x] email
- [x] entertainment
- [x] finance
- [x] gaming
- [x] government
- [x] health
- [ ] hosting
  - Hostnet has insufficient documentation
- [x] identity
- [x] investing
- [x] legal
- [x] other
- [x] payments
- [x] remote
- [x] retail
- [x] security
- [x] social
- [x] task
- [x] transport
- [x] utilities
- [x] vpn

**Comment by phallobst** [comment]
So far, I have packed all the categories in to one PR, but by now I think it might become a bit crowded in there. Shall I rather open one PR per category?

**Comment by Carlgo11** [comment]
One per category please!
