### ISSUE TITLE
Add Clavid

### ISSUE THREAD

**Issue by thr0wable** [2factorauth/twofactorauth#445]
You should add http://www.clavid.com as a 2FA provider to your list.

**Comment by ilyakatz** [comment]
@thr0wable are you able to open a pull request for this? let me know if you need any help with this

**Comment by thr0wable** [comment]
@ilyakatz I opened a pull request, hope I did it the right way though.

**Comment by jdavis** [comment]
@thr0wable Awesome. I'm closing this in favor of #600.
