### ISSUE TITLE
Request: replace tick with some indicator of 'partial support' if user-agent whitelisting is used

### ISSUE THREAD

**Issue by fredemmott** [2factorauth/twofactorauth#4450]
For example, Google accounts [support WebAuthn](https://security.googleblog.com/2019/08/making-authentication-even-easier-with_12.html), however this is only supported if you use Google Chrome - not any other WebAuthn-capable browser.

![Screen Shot 2019-12-18 at 10 16 39 AM](https://user-images.githubusercontent.com/360927/71112369-2ea02880-2180-11ea-8dc4-28e3a347cee5.png)

**Comment by phallobst** [comment]
Are we only talking about _adding_ the security key, or actually _logging into Google_ with that browser+key? If adding the key is the problem, this does not belong here, I think. However, if the login itself is not supported, an appropriate exception text may be the best, as long as it does not get out of hands.

As this applies to Google and all of its services, maintaining these exceptions would be somewhat cumbersome, so an [include mechanism](https://github.com/2factorauth/twofactorauth/pull/4034#issuecomment-566500921) would be nice (although not essential).

BTW: Which browser/OS did you use to get this error?

**Comment by fredemmott** [comment]
That was when adding with Safari 13.0.4 on MacOS 10.15.2; I've not tried adding with Chrome and using on Safari

**Comment by Carlgo11** [comment]
@fredemmott Safari doesn't support U2F. Try Chrome and Firefox. If it works with one of those then it's just due to lacking support from Apple (and we don't explicitly list browser support here).

If it only works on Chrome and not Firefox then it would be worth adding an exception, like we've done with Microsoft Accounts.

**Comment by Carlgo11** [comment]
See https://caniuse.com/#search=u2f for a list of browsers supporting U2F

**Comment by fredemmott** [comment]
Safari supports webauthn, both on MacOS and iOS, including FIDO2

**Comment by fredemmott** [comment]
https://caniuse.com/#search=webauthn

**Comment by fredemmott** [comment]
To confirm, yes, this restriction appears to only be for adding keys, not logging in with them. I can add a yubikey 5 NFC with chrome von macOS via USB, then I can successfully login with that key:
- on safari on macos via USB
- on safari on iOS via NFC

No extensions used, native webauthn.

**Comment by Carlgo11** [comment]
Okay. I guess we'll write an exception text then. Something long the lines of `Initial setup of U2F requires a Chromium browser`

**Comment by onkarshinde** [comment]
Please note that U2F and WebAuthn are different things. So the exception text needs to written accordingly.

**Comment by Carlgo11** [comment]
Fixed as U2F implementation have been more standardized.
