### ISSUE TITLE
Add Column for FIDO2/WebAuthn

### ISSUE THREAD

**Issue by jsfrederick** [2factorauth/twofactorauth#4452]
Please add a new column for FIDO2/WebAuthn.  This is the future of strong 2FA.

**Comment by phallobst** [comment]
The data files already have a "u2f" method where applicable (see also [2FA Types](https://github.com/2factorauth/twofactorauth/wiki/FAQ-2FA-Types) in the wiki) which should cover that. There will be a dedicated column once the data is ready, as far as I understood it.

Maybe (in the not-too-distant future) there is also the chance to re-integrate the data from [dongleauth.info](https://www.dongleauth.info) ([github repo](https://github.com/nitrokey/dongleauth)). No need to duplicate the effort.

**Comment by leggomyinfo** [comment]
@phallobst I noticed on the mobile site some sites have U2F (Dropbox) and some have "hardware" & "U2F" (files.com) but on the desktop site those sites have only "hardware." I'm a bit confused. Do you know how that came about? I wasn't sure what the correct ticket was.

**Comment by phallobst** [comment]
The inclusion of "U2F" for the mobile site was done in a [commit](https://github.com/2factorauth/twofactorauth/commit/6a801e56851fba43b516b658df837c777e7c5d5f) for PR #4090 by @Carlgo11. The desktop site has not been changed to distinguish these yet, but this is still on the [to do](https://github.com/2factorauth/twofactorauth/projects/5#card-27644150) list.

**Comment by leggomyinfo** [comment]
@phallobst Thanks. I just read through a bunch of linked tickets, etc. Is one of the implications that the "hardware" tag will be phased out over time in favor of more specific information? Or it will continue to exist alongside more specific tags?

**Comment by phallobst** [comment]
My guess is that it will stay for now. I have not heard of other, more specific terms to be introduced -- but I'm not responsible for the code or design either.

**Comment by Carlgo11** [comment]
Hi there,
at the moment there’s no plan to remove the hardware tag as there are so many different implementations of hardware 2FA.

**Comment by Carlgo11** [comment]
Fixed in v3.0
