### ISSUE TITLE
TurboTax needs an exception

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4467]
Exceptions & Restrictions: Software 2FA requires also enabling SMS as an alternative login option.

My reasoning: SMS authentication is weaker than software token verification, and 2FA is only as strong as the weakest option enabled.

**Comment by aidenmitchell** [comment]
Do you have a link to some documentation or screenshot(s)?

**Comment by leggomyinfo** [comment]
@ilovecats516 Is this the sort of thing you were looking for?
[TurboTax Screenshots.pdf](https://github.com/2factorauth/twofactorauth/files/4049578/TurboTax.Screenshots.pdf)
