### ISSUE TITLE
Facebook exceptions/restrictions inaccurate

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4469]
Currently "Exceptions & Restrictions" reads: "Software or SMS 2FA must be set up before a hardware token can be added."

Instead it should read: "Hardware 2FA requires enabling Software or SMS 2FA as a workaround."

The current phrasing suggests as long as you set up software or SMS first, you can then use hardware with or without software/SMS. In actuality, you need to leave SMS or software enabled and hardware can only be used as an alternative (which can be bypassed by SMS/software). This largely defeats the purpose of a hardware token (i.e. greater security than software/SMS).

Related: #4293 #4294

**Comment by RichJeanes** [comment]
The word "workaround" usually means that the given solution must be used to overcome some kind of bug or problem. In this case, that is not true. Facebook's system is working as intended. In terms of best practices, should it work that way? Probably not. But the way it behaves now is how they have designed it to work. Personally, I don't see how the current wording implies what you're saying.

**Comment by leggomyinfo** [comment]
> The word "workaround" usually means that the given solution must be used to overcome some kind of bug or problem.

I think you make a fair point about "workaround" connoting a bug. Perhaps this is more precise: **"Hardware 2FA requires also enabling Software or SMS 2FA as an alternative login option."**

> Personally, I don't see how the current wording implies what you're saying.

I agree: I was making some assumptions about how it would be read. To your point, the current phrasing doesn't inform the user about how 2FA will work once the hardware token option is enabled; it only explains that the SMS or software token must be enabled first before it's possible to enable the hardware token. 

I think in addition to flagging the minor set-up inconvenience of having to first enable SMS or software token before being able to enable hardware token, this project should also flag that a hardware token cannot be used on its own. The former relates to the particular site’s set-up instructions, which is ordinarily addressed by linking to the site’s set-up documentation. The latter is a security weakness resulting from a counter-intuitive hardware token policy, exactly the sort of thing the “exceptions & restrictions” warning is meant to address. Flagging this is consistent with [the purpose of this project](https://github.com/2factorauth/twofactorauth): “Our hope is to aid consumers who are deciding between alternative services based on the security they offer for their customers” and to provide “an indicator of general security efforts used on a site.” When deciding whether to use a service based on the checkmark next to “hardware token,” the user should also know that an attacker can circumvent it with a weaker login option. This distinction is especially relevant to the sort of person who goes to the trouble of using a security key.
