### ISSUE TITLE
Update Sprint

### ISSUE THREAD

**Issue by ldunzweiler** [2factorauth/twofactorauth#4470]
they support MFA via SMS

**Comment by aidenmitchell** [comment]
Do you have screenshots of the 2FA process?

**Comment by ldunzweiler** [comment]
Well, I just changed providers, no longer a Sprint customer.  For some
reason it removed 2FA via SMS as a login option.  I have included screen
shot of old 2FA SMS passcodes I received from Sprint.

**Comment by aidenmitchell** [comment]
Ok, thanks. I contacted Sprint and they were not clear on their 2FA practices, so I don't think any changes need to be made.

**Comment by ApCoder123** [comment]
Closing, as sprint was removed in #5073
