### ISSUE TITLE
Add site: Stash

### ISSUE THREAD

**Issue by wwejason** [2factorauth/twofactorauth#4483]
Site name:  Stash
Main URL of the site:  https://app.stashinvest.com
Category which the site would be in:  Investing
What kinds of 2FA authentication the site supports:  none

**Comment by phallobst** [comment]
The site seems to support 2FA (SMS and email?) at least for some users according to <strike>https://ask.stashinvest.com/ask/how-to-turn-on-two-factor-authentication-2fa/</strike> [Edit: 404, but https://ask.stashinvest.com/tag/two-factor-authentication-2fa/ indicates some support for 2FA].
Can you verify that?

**Comment by phallobst** [comment]
They seem to have activated 2FA (sms, phone, email) for all users according to https://ask.stashinvest.com/ask/what-is-two-factor-authentication/
