### ISSUE TITLE
Suggestion: Explain hardware tokens and software tokens

### ISSUE THREAD

**Issue by aidenmitchell** [2factorauth/twofactorauth#4486]

**Comment by Carlgo11** [comment]
Have you looked at https://github.com/2factorauth/twofactorauth/wiki/FAQ-2FA-Types#software and https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites?

**Comment by aidenmitchell** [comment]
Yes, but I mean explain it on the actual website, or link to those pages.

**Comment by Carlgo11** [comment]
Ah, yeah that's on the todo list https://github.com/2factorauth/twofactorauth/projects/2#card-1157180

**Comment by aidenmitchell** [comment]
Oh, I didn't see that. Thanks.
