### ISSUE TITLE
Add subreg.cz site

### ISSUE THREAD

**Issue by JanHrivnak** [2factorauth/twofactorauth#4499]
Site name: Subreg.cz
Main URL of the site: https://subreg.cz/
Category which the site would be in: Domains
What kinds of 2FA authentication the site supports: Software Token

**Comment by Carlgo11** [comment]
I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by JanHrivnak** [comment]
I didn't find any documentation. They have an info after sign-in. 

![info1](https://user-images.githubusercontent.com/3205027/71822257-b8af2300-3094-11ea-92ff-5fd01ec18752.jpg)

And in User settings:
![2fa](https://user-images.githubusercontent.com/3205027/71822261-ba78e680-3094-11ea-8cb4-8a0e31b2c268.jpg)

**Comment by Carlgo11** [comment]
Your screenshots aren't clear about how the 2FA works. Is it a normal totp or some proprietary system?

**Comment by JanHrivnak** [comment]
I think it is normal TOTP. This is form for first setting of 2FA.

![image](https://user-images.githubusercontent.com/3205027/71823365-573c8380-3097-11ea-87fc-95591b6284b0.png)

**Comment by Carlgo11** [comment]
Thanks for the info!

I just checked the site and I'm afraid it's ranked above 200K on Alexa. To make our lists more manageable we currently have a >200K Alexa rank limit on new site additions and thus I'm afraid Subreg.cz can't be added to our list.

Sorry for the inconvenience!
