### ISSUE TITLE
OAuth and 2Factor?

### ISSUE THREAD

**Issue by stevepereira** [2factorauth/twofactorauth#450]
Hey team,

If an app supports an OAuth provider using 2factor, does it not qualify as a 2factor supported app? It may be prudent to feature those apps (at least the popular ones) as well, perhaps on a separate tab, an expandable section or just the bottom of the main. What do you think? I'd happily do some legwork to get it started.

**Comment by mxxcon** [comment]
I don't exactly understand what do you mean by _"OAuth provider using 2factor"_...Like login into some site using Google account which has 2FA enabled?

**Comment by stevepereira** [comment]
Exactly, if I use a Google account to connect to a service, and my Google account has 2factor auth, the service I'm connecting to is safe (provided I haven't authorized it for more than I should), and I think it would be valuable to track the major players that allow that

A better implementation than, say: http://wiki.oauth.net/w/page/12238551/ServiceProviders or http://www.cheatography.com/kayalshri/cheat-sheets/oauth-end-points/ or http://ngiriraj.com/socialMedia/oauthlogin/

I suppose that could manifest itself in another site but I think it would be great to integrate it here as a one-stop reference for vetting apps

**Comment by smholloway** [comment]
My gut reaction is that getting 2fa through OAuth is a bit clumsy. I'd love to see how sites have described 2fa-through-OAuth--can you please point me to an example docs link stating that users can enable 2fa on the site by signing in through OAuth?
