### ISSUE TITLE
Connection between Google products unclear

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4510]
It makes sense for each Google product (Drive, Gmail, etc) to appear on its own to make it easy to find for those looking for it, but it is also confusing because it suggests that each has its own independent 2FA settings. To address the latter shortcoming, I would suggest the following:

(1) Append " (Google account)" to the name column of every site which draws from one's Google account settings for 2FA.
(2) Add "Google account" as a row in the "Other" section.

This would also address the problem that certain Google products don't show up when you search Google (e.g. YouTube, even though "Hangouts" shows up despite also not having "Google" in the name).

**Comment by Carlgo11** [comment]
Closing as the accompanying PR #4522 was closed.
