### ISSUE TITLE
Google does not support NFC security keys

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4511]
Google does not support NFC security keys (https://support.google.com/accounts/thread/13082621?hl=en). As a result, you cannot use YubiKeys to log onto anything Google-connected through iOS (except through a workaround like the Yubico Authenticator app).

Suggested solve - add "Exceptions & Restrictions" for all Google products: "NFC security keys not supported"

Would apply to Google Drive, Google Cloud Platform, Hangouts, Google Domains, Gmail, Google Play, Google Fit, Google Pay, Google Fi, Google Fiber, YouTube (there may also be others)

**Comment by onkarshinde** [comment]
I think you have misinterpreted the issue. The issue is because of restrictions on iOS which were only addressed in version 13 so the Google app now needs to update to use NFC.
I have used Yubico 4 NFC key on my google account on an Android phone with both Chrome as well as Firefox. So there is no restriction with the Google sites.

**Comment by leggomyinfo** [comment]
@onkarshinde I think you're right; good call. How does this sound instead? "NFC security keys cannot currently be used on iOS for Google accounts"

I added "currently" to allude to the fact that this only recently arose and will likely be fixed at some point.

**Comment by onkarshinde** [comment]
@djfredalert 
That's not the exact representation of the latest status as well. The link below says that NFC keys can now be used in Safari browser on iOS 13.
https://www.yubico.com/blog/yubico-ios-authentication-expands-to-include-nfc/
So I suggest exception text like this - "Using NFC security key on iOS requires at least iOS 13. Additional updates may be required to Safari and other browsers."
