### ISSUE TITLE
Skype hardware token requires Edge browser

### ISSUE THREAD

**Issue by leggomyinfo** [2factorauth/twofactorauth#4513]
Update Skype exceptions & restrictions from "Must be associated with a Microsoft Account." to "Must be associated with a Microsoft Account. Hardware token only compatible with Edge browser."

Documentation: https://support.microsoft.com/en-us/help/4463210/windows-10-sign-in-microsoft-account-windows-hello-security-key

**Comment by Carlgo11** [comment]
The easiest way would be if you made a PR with the change. If I remember correctly you didn't know how to create PRs so I made a little guide:
1. 
![1](https://user-images.githubusercontent.com/3535780/72211338-f4e5e780-34c9-11ea-80bd-1ba315b81da9.png)
Go to the main page of this repository and press the "Fork" button. (You only need to do this once)

2. 
![2](https://user-images.githubusercontent.com/3535780/72211345-0f1fc580-34ca-11ea-86f3-b653cfff81b3.png)
Make sure your own username is displayed at the top.
Go to the "Branch:" button and write a relevant name for the new branch (which will become the PR)
Press Enter and the Branch button should now say "Branch: <chosen name>"

3. 
![3](https://user-images.githubusercontent.com/3535780/72211364-51490700-34ca-11ea-8962-d03b1f3da74b.png)
Go to the YAML file that the site in question is located in. In this case Skype is located inside the communication.yml file.
Press the pen icon to edit it.

4.
![4](https://user-images.githubusercontent.com/3535780/72211374-76d61080-34ca-11ea-8305-081884ef176c.png)
Write your change to the exception text.
Make a short description of what you changed (see point 2 in the picture)
Press "Commit".

5. 
![5](https://user-images.githubusercontent.com/3535780/72211379-b00e8080-34ca-11ea-9f8b-27811374a1cf.png)
Go back to the main page and you should now see a message with a "Compare & pull request" button. Press it.

6. 
![6](https://user-images.githubusercontent.com/3535780/72211387-d3d1c680-34ca-11ea-8d07-0590caafc652.png)
Give the PR an appropriate title.
Optionally write a short description of what you've changed, why it needs to be changed and any relevant sources/documentation for us to look at.
Press the "Create pull request" button _(not on the down arrow part)_.

**Comment by leggomyinfo** [comment]
@Carlgo11 Thanks so much for putting this together for me!

I just followed these steps (PR #4516) to submit the changes I captured in issue #4515.

One follow-up Q: When creating pull requests, is it best practice to submit changes to different sites at once? Or should each changed site be broken out into its own pull request? (Once you answer, I'll convert the request of the issues I opened into pull request/s.)

**Comment by Carlgo11** [comment]
We generally want one site change per PR. It makes it easier to read the change logs and for us to keep track of our work.

**Comment by leggomyinfo** [comment]
@Carlgo11 Hitting pause on converting my issues due to one more Q. Should I be creating a new branch for each change as well, or one branch with multiple pull requests?

**Comment by Carlgo11** [comment]
One branch per PR/change since the thing that the PR does is merge your branch into our main branch.
