### ISSUE TITLE
Add site: LayerStack

### ISSUE THREAD

**Issue by jason-ls** [2factorauth/twofactorauth#4534]
Hello, 
I would like to add my site to 2FA list, 

Site name: 
- LayerStack
Main URL of the site: 
- https://www.layerstack.com/
Category which the site would be in: 
- Cloud Computing
What kinds of 2FA authentication the site supports.
- Software Token
When the site asks for 2FA.
- Login
Link to any documentation on how to enable 2FA on the site. If no documentation is available, please provide screenshot(s) of the setup process and/or login process. Remember to blur or crop out any personal information linked to you.
- User Manual: https://www.layerstack.com/resources/docs/Two-factor-Authentication-(2FA)
![layerstack-2fa-1](https://user-images.githubusercontent.com/59814473/72232751-12b46900-35fe-11ea-86af-703d016fe8d4.png)
![layerstack-2fa-2](https://user-images.githubusercontent.com/59814473/72232754-147e2c80-35fe-11ea-8c0e-6b3570ab2a0b.png)

**Comment by Carlgo11** [comment]
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.
