### ISSUE TITLE
add: Zelle

### ISSUE THREAD

**Issue by marshyrooney** [2factorauth/twofactorauth#4558]
- **Site name:** Zelle
- **Main URL of the site:** https://www.zellepay.com
- **Category which the site would be in:** Banking
- **What kinds of 2FA authentication the site supports:** Text (on signup and first setup on phone)
- **When the site asks for 2FA:** Only on signup and first setup on phone
- **Documentation:** There appears to be none on this topic
![zelle](https://user-images.githubusercontent.com/60326619/73141133-7a32d580-404e-11ea-815f-9e4a36c887ef.png)

Thank you!

**Comment by marshyrooney** [comment]
Note that this is just for the stand-alone app. Some banks have this service integrated within their own apps.

**Comment by phallobst** [comment]
They don't seem to offer any kind of account that would require logging in, let alone using 2FA. This website does not meet our requirements for inclusion then.

**Comment by marshyrooney** [comment]
> They don't seem to offer any kind of account that would require logging in, let alone using 2FA. This website does not meet our requirements for inclusion then.

You can in their phone app. I created an account not through a bank. Your phone number is your username.
