### ISSUE TITLE
Method of pushing content to the site after merging pull requests and adding commits

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#457]
Are you manually updating the site (pulling from GitHub) after you add a commit or merge a pull request?

It just seems like time passes between the pull request being merged and it showing up on the website (which is reasonable given the number of pull requests you get).

To make updates to the site faster (and your life easier), you could use automatic deployments so when you update the project on GitHub, it updates on the website automatically.

Some options are:

http://ftploy.com (supports FTP or SSH and integrates with GitHub)

and

http://deployhq.com by aTech Media (supports FTP & SFTP servers, SSH servers, Amazon S3, or Rackspace Cloud Files. It also has 2fa. :smile:)

DeployHQ is built directly into GitHub on the https://github.com/jdavis/twofactorauth/settings/hooks page (you still need to set it up at deployhq.com)

As a warning, DeployHQ is MUCH more complicated than FTPloy and requires a lot more setup.

**Comment by jdavis** [comment]
The site is actually being ran on GitHub Pages. So in order to update the site, I just need to update the gh-pages branch. I've been using master as the sort of development and then merging it onto gh-pages when enough has been changed.

Whenever I update the site, I pull master, run Jekyll, look things over, and update gh-pages. I do it to make sure there are no breaking commits before updating the site.

I totally understand the want to automate things. If I was using anything but GitHub Pages (like deploying using FTP or something), it'd drive me insane and I would already have a solution.

**Comment by jdavis** [comment]
I'm going to close this because right now I think there are enough collaborators, that the `gh-pages` branch could be updated by any of them.

**Comment by edmorley** [comment]
As an alternative - would you be open to making gh-pages the default branch for this repo? This would avoid having to manually update it, and aligns with the "fail fast" approach that makes it easier to correlate regression with cause.

Even if you don't wish to take this approach - could we document the current deployment strategy (and set expectation that deploys only happen occasionally) in the repo readme?

Context: I was about to open a PR for a site that isn't listed on twofactorauth.org, when I came across the commit to master. Had I not spotted that I would have duplicated effort. It hadn't occurred to me that the deployed site might be 3 weeks behind master.

Many thanks!

**Comment by Carlgo11** [comment]
No we don't want that. With a lot of users connecting to our site around the day. If someone broke the site with a commit it might take several hours for one of us to notice it. That means that a lot of people would see a non-working site. Something we really want to avoid.

This approach enables us to verify that everything looks good before it goes live.

**Comment by edmorley** [comment]
Understand; can we at least:

> document the current deployment strategy (and set expectation that deploys only happen occasionally) in the repo readme?

**Comment by Carlgo11** [comment]
@edmorley https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge

**Comment by edmorley** [comment]
That wiki page didn't mention the `gh-pages` vs `master` relationship, so I've tweaked it to make that clearer + added a link to the changes pending deploy:
https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge/_compare/6c636932eb76a9366bc88c6e0c7b73571e2bd93f...b6e7e8b21377b6759bb8e74e25c9d317f639a95c

That said, it wasn't clear to me that there was content in the wiki. The repo readme directs contributors to CONTRIBUTING.md, which doesn't mention the wiki at all.

Would it be possible to add links somewhere (the main readme and/or CONTRIBUTING.md) that link to the wiki? Or even better, could the two be consolidated? Having content split across the two makes things harder to find.

Thank you for your help :-)

**Comment by edmorley** [comment]
(I'm happy to submit a PR for the readme/CONTRIBUTING.md tweaks, if it would be accepted)

**Comment by mxxcon** [comment]
That diff looks good to me.
