### ISSUE TITLE
Add: pCloudy Mobile Device Cloud.

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#4570]
Site name: pCloudy 
Main URL : www.pcloudy.com
What kinds of 2FA authentication the site supports: SMS
When the site asks for 2FA. Only on Signup
Documentation: There is none on this topic.

**Comment by Carlgo11** [comment]
@pmn247 so it doesn't ask for 2FA on login?

**Comment by ghost** [comment]
@Carlgo11 It asks for 2FA on first time signup to authenticate an user. Not on login.

**Comment by Carlgo11** [comment]
If they don't ask for it upon login then it's not 2FA according to us.
