### ISSUE TITLE
Add CQUniversity Australia

### ISSUE THREAD

**Issue by Jawshy** [2factorauth/twofactorauth#4603]
[CQUniversity Australia](https://www.cqu.edu.au/) (CQU) is a trading name of Central Queensland University. 

They offer two-factor authentication (2FA) via Duo (SMS, proprietary, and U2F), but only for staff logging into ~Employee Self Service Online (ESSO)~ Office365 applications, Moodle, ESSO and VPN outside of the internal network. Other staff logins and all student logins do not yet offer 2FA. No public facing documentation, but because they use Duo the documentation is essentially [this guide](https://guide.duo.com/). Social media handles: [Facebook](https://www.facebook.com/CQUniversityAustralia) and [Twitter](https://twitter.com/CQUni). 

Should CQU be listed as supporting 2FA with an exception or not supporting 2FA due to the limited deployment? 
![cquniversityaustralia](https://user-images.githubusercontent.com/10876578/74620308-98ad5d80-5130-11ea-8db2-cd7650e43b3e.png)

_Update 2020-02-29: ...only for staff logging into Office365 applications, Moodle, ESSO and VPN outside of the internal network._

**Comment by phallobst** [comment]
I tried to initiate a discussion about multiple 2FA policies with issue #4306, but it didn't really take off so far...

My opinion is to list it as supporting 2FA, but with an exception text.

**Comment by Carlgo11** [comment]
By the looks of it, CQU uses Microsoft Azure AD for authentication which would mean the same 2FA support as with Microsoft Accounts, regardless of account type.
Can you confirm @Jawshy?

**Comment by Jawshy** [comment]
> By the looks of it, CQU uses Microsoft Azure AD for authentication which would mean the same 2FA support as with Microsoft Accounts, regardless of account type. Can you confirm @Jawshy?

Sorry for the belated response, @Carlgo11. No, only `custom-software` and `sms` 2FA are being implemented for students starting April 2023 onwards. 

The only public documentation I've found is [this page without a date](https://www.cqu.edu.au/eresearch/security) mentioning multi factor authentication using the Microsoft Authenticator app and SMS code methods. There are links to user guides on that page. 

Also, there's an article behind a login that mentions key information like: 

> _[...]_ From April 2023, you’ll be required to use multi-factor authentication whenever you log in to a CQUniversity website, app, or system. _[...]_

> _[...]_ For this authentication to work, you must have a valid mobile phone number recorded in MyCQU. _[...]_

**Comment by Jawshy** [comment]
I can now confirm that time-based one-time passwords (`totp`) are supported. One simply chooses 'I want to use a different authenticator app' when adding an authenticator app as a sign-in method.

**Comment by Jawshy** [comment]
And also phone call based authentication (`call`).
