### ISSUE TITLE
Fidelity Investments question

### ISSUE THREAD

**Issue by dseese01** [2factorauth/twofactorauth#462]
Fidelity Investments does offer two-factor authentication (hardware token and software implementation) but they don't seem to have an official documentation webpage. There is a Gist describing it at https://gist.github.com/dseese01/11100219#file-fidelity2factor-md.

Can the Fidelity entry be modified with a link to the Gist?

**Comment by jdavis** [comment]
I like this idea; I hate that they hide 2FA but showing people how to enable it sounds really great.

Edit: Do you mind if I take that Gist and turn it into an individual page on 2fa.org?

**Comment by jdavis** [comment]
Thanks for the info, @dseese01! I just updated it. GIve it a look here: http://twofactorauth.org/notes/fidelity/
