### ISSUE TITLE
Know more about twofactorauth

### ISSUE THREAD

**Issue by Abubakr077** [2factorauth/twofactorauth#4676]
You guys did a great job, I want to know how data acquisition is happening. how you guys know which website provides two-way authentication. I am from Pakistan and i want to add local websites of Pakistan in this project as well and make a new pull request but I am confused if is it manual work or is there any workaround? 
please bear my English as it is my second language 
I have searched already please don't just ignore this 
thanks

**Comment by phallobst** [comment]
There is no way to automatically determine whether a website supports 2FA or not. All the entries you see in the list have been examined manually at some point. Unfortunately, this also means there is no means of automatically updating an entry. This project relies on user input.

My personal experience is: Once you use or know a certain website/service that supports 2FA (or should do so), you add it to the list by opening a PR. It's also a good idea to look for similar websites, e.g. not only add the bank (university, web hoster, ...) for your own account, but other institutions as well.

Regarding new websites:
Please note our [CONTRIBUTING](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) document, especially the Alexa rank requirement. Also, for review purposes it is beneficial to have an English version of the website.

Maybe our [Wiki](https://github.com/2factorauth/twofactorauth/wiki) is good starting point as well.

**Comment by Abubakr077** [comment]
THANK MAN.
