### ISSUE TITLE
Add Hostinger

### ISSUE THREAD

**Issue by tingling-sensation** [2factorauth/twofactorauth#4702]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Hostinger`

* Site URL - `https://www.hostinger.com`

* Does the site support 2FA? - `Yes`

* Documentation URL - 

![](https://user-images.githubusercontent.com/62018979/76943697-701fab80-6908-11ea-939d-0b5415b284c9.png)

![](https://user-images.githubusercontent.com/62018979/76943700-7150d880-6908-11ea-92a3-a7cbec946202.png)

![](https://user-images.githubusercontent.com/62018979/76943701-71e96f00-6908-11ea-9be3-82621ef7cba3.png)

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [x] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [x] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by phallobst** [comment]
Are you sure "Proprietary" is correct? The screenshots mention _Authy_, but this does not necessarily mean that its proprietary protocol is used there, especially since _LastPass_ is shown right next to it. I suspect that _Authy_ was just used as an example for "TOTP" support.

(Maybe we need to clarify this in the issue template.)
