### ISSUE TITLE
Add Woodforest National Bank

### ISSUE THREAD

**Issue by eshattow** [2factorauth/twofactorauth#4703]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Woodforest National Bank`

* Site URL - `https://www.woodforest.com/`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://www.woodforest.com/Personal/Services/Online-Banking/Online-Banking-Security`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [x] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

Looks like the only banking website in the USA that supports generic TOTP and is available to civilians as of this writing. Found this information via comments at (https://krebsonsecurity.com/2018/03/what-is-your-banks-security-banking-on/comment-page-1/)

**Comment by phallobst** [comment]
What about SMS then? On their doc page, there is also a section called "Text Message Authentication":
> Text message authentication allows you to set up your mobile phone number to receive one-time codes when logging into Online Services (...)

**Comment by eshattow** [comment]
> What about SMS then? ...

Yes also SMS.
