### ISSUE TITLE
Comixology

### ISSUE THREAD

**Issue by Ptackman** [2factorauth/twofactorauth#471]
Comixology (http://comixology.com) does not appear to directly support two factor authentication on the website. The newest revision to the iOS app removed in-app purchases so one is required to purchase comics on their website. I did not see an option to set up two-factor authentication directly on the site. They do appear to take Paypal as an option though.

**Comment by Ptackman** [comment]
Sorry, I am new at this.

**Comment by mxxcon** [comment]
What category would you put it in? Retail or Other?
