### ISSUE TITLE
Update H&R Block

### ISSUE THREAD

**Issue by bmkaiser** [2factorauth/twofactorauth#4723]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - `H&R Block`

* Site URL - `https://www.hrblock.com/`

* Site category - `Finance`

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [x] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###

H&R Block now supports SMS for 2FA:

<img width="490" alt="Screen Shot 2020-04-18 at 12 05 59 PM" src="https://user-images.githubusercontent.com/5446414/79642889-fa5c6900-816d-11ea-9255-ca0b4f2e5f41.png">

**Comment by jamcat22** [comment]
Thanks for letting us know @bmkaiser! The change should be visible on the site shortly. 👍
