### ISSUE TITLE
Freeze column headers when scrolling down page

### ISSUE THREAD

**Issue by vmm20** [2factorauth/twofactorauth#4745]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###
When I'm scrolling down the page, I sometimes forget the order in which the check marks display.  I have to hover over the check mark to get it to remind me which type of authentication it is indicating.  It would be nice if the column headers (i.e., the types of 2FA) would stick to the top of the page as I scroll down the page (like the "Freeze Panes" feature in Microsoft Excel).  That way it would be easier to see the type of 2FA to which each check mark is referring.

**Comment by phallobst** [comment]
This already worked in Firefox, but not in Chrome (or Chromium-based browsers). A little tweak to the CSS fixes this problem.
