### ISSUE TITLE
Add PKO BP

### ISSUE THREAD

**Issue by sandrzejewskipl** [2factorauth/twofactorauth#4750]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `PKO BP`

* Site URL - `Bank website - https://pkobp.pl
Electronic banking where is 2FA - https://ipko.pl`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://iko.pkobp.pl/funkcje/mobilna-autoryzacja/`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [ ] TOTP (RFC-6238, Google Authenticator)
  - [x] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [x] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [x] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

This is the most popular bank in Poland.
Software 2FA - bank app IKO

**Comment by kkhhaalleedd** [comment]
@szymonx20

**Comment by sandrzejewskipl** [comment]
> @szymonx20

what?
