### ISSUE TITLE
Add [www.specsypieslive.com]

### ISSUE THREAD

**Issue by nileshterabaap** [2factorauth/twofactorauth#4754]
- [ ] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [ ] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request by [SPECSYPIES](https://www.specsypieslive.com)

### Information about the site to be added that supports 2FA: ###

* Site name - ``

* Site URL - ``

* Does the site support 2FA? - `Yes`

* Documentation URL - ``

### Information about what methods of 2FA the site supports: ###

* Software:
  - [ ] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [ ] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [ ] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [ ] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by Carlgo11** [comment]
@nileshterabaap please submit a properly formatted issue with actual information.

**Comment by jamcat22** [comment]
@nileshterabaap additionally, it appears that the website you're referencing has an [Alexa ranking of 7,611,008](https://www.alexa.com/siteinfo/specsypieslive.com).

As the Issue Template states, sites must be ranked within the top 200,000 sites on Alexa, or have a substantial social media following.

If the site you're requesting to be added meets the criteria in the future and you update your issue to be properly formatted with the requested information, we'll reconsider your request.

For now, I'm closing this issue.

Thanks,
Jacob
