### ISSUE TITLE
Update Allegro.pl - sotware TFA is available

### ISSUE THREAD

**Issue by stivo85** [2factorauth/twofactorauth#4759]
Hi.

Allegro.pl has software TFA. Maybe it's not described at their pages (or I didn't find it), but in account settings there is option to turn on using codes from any app.

- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - `Allegro.pl`

* Site URL - `https://allegro.pl`

* Site category - `Retail`

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [x] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###
Allegro supports now TFA with external app and/or SMS
Settings are at: https://allegro.pl/moje-allegro/moje-konto/dwustopniowe-logowanie
![image](https://user-images.githubusercontent.com/64167026/81216843-e6bd5900-8fdb-11ea-9af1-24be430652e7.png)

**Comment by Carlgo11** [comment]
It looks like you removed a couple of lines of required information. Here’s the complete template of information we need:
```
<!-- Before submitting this issue, please update the title to include the name of the site to be updated.
Submit a single issue for each site to be updated.

In Markdown, checkboxes work like this:
- [ ] Unchecked box.
- [x] Checked box.

Check the box below before submitting your issue to verify that you have already checked for duplicate open issues and pull requests relating to your request. -->

- [ ] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###
<!-- Name of the site, as currently listed on twofactorauth.org -->
* Site name - ``

<!-- Link to the main page of the site, as currently listed on twofactorauth.org -->
* Site URL - ``

<!-- Category of the site, as currently listed on twofactorauth.org -->
* Site category - ``

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [ ] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###
<!-- List the specific changes to the site entry that should be made below.
For example, if a site now supports 2FA, list the methods of 2FA the site now supports.
Please include any supporting documentation for the changes as well, such as official documentation links or announcement blog posts.
If no public-facing documentation is available, please include screenshots of the changes, redacting any personal information. -->
```

Please provide all the required information. Especially the information asked for in the last paragraph.

**Comment by stivo85** [comment]
Sorry, didn't know that whole information is required - other Issues doesn't have it at all.
I've updated my Issue.

**Comment by phallobst** [comment]
According to https://www.issms2fasecure.com/details?name=allegro the SMS method is mandatory (as a backup). Can you confirm or deny that?

**Comment by stivo85** [comment]
SMS authentication is basic method. So user can activate two options:
- SMS method
- SMS + application method

Cannot choose only external app, but I am using application and don't remeber when I've to use SMS last time.
