### ISSUE TITLE
Recent change section

### ISSUE THREAD

**Issue by SinginLow** [2factorauth/twofactorauth#4761]
- [x ] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

I'd like to request a recent change category. I check this website periodically but it's hard to keep track of which of the dozens of websites I use have added or removed security features.

**Comment by Carlgo11** [comment]
Duplicate of #2159, #3603, #1870, #519
