### ISSUE TITLE
Accepting email address as password too

### ISSUE THREAD

**Issue by szepeviktor** [2factorauth/twofactorauth#4763]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

How about adding a column whether the site accepts registrations with password===email?

**Comment by Carlgo11** [comment]
@szepeviktor so what would be the other auth factor?

**Comment by szepeviktor** [comment]
You would be surprised that majority of the sites do not dare to hold back customers with a message like "Please enter a password different from your email address".

Many-many [big companies](https://www.instagram.com/) are brave enough to accept password===email.

**Comment by phallobst** [comment]
Given that the most common password is still "password", we have all kinds of problems in that area. I think providing information about the password security concerns of websites is way beyond the scope of this project.

**Comment by szepeviktor** [comment]
I agree.

2FA is not luxury.

**Comment by Carlgo11** [comment]
Oh now I get you. No, passwords are beyond the scope of this site. We list authentication factors used alongside passwords but we don't list anything about passwords.
