### ISSUE TITLE
Add postale.io

### ISSUE THREAD

**Issue by emmainthesky** [2factorauth/twofactorauth#4773]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that does not support 2FA: ###

* Site name - `postale.io`

* Site URL - `https://postale.io`

* Does the site support 2FA? - `No`

### Information about the site's contact information: ###

support@postale.io

* Site language - `English`

* Twitter username - ``

* Facebook link - ``

* Email address - `support@postale.io`

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by phallobst** [comment]
The current Alexa rank is over 740k, and I don't see a "substantial social media following" either. This issue will therefore be closed, but you are welcome to re-open it once the rank drops below 200k.

**Comment by emmainthesky** [comment]
Thank you for that feedback! Apologies, I didn't pay attention to the Alexa rank. Will re-open when it drops under 200k. :)
