### ISSUE TITLE
Add [NordVPN Teams]

### ISSUE THREAD

**Issue by acordiandude** [2factorauth/twofactorauth#4774]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that does not support 2FA: ###

* Site name - ``NordVPN Teams

* Site URL - ``https://nordvpnteams.com/

* Does the site support 2FA? - `No`

### Information about the site's contact information: ###

* Site language - `English`

* Twitter username - ``@nordvpnteams 

* Facebook link - ``https://www.facebook.com/NordVPNTeams/

* Email address - ``support@nordvpnteams.com

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by phallobst** [comment]
The home page says 2FA is "coming soon". Is worth waiting before we add the entry?

**Comment by acordiandude** [comment]
The 2FA is now live

**Comment by acordiandude** [comment]
> The home page says 2FA is "coming soon". Is worth waiting before we add the entry?

The 2FA is now live on their website

**Comment by phallobst** [comment]
Is there any official documentation available regarding 2FA? Or can you provide screenshots of the set-up process?

**Comment by acordiandude** [comment]
I don't know about documentation, but I can show you the screenshots I made:

<img width="532" alt="Screenshot1" src="https://user-images.githubusercontent.com/59089738/89415766-0841f400-d735-11ea-9aab-bb4b07f55e1a.png">
ng…]()
<img width="480" alt="Screenshot2" src="https://user-images.githubusercontent.com/59089738/89415812-1859d380-d735-11ea-9f03-441d236c3cec.png">
<img width="482" alt="Screenshot3" src="https://user-images.githubusercontent.com/59089738/89415843-214aa500-d735-11ea-90b8-7c214235f197.png">

**Comment by phallobst** [comment]
I suppose this was closed by mistake - reopening...
