### ISSUE TITLE
Services that do not allow hardware/software token as a sole, independent factor

### ISSUE THREAD

**Issue by identigral** [2factorauth/twofactorauth#4786]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

A service requires an email or SMS as an authentication factor. At some point they learn about various attack vectors and they add a hardware/software token as an option. Unfortunately they decide that for ease of use they'll require email or SMS as a factor (they can't be removed) with hw/sw token being an alternative. That's a half-measure in that an attacker can still take over the victim's account via your favorite email or SMS vector even if they have the token configured as an option. 

Our suggestion is to improve the UX so that it shows partial support. The Notes is a weaker option, kinda like saying "oh you should have read the instructions on a fire extinguisher" when your house burned down.

**Comment by phallobst** [comment]
Duplicate to #4308
