### ISSUE TITLE
Update Surfshark

### ISSUE THREAD

**Issue by grrrrr** [2factorauth/twofactorauth#4790]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - `Surfshark`

* Site URL - `https://surfshark.com/`

* Site category - `Security`

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [ ] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [x] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###

The site is currently listed under security but is a VPN provider, as such, it would be better to put it into the `VPN Section`

**Comment by saratchandrakarumuri** [comment]
Since this is a VPN provider, shouldn't this fall under `VPN Providers` category, rather than security?

**Comment by phallobst** [comment]
> Since this is a VPN provider, shouldn't this fall under `VPN Providers` category, rather than security?

This is exactly the purpose of this issue.
