### ISSUE TITLE
Lazy-load images below the fold?

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#480]
As of this writing twofactorauth.org has 229 page resources loaded (virtually) every time the page loaded. Obviously vast majority of them are site logos.
Here's what it looks like http://www.webpagetest.org/result/140507_Y0_SZW/ Nasty looking stairs.

Perhaps this situation can be improved using some lazy-load javascript that downloads images only once they enter the viewport.

**Comment by jdavis** [comment]
I agree; lazy loading would definitely be good.

Another possibility is that we could create a tool to dynamically put all the images onto a single image, then just do sprites.

We could still leave the images in the folders they are now, we'd just make the Jekyll side a bit smarter.

**Comment by mxxcon** [comment]
I think in this site's use-case spriting images might be detrimental in the long term.
You are going to generate a sprite out of ~200+ images, any change/addition/deletion will invalidate and re-download the whole sprite+new css. Where as if images remain independent change in 1 image file will not affect already cached 200 other images.

**Comment by jdavis** [comment]
Caching isn't really on my list of concerns for the site. Plus we could break it up by category.

**Comment by mxxcon** [comment]
Jekyll can generate static pages, but how would you automate sprite creation? afaik github pages is purely static, you can't run php/python/anything else there, right?

**Comment by jdavis** [comment]
Yup, I think we could create a script in Python or something that creates the sprite. It'd have to be ran every now and then, but even if it was ran after 5 sites or so have been changed/added, it'd still cut down on loading.

**Comment by Carlgo11** [comment]
Is this done?

**Comment by jdavis** [comment]
Nope, it is still something that we would like to do. Or at least be smarter about image loading in some way.

**Comment by mxxcon** [comment]
Is it possible to at least reorder css and js? Something like what this thing recommend https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftwofactorauth.org%2F&tab=desktop

**Comment by mckramer** [comment]
Re: sprites.  Since Jekyll is ruby, you might find it easiest to use [Compass](http://compass-style.org/reference/compass/utilities/sprites/).  You can simply compile the logos into a sprite and check it in.

And Jekyll does [include basic support for SASS and CoffeeScript](http://jekyllrb.com/docs/assets/).  If you are familiar with how Rails handles assets, then you might be interested in the [jekyll-assets](http://ixti.net/jekyll-assets/) plugin.

**Comment by jdavis** [comment]
Cool, we'll have to look into Compass. Thanks for that info, @mckramer

**Comment by RichJeanes** [comment]
It would seem that @psgs has handled this with fa77b25d9151d61e8f38abff695e05a9d4fae946
