### ISSUE TITLE
Hosting Plus

### ISSUE THREAD

**Issue by khkz** [2factorauth/twofactorauth#4812]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Hosting Plus`

* Site URL - `https://www.hostingplus.cl`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://clientes.hostingplus.lat/knowledgebase/33/Autenticacion-de-2-factores.html`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [x] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

our sites https://www.hostingplus.com.co - https://www.hostingplus.pe - https://www.hostingplus.com.ar - https://www.hostingplus.mx - https://www.hostingplus.com.es 
all included 2FA
Thank You!

**Comment by Carlgo11** [comment]
Unfortunately as your sites are ranked above 200K on Alexa and without any substantial social media following I'm afraid it doesn't meet our site criteria.
