### ISSUE TITLE
Add Hi-Rez Studios

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#4817]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###
* Site name - `Hi-Rez Studios`

* Site URL - `https://www.hirezstudios.com/`

* Does the site support 2FA? - `Yes`

* Documentation URL - `-`

![image](https://user-images.githubusercontent.com/8037790/85945081-a4f5c280-b93b-11ea-8926-14e9a2e29a87.png)

![image](https://user-images.githubusercontent.com/8037790/85945122-dd959c00-b93b-11ea-9277-a8ea012f26a4.png)

### Information about what methods of 2FA the site supports: ###

* Software:
  - [ ] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [x] SMS tokens
- [x] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
The rank is **#41,384**
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###
* I contacted the support of Hi-Rez Studios and requested to add 2FA via TOTP (RFC-6238, Google Authenticator)
* The category in the Two Factor Auth List would be **Gaming** (maybe you add a "Category" to this form)

**Comment by ne1z06** [comment]
Site name - Hi-Rez Studios

    Site URL - https://www.hirezstudios.com/

**Comment by OLLI-S** [comment]
@kmpoppe Thank you for adding this site!
