### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by rugk** [2factorauth/twofactorauth#4845]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

The website does not seem to list anything and the search does not work, i.e. everything is broken.

**Bug reproduction:**

Visit website. (maybe only in Firefox? Maybe some add-on issue? Dunno?)

![grafik](https://user-images.githubusercontent.com/11966684/87176686-beebb980-c2da-11ea-928f-ce0da7062f1f.png)

**Impacted devices:**

desktop, Firefox 78.0.1

**Expected behavior:**

I guess the search should work, at least.

**Additional information:**

I've tried to disable some blocking add-ons (although they report nothing as found) 

console:
```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf moz-extension://af8710d9-628a-45c2-9bff-89fe3c92d126/resources/fontawesome/5.13.1/css/all.min.css. (Grund: CORS-Anfrage war nicht http).
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css. (Grund: CORS-Anschlag schlug fehl).
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf moz-extension://af8710d9-628a-45c2-9bff-89fe3c92d126/resources/jquery/3.5.1/jquery.min.jsm. (Grund: CORS-Anfrage war nicht http).
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js. (Grund: CORS-Anschlag schlug fehl).
Keine der "sha512"-Hashes im "integrity"-Attribut stimmen mit dem Inhalt der Subressource überein. twofactorauth.org
Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
    jQueryDetection https://twofactorauth.org/js/bootstrap.min.js:5
    <anonymous> https://twofactorauth.org/js/bootstrap.min.js:5
    <anonymous> https://twofactorauth.org/js/bootstrap.min.js:5
    <anonymous> https://twofactorauth.org/js/bootstrap.min.js:5
bootstrap.min.js:5:3633
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://twofactorauth.org/js/popup.js:1
popup.js:1:1
Uncaught ReferenceError: $ is not defined
    <anonymous> https://twofactorauth.org/js/main.js:1
main.js:1:1
Uncaught ReferenceError: $ is not defined
    <anonymous> https://twofactorauth.org/js/social-media.js:1
social-media.js:1:1
Uncaught ReferenceError: $ is not defined
    <anonymous> https://twofactorauth.org/js/search.js:1
search.js:1:1
```

**Comment by Carlgo11** [comment]
@rugk If you go to settings>Help>Restart with Add-ons disabled... does the site look normal then?
From looking at your console log it seems like something (possibly an add-on) tries to load some of our dependencies as add-on files instead of from https.

**Comment by rugk** [comment]
Tested in a new profile and it works there.

Seems to be LocalCDN causing this, if I disable it for the site, it works.

Opened, 
https://codeberg.org/nobody/LocalCDN/issues/56
but it seems you use [strict SOP](https://codeberg.org/nobody/LocalCDN/wiki/Broken-JavaScript-or-CSS-on-some-websites), which is causing this.

And it is only one file??! :cry: 

Also it's a font file. It's one request to `https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto:300|Spartan:500&display=swap` that breaks the site.
Can't your site work without that font and fallback to some fallback font??

**Comment by Carlgo11** [comment]
We use SRI on all external resources. These are: jets.js, jQuery, lazyload & Font Awesome. The request to Google Fonts doesn't use SRI as there's no proper versioning available (content might change suddenly without any warning).

#4844 changes the default fonts so if you don't want to use Google Fonts and don't have the fonts locally (like I do) then that PR should probably help you.

**Comment by Carlgo11** [comment]
Other than that I'm afraid I can't help you.
You're making yourself an extreme edge case by using LocalCDN and blocking any other CDN requests. We use SRI to help prevent the kinds of injections that LocalCDN does as it's mostly just used for nefarious reasons on the web.

Also, if you're using LocalCDN for anti-fingerprinting I'm afraid you're just making it easier to fingerprint you 😄

**Comment by rugk** [comment]
No, this is not about SRI, AFAIK. SRI should be fine, Local CDN can deal with that and basically also does not modify the content, so everything should be fine. (SRI hashes should match)

Local CDN is mostly just for not allowing tracking by third-parties and serving files… well… locally…

See https://codeberg.org/nobody/LocalCDN/wiki/Broken-JavaScript-or-CSS-on-some-websites. It's some kind of "strict" SOP that produces CORS errors. (also did not know there are multiple ones?? Don't what the Local CDN makers want to tell me there… at least there is a bugzilla report for this. _if_ this is the issue.)

https://github.com/2factorauth/twofactorauth/pull/4844 looks good, too.

**Comment by Carlgo11** [comment]
Probably something that Cloudflare handles then. Not sure if it's possible for us to disable it but then agian, it's a security feature so I'm not really sure if it's wise to even do so.

And regarding the tracking. If I have 1M clients requesting the files from the CDN and one client injecting their own CDN requests. Which group do you think is the easiest to track? 😛
See https://panopticlick.eff.org/ and I'd bet you have a unique fingerprint
