### ISSUE TITLE
HOTP

### ISSUE THREAD

**Issue by szepeviktor** [2factorauth/twofactorauth#4868]
Hello!

Are there sites on the internet using HOTP?
Do you list HOTP as a feature?

**Comment by Carlgo11** [comment]
Hello @szepeviktor,
Yes, sites using HOTP are marked as supporting miscellaneous hardware 2FA. We don't have a specific HOTP list.

**Comment by szepeviktor** [comment]
> We don't have a specific HOTP list.

Thank you for making it clear that there is no 2FA method field.

**Comment by szepeviktor** [comment]
@Carlgo11 

```yaml
    tfa:
      - totp
```

There **is** a 2FA method field.

Could it be that none of the listed companies provide the HOTP method??

**Comment by Carlgo11** [comment]
Yes it's possible to add but as we don't currently track it, someone would have to manually add the tag to each site that support it.
Furthermore you're the first one to ask for this and so it seems like the demand for this data point is really low.
