### ISSUE TITLE
twitter SMS doesnt work german d1 network (t-mobile)

### ISSUE THREAD

**Issue by Daij-Djan** [2factorauth/twofactorauth#49]
twitter SMS doesnt work german d1 network (t-mobile)

**Comment by victorhaggqvist** [comment]
Not in Sweden with Tele2 as carrier either.

I think there would be a good idea to have an icon for like partially supported or something like that.

**Comment by mpdavis** [comment]
Is this an issue with Twitter's implementation or with the carriers?

**Comment by ryanralph** [comment]
Twitter must be doing some sort of partnership with major telco's in different areas. My provider isn't supported in Australia. 

This is not a problem with this repo, it's a problem with twitter's implementation.

**Comment by jdavis** [comment]
Hmm. I can imagine it would be helpful to show on the website. But I just feel that the percentage of users it affects is small enough that these little discrepancies will be hard to address.

Regardless, Twitter still does have the code generation in the Twitter app.

I'm closing this for now.

**Comment by victorhaggqvist** [comment]
About the SMS thing in general, the case is that some of those might just work in US. As far as I know it depends more on the SMS service provider that a particular site/sevice are using to deliver the text, but I might be wrong here.

If and how that should be presented here is another question.
