### ISSUE TITLE
Add Panther

### ISSUE THREAD

**Issue by kartikeypan** [2factorauth/twofactorauth#4921]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Panther Labs`

* Site URL - `https://runpanther.io`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://docs.runpanther.io/`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by Carlgo11** [comment]
@kartikeypan The documentation page you linked to doesn't contain any info of how to set up 2FA on runpanther.io.
Could you please link to a more specific URI?

**Comment by kartikeypan** [comment]
@Carlgo11 Sure. Allow me some time please and I'll get back to you with further details on setting up 2FA in Panther. Appreciate your patience.

Thanks!

**Comment by Carlgo11** [comment]
@kartikeypan You have 5 seconds! 🤪

Just post it here when you find it. Otherwise attach screenshots of the 2FA setup/login process with any PII blurred or cropped out. 😉

**Comment by kartikeypan** [comment]
@Carlgo11 You're very kind! Thank you.

I've attached the 2FA setup/login process here with the screenshots. Let me know if this helps?

Step 1: When logging into Panther for the first time, you will see the following:

![image](https://user-images.githubusercontent.com/58938775/92390243-1e7a1000-f138-11ea-887b-0f690b7d9dce.png)

Step 2: Now, open the Duo app and click on the '+' sign as shown in the screenshot below. This will open your camera. Point the camera to the screen and target the “Section to Scan”.

![image](https://user-images.githubusercontent.com/58938775/92390488-90eaf000-f138-11ea-8e66-71ca71d2e794.png)

Step 3: Duo will show the following. Now, copy and paste this into the form under the “Section to Scan”. 

![image](https://user-images.githubusercontent.com/58938775/92390732-14a4dc80-f139-11ea-9d75-8c6a551ae3df.png)

Note: Every time you log in from now on, you need to use Duo and copy and paste the Code (scanning is only required 1 time).

**Comment by phallobst** [comment]
I took the liberty to uncheck the "Proprietary" marker, since you can use any kind of TOTP software here - _Duo_ just happens to be one of them in this case.

**Comment by kartikeypan** [comment]
@phallobst sounds good, thanks!
