### ISSUE TITLE
Broken Twitter post button

### ISSUE THREAD

**Issue by hassankhan** [2factorauth/twofactorauth#4935]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

When clicking the 'Post to Twitter' button for a service that doesn't currently support 2FA, the resulting Twitter post only contains the twofactorauth.org URL.

**Bug reproduction:**

Go to twofactorauth.org and click on any 'Post to Twitter' button for a service that doesn't support 2FA.

**Impacted devices:**

Can reproduce on macOS Firefox and iOS Safari.

**Expected behavior:**

A Twitter post should autopopulate with the following message:

```
Security is important, @GameFly. We'd like it if you supported two factor auth. https://twofactorauth.org #SupportTwoFactorAuth 
```

**Additional information:**

The issue is caused by incorrect URL encoding.

The URL currently looks like this:
```
https://twitter.com/intent/tweet?url=https%3A%2F%2Ftwofactorauth.org&amp%3Bhashtags=SupportTwoFactorAuth&amp%3Btext=Security%20is%20important%2C%20%40GameFly.%20We%27d%20like%20it%20if%20you%20supported%20two%20factor%20auth.
```

In the above, the `&` meant to denote a new parameter in the URL query is being url-encoded, which then leads to the issue. A fixed version of the URL would be:

```
https://twitter.com/intent/tweet?url=https%3A%2F%2Ftwofactorauth.org&hashtags=SupportTwoFactorAuth&text=Security%20is%20important%2C%20%40GameFly.%20We%27d%20like%20it%20if%20you%20supported%20two%20factor%20auth.
```

**Comment by jamcat22** [comment]
Verified fixed after deploying #4938 and clearing edge cache.

Thanks for the bug report @hassankhan!
