### ISSUE TITLE
Update realvnc.com - "help" subdomain does not support tfa

### ISSUE THREAD

**Issue by chamaelion** [2factorauth/twofactorauth#4945]
twofactorauth correctly identifies realvnc.com as supporting tfa, however this does not flow through to it's support subdomain, which requires separate login credentials to it's main domain.

subdomain wihtout tfa - help.realvnc.com

**Comment by Carlgo11** [comment]
Our listing is for realvnc.com not help.realvnc.com. We don't list zendesk portals on twofactorauth.org
