### ISSUE TITLE
Automatically compress images

### ISSUE THREAD

**Issue by hassankhan** [2factorauth/twofactorauth#4948]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

It would be nice if PRs adding new icons were automatically compressed, thus saving both the contributor and reviewer's time. This can be achieved by adding a [GitHub action](https://github.com/marketplace/actions/image-actions).

**Comment by phallobst** [comment]
The "TinyPNG" service performs a _lossy_ transformation, so it's probably best to visually check its result. This might be hard to do with an automatic GitHub action. Also you may not want to compress the icon twice.

I think it's time to switch to SVG anyway... :wink:

**Comment by hassankhan** [comment]
> I think it's time to switch to SVG anyway... 😉

@phallobst Amen to that 😄 should we create a new issue for it?
