### ISSUE TITLE
Use SVG logos

### ISSUE THREAD

**Issue by hassankhan** [2factorauth/twofactorauth#4950]
- [X] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

It would be advantageous to use SVG versions of logos wherever possible because they can be scaled infinitely.

As discussed(/mentioned?) in #4948

**Comment by Carlgo11** [comment]
There's already partial support for SVG files and full support is on the road map for v3.1
