### ISSUE TITLE
Add HostingPlus LAT

### ISSUE THREAD

**Issue by khkz** [2factorauth/twofactorauth#4955]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [ ] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `HostingPlus LAT`

* Site URL - `https://www.hostingplus.lat`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://clientes.hostingplus.lat/knowledgebase/33/Autenticacion-de-2-factores.html`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [x] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by phallobst** [comment]
The documentation at the given URL mentions _Google Authenticator_ and _Duo_. Is the proprietary protocol of _Duo_ used there, or does it use regular TOTP as well?

Also, there is no hint of 2FA via email. If they do use it: Do you have further information, or can you provide screenshots (without personal information)?

**Comment by khkz** [comment]
HostingPlus use a TOTP. 

And not use Email Tokens, I was wrong to add it

**Comment by khkz** [comment]
<img width="1219" alt="Captura de Pantalla 2020-09-21 a la(s) 13 02 05" src="https://user-images.githubusercontent.com/67115613/93791884-2abb9e00-fc0b-11ea-9e04-7e3090b4673a.png">
<img width="1230" alt="Captura de Pantalla 2020-09-21 a la(s) 13 02 17" src="https://user-images.githubusercontent.com/67115613/93791895-2ee7bb80-fc0b-11ea-8ad7-33ba7967f8cc.png">
<img width="1193" alt="Captura de Pantalla 2020-09-21 a la(s) 13 02 41" src="https://user-images.githubusercontent.com/67115613/93791915-34450600-fc0b-11ea-85dc-d247345bf02d.png">

**Comment by ApCoder123** [comment]
Closing, as site is outside of the Alexa top 200k, so is not eligible to be added based on our site requirements.
