### ISSUE TITLE
Show worldwide 2FA support

### ISSUE THREAD

**Issue by codedit** [2factorauth/twofactorauth#498]
Various companies providing 2FA only provide the service to a limited amount of countries. This mainly applies to SMS 2FA. Examples are Twitter and Apple. Perhaps there could be an additional indicator to indicate whether the service offers 2FA to worldwide customers or not.

**Comment by mxxcon** [comment]
I guess that's related to #241

**Comment by jdavis** [comment]
I'm closing in favor of the #241 issue. Thanks for the concern and support though.

**Comment by erintiransom** [comment]
And eBay + PayPal
