### ISSUE TITLE
Update LastPass

### ISSUE THREAD

**Issue by billypoke** [2factorauth/twofactorauth#5034]
- [X] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - `LastPass`

* Site URL - `https://www.lastpass.com/`

* Site category - `Identity Management`

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [X] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [X] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###

There are two sets of docs for Admins and Users of the software with different available options as seen here:
https://support.logmeininc.com/lastpass/help/enable-multifactor-authentication-admins-lp010035
https://support.logmeininc.com/lastpass/help/enable-multifactor-authentication-lp010002

Is there a way to add multiple doc links? I'm going to initially update using the user link with an exception text referring to the enterprise options

**Comment by billypoke** [comment]
@Carlgo11 am I doing this wrong? Is the update info supposed to go in the pull request containing the changes? Or is the update issue template only for requesting someone else update the site info?

**Comment by Carlgo11** [comment]
@billypoke yeah issues aren't needed if a PR is available already. We mostly just use issues for people who don't know how to create PRs 😉

**Comment by billypoke** [comment]
👍 awesome, sorry for the duplicate.

**Comment by Carlgo11** [comment]
No worries. Thanks for the PR 🙂
