### ISSUE TITLE
Automate deployments with TravisCI

### ISSUE THREAD

**Issue by philipithomas** [2factorauth/twofactorauth#511]
I notice that merging to master didn't deploy changes to twofactorauth.org. It's fairly straightforward to set up - here are how I do it using CircleCI for my jekyll site: 

https://github.com/philipithomas/www.philipithomas.com/blob/master/deploy.sh
https://github.com/philipithomas/www.philipithomas.com/blob/master/deploy.sh

It would be fairly straightforward to set up deployments of the master branch to your server through RSync or a gem. 

If you can post details about your server setup we could write some ERB and you could plug the api / ssh keys into Travis.

**Comment by jdavis** [comment]
Hey again @philipithomas!

We are actually using GitHub Pages to host the site. So all of contents of the site live in the `gh-pages` branch. It is almost always an exact copy of the `master` branch.

Issue #457 talked about this as well but here was my reply:

> The site is actually being ran on GitHub Pages. So in order to update the site, I just need to update the gh-pages branch. I've been using master as the sort of development and then merging it onto gh-pages when enough has been changed.
> 
> Whenever I update the site, I pull master, run Jekyll, look things over, and update gh-pages. I do it to make sure there are no breaking commits before updating the site.
> 
> I totally understand the want to automate things. If I was using anything but GitHub Pages (like deploying using FTP or something), it'd drive me insane and I would already have a solution.

**Comment by jdavis** [comment]
Since we already use TravisCI and don't have to do anything for  deploying beyond merging into `gh-pages`, I'm closing this =]
