### ISSUE TITLE
Update TD - Canadian branding

### ISSUE THREAD

**Issue by mmomjian** [2factorauth/twofactorauth#5119]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - TD Canada Trust + TD Waterhouse

* Site URL - https://www.tdcanadatrust.com/ + https://www.tdwaterhouse.ca/

* Site category - Banking + Investing

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [ ] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [x] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [x] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###

It seems that the TD Canada Trust and TD Waterhouse domains now redirect to pages on https://td.com. Unsure what to do but I assume they should maybe be included in the existing td.com entry and the Canada region added to that entry?

**Comment by phallobst** [comment]
That seems reasonable to me. :+1:

**Comment by mmomjian** [comment]
I have created a draft PR, I'm not sure if I should wait for a certain number of people to agree with this issue or propose the change in the PR.
