### ISSUE TITLE
Add a category for 'Music' services

### ISSUE THREAD

**Issue by Ibby** [2factorauth/twofactorauth#512]
Add a category for 'Music' services so we can add Spotify, Soundcloud, etc.

**Comment by Ibby** [comment]
Not sure about Spotify but SoundCloud should be definitely included as lots of Musicians post their work in there, they could deal with intruders deleting their content/tracks.

**Comment by jdavis** [comment]
That's a good point. Plus there is Rdio as well. Let me ponder on this for a bit and do some research.  If anything, maybe Spotify/Rdio aren't much of a threat to be compromised but I can see the point with SoundCloud.

But yeah, I'll look into this and see.

**Comment by jdavis** [comment]
I think a Music section would be fine with SoundCloud being the first to be added. If someone wants to do that, awesome.

**Comment by jdavis** [comment]
Closed with @dsoegijono's commits.
