### ISSUE TITLE
Add 'CloudApp'

### ISSUE THREAD

**Issue by Ibby** [2factorauth/twofactorauth#514]
name: CloudApp
url: http://www.getcloudapp.com/
twitter: cloudapp
img: ![cloudapp icon 32x32](https://cloud.githubusercontent.com/assets/394316/3066997/88684b60-e27d-11e3-8b79-76c8de5a24a3.png)
tfa: No

**Comment by mxxcon** [comment]
@Ibby Are you planning to make actual commits or you don't know how to do that?

**Comment by Ibby** [comment]
hey @mxxcon unfortunately I don't know how to do that so I was told by Josh that I should add them to the 'Issues' section.
