### ISSUE TITLE
Update Zoom - additional information on limitations regarding 2FA

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#5143]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - `Zoom`

* Site URL - `https://www.zoom.us/`

* Site category - `Communication`

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [ ] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [x] Other (please describe below).

### Information about how the site entry should be updated: ###

Although Zoom currently supports 2FA, it appears that 2FA is solely available for those who login via password. In their blog [post](https://blog.zoom.us/secure-your-zoom-account-with-two-factor-authentication/) about the introduction of 2FA, the following statement (under `How to enable Zoom’s 2FA`) mentions that 2FA is for password-based logins: `To enable Zoom’s 2FA at the account-level for password-based authentication, account admins should take the following steps:`

I have enabled 2FA on Zoom but could not get the prompt for setup to appear, because my sole login for Zoom is via Google. I'm not sure if something else is a problem but I do believe 2FA cannot be used for sign-in methods other than password-based.

**Comment by Carlgo11** [comment]
Oauth via a third party will nearly always result in the first party not offering 2FA for the user. That's an expected behavior when choosing a third party authentication option thus not an exception.

**Comment by ghost** [comment]
Understood.
