### ISSUE TITLE
Add 'Media Temple'

### ISSUE THREAD

**Issue by Ibby** [2factorauth/twofactorauth#515]
Add Media Temple to the 'Hosting/VPS' list with the following details:

name: Media Temple
url: http://mediatemple.net/
twitter: mediatemple
img: ![mt32x32](https://cloud.githubusercontent.com/assets/394316/3067622/efecb01c-e284-11e3-9045-55ebe08b011a.png)
tfa: No

**Comment by jdavis** [comment]
Would you like to try your new branching abilities to handle this issue, @Ibby? :smile:

**Comment by Ibby** [comment]
Hey @jdavis sure! Thanks for letting me do it :dancers:

**Comment by jamcat22** [comment]
Should this be closed since #518 was merged?

**Comment by jdavis** [comment]
Yes it should, thanks for pointing this out, @jamcat22.
