### ISSUE TITLE
Add column for U2F

### ISSUE THREAD

**Issue by maltfield** [2factorauth/twofactorauth#5169]
- [X] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

Can you please **add a column** to the table that denotes whether or not the service provides **support for U2F**?

### See also

 * https://en.wikipedia.org/wiki/Universal_2nd_Factor
 * https://fidoalliance.org/specifications/

**Comment by mmomjian** [comment]
As seen below, this information is already present in the "hardware token" column. You can search for "U2F" at the top of the page to see only sites with U2F support.

![image](https://user-images.githubusercontent.com/50788000/104645050-8d361f80-567c-11eb-8fab-9d82257ae2f8.png)
