### ISSUE TITLE
Add Sonix

### ISSUE THREAD

**Issue by freshgoods** [2factorauth/twofactorauth#5189]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Sonix`

* Site URL - `https://sonix.ai/`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://help.sonix.ai/en/articles/4188823`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

Updated documentation link to shorter version as suggested.

**Comment by 40504** [comment]
use:  -> Documentation URL - https://help.sonix.ai/en/articles/4188823

instead of: Documentation URL - https://help.sonix.ai/en/articles/4188823-does-sonix-have-two-factor-authentication

**Comment by 40504** [comment]
use this optimezed icon:
![sonix](https://user-images.githubusercontent.com/71176569/105363182-0e049680-5bfc-11eb-8ae8-dadb9798ec8d.png)
