### ISSUE TITLE
Add Discogs

### ISSUE THREAD

**Issue by freshgoods** [2factorauth/twofactorauth#5204]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Discogs`

* Site URL - `https://www.discogs.com/`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://auth.discogs.com/sessions`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

Although they've implemented 2FA, it's located inside the user's account and there's currently no public documentation. The current Documentation URL specified above is where the user can activate 2FA. The URL could be updated if and when documentation becomes available.

**Comment by 40504** [comment]
You must be logged in to access this link "https://auth.discogs.com/sessions", I mean this is not suitable for documentation.
I didn't find 2FA option from user settings. How did you find that link?

<img width="514" alt="1" src="https://user-images.githubusercontent.com/71176569/105781171-590f0880-5f72-11eb-8fbc-b95fef790156.png">
<img width="504" alt="2" src="https://user-images.githubusercontent.com/71176569/105781174-5ad8cc00-5f72-11eb-8737-515a2abc8067.png">

**Comment by freshgoods** [comment]
Yes, I did note in Additional Info that the current documentation URL is only a link to where a logged-in user can set up 2FA.

The way Discogs is rolling out 2FA is not clear to end-users. At some random time, after a user logs in to the site, it will ask to set up 2FA without explanation. I've seen this myself. Alternatively, any user can go directly to the sessions URL above and set it up whenever they want to. That link (which is also used to manage logged-in sessions) has appeared in the Discogs forums, and was also provided to me by Discogs Support. I asked them to document 2FA setup in their help documentation and they've forwarded the request to their product team. I don't expect it to be documented soon though.

**Comment by 40504** [comment]
👍
