### ISSUE TITLE
Fidelity uses Symantec for software token 2FA

### ISSUE THREAD

**Issue by schwit61** [2factorauth/twofactorauth#5227]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the site entry to be updated: ###

* Site name - Fidelity Investments``

* Site URL - https://www.fidelity.com/``

* Site category - investing``

### Information about why the site entry should be updated: ###
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [x] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on twofactorauth.org.
- [ ] Other (please describe below).

### Information about how the site entry should be updated: ###
<!-- List the specific changes to the site entry that should be made below.
Non-proprietary software token option. Symantec VIP
https://www.fidelity.com/security/extra-security-login

**Comment by ApCoder123** [comment]
Hi there,
The entry for Fidelity already lists `proprietary` as a 2FA method, which is what a Software Token like that would be. If you are referring to a Symantec hardware token, `hardware` is also already listed as a 2FA method.
https://github.com/2factorauth/twofactorauth/blob/c7d680263929b9b15f614f4f0c3421dcb43d6237/_data/investing.yml#L93
