### ISSUE TITLE
Add Moqups

### ISSUE THREAD

**Issue by mihaicostin** [2factorauth/twofactorauth#5228]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `Moqups`

* Site URL - `https://moqups.com/`

* Does the site support 2FA? - `Yes`

* Documentation URL - `https://support.moqups.com/hc/en-us/articles/360019781980#account_2FA`

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

https://github.com/mihaicostin/twofactorauth

**Comment by 40504** [comment]
`https://support.moqups.com/hc/en-us/articles/360018866160-Password-Security#TFAuth`
👇
`https://support.moqups.com/hc/en-us/articles/360018866160#TFAuth`

**Comment by mihaicostin** [comment]
documentation link changed in the meantime to https://support.moqups.com/hc/en-us/articles/360019781980#account_2FA  
@40504 I've updated the link in the description and in the fork (if you want to use that)
