### ISSUE TITLE
Please document which sites support enrolling multiple 2FA keys

### ISSUE THREAD

**Issue by joshtriplett** [2factorauth/twofactorauth#5233]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###
I'd like to be able to enroll multiple 2FA keys for the same site, or enroll a hardware 2FA key and a software authenticator. I'd love to see documentation for which sites support this.

**Comment by person1234-ux** [comment]
How would we do this without making the website to cluttered?

**Comment by joshtriplett** [comment]
Personally, I would appreciate seeing this detail within the "hardware token" column, because that's the primary case it affects. Sites supporting only one key could get a mark `ONE`, while sites supporting multiple could get a `MULT`, or similar.

**Comment by phallobst** [comment]
That sounds similar to what https://dongleauth.com is doing with the "Multiple Dongle Support" icon.

**Comment by Carlgo11** [comment]
Yeah I think dongleauth is a better place for that as they only handle hardware key support. 2fa.directory is marketed to a broader audience and displaying too much info will hurt our cause.
