### ISSUE TITLE
Add *.mynetpay.be

### ISSUE THREAD

**Issue by Egregius** [2factorauth/twofactorauth#5236]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###
* Site name - `mynetpay.be`
* Site URL - `https://mynetpay.be`
* Does the site support 2FA? - `Yes`
* Documentation URL - ``

### Information about what methods of 2FA the site supports: ###
* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###
- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [ ] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

User site for a closed user payment system, so no Alexa ranking but critical private information, therefor 2FA enabled.

Issue updated according https://github.com/2factorauth/twofactorauth/issues/3835
There are many subdomains hosted, one for each end client (school, university, business) , all providing 2FA authentication.

**Comment by Carlgo11** [comment]
Hello @Egregius, sorry for the long delay. We had a lot to do around Jan-Feb and your issue must have been forgotten in the process.

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

**Comment by Egregius** [comment]
Hi @Carlgo11 ,

Thanks for the reply. 
On the user profile page there's a button to activate 2FA:
![button](https://user-images.githubusercontent.com/7478797/136529082-d7b96e83-d9be-4878-94eb-b0f203926617.png)

That'll lead them to a page with the QR code and secret:
![save](https://user-images.githubusercontent.com/7478797/136529173-19be1cdc-a7a2-4196-8086-ac10fee64e46.png)

Once filled in they have to enter username/password followed by the TOTP:

![login](https://user-images.githubusercontent.com/7478797/136529547-31307ea7-715d-481a-a90f-e33beb557def.png)

![2FA](https://user-images.githubusercontent.com/7478797/136529566-cd3f4dc9-665e-4f69-8817-c6841aee50f6.png)

Thanks for adding the site!

**Comment by Carlgo11** [comment]
Closing as  SimilarWeb rank is above the maximum threshold. Even though all traffic is done using subdomains the global rank should still function as an indicator.
