### ISSUE TITLE
Godaddy does not support 2FA

### ISSUE THREAD

**Issue by token2** [2factorauth/twofactorauth#525]
Seems like 2FA over SMS is only available for US and Canada.
I do not see it for my account (i am in switzerland)

**Comment by jdavis** [comment]
For this, you can now add a little icon indicating there is a restriction to 2FA. I think adding it to GoDaddy would be the best for this issue.

**Comment by jdavis** [comment]
Closing this as @token2 opened a pull request for this: #576
