### ISSUE TITLE
REST API to Access website enteries from the website!

### ISSUE THREAD

**Issue by afridi26** [2factorauth/twofactorauth#5251]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the feature to be added: ###

Hey, 

I would like to request the REST API feature. It will be awesome to have REST API endpoint to query about specific website whether it support 2FA or Webauthn etc.. Being lazy, I would like to have my own small cmd tool where I can provide a website name, it will get information from this website instead of searching manually so I can check and decide whether to sign up with that website or not.

**Comment by Carlgo11** [comment]
As REST requests practically don’t work on statically served sites it’s not something we can do.
We do however offer a bunch of JSON files. See /api for more info

**Comment by afridi26** [comment]
Thanks, and sorry I missed API.md.

I checked the URIs it is redirecting me to another website!
