### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by waako** [2factorauth/twofactorauth#529]
I've started doing a bit of work on contemplating how to have tables that would be more usable on narrow devices.

Still a complete WIP as needs some more thought, especially the website name and how it is displayed.
Nevertheless here is my branch of work so far https://github.com/waako/twofactorauth/tree/responsivetable

**Comment by mxxcon** [comment]
:+1:
That reminds me, i wanted to bring up this issue a while ago. :sweat_smile:

**Comment by jdavis** [comment]
Yup, I knew about this issue as well but just kept sweeping it under the rug.

Very cool.

I'm taking a look at it now and so far this is what I see (without being on a mobile device):
![screen shot 2014-05-30 at 9 59 20 am](https://cloud.githubusercontent.com/assets/157801/3132033/1799d442-e80b-11e3-9f66-9dd24603dd26.png)

Is this just an error on the non-responsive part? Or do you want to display the table headers in each cell for non-mobile? I'm assuming you only want the headers to show when being displayed on a mobile device.

**Comment by waako** [comment]
Oh yeah, I was just testing in Chrome with iPhone 4 emulation, and totally forgot to hide the header labels in each cell when the table headers aren't hidden.
They would normally hidden, but only show on narrow devices

/me facepalm!)

**Comment by jdavis** [comment]
Ahh, okay. That's what I assumed but I just wanted to be sure.

That's a great idea; I'll be watching it develop. Let us know if you need help, comments, or anything.

**Comment by jdavis** [comment]
Any progress on this, @waako? :smile:

**Comment by waako** [comment]
Holy cow! 2 weeks already?!  
I'll try to do the breakpoints this weekend.

**Comment by jdavis** [comment]
Yeah, time flies, for real.

**Comment by jdavis** [comment]
I'm closing this since #587 is the accompanying pull request.
