### ISSUE TITLE
IFTTT is working on two factor auth please add this to the list.

### ISSUE THREAD

**Issue by captain118** [2factorauth/twofactorauth#534]
https://twitter.com/Appils/status/409318475824631808

**Comment by mxxcon** [comment]
To me "It's on our list for improvement!" is not the same as "we are working on it".
One could say tfa is on every service's wish list...

**Comment by jdavis** [comment]
Yeah, I second @mxxcon. Unless they are actually changing their service to support it, then they should still be "in the red".

**Comment by captain118** [comment]
Ok I didnt see IFTTT on the list at all.  So even if that wasn't proof
enough it would be nice to have it on the list.

Thanks and Have a Good Day,
Kirk McCann
