### ISSUE TITLE
Remove websites with Alexa ranking over 200K

### ISSUE THREAD

**Issue by 40504** [2factorauth/twofactorauth#5382]
A lot of websites without 2fa support, that currently appear in this 2fa.directory, are ranking over 200K. I think it will better to remove them.

**Comment by Carlgo11** [comment]
If a listed site is far from the 200K limit I agree that it should be removed but if it's only a <100K difference it's probably better to leave it be.

**Comment by phallobst** [comment]
@40504 @ApCoder123
You may not want to waste your time and energy on this. We already removed the corresponding entries in a new (currently private) repository.

**Comment by ApCoder123** [comment]
Noted, thanks.
