### ISSUE TITLE
Add San José State University

### ISSUE THREAD

**Issue by 4ujmUW3R** [2factorauth/twofactorauth#5414]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - ``San José State University``

* Site URL - ``https://one.sjsu.edu/``

* Does the site support 2FA? - `Yes`

* Documentation URL - ``https://www.sjsu.edu/it/services/computer-security/duo/``

### Information about what methods of 2FA the site supports: ###

* Software:
  - [ ] TOTP (RFC-6238, Google Authenticator)
  - [x] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to 2fa.directory: ###

- [x] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### Additional information: ###

The service is advertised on this page, and this extends password reset to a longer time period.
https://one.sjsu.edu/

**Comment by person1234-ux** [comment]
don't really see how this could be considered usefull becasue unless you go to the school you aren't going to creating an account for this university. Same reason I wouldn't put my school on there

**Comment by Carlgo11** [comment]
I agree with you @person1234-ux. The Education was intended to list school platforms (Google Classroom, Schoolsoft etc) but nowadays it's filled with individual schools which certainly isn't of use to the general consumer (the goal of this project.)

There might be a need to add this to the exclusion list in the future.

**Comment by phallobst** [comment]
I have to disagree on this one. Many entries are not useful to the general consumer, either because the region doesn't apply to them, or because they don't have an alternative to choose from anyway. I reckon we should not restrict the entries on that basis. If a university website (or any other local institution or service provider) satisfies all criteria, it should go in.
