### ISSUE TITLE
Change Preferred Image Format to SVG?

### ISSUE THREAD

**Issue by ApCoder123** [2factorauth/twofactorauth#5448]
The preferred image format for new icons seems to be SVG based what I have seen, although the CONTRIBUTING.md documentation still states that PNG is the preferred format.

> Use a Nice Icon: The icon must have a resolution of 32x32. PNG is the preferred format. If possible, please also run the image through an optimizing utility such as TinyPNG before committing it to the repo and keep the file to be under 2.5 kB.

My question is whether the preferred image format in the contributing guide be changed to SVG, followed by PNG?

**Comment by Carlgo11** [comment]
Yes SVGs are prefered and we haven't gotten around to changing the guidelines in CONTRIBUTING.md yet. Feel free to open a PR fixing it! 👍
