### ISSUE TITLE
Categories dropdown is not scrollable

### ISSUE THREAD

**Issue by dsoegijono** [2factorauth/twofactorauth#548]
If the Categories drop down is longer than my screen size, and I try to scroll down, it scrolls the page instead of the drop down ([Mac + Chrome](https://cloud.githubusercontent.com/assets/867840/3198592/c8ce3fd2-ed5b-11e3-81d0-b19c143fadee.png), iOS + Safari/Chrome).

**Comment by dsoegijono** [comment]
Was this issue fixed? Categories drop down now seems to scroll with the page.

**Comment by jamcat22** [comment]
Going to go ahead and close this. Tested on Chrome on Windows 8 and Safari/Chrome on iOS 8 and both seemed to work fine.

**Comment by Walkman100** [comment]
Working on Dolphin on Android 4.4.2 which seems to have very little js support
