### ISSUE TITLE
Add bancfirstonline.com

### ISSUE THREAD

**Issue by chyron8472** [2factorauth/twofactorauth#5490]
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `BancFirst of Oklahoma` 

* Site URL - `https://www.bancfirst.bank`
* Site URL - `http://www.bancfirstonline.com`

* Does the site support 2FA? - `Yes`

![image](https://user-images.githubusercontent.com/12549803/113428431-6a262c80-939c-11eb-8940-dc635f96b377.png)
![image](https://user-images.githubusercontent.com/12549803/113428583-ab1e4100-939c-11eb-92b9-4edd437ebd7d.png)
![image](https://user-images.githubusercontent.com/12549803/113429451-2a604480-939e-11eb-9604-cf23020a6979.png)

### Information about what methods of 2FA the site supports: ###

* Software:
  - [x] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [x] SMS tokens
- [x] Email tokens

### Information about the site's eligibility to be added to 2fa.directory: ###

- [ ] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
-- **Site was not quite in Alexa 200K in last 90 days.**
- [ ] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
-- **Was ranked 204,684 on 09 Feb 2021.**
- [x] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

**Comment by 40504** [comment]
Alexa Rank
326,814 In global internet traffic and engagement over the past 90 days

**Comment by chyron8472** [comment]
I read it as: it currently ranks 326,814, but in global internet traffic and engagement over the past 90 days, on 09 Feb 2021 it ranked 204,684. From the graph, it wouldn't appear that 326,814 is the 90-day average, but the rank for this particular day.

**Comment by phallobst** [comment]
Neither "bancfirst.bank" nor "bancfirstonline.com" are within the top 200K right now. This issue will therefore be closed, but you are welcome to re-open it once the rank drops below that limit.
