### ISSUE TITLE
1and1 "Looking into" 2FA 

### ISSUE THREAD

**Issue by CoelacanthsKill** [2factorauth/twofactorauth#551]
https://twitter.com/1and1help/status/474616659567984640

**Comment by mxxcon** [comment]
ya, "looking into this" feels like a non-answer answer.. It's not like they said they are definitely working on it.. just looking into it. :confused:

**Comment by jdavis** [comment]
This is similar to #534. Unless they are updating/changing their service, this is kind of response is just to satisfy customers.

Thanks for the info though.
