### ISSUE TITLE
First Tech Federal Credit Union FTFC current issues

### ISSUE THREAD

**Issue by symbioquine** [2factorauth/twofactorauth#5516]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

![image](https://user-images.githubusercontent.com/30754460/113484051-38c06600-945b-11eb-936f-06a975fb8ff4.png)

* Does support `sms`, `phone`, `email` "second factors"
* Broken docs link - it's unclear what the replacement URL should be though; https://github.com/2factorauth/twofactorauth/blob/336b423e04ac4bb421aae59233e2b8b909761ba5/_data/banking.yml#L687
* Info icon says "proprietary software based 2FA" but should instead say "proprietary hardware based 2FA" - these can be requested through the online banking portal and look like this;
  ![image](https://user-images.githubusercontent.com/30754460/113484196-e3d11f80-945b-11eb-8510-d3e1cd3b27bb.png)

**Bug reproduction:**

N/A - content issues

**Impacted devices:**

All

**Expected behavior:**

Content should be accurate

**Additional information:**

Thanks for maintaining this resource!

**Comment by ApCoder123** [comment]
> Broken docs link - it's unclear what the replacement URL should be though

Perhaps this page as a doc link: https://www.firsttechfed.com/help/security/prevent#multifunction

**Comment by symbioquine** [comment]
Oh, yeah that looks like a reasonable replacement.

**Comment by ApCoder123** [comment]
> Does support sms, phone, email "second factors"

Since there is not information about this in the documentation available, please could you provide us with screenshots of the setup process? Please remember to block out any personal information.

**Comment by symbioquine** [comment]
I personally only have hard tokens enabled, but I've captured screenshots showing where other "second factors" could be enabled in the settings. When they are enabled it gives the option of using any of the enabled ones at login.

![image](https://user-images.githubusercontent.com/30754460/114047403-84e61e80-983e-11eb-8a56-6ddb946c94c1.png)
![image](https://user-images.githubusercontent.com/30754460/114047479-8f081d00-983e-11eb-9647-de119e5ecb8c.png)
![image](https://user-images.githubusercontent.com/30754460/114047507-94fdfe00-983e-11eb-823a-410dff162176.png)

> Info icon says "proprietary software based 2FA" but should instead say "proprietary hardware based 2FA"

It also looks like the info icon should say that both the hardware and software based 2FA are proprietary.

![image](https://user-images.githubusercontent.com/30754460/114047533-98918500-983e-11eb-91b2-849cc4e1a43c.png)
![image](https://user-images.githubusercontent.com/30754460/114047556-9cbda280-983e-11eb-8288-aede00e1f1f1.png)

**Comment by ApCoder123** [comment]
Thanks for that. 

> It also looks like the info icon should say that both the hardware and software based 2FA are proprietary.

Software 2FA is already listed as `proprietary` and we don't list hardware as proprietary, so the `hardware` listing is already handling that.
