### ISSUE TITLE
Update the link on product hunt

### ISSUE THREAD

**Issue by 40504** [2factorauth/twofactorauth#5547]
Two Factor Auth (2FA): List of websites and whether or not they support 2FA via @ProductHunt https://www.producthunt.com/posts/two-factor-auth-2fa

**Comment by Carlgo11** [comment]
I don't really understand what you want us to do about that? We don't control that site and there doesn't seem to be any way to edit the post.

**Comment by 40504** [comment]
@Carlgo11 sorry, I'll provide more details next time
<img width="1573" alt="1" src="https://user-images.githubusercontent.com/71176569/114073451-93b2ec80-98a3-11eb-8262-11333fc05e74.png">

**Comment by Carlgo11** [comment]
Yeah I saw that already but I don't see a way to change it.

**Comment by 40504** [comment]
If you are the owner of the post, it should be right there
<img width="780" alt="2" src="https://user-images.githubusercontent.com/71176569/114074645-e214bb00-98a4-11eb-9f0f-0f1dfa25b796.png">

**Comment by Carlgo11** [comment]
And who's the owner?

**Comment by 40504** [comment]
<img width="384" alt="3" src="https://user-images.githubusercontent.com/71176569/114075330-bb0ab900-98a5-11eb-8063-9bb72266fc79.png">

Also, I suppose you can contact ProductHunt directly and request that changes

**Comment by 40504** [comment]
https://twitter.com/bentossell

**Comment by Carlgo11** [comment]
I see. Contacting a single website to ask them to change their links to us isn't really something we do. Especially not for sites that don't seem to bring any significant traffic to the project.
If you have the time and are willing to contact the website or author on our behalf then feel free to do so! 👍

Our objectives right now are to get through all the open PRs, complete version 4.0 of the project and do necessary changes to the legal structure of the project.

**Comment by 40504** [comment]
I wrote him a direct message on Twitter, he saw the message but nothing changed. In the meanwhile, he is active on Twitter.

**Comment by thibaultmol** [comment]
Issue can be closed, I just contacted product hunt support and they changed it.
https://www.producthunt.com/posts/two-factor-auth-2fa

![image](https://user-images.githubusercontent.com/1010226/115452963-5fceb400-a21f-11eb-9abe-a46d212c6747.png)

**Comment by Carlgo11** [comment]
That's great @thibaultmol!
Closing the issue now
