### ISSUE TITLE
mixpanel.png is blocked in Brave

### ISSUE THREAD

**Issue by 40504** [2factorauth/twofactorauth#5651]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###
**Bug description:**

**Bug reproduction:**

**Impacted devices:**

**Expected behavior:**

**Additional information:**

<img width="1329" alt="1" src="https://user-images.githubusercontent.com/71176569/116237254-47e7ba80-a760-11eb-93fb-2a1847790178.png">

**Comment by phallobst** [comment]
Renaming `mixpanel.png` to `mix-panel.png` works, but I'm not quite sure this is our fault, to be honest. If the tracker blocker from Brave detects a cross-site tracker just by matching an image file name, it's a little simplistic.
