### ISSUE TITLE
Menu bar on narrow screen

### ISSUE THREAD

**Issue by dsoegijono** [2factorauth/twofactorauth#571]
This might be related to #548 and/or #529.

As seen [here (iPhone + Safari)](https://cloud.githubusercontent.com/assets/867840/3262717/edc533f6-f268-11e3-8710-fdc345d8af24.png), the menu bar isn't fully visible on narrow screens. Even when content is wider, and I try to scroll right, the menu bar stays fixed. You probably don't want a horizontal scroll for the menu bar, so the menu should be somehow squeezed if the screen is too narrow? I was thinking only show icons instead of labels, but not sure if icons are descriptive enough (also, there's currently no icon for "Categories").

**Comment by jdavis** [comment]
I definitely think this goes with the responsive issue. The support for responsiveness definitely can be improved... I took out the responsive stuff from SemanticUI because it looked awful.
