### ISSUE TITLE
Update Nordvpn

### ISSUE THREAD

**Issue by person1234-ux** [2factorauth/twofactorauth#5816]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.
##there were some pull requests but they had already all been murged and they are very old
### Information about the site entry to be updated: 

* Nordvpn ``

* https://nordvpn.com/

* VPN Providers

### Information about why the site entry should be updated:
**This site entry should be updated because:**
- [ ] It now supports 2FA.
- [x] The methods of 2FA that it supports have changed.
- [ ] It has begun the process of implementing 2FA.
- [ ] It no longer supports 2FA.
- [ ] Its name has changed.
- [ ] Its documentation link has changed.
- [ ] Its Twitter username, Facebook page, and/or email address have changed.
- [ ] It fits better in a different category.
- [ ] Its logo has changed.
- [ ] It has been acquired or absorbed by another site, and the new site is eligible to be listed on 2fa.directory.
- [ ] Other (please describe below).

### Information about how the site entry should be updated:

For example, if a site now supports 2FA, list the methods of 2FA the site now supports.
Please include any supporting documentation for the changes as well, such as official documentation links or announcement blog posts.
a hardware secerity key is now supported by nordvpn. 
side note nordvpn doesn't require 2 factor authenication if you are connecting via there linux commandline in order to use the vpn
![Screenshot from 2021-06-17 15-20-25](https://user-images.githubusercontent.com/76968588/122473836-9a36a200-cf7f-11eb-9a03-cc2c5c31211c.png)

If no public-facing documentation is available, please include screenshots of the changes, redacting any personal information. -->

**Comment by person1234-ux** [comment]
please link  to #5827

**Comment by phallobst** [comment]
You can link a PR to an issue by including a text like `Closes #5816` or `Fixes #5816` in the commit message.

However, if you want to open a PR anyway, it's not necessary to open an issue beforehand.
