### ISSUE TITLE
why can't we use an IDE such as intellj to submit pull requests

### ISSUE THREAD

**Issue by person1234-ux** [2factorauth/twofactorauth#5817]
I tried to use intellj to submite a pull request but it won't let me. Can somone please explain why the organization has choosen to restiric 3rd party access to this project making it so I can't use intellj to submite pull request thanks.

**Comment by Carlgo11** [comment]
We don't limit that. I don't even think there's a way we could limit that.
Check your settings in your IDE as that's most likely the problem.
