### ISSUE TITLE
TextPower has a SMS 2FA solution

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#582]
The co-founder, Scott Goldman, has emailed me with information about TextPower/TextKey.

If you guys want to take a look and confirm that they would fit under the `/providers/` page, then I can go ahead and add it.

Here's the link: http://www.textpower.com/public/

**Comment by mxxcon** [comment]
it does look like they are 2fa providers...
but it's disappointing they are going "camera megapixel" route. "7-factor authentication"? :disappointed:
more is not better. :/
