### ISSUE TITLE
Why is twofactorauth.org no longer working?

### ISSUE THREAD

**Issue by OLLI-S** [2factorauth/twofactorauth#5845]
When I open twofactorauth.org (from my bookmarks) then I get forwarded to https://brainstation.io/cybersecurity/two-factor-auth
Is this behaviour intended?

**Comment by ApCoder123** [comment]
Hi @OLLI-S 

The site is no longer at twofactorauth.org The domain has changed to [2fa.directory](https://2fa.directory). Please see #5238 for context.

**Comment by OLLI-S** [comment]
Thank you @ApCoder123
