### ISSUE TITLE
Add chatlayer.ai

### ISSUE THREAD

**Issue by 40504** [2factorauth/twofactorauth#5863]
<img width="2545" alt="15" src="https://user-images.githubusercontent.com/71176569/123427207-9bda1880-d5c4-11eb-8af3-34eed3ecc94c.png">

I don't know what type of 2fa to write when adding this service. please help. 

https://chatlayer.ai/

**Comment by person1234-ux** [comment]
If my understanding is correct this is just a different form of single factor please refer to [this](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) for more details on what 2fa is.

**Comment by ApCoder123** [comment]
We currently don't list sites that only provide 2FA via SSO. At the moment, we only list sites with built-in 2FA support.
See https://github.com/2factorauth/twofactorauth/pull/1372#issuecomment-148413534 for more info.
