### ISSUE TITLE
Add "Recovery" column on 2fa.directory website

### ISSUE THREAD

**Issue by 40504** [2factorauth/twofactorauth#5892]
for example this one https://github.com/2factorauth/twofactorauth/blob/master/entries/t/technicpack.net.json
```
{
  "Technic": {
    "domain": "technicpack.net",
    "tfa": [
      "totp"
    ],
    "recovery": "https://www.technicpack.net/tfa/remove",
    "keywords": [
      "gaming"
    ]
  }
}
```

has "recovery" option but never used on [2fa.directory](https://2fa.directory)

I propose to display this one as it is useful information, like "Docs" right now.

<img width="1413" alt="1" src="https://user-images.githubusercontent.com/71176569/123888238-5b2b2800-d953-11eb-81a8-1460a3d1d3be.png">

**Comment by person1234-ux** [comment]
Like the idea, but I think that this will add unnecessary clutter to the website

**Comment by Carlgo11** [comment]
Yeah this is already being worked on.

**Comment by person1234-ux** [comment]
Ok
