### ISSUE TITLE
Opera and/or Anti-Phishing Working Group flagged website https://2fa.directory as phishing site.

### ISSUE THREAD

**Issue by Encryptionus** [2factorauth/twofactorauth#5911]
As the title reads, a couple of days ago I noticed a false positive warning when I was browsing to https://2fa.directory on Opera GX (I tested it on 2 versions of the browser: the one based on Chromium 76.0.4017.208 and on the newest version as of 4th July 2021 based on Chromium 76.0.4017.220), also according to the warning from the browser, the site was reported by Anti-Phishing Working Group. Are you aware of this situation? I'm also attaching the screenshot from the browser when I try to enter https://2fa.directory
![2fadir2](https://user-images.githubusercontent.com/27779936/124381951-55bc3d80-dcc5-11eb-911f-295443558c98.PNG)

**Comment by phallobst** [comment]
I use Opera myself and have seen this warning as well. It is a false positive.

The 2fa.directory website does not use personal data, nor does it offer any kind of login itself.

Maybe one of the linked sites is considered to be fraudulent (the _Cryptocurrencies_ category comes to mind), causing this warning. Unfortunately, I don't see any way to report a false positive on the apwg.org website, nor does it tell when or how this was reported.

Hopefully this will be resolved in the next couple of days.

**Comment by Encryptionus** [comment]
That might be the case. I also hope it will get resolved as soon as possible. I might also try to get in touch with Opera directly but I don't know if that will resolve the issue. Anyways, the issue can be closed.
