### ISSUE TITLE
Issue Forms

### ISSUE THREAD

**Issue by ApCoder123** [2factorauth/twofactorauth#5927]
GitHub recently launched [Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) which allow issue templates to be replaced by form fields. E.g.
![image](https://user-images.githubusercontent.com/20560218/124786900-033a8580-df40-11eb-95d2-191323522881.png)

This could be useful for the add/update/remove site templates, as it would force issue submitters to fill in the correct information and make it easier for those unfamiliar with markdown. It could also save maintainer time in terms of asking for additional information.

Happy to open a PR to convert current templates to issue forms, but was wondering what others thought about this?

**Comment by phallobst** [comment]
Looks promising, and it will (probably) also get rid of the "_X of Y tasks_" tag on the issue that serves to purpose whatsoever, since the checkboxes are not a task list at all.
