### ISSUE TITLE
Update American Express

### ISSUE THREAD

**Issue by zachriggle** [2factorauth/twofactorauth#5969]
### Site name

American Express

### Site URL

https://americanexpress.com

### Documentation URL

https://www.americanexpress.com/en-us/account/two-step-verification/manage?linknav=US-Ser-axpAccountManagement-ManageTwoStepVerification#

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [X] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

AmEx supports SMS, phone, and e-mail 2FA.

You must be logged in to AmEx to access the provided URL.

Can provide screenshots if necessary.

Not sure how I enabled it, but it's definitely supported.

**Comment by ApCoder123** [comment]
Hi there, since there is no publicly accessible documentation available, please could you provide us with screenshots of the setup or login process as evidence of 2FA? Please remember to block out any personal information. Thanks
