### ISSUE TITLE
Add mailbox.org

### ISSUE THREAD

**Issue by generalmanager** [2factorauth/twofactorauth#601]
Please add this German e-mail service which is very security focused (supports DANE, auto-encryption of incoming mails with PGP, sending only over encrypted connections and so on):

```
    - name: mailbox.org
      url: https://www.mailbox.org/
      twitter: mailbox_org
      img: site.png
      tfa: Yes
      hardware: Yes
      doc: https://mailbox.org/en/one-time-passwords-for-secure-login-to-our-webmailer/
```

**Comment by jdavis** [comment]
Do you have a 32x32 image that we could use? Feel free to add it to a comment so someone can make the changes without having to hunt for an image.

**Comment by generalmanager** [comment]
The official logo is available here: https://mailbox.org/en/press/
I grabbed the RGB logo and modified it to resemble the favicon:
![logo_mailbox](https://cloud.githubusercontent.com/assets/6797943/3386620/43fa337c-fc76-11e3-80b9-8e881803889f.png)

I hope that helps ;)

**Comment by jamcat22** [comment]
Created a pull request for this. #603.

**Comment by generalmanager** [comment]
Greatly appreciated, thanks!
