### ISSUE TITLE
Add [Linode]

### ISSUE THREAD

**Issue by GeneticallyModifiedAlex** [2factorauth/twofactorauth#6038]
### Site name

Linode

### Site URL

https://www.linode.com/

### Documentation URL

https://www.linode.com/docs/guides/how-to-use-yubikey-for-two-factor-ssh-authentication/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [X] FIDO2/U2F/WebAuthn security keys
- [X] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by GeneticallyModifiedAlex** [comment]
I believe I've filled out everything properly. Hope this helps. Great community project

**Comment by ApCoder123** [comment]
Hi there,

Linode is already listed as supporting 2FA on the site, so this issue will be closed. Sorry for the inconvenience.
https://github.com/2factorauth/twofactorauth/blob/bbb80480193adfcc2b83835706dd491546a07125/entries/l/linode.com.json#L2

The doc link provided is generic for enabling 2FA for SSH, so the current Linode 2FA methods do not need to be updated.
![image](https://user-images.githubusercontent.com/20560218/128768623-0e15a65f-d0fe-473e-a87d-35e7b55342fd.png)
