### ISSUE TITLE
Partner with plaintextoffenders.com?

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#605]
What do you think about somehow partnering with http://plaintextoffenders.com?
While topics are somewhat different, both are relevant to improving user account security.

**Comment by jdavis** [comment]
I think the site is a great idea because I literally just received an email from a website that sent me their password. I was pretty appalled.

How would this partner ship work? Do you know the people that run it?

**Comment by mxxcon** [comment]
I don't know people there. Just saw it yesterday.
Since both sites are part user education and part public shaming, sites could cross-link to each other...(Particularly I imagine them linking here would make more sense..)

**Comment by jamcat22** [comment]
Fun fact, they already link to your site.

http://plaintextoffenders.com/faq/non-devs

Question 9 section 2.

**Comment by mxxcon** [comment]
alrighty then, i guess it's taken care of. :smile:

**Comment by jdavis** [comment]
That's great! Thanks for pointing that out, @jamcat22.
