### ISSUE TITLE
Update Bitwala

### ISSUE THREAD

**Issue by Sami32** [2factorauth/twofactorauth#6062]
### Site name

Nuri

### Site URL

https://www.nuri.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Add SMS tfa method:
https://support.nuri.com/hc/en-gb/articles/360009149240-TAN

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by ApCoder123** [comment]
Duplicate of #6059. Closing.
