### ISSUE TITLE
Xbox Live supports passwordless authentication through U2F Security Keys

### ISSUE THREAD

**Issue by Encryptionus** [2factorauth/twofactorauth#6092]
### Site name

Xbox Live

### Site URL

https://www.xbox.com/live

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

As the title says. Xbox Live supports signing in with security key (or Windows Hello if configured), once you click sign-in on https://xbox.com/live you can choose the option for paswordless authentication with the help of U2F Security Key (I can confirm this works)
![Xbox Live U2F](https://user-images.githubusercontent.com/27779936/131501852-98936c4a-0cff-4a90-a184-fe7f1226b586.PNG)

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by phallobst** [comment]
Using a U2F key (or a "magic link" or whatever) _instead_ of the password does not constitute two-factor authentication, since you merely replace one factor (password) with another.

The actual 2FA options of `login.live.com` have not changed, so there's no need to update its entry,
