### ISSUE TITLE
Paypal 2fa is broken/disabled

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#610]
http://www.darkreading.com/mobile/paypal-two-factor-authentication-broken/d/d-id/1278840
https://duosecurity.wistia.com/medias/eu5l5sj36x
Should we address this somehow?

**Comment by dsoegijono** [comment]
I think we should change it to `tfa: No` since it's disabled, and maybe add an exception for explanation.

**Comment by jamcat22** [comment]
If you read the full article, you will see that 2fa isn't disabled, but the ability to login to the PayPal mobile app with an account that has 2fa is disabled. Therefore, 2fa isn't disabled on accounts, just the ability to login. The website still works.

**Comment by ilyakatz** [comment]
whoa, thanks duosecurity for giving exact instructions on how to hack things. what a back handed move. Duo is not the only one to report this issue, but I would expect a much better behavior from a security company :(

**Comment by mxxcon** [comment]
@ilyakatz they followed responsible disclosure methods but paypal stopped providing them with status updates so they went public with it.

**Comment by ilyakatz** [comment]
yes, they responded about that and I did see that PayPal was taking their time. I take it back, Duo :) As far as the actual question, I think we should not change it to "No" but can add a note about this issue.

**Comment by jdavis** [comment]
Yeah, I just logged in this morning with it from my desktop, so it definitely works. I think an exception could be added noting the vulnerability and lack of it for mobile but nothing beyond that.

**Comment by Carlgo11** [comment]
@jdavis and the fact that most of us can't use it. I don't call it tfa if it's only available for one country.

**Comment by Carlgo11** [comment]
Can this be moved to #1026?

**Comment by mxxcon** [comment]
:+1:
