### ISSUE TITLE
Add HMBradley

### ISSUE THREAD

**Issue by StephenBrown2** [2factorauth/twofactorauth#6102]
### Site name

HMBradley

### Site URL

https://hmbradley.com

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [ ] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

HMBradley is a banking site that was in the 200,000 Alexa top sites a few months ago but has since fallen to Alexa Rank 210,850, likely due to their extremely quick growth necessitating a switch to an invite-only system: https://www.hmbradley.com/blog/HMBradley-2021-update

Icon URL: https://play-lh.googleusercontent.com/nxuROtjkO8xQgI5HYDyKs1GWRD0q29P8oCVT0P3I8l8Ki1Sie93ASN0F0Lu8-gAqdA=s180

There isn't public documentation for setting up 2FA yet, but one can do so in the Account Details > Security settings.
![HMBradley Security](https://user-images.githubusercontent.com/1148665/131721968-ad58d89b-85b0-4913-b556-bf8bb8acb5fa.png)

Here is the initial login screen:
![HMBradley Login 1](https://user-images.githubusercontent.com/1148665/131722011-ea55fd46-25f5-4827-9e60-c455e16f643b.png)
And the prompt for the TOTP code:
![HMBradley Login 2fa](https://user-images.githubusercontent.com/1148665/131722049-01681de9-91bd-41fc-ac50-4564cf0a3f37.png)

**Comment by Carlgo11** [comment]
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.
