### ISSUE TITLE
Should we add iCloud?

### ISSUE THREAD

**Issue by dsoegijono** [2factorauth/twofactorauth#619]
http://www.theverge.com/2014/7/1/5860436/apple-brings-two-step-verification-to-icloud-website

We already have Apple under Retail, and an iCloud account is an Apple ID. However, there are people (me included) who have separate iTunes account and iCloud account. Or maybe, instead of creating a separate entry for iCloud, we can just note it somewhere? Because without this article I wouldn't have realized that I only turned on TFA for one of my Apple IDs.

**Comment by mxxcon** [comment]
I think it's fine to add icloud as a separate entry.
Google and Microsoft are listed multiple times for various products. Until we figure out how to link/connect multiple entries together, i think it's fine to add them.

**Comment by jdavis** [comment]
:+1:

**Comment by jdavis** [comment]
Closed by #620.
