### ISSUE TITLE
Add *.live.com

### ISSUE THREAD

**Issue by sn00py1310** [2factorauth/twofactorauth#6225]
### Site name

Outlook - Microsoft

### Site URL

https://outlook.live.com/owa/

### Documentation URL

https://support.microsoft.com/en-us/help/12408/

### Supported 2FA methods

- [X] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [x] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [X] Phone calls
- [X] SMS tokens
- [X] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Notes: `2FA phone calls may not be available in all regions. Not all FIDO2 keys work because of custom requirements.`
FIDO2 note: [Blog post](https://www.microsoft.com/en-us/microsoft-365/blog/2018/11/20/sign-in-to-your-microsoft-account-without-a-password-using-windows-hello-or-a-security-key/) and [specs](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key)

Not sure if it's a similar case to #3698. The new scheme in #6185 would fit best.

**Comment by phallobst** [comment]
We already list this site as "Outlook.com".

For U2F support, please also see #6154 - this does not constitute 2FA, but allows for a passwordless login.

**Comment by sn00py1310** [comment]
@phallobst maybe `outlook.live.com` or `*.live.com` should be added in as "additional-domains" for "Outlook.com", because it redirects to outlook.live.com.
