### ISSUE TITLE
Apple supports 2FA in more countries than just the US

### ISSUE THREAD

**Issue by Matt3o12** [2factorauth/twofactorauth#623]
Apple supports 2FA in more than just the US. Here is a full list of all countries and the supported providers: ["Apple ID: About SMS and two-step verification"](http://support.apple.com/kb/HT5593)

**Comment by jdavis** [comment]
Great, thanks for that info, @Matt3o12. Take a look at #624 that @mxxcon opened up and let us know if that suffices.
