### ISSUE TITLE
Add 2FA provider AlterEgo

### ISSUE THREAD

**Issue by michaelsteiner** [2factorauth/twofactorauth#633]
The list of 2FA providers shall be extended with https://alteregoapp.com/ .

**Comment by jdavis** [comment]
If you could find a 32x32 logo as well as provide the rest of the information, it would make it easier for a contributor to add AlterEgo :smile:

**Comment by jamcat22** [comment]
Added a pull request for this. See #643

**Comment by jdavis** [comment]
Closed with @jamcat22's changes in #643.
