### ISSUE TITLE
Please add my1login.

### ISSUE THREAD

**Issue by ljackman** [2factorauth/twofactorauth#634]
We are a cloud based password manager and we support 2FA

**Comment by mxxcon** [comment]
@ljackman can you link to any docs that describe what 2fa you support or how users would enable it?

**Comment by dsoegijono** [comment]
From https://www.my1login.com/content/security.php

> my1login uses 2-step authentication by default - a Password and Key Phrase protects accounts. Additionally, a dropdown is used for the authentication password entry mitigating against screengrabbers and keyloggers. A Key Phrase rather than a password is used as the encryption key, the longer length of a phrase over a password hugely increases encryption key permutations.

I'm not exactly sure, but after googling it seems that Key Phrase is similar to a password but longer (a few words). If that's true, I don't think it counts as 2FA.

**Comment by ljackman** [comment]
In addition to having a key phrase and password, we use Google authenticator to provide 2FA.  I have asked my development team to prepare a document for me on our encryption which I will send across when it is available.

Kind regards

Lucy

Lucy Jackman

Account Executive

my1login https://www.my1login.com  |  Protecting Passwords in the Cloud Since 2007

tel: +44 (0) 141 427 0454 | mob: +44 (0) 7817 030 635

**Comment by dsoegijono** [comment]
@ljackman Any update?

**Comment by ljackman** [comment]
Hi and thanks for your email.

So sorry I haven't got back to you sooner. Yes, we have the key phrase + additional 2 factor authentication as standard. I have just completed a document which illustrates this. Let me modify the document slightly to show you, in detail, the full 2FA experience and send to you later today when I sign into my laptop. I am in uk time zone currently so in 2 hours.

Alternatively, if you go to my1login.com (google chrome best as has additional features) you can sign up for a free trial which will take you through the key phrase and 2FA process. Any questions then email or call me. Will get document across asap.

Thanks,

Lucy

Sent from Samsung Mobile on O2

-------- Original message --------

**Comment by RichJeanes** [comment]
@ljackman Can we get an updated doc so we can add you to the list? Otherwise this issue will be closed as dead.

**Comment by dsoegijono** [comment]
Closing this issue since it's been months and there's no update. @ljackman feel free to reopen if you'd like.
