### ISSUE TITLE
Add video service category

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#640]
I'd like to see a video service category with, YouTube, Vimeo, Twitch, Livestream etc

If someone could add the category I could upload the services

**Comment by jdavis** [comment]
What about merging music/movies? And instead use Multimedia as the title?

**Comment by Carlgo11** [comment]
@jdavis Sure that could work. I'll get started on it

**Comment by mxxcon** [comment]
"Multimedia" makes sense, but it is so 90s.. :)
Maybe Entertainment?

**Comment by Carlgo11** [comment]
you have a point there @mxxcon but don't we all just love the 90s? :P

**Comment by jdavis** [comment]
Hahah, :+1: @mxxcon. My age is showing :wink:

**Comment by jdavis** [comment]
Closing in favor of #651
