### ISSUE TITLE
Chase Docs

### ISSUE THREAD

**Issue by ChrisMcClendon** [2factorauth/twofactorauth#644]
The "Docs" section for Chase follows a mobile link. If you try to convert this to a standard browser link it gives a 404.

**Comment by mxxcon** [comment]
Yes, that's a problem with Chase's confusing website. :confused:
Do you know of a better link we can use?

**Comment by ChrisMcClendon** [comment]
Actually, it appears as though it isn't really two factor. I guess technically it is, but it ONLY works when going through their mobile site and you have no control over the process otherwise.

I'm not quite sure what to do about this one.

**Comment by jdavis** [comment]
One option is to create a Note for this detailing it: https://github.com/jdavis/twofactorauth/tree/master/notes

**Comment by mxxcon** [comment]
@ChrisMcClendon you are mistaken. See #91 and #263

**Comment by ChrisMcClendon** [comment]
Thank you for the clarification. Would a note slightly describing this 'issue' still be appropriate as per @jdavis 's comment?

**Comment by jdavis** [comment]
Some of the people that Chase that have confirmed it would be better people to ping for this. This includes @jfocht and @RichJeanes.

If the current documentation link doesn't suffice for Chase's 2FA, then a custom Note would be better.

**Comment by jdavis** [comment]
I just got an email from Charlie Sobel saying this:

> You have Chase listed on your site as supporting 2FA, but you may want to update that. According to the docs you linked to, they only support 2FA for their mobile site and thru their mobile app, not via the primary website. That's a pretty big oversight on their part.

Like Charlie mentions, the [doc](https://mobilebanking.chase.com/Public/Docs/Faq?nodeId=1&itemId=2) only says that it has 2FA on mobile. Is there anyone with Chase again that can look into this?

**Comment by jamcat22** [comment]
@jdavis Chase supports 2FA on all platforms. All their apps, websites, and mobile websites require 2FA to login from a new computer.

The only doc available is the mobile web doc, but 2FA is required for all users (you cannot opt out and you are "opted in" right when you sign up) on all devices.=

**Comment by jamcat22** [comment]
@jdavis See #91 and #263

**Comment by mxxcon** [comment]
@jdavis This is what 2fa on Chase desktop looks like
![clipboard01](https://cloud.githubusercontent.com/assets/847140/4695784/0bebbb2c-57de-11e4-8cf0-dfa26dc3ba96.png)
![clipboard02](https://cloud.githubusercontent.com/assets/847140/4695785/0beef24c-57de-11e4-8ec4-3e50f6de4f23.png)
![clipboard03](https://cloud.githubusercontent.com/assets/847140/4695786/0bef5598-57de-11e4-95e7-b5cf31230b25.png)

**Comment by jdavis** [comment]
Okay, so should we close this then?

**Comment by jamcat22** [comment]
@jdavis Maybe. Tomorrow I can create a note for Chase to use instead of the 
current (confusing) doc, if that helps.

**Comment by jdavis** [comment]
That'd be great, @jamcat22. I think that'd edge you into "Collaborator" territory as well =]

**Comment by jamcat22** [comment]
Done! See #825. Please tell me if I messed anything up (which I hopefully didn't)! :smiley:

@jdavis Well, it's not my first time creating a doc. Created one for GREE in #805.

**Comment by jamcat22** [comment]
@jdavis Thank you so much! Really didn't think you were serious! :smile:

Seriously, thank you!

**Comment by Carlgo11** [comment]
Wow congrats and welcome to the team @jamcat22!
If you have irc then you're more than welcome to join mxxcon and me on freenode in #2fa. We're lonely ;)
I'm probably going to make a pr to add some form of link to the irc later.

**Comment by jdavis** [comment]
You guys both use Freenode? wat. I'll join soon.
