### ISSUE TITLE
Wealthfront

### ISSUE THREAD

**Issue by gregschwartz** [2factorauth/twofactorauth#658]
It'd be great to put pressure on wealthfront.com to support two-factor.

**Comment by mxxcon** [comment]
@gregschwartz it's just YAML text and 32x32 logo. Pull requests welcome. :smile:

**Comment by gregschwartz** [comment]
Ahhh, gotcha. Just created one: https://github.com/jdavis/twofactorauth/pull/659

**Comment by jdavis** [comment]
Closing this in favor of the new issue.
