### ISSUE TITLE
frostbox link not working

### ISSUE THREAD

**Issue by davidhartleyllc** [2factorauth/twofactorauth#667]
frostbox link not working

**Comment by Carlgo11** [comment]
Can you give us a working one?

**Comment by mxxcon** [comment]
It seems like either they are dead or there's a routing problem or server issues.
Let's give them a couple more days and if still down, deadpoll it.

**Comment by Carlgo11** [comment]
It looks to be working now.
Close issue?

**Comment by dsoegijono** [comment]
Confirmed link works now.
