### ISSUE TITLE
Fifth Third Bank

### ISSUE THREAD

**Issue by mcnkldzyn** [2factorauth/twofactorauth#675]
No two factor authentication and does not permit special characters to be used in passwords.

**Comment by Carlgo11** [comment]
@mcnkldzyn Feel free to make a pr with any new sites you'd like to add to the list.

**Comment by mxxcon** [comment]
Sorry about all that. I did something wrong and it commited this change directly into this repo's master :confused: The commit seems to be fine, but it didn't follow proper PR process. :disappointed:

**Comment by dsoegijono** [comment]
Closing this since @mxxcon added the entry.
