### ISSUE TITLE
Amazon WorkSpaces Multi-Factor Authentication.

### ISSUE THREAD

**Issue by mxxcon** [2factorauth/twofactorauth#678]
https://aws.amazon.com/blogs/aws/multi-factor-auth-for-workspaces/

**Comment by jdavis** [comment]
Good idea. What section would this go under?

**Comment by mxxcon** [comment]
I guess `cloud computing` or `other`...although we do already have AWS listed...

**Comment by jdavis** [comment]
In an interesting way, this is sort of "Remote Access" in a few respects. And this is different than AWS 2FA as it states in the article.

**Comment by mxxcon** [comment]
hmm ya, remote access fits too.
