### ISSUE TITLE
Update Indeed

### ISSUE THREAD

**Issue by ramelaaa** [2factorauth/twofactorauth#6790]
### Site name

Indeed.com

### Site URL

https://www.indeed.com/

### Update reason

Other (please describe below).

### Additional information

Entry states that 2FA is not available for job seekers, however it is available to job seekers now (through SMS).

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

**Comment by fletcherdodd** [comment]
Hey ramelaaa,
Is there any documentation on this? I don't see any option on the account settings page of my job seeker account nor am I prompted for a code when I log in from somewhere I haven't before? (I do have my mobile attached to my account)

**Comment by ramelaaa** [comment]
The documentation doesn't mention job seekers, but it is avaiable.
Link: https://www.indeed.com/lead/two-factor-authentication
On the settings page, I am listed as a job seeker, and my 2fa is active.
<img width="821" alt="Screen Shot 2022-06-16 at 11 20 32 AM" src="https://user-images.githubusercontent.com/55069265/174104768-b90705f7-efc0-425d-b25b-7136569bf426.png">
Here is the SMS I got:
![IMG_0691](https://user-images.githubusercontent.com/55069265/174104884-d633ed1f-c2c4-4ae9-851c-38a48c1d4224.jpg)
