### ISSUE TITLE
PayPal 2FA isn't internationally available

### ISSUE THREAD

**Issue by codebeta** [2factorauth/twofactorauth#685]
I'm unable to use the 2FA from PayPal, either software or hardware, because my account is from Costa Rica and not from the US or one of the supported countries.

Hopefully they fix it to have it work internationally and not just in some areas.

**Comment by mxxcon** [comment]
@codebeta do you have a list of allowed/restricted countries?

**Comment by codebeta** [comment]
Unfortunately no, when I asked PayPal support as to why I couldn't enable the feature they sent me the following reply:

"My name is Rampell Emil from PayPal Consumer Support and I appreciate the opportunity of answering your inquiry about the availability of additional features in PayPal Costa Rica.

Right now, Security Keys is not yet available in your country. Thank you for letting us know your interest about getting this feature added. We appreciate your feedback and I will be forwarding this suggestion to our account specialist so we can take a look at the possibilities of considering this in the future."

**Comment by mxxcon** [comment]
Any chance you could follow up with him to ask for a list countries so that we can update this site?

**Comment by codebeta** [comment]
Yes, I sent them an e-mail hoping that they will reply. Will update here as soon as they reply with the information.

**Comment by codebeta** [comment]
This is the reply I got from PayPal

Currently, the "Two Factor Authentication" is only available on US and Canada. We are still working on making the feature available on every country where PayPal is available. We greatly appreciate your interest in this feature and I will definitely raise this so we can possibly make this available in the future. We are always happy to hear from our PayPal members. We at PayPal take pride in our service, and it's a pleasure for us to know what services we could still offer to satisfy PayPal members
