### ISSUE TITLE
Authy.com added to developer category?

### ISSUE THREAD

**Issue by Carlgo11** [2factorauth/twofactorauth#697]
Since Authy.com also provides API handling via https://dashboard.authy.com/ should the site also be added in the dev category?

**Comment by smholloway** [comment]
I think most providers offer an API. The API is a way to interact with the 2fa provider, so it's redundant to include it both places.

**Comment by jdavis** [comment]
I agree with Mr. @smholloway. He pioneered the Provider's page and has a lot of experience with that matter.

**Comment by Carlgo11** [comment]
Yes but they offer more than just an API list. The dashboard let's you manage your authy apps.
Like color schemes, user registration and payments.
![ss 2014-08-20 at 05 51 53](https://cloud.githubusercontent.com/assets/3535780/3983730/f9890fd8-2881-11e4-8e29-345d789452c2.png)

**Comment by mxxcon** [comment]
I think `developer` category is for products/tools/services designed specifically for developers.
While Authy does have that component, developers are not their primary target audience.

It could be included if we were using a tagging system, but I think with the current category system it would not be the best fit.

**Comment by Carlgo11** [comment]
@mxxcon I'd say developers are their primary target audience. It's probably their only audience.
The dashboard is designed to help developers create and manage their Authy apps.
(I'm not a spokes person for Authy Inc but that's my personal view)

**Comment by mxxcon** [comment]
But that dashboard is complimentary to their primary product. That dashboard is useless if you are not using Authy. However, you can use Authy without the dashboard.

**Comment by Carlgo11** [comment]
You can use Authy without the dashboard but you can't use Authy's services to protect your app/site without the dashboard

**Comment by smholloway** [comment]
A company like Google has `Google Authenticator` in the providers list as well as distinct services like `Google Wallet`, `Google Drive`, and `Google Cloud Platform` in the services list. Google has a diverse portfolio. Authy does not. Authy is a 2fa provider. Their API supports their 2fa service, which is already represented on the provider page. This isn't unique to Authy--most providers have an API (see Toopher, Duo, Rublon, Launchkey, Wikid, etc). To keep things simple and DRY we list 2fa providers only once--on the provider page.
