### ISSUE TITLE
Add phone callback as a specific column

### ISSUE THREAD

**Issue by zmarties** [2factorauth/twofactorauth#70]
Phone callback, as offered by Google, is a great method of 2FA, and deserves its own column in the tables so you can easily see what services offer it.

**Comment by jdavis** [comment]
Does phone callback imply SMS in this case though? Are there any sites out there that have callback but not SMS?

**Comment by jdavis** [comment]
While I agree that phone callback could be added as a new column, I'd only want to add it if there's significant evidence suggesting that it exists as a 2FA method when SMS doens't exist. But as far as I can tell, it only exists when SMS already exists, which is a bit defeating. I'm closing this for now =]

**Comment by zmarties** [comment]
Glad to see that this has now been added as a column.

**Comment by jdavis** [comment]
That's great. I think the way we have it now should please everyone =]
