### ISSUE TITLE
Bitbucket is not actively in progress

### ISSUE THREAD

**Issue by Pitta** [2factorauth/twofactorauth#705]
This should be switched back not supported status.

**Comment by jdavis** [comment]
Do you have a source for this?

**Comment by Pitta** [comment]
Main source I have for this is a 2 year old issue about it that is still getting traffic.

https://bitbucket.org/site/master/issue/5811/support-two-factor-authentication-bb-7016

**Comment by mxxcon** [comment]
@Pitta it seems like they are kinda working on it, but keep feeding people "coming soon".
I think it's sensible to remove "working on it" for bitbucket.

**Comment by smholloway** [comment]
You'll notice a tweet from our very own @jdavis in that thread: https://twitter.com/bitbucket/status/445631335169028096. As of March 17, 2014 Atlassian said they
"... are working to #SupportTwoFactorAuth in the future. No eta at this time..." With no additional information and no ETA, I tend to agree with @Pitta.

**Comment by Pitta** [comment]
It basically what I mean - they may have talked about it, but there is no communication saying its being worked on or if it will ever come. I think it should be dropped back to unsupported to encourage more folks to badger them about it.

**Comment by jdavis** [comment]
Yup, let's remove it.

**Comment by jdavis** [comment]
Closing in favor of #730.
