### ISSUE TITLE
Skype & Microsoft Accounts

### ISSUE THREAD

**Issue by TheSeg** [2factorauth/twofactorauth#706]
Skype, even with a Microsoft account paired, does not support two-factor auth.

1) Even after pairing MS account, your Skype password is still used.
2) Skype itself does not have 2FA.

Because the MS account is irrelevant to logging in to Skype, you do not have the 2FA protection with Skype under any situation. Thus, there are no options for effective 2FA for your Skype account.

I don't know how you want to document this, but it should be known that right now, the site is communicating a false sense of protection.

**Comment by jdavis** [comment]
So in the past, was the information provided by #102 and #118 wrong? cc: @tathamoddie @ScaleOvenStove

**Comment by TheSeg** [comment]
I tried finding some way to fully migrate and thus get rid of the Skype standalone credentials and couldn't find anything. Just the pairing with the MS account.

If anyone does know a way to remove the standalone credentials to an existing account, I'm all ears!

**Comment by mxxcon** [comment]
It's not wrong. It's just that Skype accounts and MS accounts are still separate.
If you use _MS account_ to login to Skype then TFA does come into play.
However, if you use _Skype account_ then there's no TFA.
Perhaps instead of `Skype (w/Microsoft Account)` name, we should have just `Skype` and use exception for a bit more verbose explanation.

**Comment by TheSeg** [comment]
@mxxcon I think that's best. The result is that one can get to your Skype account without needing to do TFA, so long as the attacker isn't using the MS credentials.

**Comment by jdavis** [comment]
@mxxcon I think that's a good way to describe it.

**Comment by Carlgo11** [comment]
@mxxcon Could you commit this then?

**Comment by RichJeanes** [comment]
Bump.
Is this still an issue or has MS fully migrated accounts?

**Comment by Carlgo11** [comment]
This is still an issue

**Comment by RichJeanes** [comment]
Thank you, @mxxcon.
