### ISSUE TITLE
Personal Capital support two factor authentication

### ISSUE THREAD

**Issue by pc-elavassani** [2factorauth/twofactorauth#721]
Please see https://www.personalcapital.com/safety-and-security

We do support two factor authentication using email and phone out of band authentication. When verifying this security feature please note that it will not kick in until you aggregate a FI.

**Comment by mxxcon** [comment]
> it will not kick in until you aggregate a FI.

Fl?
When you say "phone", do you mean sms or a voice call?

Ehsan, would you like to submit a pull request for this? It's just a YAML block and 32x32 png logo.

**Comment by pc-jdelfavero** [comment]
FI. Financial Institution.  So if you were to register for a Personal Capital account we don't challenge on a second device until you have something in your login that's needs protecting, so if you just register and don't add anything we don't challenge on a second device until you add something.

**Comment by jamcat22** [comment]
Should this be closed?

**Comment by pc-elavassani** [comment]
Yes!
