### ISSUE TITLE
2FA by Cellular carriers

### ISSUE THREAD

**Issue by wilsonmar** [2factorauth/twofactorauth#723]
What protects the authenticaton of accounts on Verizon, AT&T, Sprint, T-Mobile, etc. on which phone SMS 2FA is based? (ATT doesn't even allow special characters in passwords.)

**Comment by smholloway** [comment]
I don't follow. How would you like us to reply? What action can be taken based on your issue?

**Comment by wilsonmar** [comment]
Sorry, how about this more action-oriented:
Add cellular carriers websites to the list (Verizon, AT&T, Sprint, T-Mobile, etc.)

**Comment by dsoegijono** [comment]
+1 for carrier category

**Comment by Carlgo11** [comment]
I'll start working on that.

**Comment by jdavis** [comment]
I don't quite understand. How common is it for 2FA to only work for certain providers? Looking at the site currently, I only saw Apple that even mentions carriers.

**Comment by mxxcon** [comment]
@jdavis they are talking about accounts from phone carriers. When you login into your Sprint account, Sprint should be using 2FA...

**Comment by jdavis** [comment]
Ahh. Well I've always had issues with reading comprehension but at least I wasn't the only one that didn't understand.

If we didn't want to add a new category, Communication might be a good fit.

**Comment by RichJeanes** [comment]
This is being discussed pretty extensively in #761 and seems a likely inclusion once details are sorted. Closing this Issue thread for housekeeping.
