### ISSUE TITLE
State Farm and Capital One

### ISSUE THREAD

**Issue by Keltian** [2factorauth/twofactorauth#728]
I was looking at the list of all the banks supporting 2fa, I wanted to add Capital One and State Farm to the list. Adding Capital One is pretty straightforward, their twitter account is CapitalOne but they answer to tweets using AskCapitalOne. I've sent them a tweet asking about 2fa support and am waiting for a response, which should come soon enough. State Farm is a little trickier. I use them as a bank but most people use them for their insurance and their is no category for insurance on the list. Their twitter account is StateFarm. I've sent them a tweet asking them about 2fa as well and am waiting for them to respond. To my knowledge, at this time they both don't have 2fa unless I've somehow missed it.

Edit: Got a response from Capital One, https://twitter.com/ShlomoBoukai/status/504661618748563456. Basically, they don't have 2fa and don't plan to add it anytime soon. State Farm's response was odd, https://twitter.com/ShlomoBoukai/status/504660247404118016. I think it's safe to say they aren't adding 2fa either.

**Comment by dsoegijono** [comment]
Can you submit a pull request for Capital One? I think we should use AskCapitalOne for their twitter account.

As for State Farm, I think we can add insurance as a category?

**Comment by Keltian** [comment]
I would but I've never done a pull request and I'm terrified I'll break something. :(

**Comment by mxxcon** [comment]
won't break it. fork this repo, create a new branch and name it something useful. Then edit `/_data/banking.yml` file and follow other formats there. After you do that, on your repo's main page Github should give you a link to create a pull request.

**Comment by dsoegijono** [comment]
Don't worry, your request won't affect the site unless we merge it. Plus, it's just editing a YAML file and adding a PNG image. I can help you! 😀

Check out the contributing guide. Add your entry to the correct yaml file and add the image to the corresponding folder. Feel free to ask any questions.

**Comment by Keltian** [comment]
Oh wait, Capital One and Capital One 360 are already there. I swear I didn't see them when I checked the site earlier. Sorry.

**Comment by Carlgo11** [comment]
so can we close this ticket?

**Comment by dsoegijono** [comment]
Where are we on Insurance category? I think it makes sense to be added since most insurance sites will include sensitive information.
