### ISSUE TITLE
Add Roboform

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#733]
I received an email mentioning Roboform:

> I would like to let you know that Roboform,  Version 7.9.8, the password manager, has implemented 2FA for logon to its own online site for "Everywhere" accounts.  Only email is supported but allows for multiple devices.  Documentation is at:  http://www.roboform.com

**Comment by PaulMoore2014** [comment]
You should also know that SiberSystems (creators of Roboform) are actually changing their marketing / website to remove the phrase 2FA and use the correct term, 2SV...

Just a heads up ;)
