### ISSUE TITLE
Garena Two Factor Authentication Enrollment

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#739]
Just a heads up that right now, the enrollment flow for Garena Two Factor Authentication is broken.

I do not know if their two factor authentication still works, but even after filling the requirements, it still won't let me enroll. I have emailed them and they said that a fix was in the works, but that was two weeks ago.

Should we update the exception or wait a little longer?

**Comment by dsoegijono** [comment]
+1 for exception. I think 2 weeks is a long enough wait time.

**Comment by jamcat22** [comment]
Just tried to send them another email and was rejected by their saying my ticket was closed. They never told me my ticket was closed and the problem still isn’t fixed. Thinking of emailing them again.

**Comment by dsoegijono** [comment]
@jamcat22 Any updates on this?

**Comment by jamcat22** [comment]
I still haven’t received an email from them and they still haven’t fixed the problem, so I think we should just add the exception until they fix it.

**Comment by jamcat22** [comment]
Just created #790 to address this.
