### ISSUE TITLE
Mojang is looking into adding two-factor authorization

### ISSUE THREAD

**Issue by Daikamar** [2factorauth/twofactorauth#745]
Link to their Twitter response:
https://twitter.com/Daikamar/status/506494593936805889

Edited broken link (thanks Walkman100)

**Comment by Daikamar** [comment]
This work better?:

<blockquote class="twitter-tweet" lang="en"><p>Security is important, <a href="https://twitter.com/MojangSupport">@MojangSupport</a>. We&#39;d like it if you supported two factor auth. <a href="http://t.co/hyd24bQgX2">http://t.co/hyd24bQgX2</a> <a href="https://twitter.com/hashtag/SupportTwoFactorAuth?src=hash">#SupportTwoFactorAuth</a></p>&mdash; Stephen Sweeney (@Daikamar) <a href="https://twitter.com/Daikamar/statuses/506494593936805889">September 1, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/Daikamar">@Daikamar</a> We&#39;re currently looking into it. ^MW</p>&mdash; Mojang Support (@MojangSupport) <a href="https://twitter.com/MojangSupport/statuses/506714959753924609">September 2, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by Carlgo11** [comment]
So they're looking into it. Doesn't mean they're working on it

**Comment by dsoegijono** [comment]
Agree with @Carlgo11.
