### ISSUE TITLE
Where is our Listing

### ISSUE THREAD

**Issue by PortalGuard** [2factorauth/twofactorauth#746]
We had a thread to get PortalGuard added to the list of providers. That conversation is now missing, and we are still not added to the list of providers.

Please provide insight into the missing conversation and being added to the list of 2FA providers.

Thanks

**Comment by mxxcon** [comment]
Your pull request is still pending peer review at #688
Even after it gets merged there's some process before it appears on the actual website.
Have patience. :wink:

**Comment by PortalGuard** [comment]
Okay thanks. I was just wondering because the conversation disappeared, and I never received confirmation.

We will wait.
