### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by bclaymiles** [2factorauth/twofactorauth#762]
As the sixth most popular site on the Internet, it would be nice to have 2FA on top of plain passwords.

**Comment by Carlgo11** [comment]
It would. I hope you understand we can't force the sites to use tfa.
We only list whether they have it or not.

If you want to add a site to the list then make a PR.

**Comment by jdavis** [comment]
Does Wikipedia really fit any of the [Site Criteria](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) that we have though?

**Comment by mxxcon** [comment]
If somebody targets popular contributor/editor/moderator...?

**Comment by bclaymiles** [comment]
No, you're all absolutely right - I failed to review the Site Criteria listing. Fundamentally _every_ site on the internet should use strong auth, but that's not a reason to add all X billion of them to the list. :)

**Comment by jdavis** [comment]
@anastrophe That's exactly the reasoning that I had.

While it would be great if every site has it, I think Wikipedia being a non-profit with limited staff as it is can manage the pressure of stronger authentication without adding them to a list that just clutters their Twitter feed.

Thanks for the understanding as well as the suggestion =]

**Comment by smholloway** [comment]
I don't have strong feelings on the issue, but perhaps the site criteria could be expanded to include the top 10 sites in the [Alexa Top Sites List](http://www.alexa.com/topsites). Those are currently
1. Google.com - on the site
2. Facebook.com - on the site
3. Youtube.com - on the site
4. Yahoo.com - on the site
5. Baidu.com - international
6. Wikipedia.org
7. Twitter.com - on the site
8. Amazon.com - on the site
9. Qq.com - international
10. Linkedin.com - on the site

So it looks like Wikipedia is the only site that would sneak in with the expanded criteria.

**Comment by jdavis** [comment]
Okay, I'm fine with either way. If someone wants to add it, we can accept the pull request.

**Comment by Carlgo11** [comment]
From what I understand the issue has been answered and can be closed now.
