### ISSUE TITLE
OVH Don't support 2FA

### ISSUE THREAD

**Issue by ghost** [2factorauth/twofactorauth#763]
Despite the link in the site saying OVH have 2FA - This is wrong.

I got on to them about this, and here's their email.

Put a button/link there asking them to implement this!

![...](https://s3.amazonaws.com/f.cl.ly/items/3Q0W0j0L042n2v3x2J3P/a.png)

**Comment by mxxcon** [comment]
@SoHiggo can you ask them what's the meaning of https://www.ovh.ie/aboutus/security.xml#double-authentification then?

**Comment by ghost** [comment]
I think that's only for certain types of services they offer, like VPS. The standard hosting cpanel does not offer 2FA :(

**Comment by mxxcon** [comment]
@SoHiggo Would you be able to get a bit more details on that so that we can update the site with accurate exception?

**Comment by ghost** [comment]
I sent this http://s.higg.im/image/0S41052X2641

Just because it says it on the site doesn't mean it's accurate. It could be they once had it, but disabled it because I think they're migrating all customers to a new control panel...

Also - if enough people bombard them about this issue, they might feverishly push forward with it:

https://www.ovh.ie/support/

/ @jdavis

**Comment by RichJeanes** [comment]
This thread would seem to be superseded by #870
