### ISSUE TITLE
2SV is not 2FA

### ISSUE THREAD

**Issue by PaulMoore2014** [2factorauth/twofactorauth#778]
I raised this with Josh on Twitter earlier, but I haven't the time to make the necessary changes... so hopefully someone here is ready and willing to do so.

Long story short, the list is full of sites which offer 2SV but are incorrectly called 2FA.  They aren't the same, and shouldn't be listed as such.

The source either needs updating to correct the list or the 2SV sites need to be removed.

Cheers.

**Comment by mxxcon** [comment]
what is 2sv?

**Comment by PaulMoore2014** [comment]
two-step verification.

**Comment by mxxcon** [comment]
What's your distinction between these 2?

**Comment by PaulMoore2014** [comment]
https://ramblingrant.co.uk/the-difference-between-two-factor-and-two-step-authentication

**Comment by jdavis** [comment]
Since Paul is a bit terse with his responses, here's the discussion that we had: https://twitter.com/Rambling_Rant/status/512928078621069313

I was only slightly kidding with that last tweet about a pull request. I think a Fork would be more appropriate ;)

**Comment by PaulMoore2014** [comment]
I get the impression you disagree Josh?

I've no intention of creating a copy site, I don't see the point... but it would be helpful if the original gave more detailed info.

**Comment by Carlgo11** [comment]
Thanks Paul for teaching us the difference. I had no idea about this ^_^

I don't think we should change anything with our site right now though.

**Comment by PaulMoore2014** [comment]
Curious to hear the reasoning behind that @Carlgo11 :)

**Comment by smholloway** [comment]
The second step in two step verification is generally a second factor. If a site is listed and they never require a second factor, we can remove them. There are numerous ways to implement multi-factor authentication (any combination of possession, knowledge, and inherence, in-band or out-of-band, single page or multi-step, etc) -- as long as a site requires a second factor and fits the site criteria, it belongs on the list.

**Comment by jdavis** [comment]
@PaulMoore2014 I still feel that 2FA is where things should be heading. I wouldn't be surprised if a more secure ways to do true 2FA on the device side in the future.

But regarding the current issue of some sites being "technically" 2SV, like I've mentioned, I don't think it is a serious issue. If an attacker can copy OTP settings from a phone, then they have access to a second factor...

**Comment by PaulMoore2014** [comment]
@smholloway With respect, I think you've missed the point.

Perhaps I've misunderstood the purpose of the site, but I thought it was meant to outline what the site required, not what the user can use (SMS OTP, Email or Yubikey).  Google do not require a second factor.  Apple do not require a second factor... these are identity verification steps, after which, the user can sign in as usual.

@jdavis Straight 2FA is a headache, regardless of the method.  The tougher it is to sign in, the lower the adoption rate.  2SV allows a user to use a second factor without requiring it, offering a similar end result without the burden of requiring the "something you have" upon every login.

The ability the copy the second factor doesn't alter the fact it's a second factor.  It's technically possible to steal a printed list of OTPs, or clone an RSA SecurID... which is why it's vital to protect the physical device too.

There's no "technically" about it, they actively promote them as 2SV... only this site and a few misinformed reporters use the term "2FA".  If we're agreed 2FA is a better, more secure solution... would it not make sense for all these firms to advertise it as 2FA if that was actually the case?

**Comment by smholloway** [comment]
From [your diagram](https://ramblingrant.co.uk/the-difference-between-two-factor-and-two-step-authentication/) and [Google's documentation](https://www.google.com/landing/2step/#tab=how-it-works), Google requires a second factor to set up two step verification.

2SV can be multi-factor authentication, which is what this site seeks to promote. (From the header of the site: "List of websites and whether or not they support 2FA.") As I said before, if a site never requires a second factor, we will remove it.

**Comment by PaulMoore2014** [comment]
@smholloway If any site requires 2FA, it's **impossible** to sign in without it... it's a crucial part of the authentication process.  You can't "remember" it, there's no cookie involved.

Yes, 2SV can utilize a second factor (as the diagram shows) but it doesn't alter the fact the actual process, what is REQUIRED of the user, is 2 step.

2FA requires a prompt on every login (presumably on that, we agree).  There is absolutely no way to configure a Gmail (free or pro) account (or any other Google service) to work in that way.  Ergo, it must be 2SV.  By all means, list it... but as 2SV so the user knows it's weaker than 2FA, but still a great addition.

**Comment by jamcat22** [comment]
@PaulMoore2014 To require a prompt on every login in Gmail, simply do not enter any account recovery information, enable any backup codes, or enable a recovery device. Then never check the box to trust the computer or "Remember me". A cookie never gets set, and there is no way to login without the second factor.

In the case of a pro/Google Apps Gmail account, the organisation administrator can disable the "Remember me" and "Trust this computer" features making it impossible to login without the second factor.

Also, it is very hard to differentiate between 2FA and 2SV because most companies/websites don't know the difference and just treat the two as different terms for the same thing. There are some websites that market what is actually two factor authentication as two step verification, and market what is actually two step verification as two factor authentication. This means it would take a VERY long time to go to every single one of the websites on this list and categorize/tag them as 2FA or 2SV.

**Comment by PaulMoore2014** [comment]
@jamcat22 

What you've described with Google is still 2SV.

I disagree that it's difficult to differentiate them, it's very simple if you understand the concept.  2FA is a requirement, 2SV is a process.  If a second factor is an "option", it's 2SV.

If Google, Apple et al call it 2SV, label it as such.

**Comment by Carlgo11** [comment]
@PaulMoore2014 I thought we agreed on not to raise this question again. We, the collaborators, and @jdavis have agreed on not to separate 2SV and 2FA.

You're more than welcome to inform people about this on your own sites but we won't do it here.

**Comment by rublon-mw** [comment]
I agree with @jdavis and the collaborators. I believe that differentiating between 2FA and 2SV at this stage would create more confusion than it's worth. Thank you for bringing this up though, @PaulMoore2014.

**Comment by PaulMoore2014** [comment]
@Carlgo11 

I replied to a comment, I didn't raise the topic again :/

**Comment by jamcat22** [comment]
Sorry! Didn't mean to bring this up again.

I'll shut up now :)
