### ISSUE TITLE
SSL certificate is invalid

### ISSUE THREAD

**Issue by pwaller** [2factorauth/twofactorauth#791]
If I visit twofactorauth.org, I see that has is an invalid certificate. It's for cloudflare, but `twofactorauth.org` isn't included in the subject-alternative-name. Same for https://joshldavis.com/.

![image](https://cloud.githubusercontent.com/assets/438648/4446378/d77209dc-4801-11e4-92a7-4109ca4c3c29.png)

![image](https://cloud.githubusercontent.com/assets/438648/4446381/e1acc5a4-4801-11e4-9db2-e2851b52a2e8.png)

**Comment by Carlgo11** [comment]
Yes this is due to a cloudflare update.
https://blog.cloudflare.com/introducing-universal-ssl/

It will be fixed sometime today.

**Comment by jdavis** [comment]
Yeah, I have a Pro account and was going to transition to the universal SSL but apparently they are rolling it out. SSL should be back and working within a few minutes.
