### ISSUE TITLE
Please add SmartSign to your list of providers

### ISSUE THREAD

**Issue by nick-smith-microcosm** [2factorauth/twofactorauth#798]
SmartSign is a 2FA solution currently offering soft-token and email-based OOB authentication.

You can find more information here:
https://smartsignsecurity.com

**Comment by Carlgo11** [comment]
Would you like to add it yourself?
Read the <a href="https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#new-providers">CONTRIBUTING.md</a>. It's not very difficult to add a site.  
Don't forget that you need to add a 32x32px logo.

**Comment by Carlgo11** [comment]
Also, what sites use SmartSign?

**Comment by mxxcon** [comment]
Covered in #800.
