### ISSUE TITLE
Reports of Dropbox Compromise

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#810]
The details aren't out yet but apparently something has happened.

I didn't receive any emails so I don't know for sure, but apparently this is the email they sent out:

> Hello Dropbox users,
> Tonight (10/13), Dropbox suffered a security breach that has resulted in the publishing of thousands of passwords online. Please change your Dropbox passwords immediately, and if possible, enable a form of 2-factor Authentication (where a cell phone is used to receive a secondary 6-digit PIN that is required for you to log in). You can enable 2-factor Authentication by logging into Dropbox, clicking the drop-down in the upper right-hand corner, choosing Settings, then the Security tab, and clicking “Enable” next to “Two-Step verification”.
> If the account is shared, you will either need to choose a device you all have access to, or go on without the two-factor authentication.
> For the record, you can also enable two-factor authentication on services like Evernote, Gmail (and all Google apps), OneDrive, iCloud, Hotmail, eBay, and many common banking websites. You can view a list of sites that support it, with instructions for each of them, at this URL: https://twofactorauth.org/

Notice that last link? Yeah, I think that's pretty awesome. Great work everyone.

**Comment by jeffgodwyll** [comment]
:+1: Yeah nice!! Pretty awesome. Congrats

**Comment by Carlgo11** [comment]
That's awesome!😃 :cake:

**Comment by Carlgo11** [comment]
well not the security breach. That's just awful. A company like Dropbox should be able to keep their users safe.

**Comment by mxxcon** [comment]
Dropbox has some very smart people working there, yet they have one of the worst security track record of any service provider. :disappointed:

**Comment by Carlgo11** [comment]
More information about this: http://thehackernews.com/2014/10/nearly-7-million-dropbox-account.html

**Comment by dsoegijono** [comment]
@Carlgo11 I was gonna mention the article quoted on your link; Dropbox is saying it wasn't their service that was hacked, but third party apps that users connected to their Dropbox account, so it's actually not their security flaw

**Comment by Carlgo11** [comment]
@dsoegijono  Yeah sadly that's often the case.
Looks to be the case of the fappening and snappening for example.  

I always nag about the importance of not using a password twice. Right now my family and friends are probably pretty feed up with it ;)
But once again I get to say I told you so.

Normal people havent adapted the Internet security eara. That's why I love this site ;)

Btw, if you ever talk to someone who refuse to let go of their standard password. Login to their email and Mail them from themself.
Never stops to amuse me 😄
