### ISSUE TITLE
Hi, Hoping you would add a category Graphic Arts, Photography

### ISSUE THREAD

**Issue by eossipov** [2factorauth/twofactorauth#819]
Adobe http://www.adobe.com (no)
Behance http://www.behance.net (no)
TypeKit (Adobe) (no)
Creative Market (no)
Deposit Photos (no)
Big Stock (no)
iStock Photo  http://istockphoto.com  No.

I took a shot of the front page and will provide you with a spread sheet later you can simply upload if that would help?

**Comment by Carlgo11** [comment]
Does the sites fit the <a href="https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria">site criteria</a>?
I can see why Adobe should be added but I don't know about the others.

**Comment by jamcat22** [comment]
Agree with @Carlgo11 so far on this one. We should probably add Adobe and maybe the others, but I don't think we need a new category for them.

**Comment by mxxcon** [comment]
What negative sid-effect would there be (beside account compromise) if somebody gets access to stock imagery site?

**Comment by snaray** [comment]
Well, any stock photo site that charges for access to content can incur false charges if an account is compromised (and if credit cards\* are kept on file), just like any other retailer. Though I don't see why they wouldn't just be listed under retailers.
- even if it's just the token & not the actual card number, a bad actor can charge downloads to it.

Adobe should be added though - customers can buy direct from them, lease cloud services (including online storage), they have an Enterprise licensing portal, and they're a major DRM platform for 3rd-party content providers.

**Comment by eossipov** [comment]
Hi, Folks, Sorry I don't know why I didn't receive any notification on this issue, but At least I'm seeing it now.

Regarding negative side-effects: Image sites can do a large volume especially sites like depositphotos where the originating business is East Asian, and have many people using their api, in addition to corporate clients. You are Required to have a subscription  + CC ON FILE, for that ever useful monthly transaction or a person can opt to purchase tokens, but many business accounts wouldn't do that. 

So, as in any other site that keeps CC on file, who knows if it's encrypted or not? Stored with the client info or not?  We don't, not until you look at a database. I've had people who wanted re-designs or consulting who have emailed me their database with all their clients CC's in there, unencrypted, right in the same row as a persons username and unencrypted password, and address, and zip code, etc. 

I'm sure everyone has horror stories like that, else, 2FA wouldn't be needed. 

sorry for the incorrect wording of "category" I believe I mean "section" (of the page, just a section for "graphic sites"

**Comment by jdavis** [comment]
I can understand wanting to protect various Adobe cloud products but I agree that stock photography doesn't fit the criteria. Even if they are targeted and their stuff is compromised, I can't imagine it is a common occurrence for those websites and I bet they would be able to do a refund quite easily and rectify things.
