### ISSUE TITLE
Exploring ways to list all sites

### ISSUE THREAD

**Issue by smholloway** [2factorauth/twofactorauth#828]
We have a lot of pent up demand for listing arbitrary sites. It's awesome that people want to contribute to the site, and that two factor auth has become so popular. What if we added a new page for sites that don't fit the criteria? Perhaps putting the data in `miscellaneous.yml`, `everything_else.yml`, or `less_popular.yml`. This allows us to keep the main page lean and focused while also listing sites that people care enough about to contribute. 2FA all the things!
## Pros:
- maintain our place as _the_ go-to source for 2FA availability
- encourage companies of all kinds to implement strong authentication
- allow broader participation
- it is easier to ask people to move their site to the `misc` section than it is to tell them that their contribution doesn't belong
## Cons:
- slow page load times
- GitHub scorn for having a repo that is too large
- too many PRs to keep up with
- lack of focus makes the `everything else` page impossible to use effectively
- the glut of sites forces us to add filter, search, and other features sooner rather than later

Thoughts?

**Comment by mxxcon** [comment]
"less_popular" would be a pretty arbitrary criteria and then you'd get marketing people from those sites protesting and asking to be moved elsewhere.(kinda like what we get in providers section every once in a while).
Maybe we should relax criteria for "other" section?
Alternatively, while we agree that we can't list everything, list only sites from top Alexa1000 or similar index?

I doubt this repo is anywhere near the size where GitHub would complain.

**Comment by Walkman100** [comment]
https://help.github.com/articles/what-is-my-disk-quota/
1 GB is their recommended limit.

**Comment by mxxcon** [comment]
And we are only 8megs. :smile:

**Comment by jdavis** [comment]
I still really want to get filtering working by the end of the year. It just hasn't been as high of a priority as the other things lately.

If we had filtering working correctly, we could do a lot of this really easily with a smart client and wouldn't have to be so picky about what sites go onto the list.

**Comment by mxxcon** [comment]
Perhaps @AaronTraas could assist with this?

**Comment by jdavis** [comment]
Is he someone you know, @mxxcon?

**Comment by mxxcon** [comment]
He's my coworker and is a lot more skilled at coding than me.

**Comment by smholloway** [comment]
Here's a hack that might work as a stopgap: add an additional field to every entry, say `topSite` for lack of a better term, that we use to show or hide a site by default. 

Here's some psuedocode for those who think in code:

```
{% for provider in sorted_providers %}
    {% if provider.topSite %}
        <tr>
    {% else %}
        <tr class="hide">
    {% endif %}
    ...
```

I'm not sure if I like that or not...

**Comment by RichJeanes** [comment]
Is this still an issue or close?

**Comment by jamcat22** [comment]
I'd say close due to the filtering issue.

**Comment by Carlgo11** [comment]
Opened due to a empty glass falling onto the touchpad. Closing again
