### ISSUE TITLE
Google just added hardware security key support

### ISSUE THREAD

**Issue by beriberikix** [2factorauth/twofactorauth#832]
http://googleonlinesecurity.blogspot.com/2014/10/strengthening-2-step-verification-with.html

**Comment by jamcat22** [comment]
Thanks very much @beriberikix! Do you want to make a pull request, or would you like me to?

:+1:

**Comment by mxxcon** [comment]
btw, this brings up a point for potential new column. It seems like that FIDO standard is getting some traction. Perhaps it makes sense to tag services that use Fido-compatible 2fa?
(I personally have no opinion yet since I didn't read the specifics.) But maybe this is something we should consider.

**Comment by beriberikix** [comment]
Feel free @jamcat22 :)

**Comment by jamcat22** [comment]
Just created a pr (#834). Thanks @beriberikix!
