### ISSUE TITLE
Expired Cert

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#833]
Sigh, I am migrating from my pro account for Cloudflare since Universal SSL is free. I disabled the Pro account and I knew that it would expire my Cert while it generates a new one. I did it last night hoping that I would have a new one this morning. It hasn't renewed as of now so I opened up a ticket with them. I also disabled URL redirecting for the time being so http://twofactorauth.org won't go to the expired https.

I'm just letting you all know.

**Comment by Carlgo11** [comment]
Last night means middle of the day in Europe

**Comment by jdavis** [comment]
It's always day somewhere.

**Comment by Carlgo11** [comment]
Could be TOR but for me the cert is still invalid

**Comment by jdavis** [comment]
Support got back to me and apparently it takes 24 hours.

**Comment by jdavis** [comment]
Good lord, Cloudflare. It could be fixed any day now...

**Comment by jdavis** [comment]
It  finally has been renewed.
