### ISSUE TITLE
Webroot Security

### ISSUE THREAD

**Issue by bclaymiles** [2factorauth/twofactorauth#836]
Webroot sells antivirus, fw, etc internet security applications for desktops, mobile, etc. As such, I'd guess they could go under the 'security' aegis.

They use a rather silly form of two factor - you set up a PIN - at least eight characters I believe - then after you log in with username/pass, it asks you to enter, for example, the third and fifth character of the PIN. Or the first and sixth, or some other pair of numbers from it. In one respect that's not bad - but it just encourages using a simple PIN so you can remember your way through the request. Real two-factor would be more desireable. 

Can they be added to the list?

**Comment by mxxcon** [comment]
additional pins/passwords do not really qualify as proper two factor auth. See https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions
So if Webroot were to be added, it would be with `tfa: no`.

**Comment by Carlgo11** [comment]
Quoting <a href="http://en.wikipedia.org/wiki/Multi-factor_authentication">Wikipedia</a>, `"Multi-factor authentication (MFA) is an approach to authentication which requires the presentation of two or more of the three independent authentication factors: a knowledge factor ("something only the user knows"), a possession factor ("something only the user has"), and an inherence factor ("something only the user is")."`
Password is something you know, username is something you know, PIN is something you know.
That's just one factor authentication. 
1 != 2 ;)
Doesn't fit our site.

**Comment by bclaymiles** [comment]
A site that does not have MFA is _not_ something that you want listed in order to encourage them to implement MFA?

That's a weird rationale. If that rationale holds, then shouldn't all the dozens of other sites that lack MFA be removed from the page?

**Comment by mxxcon** [comment]
@anastrophe you are correct. Do you want to submit a pull request to add it? it's just a simple YAML block..

**Comment by bclaymiles** [comment]
I'm not really a coder. I'd worry I'd screw something up.

**Comment by jdavis** [comment]
Don't worry, Travis will tell you quite quickly and harshly if you've messed anything up. He's kind of a jerk.

**Comment by bclaymiles** [comment]
Ha! Well okay, I'll give it a whirl.

**Comment by bclaymiles** [comment]
I'm out of my depth. Sorry.

**Comment by mxxcon** [comment]
@anastrophe see #838, it's not so difficult. :smiley:
Find another entry worth adding and try again. Feel free to ask questions.

**Comment by jdavis** [comment]
Closed by #838.
