### ISSUE TITLE
Consider increasing the standard icon resolution from 16x16

### ISSUE THREAD

**Issue by computmaxer** [2factorauth/twofactorauth#84]
This would help save the eyes of high-DPI screen users like the Retina Macbook pro from seeing pixelated icons.

**Comment by jdavis** [comment]
Oh poo, they look pixelated on retina displays?

**Comment by jdavis** [comment]
I don't have a Retina display (pity me), but does 32x32 look fine? If so, we could go with that and add it to the README.

**Comment by computmaxer** [comment]
So I just realized part of the problem is that a lot of the icons are 16x16 but are being displayed at 24x24.

From what I've read about retina support, you generally want to double the resolution.  So perhaps we want 48x48.

**Comment by RichJeanes** [comment]
It looks like it's been settled in #103 at 32x32 and added to the README. Closing this for the sake of tidiness.
