### ISSUE TITLE
status for compatibility with RFC 6238 and RFC 4226 OTP USB token

### ISSUE THREAD

**Issue by jans23** [2factorauth/twofactorauth#842]
It would be great if twofactorauth would tell which service is compatible to OTP-based (RFC 6238, RFC 4226) USB token like Yubikey and Crypto Stick. This way users of such token could easily figure which site they could use quickly without purchasing a new device.

BTW, the column "hardware token" seems to be too broad and to contain proprietary devices also.

**Comment by Walkman100** [comment]
https://github.com/jdavis/twofactorauth/issues/832#issuecomment-60034532

**Comment by Carlgo11** [comment]
I think that's a bit of a overkill.  
Sure, we could change the list to providing exactly what kind of tfa systems the site supports but that would look awful. I think it's better just to use the docs most sites provide to learn what systems they use.

**Comment by mxxcon** [comment]
@jan234 A while ago we intentionally decided to switch from listing specific implementations in columns to these generic terms. Otherwise we would be adding columns for each new spec or vendor variation.

**Comment by jans23** [comment]
Thanks for the feedback. I understand if this is overkill for your visitors. Hence, I would consider a friendly fork just for this purpose. It should be okay with your MIT License.

**Comment by mxxcon** [comment]
By all means fork away :wink:. And I imagine if your idea of these modifications will work out be better for users, we can merge it back here.

**Comment by jans23** [comment]
Hi! I created a friendly fork of twofactorauth which lists OTP (OATH) and U2F compatible websites only. See: https://github.com/Nitrokey/dongleauth/ and http://www.dongleauth.info
