### ISSUE TITLE
Request for PayU

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#850]
Like usual, this was through an email that I received. The requester wanted to remain anonymous.

https://twitter.com/_PayU
https://secure.payu.com/user/login

**Comment by mxxcon** [comment]
do they support tfa or not? looks like a Polish site?

**Comment by rublon-mw** [comment]
I know Polish and I wasn't able to find any option that would allow you to turn on 2FA inside your PayU account. Just logged in using my password.

**Comment by Walkman100** [comment]
Well the Twitter profile is in South Africa (#ProudToBeSouthAfrican :smile:)

**Comment by RichJeanes** [comment]
Bump.
Shall we close this based on @mwww's investigation?
