### ISSUE TITLE
Indicate when SMS is mandatory

### ISSUE THREAD

**Issue by WhyNotHugo** [2factorauth/twofactorauth#851]
Some providers (eg: digitalocean, facebook) require that users have an SMS-capable mobile line to enable software-based 2fa.

I believe this should be indicted as well. It's not the same when a provider allows any software impelentation as to when having an SMS is mandatory. Both of the above examples are unusable by some people (eg: me), because not everybody has a sms-capable mobile line.
- Digital ocean requires an SMS-capable line.
- Facebook requires an SMS-capable _mobile_ line, and does not support using Google Voice.

**Comment by Carlgo11** [comment]
And how come you don't have a SMS capable phone? I mean even most land lines support SMS nowadays

**Comment by WhyNotHugo** [comment]
> And how come you don't have a SMS capable phone? I mean even most land lines support SMS nowadays.

That may be true in the where you're from, but not elsewhere. My landline phone service provider does not support SMS. AFAIK, only one in Argentina does (we've quite a few phone service providers here), and even they don't cover most of the country.
Even if I had the service, most of the landline phones (eg: the devices) sold here don't support SMS (for some reason, we still use very very very old landline devices).
I'm not sure what the situation is in most countries, but you shouldn't assume it's the same everywhere and for everyone.

Also, facebook explicitly states they **do not** support sending SMS to landlines.

I don't have a mobile phone line because it's way too expensive for me and I have no use for it. Again, the costs for these things are not so low all around the world.

---

Anyway, my point is not to debate this, but rather just to add some sort of indicator to those providers that don't support standalone software devices, but require software+sms.

**Comment by mxxcon** [comment]
@hobarrera how do you suggest we show this? are there more than 2 companies from our list that use this method?

**Comment by smholloway** [comment]
I'd suggest you add an `exceptions` on the affected sites, then open a pull request.

Here's an example of using the `exceptions` field (taken from [backup.yaml](https://github.com/jdavis/twofactorauth/blob/master/_data/backup.yml))

```
  - name: iCloud
    url: https://www.icloud.com
    img: icloud.png
    tfa: Yes
    sms: Yes
    software: Yes
    exceptions:
        text: "SMS only available on select providers."
    doc: http://support.apple.com/kb/ht5570
```

**Comment by RichJeanes** [comment]
Bump.
Seems a fairly straight forward issue. Is this something we would like to pursue? It would seem that this is probably something that we would like contributors to note when first adding a site. If someone else wants to go back and update existing sites, PRs can be opened.
Just trying to see if we can either mark it on-going or close it for housekeeping.

**Comment by Carlgo11** [comment]
@psgs do you volunteer? :wink:

**Comment by fpigerre** [comment]
Sure @Carlgo11 :smiley:

Also @hobarrera, it appears that Facebook users are able to use the Facebook application on their mobile phone, instead of an SMS-capable line. Is this correct?
The fact that SMS is mandatory is usually also indicated when the `SMS` section of the table is checked, and the `Software Implementation` section is unchecked.

**Comment by jdavis** [comment]
Closing because #902 was merged.
