### ISSUE TITLE
Add Genesys IVR System (http://www.genesys.com/)

### ISSUE THREAD

**Issue by thigley986** [2factorauth/twofactorauth#853]
Add Genesys IVR Service (http://www.genesys.com/).  Does not currently support 2FA.

**Comment by mxxcon** [comment]
> Genesys is the market leader in multi-channel customer experience (CX) and contact center solutions in the cloud and on-premises. We help brands of all sizes make great CX great business. The Genesys Customer Experience Platform powers optimal customer journeys consistently across all touchpoints, channels and interactions to turn customers into brand advocates.

Holy crap...talk about marketing bullshit generator. :confused: I still don't understand what they do... 
@thigley986 does this site match https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria and what category would it fit into?

**Comment by thigley986** [comment]
I believe it does meet the criteria.  Genesys mainly deals in interactive voice response and call center management delivered as SaaS apps for businesses.  They are fairly large in the small and medium business space.  Genesys handles sensitive data entered over their platform by consumers, like credit cards and social security numbers.  A compromise of their administration tools could allow an attacker to divert information flows to a malicious endpoint or insert an endpoint into the flow that captures that information..

**Comment by Carlgo11** [comment]
The providers page is being removed. You can read more about that on #1177.
