### ISSUE TITLE
We are in a book!

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#866]
I got an email from the authors of the book called [Protect Your Tech: Your geek-free guide to a secure and private digital life](http://smile.amazon.com/exec/obidos/ASIN/1502908662) saying they put a link to our site in their book.

I thought it was a neat gesture. The book is free for the next few days on Kindle too.

**Comment by mxxcon** [comment]
:grinning:

**Comment by jamcat22** [comment]
Yay! :D

**Comment by Carlgo11** [comment]
But why does it have to be kindle?! I'd much rather buy an iBooks version :/

**Comment by dsoegijono** [comment]
@jdavis They didn't give you a free copy of the book? 😛

**Comment by ilyakatz** [comment]
that's great, all 200+ contributors deserve a :cake:

**Comment by Walkman100** [comment]
Since # 871 is getting quite long (and this has nothing to do with either PR):
http://securityreactions.tumblr.com/post/108177214796/management-has-decreed-that-2fa-will-be-stripped
Thought you guys could get a kick out of that :P

**Comment by jdavis** [comment]
Hahah, nice.

**Comment by Carlgo11** [comment]
Well since we're here, 
Here's my book ^_^ <img src="http://i.imgur.com/3WpQMMh.jpg">
