### ISSUE TITLE
Add Dreamhost

### ISSUE THREAD

**Issue by nomad-geek** [2factorauth/twofactorauth#868]
Dreamhost supports Google Auth.

**Comment by Carlgo11** [comment]
Any docs or mail from Dreamhost that confirms this?

**Comment by mxxcon** [comment]
http://wiki.dreamhost.com/Enabling_Multifactor_Authentication

**Comment by dsoegijono** [comment]
We already have `software` for Dreamhost. It also supports Yubikey though. Does that count as `hardware`?

**Comment by RichJeanes** [comment]
No, this does not count as `hardware`. It only supports Yubikey through Yubikey OTP. The only difference between that and Google Auth is that the secret key is stored on the Yubikey instead of your phone.
Seeing as Dreamhost is already listed as supporting `software`, I'm closing this.

**Comment by smholloway** [comment]
We have been classifying Yubikey as `hardware`. When I created the column I thought that `hardware` would include any dedicated piece of hardware, like Yubikey or RSA SecurID.

**Comment by RichJeanes** [comment]
This is simply using a Yubikey as a generic OTP generator with the key hardware replacing the phone hardware and still relying on software (the Yubikey Personalization Tool installed on the computer vs an app on the phone), therefore dependant on the software. A hardware solution should be standalone, such as a device that displays the key on it or a FIDO U2F compliant device. If this method of using Yubikeys as OTP generators is considered `hardware`, then by the same logic, Google Auth et all should be too.
@jdavis Would you agree with this reasoning?

**Comment by RichJeanes** [comment]
@jdavis This discussion seems to be evolving in multiple places.
For your consideration: #719 and #895 
Your input would be appreciated in these areas.
