### ISSUE TITLE
Paypal no longer offers 2FA hardware

### ISSUE THREAD

**Issue by n8willis** [2factorauth/twofactorauth#880]
The Paypal hardware two-factor auth token is no longer for sale.  It continues to work for those who still have one, but they are not distributing new or replacement untis. They aren't clear about this on the web site, but I emailed customer service and got a straight answer.

They say they're lookign at other options for the future and will put you on a notification list (perhaps that's in reference to the FIDO U2F stuff), but there needs to be a note added to their entry on this site explaining that the hardware option has been discontinued. At the very least; it probably should be marked as a "no".

**Comment by mxxcon** [comment]
Would you like to submit a pull request with such an exception?
