### ISSUE TITLE
Tresorit 2FA is read

### ISSUE THREAD

**Issue by bobem** [2factorauth/twofactorauth#882]
Visit the blog for more info: https://tresorit.com/blog/introducing-2-step-verification-for-tresorit/
Tresorit 2 step verification options: either SMS, voice call, a verification app or an email.

**Comment by mxxcon** [comment]
@bobem This was updated in #875 just main website have not been regenerated yet.
Perhaps @jdavis could do it?

**Comment by bobem** [comment]
@mxxcon thx! somehow I missed that. Hope it will be up soon.

**Comment by jdavis** [comment]
Ah, sorry guys. I'll update it now.

**Comment by jdavis** [comment]
Besides accidentally clobbering the gh-pages branch and restoring it, I've updated the site. It should work for you now, @bobem.
