### ISSUE TITLE
Vanguard now supports 2FA.

### ISSUE THREAD

**Issue by annonman** [2factorauth/twofactorauth#892]
Supports only text message auth.

Option for device based code, or every time you log on.

![screen_shot_2014-12-02_at_5_18_30_pm](https://cloud.githubusercontent.com/assets/5091348/5272126/02ea2bbc-7a48-11e4-808b-cf864ebde6cd.png)

**Comment by mxxcon** [comment]
@annonman what's that "learn more" link?

**Comment by annonman** [comment]
It's part of the image.

**Comment by mxxcon** [comment]
but what is the actual url there?

**Comment by annonman** [comment]
Javascript popup.

How security codes work

What you'll see when you log on:

After you enter your user name, we'll send you a security code via text message to your cell phone.

Phone displaying message that reads Vanguard security code: 123123 Code expires in 5 mins. 1 msg/req Reply HELP for help, STOP to cancel, Msg&Data Rates May Apply      

Enter the security code on our site, then your password, to complete the logon process.

Vanguard logon screen showing input field for security code

How frequently will I receive a security code?
When you set up this service, you choose whether you want to receive a security code every time you log on to vanguard.com or our mobile apps or only when we don't recognize the device that you're using.

Do I have to save the security code?
No. Each time you log on, you'll receive a unique 6-digit code via text message that can only be used once. The code will expire after 10 minutes.

If I enroll in the security code service, do I access my Vanguard accounts as I do today?
You'll continue to use your current user name and password to access your Vanguard accounts online. If you've enrolled in the service, you'll be prompted to enter a security code during log on in lieu of your security question. You won't be able to access your accounts through the mobile website (vanguard.mobi) if you've enrolled in this service.

Can I change where the security code is sent while I'm logging on?
No. We'll always send the security code to the phone number you entered during the setup process. To protect your account, we don't allow you to change this phone number during the logon process.

If you have individual accounts, you can change the phone number associated with this service through the Account Maintenance area by clicking Security code and selecting Edit next to your registered phone number.

If you have accounts through an employer-sponsored plan, you can change the phone number associated with this service by clicking My Profile and then choosing Overview. On the next page, click Security code and select Edit next to your registered phone number.

How do I change where the security code is sent?
If you have individual accounts, you can change your phone number through the Account Maintenance area by clicking Security codes and selecting Edit next to your registered phone number.

If you have accounts through an employer-sponsored plan, you can change your phone number by clicking My Profile and then choosing Overview. On the next page, click Security codes and select Edit next to your registered phone number.

How long does it take for me to get my security code?
It depends on your text message carrier. Typically, you'll receive your security code within a few seconds.

Should I use this service if I've registered with a data aggregation service?
If you use aggregation tools like Mint.com, you may not want to sign up for this security feature. Since these software tools access your accounts on your behalf—and can't enter a security code during logon—you could potentially lock yourself out of your account. The security code service will work if you use CashEdge, Quicken, or Yodlee, however.

Which carriers are set up to send security codes via text message?
Alltel, AT&T, MetroPCS, Cricket, T-Mobile, U.S. Cellular, Sprint, Google Voice, Boost, Virgin Mobile, Verizon Wireless, and others.

Standard carrier message and data rates may apply.

What if I don't have access to my phone when I log on, but I'm enrolled in this service?
If you're set up to enter your security code only when we don't recognize the device you're using, please log on from a recognized device (so we won't ask you to enter a security code).

Please contact Vanguard for assistance if you don't have access to a device that we recognize or are set up to enter your security code every time that you log on to vanguard.com or our mobile apps.

Do I still need to remember my security questions and answers?
Yes, you may need to answer your security questions and answers when calling Vanguard. Also, for your protection, we may ask you to answer your security questions and answers before processing certain clerical transactions.

How do I disable this service?
If you have individual accounts, you can disable this service through the Account Maintenance area by clicking Security code and selecting Disable next to your service status.

If you have accounts through an employer-sponsored plan, you can disable this service by clicking My Profile and then choosing Overview. On the next page, click Security code and select Disable next to your service status.

Do not reply to a Vanguard text message to disable this service.

**Comment by jdavis** [comment]
Yup, I can confirm that 2FA is available for Vanguard now. I've made a PR #894  so head over there @annonman and let me know what you think.

**Comment by annonman** [comment]
Looks Good.
