### ISSUE TITLE
Hipchat is working on two factor authorization

### ISSUE THREAD

**Issue by matt-the-ogre** [2factorauth/twofactorauth#893]
According to their twitter reply, Hipchat is working on 2FA.
![screen shot 2014-12-03 at 10 53 40](https://cloud.githubusercontent.com/assets/2666810/5286622/bb38e450-7ada-11e4-8dd1-df13d061ef86.png)

**Comment by mxxcon** [comment]
I don't trust that reply. I think it's misleading
Considering this huge thread about their BitBucket 2fa support https://bitbucket.org/site/master/issue/5811/support-two-factor-authentication-bb-7016#comment-13824468
They are supposedly working on an overall Atlassian SSO system which at some point in the future might support 2fa.
I'm pretty sure HipChat is in the same boat, but would love to be proven wrong..

@matt-the-ogre would you consider following up with that reply to get clarification if they are actually working on a separate HipChat 2fa or do they mean Atlassian accounts/sso system?

**Comment by matt-the-ogre** [comment]
I'm on it -- more info when I hear back.

**Comment by matt-the-ogre** [comment]
Their response was "We don't speak for Atlassian." Which I take to mean
they are independently developing 2FA ahead of the SSO solution.

On Wed, Dec 3, 2014 at 11:24 AM, mxxcon notifications@github.com wrote:

> I don't trust that reply. I think it's misleading
> Considering this huge thread about their BitBucket 2fa support
> https://bitbucket.org/site/master/issue/5811/support-two-factor-authentication-bb-7016#comment-13824468
> They are supposedly working on an overall Atlassian SSO system which at
> some point in the future might support 2fa.
> I'm pretty sure HipChat is in the same boat, but would love to be proven
> wrong..
> 
> @matt-the-ogre https://github.com/matt-the-ogre would you consider
> following up with that reply to get clarification if they are actually
> working on a separate HipChat 2fa or do they mean Atlassian accounts/sso
> system?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jdavis/twofactorauth/issues/893#issuecomment-65471197
> .

## 

www.mattmanuel.com
