### ISSUE TITLE
Vanguard supports SMS

### ISSUE THREAD

**Issue by jjohns63** [2factorauth/twofactorauth#896]
Vanguard has added two-factor authentication via SMS.
No backup codes though.

**Comment by mxxcon** [comment]
do you have any doc links for that?

**Comment by jjohns63** [comment]
I was prompted to set it up when I logged in today. I can't find any doc that's accessible from outside an account, but here's the screenshot of the info page and the login notice.
![vanguard_sc](https://cloud.githubusercontent.com/assets/616725/5307893/4646f7f6-7bd7-11e4-9d7d-947da196081b.png)
![vanguard_sc3](https://cloud.githubusercontent.com/assets/616725/5307959/ca87c8d8-7bd7-11e4-8ee2-569c24a5bfb4.png)
![vanguard_sc2](https://cloud.githubusercontent.com/assets/616725/5307976/f69cfd26-7bd7-11e4-9bc2-2460cc3c025d.png)

**Comment by jdavis** [comment]
There are no doc links. I addressed this in this pull request: #894.
