### ISSUE TITLE
Koding?

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#899]
http://koding.com is a site for developers to get free access to virtual machines to, well, develop on. But you can also host websites on it and they have subscription tiers which means they host payment info.

So
1. Is Koding sensitive enough to be on tfa.org? (I'm thinking yes because of the already expansive lists of hosting providers, even if it is intended to be more of a practice/testing platform)
2. If yes to 1, what category? Developer or hosting? (I would lean towards the former, but thought I'd get input)

**Comment by Carlgo11** [comment]
If they provide VMs then I'd say it's hosting

**Comment by RichJeanes** [comment]
Well they're VMs specifically for developing on, you don't get a ton of horsepower on any tier. You just have the ability to host your projects with public facing IPs/domains (not even custom ones, just vm.uname.koding.io). 
![koding_plans](https://cloud.githubusercontent.com/assets/6753081/5320627/e49ef61c-7c70-11e4-871d-2a71eb0bbc75.PNG)

**Comment by mxxcon** [comment]
I think if it gets listed, it should be dev category.

**Comment by jamcat22** [comment]
+1 for Developer category

**Comment by Carlgo11** [comment]
Okay developer category it is. So do we agree that the site fits site requirements?

**Comment by jamcat22** [comment]
I do. :D

**Comment by Carlgo11** [comment]
Urgh why can't github have a working label management for the mobile version of their site?! I always misclick

**Comment by jdavis** [comment]
Developer is the perfect place for it.

**Comment by RichJeanes** [comment]
I'll go ahead and work on adding Koding then and add the PR when it's in.
