### ISSUE TITLE
Schwab Entry Incorrect

### ISSUE THREAD

**Issue by Starcom** [2factorauth/twofactorauth#90]
This would probably go under the custom category, but Schwab supports 2FA by way of hardware security tokens which may be requested for free.

http://www.schwab.com/public/schwab/nn/legal_compliance/schwabsafe/protect_your_account

**Comment by Starcom** [comment]
Oops, the entry showed up wrong due to my NoScript settings. Closing.

**Comment by mpdavis** [comment]
As you saw, we already had that info, but I like your link better, so I am going to go ahead and replace it with yours.  Thank you.
