### ISSUE TITLE
Add a warning for Charles Schwab

### ISSUE THREAD

**Issue by somethingnew2-0** [2factorauth/twofactorauth#914]
As described in this [blog post](http://www.jeremytunnell.com/posts/swab-password-policies-and-two-factor-authentication-a-comedy-of-errors), Charles Schwab 2FA is not actually required when enabled and therefore doesn't actually work.  I would go so far as to suggest removing them altogether until this issue is resolved.

**Comment by jamcat22** [comment]
That is not what the blog post is saying. The blog post says that sometimes, the token may not be enabled properly if you tried to set a password over 8 characters. If you activate the token correctly, the token is required.

**Comment by jamcat22** [comment]
We could however add an exception saying that their website has a maximum length of 8 characters and only checks the first 8. So we could warn people that they can only type 8 characters then the token code.

**Comment by somethingnew2-0** [comment]
Ok,  I see that now. Yes, I believe that would be fair. Thanks for this site btw!

**Comment by Carlgo11** [comment]
Who wants to make the PR then?
