### ISSUE TITLE
Exostar Provider

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#920]
I received an email from an individual that mentioned [Exostar](http://www.exostar.com/) and said that it wasn't on the list.

**Comment by mxxcon** [comment]
according to http://www.exostar.com/Problems-We-Solve/Products/Second_Factor_Credential_Authentication/ they support
Hardware tokens
SMS (text message)
IVR (voice call)

**Comment by RichJeanes** [comment]
Handled in #1146.
