### ISSUE TITLE
PerfectPass.org

### ISSUE THREAD

**Issue by jdavis** [2factorauth/twofactorauth#924]
For those that are interested, I have a friend, @hoovercj, that is working on a site called [PerfectPass](http://www.perfectpass.org/) and the repo is here: https://github.com/hoovercj/perfectpass

It's similar to 2FA but instead focuses on password info.

@Carlgo11 (and probably @psgs) You actually had emailed me about this, so I think you'd be pretty interested in it.

I thought I'd let you all know. Feel free to help out or give constructive criticism, I'm sure Cody would appreciate it.

**Comment by Carlgo11** [comment]
Ah thanks a lot! I'll check it out :smile:

**Comment by fpigerre** [comment]
PerfectPass looks great @jdavis!
I'll see if there's any way I can help out.

**Comment by hoovercj** [comment]
Thanks @jdavis and company!

I think the repo and docs explain, but I'll add a few words (or a short novel) here, also:

I want help to collect empirical information on  password policies to see what the landscape looks like. As more information gets gathered then it should become clear how to best display it (better than it is now?) So the average person can do something with it -- one example being shaming Visa into oblivion for having an 8 character limit for "Verified by Visa" accounts.

I welcome any and all suggestions regarding:
-what info should be collected
-how it should be displayed
-what should be done with it

Additionally, I want to provide general password information presented in a way that normal people can read and understand WHY password 123 isn't a good password, and guidance on how to be more secure in their personal password management. To that end I have already built two pages. 

One being a list of digital password managers. Again, I welcome feedback for what information is useful, how to present it, etc. 

The second is a password resetter tool which accepts an email address and automatically triggers email reset passwords for that address on a (currently very small) number of sites. The purpose behind the tool is twofold. 1) Ease in the transition from manual password management to digital password managers by giving you an inbox full of password reset links. This also works well for updating old passwords by hand if you don't want to use a manager. 2) gives you a decent overview of all the accounts you have with a certain email address, especially if it is an older/unused email address and you arent sure what accounts are tied to it.

For this I need help encoding the forgot-password forms. This is a brand new project though so I need to make better Contributing documentation.

I hope you all find some value in these ideas and are able to help. Cheers!

**Comment by jamcat22** [comment]
Love the website and idea!

**Comment by Walkman100** [comment]
I think we should add a link to it at the bottom of tfa.org

**Comment by mxxcon** [comment]
@hoovercj I think password reset tool is a bad idea. Trivial to abuse it. It can cripple a ton of sites and users.
I maliciously enter your email and suddenly you have a flood of emails to deal with. Some sites allow you to ignore password reset emails, while others could lock you out until you take action.

**Comment by Carlgo11** [comment]
What about listing how the passwords are stored?
Like, plaintext, hashed, hashed + salted etc.
Oh and maybe we should move the discussion to the actual repo? :wink:

**Comment by mxxcon** [comment]
@Carlgo11 you will not get honest answers. Who will admit that they store passwords in plain text? Everybody will either say salted+hashed or simply "we don't disclose our security practices" or "using industry standard methods".

**Comment by Carlgo11** [comment]
mmm true. sadly...

**Comment by hoovercj** [comment]
@mxxcon I'm not worried about the emails flooding an inbox of a user. Deleting them would be trivial.

I would be ok with staying away from implementing it for sites that do lock you out when the email reset is requested, though, and only resetting at sites where emails can safely be ignored.

Can you elaborate on how you think it could cripple sites and users, though? If you're concerned about somebody attaching a bot (or bot net) to this to somehow annoy people with mass email resets, my answer would be a) I can guarantee whatever implementation I use for this would not be robust enough for them to do too much without it crashing my server and b) I could add a captcha if that would make you feel better.
