### ISSUE TITLE
JSON representation

### ISSUE THREAD

**Issue by zbuc** [2factorauth/twofactorauth#931]
Great work aggregating all this data!

I'm looking to build a Chrome extension that uses the information here -- it would be useful to have a JSON representation of the data.

Would you be open to a pull request to add this?

**Comment by RichJeanes** [comment]
If you would like to contribute that, you would certainly be more than welcome to open a pull request with the modifications yourself. If not, it could go on our list of things to do if one of our collaborators (or anyone else) wants to work on it.

**Comment by jdavis** [comment]
I really like this idea and it shouldn't be too hard either.

I imagine a `/data.json` file or something that Jekyll renders as pseudo-JSON since my cursory searching it doesn't look like Jekyll can do this natively. It wouldn't be the prettiest but it would work.

I imagine it would look like:

``` javascript
{
    {% for section in site.data %}
    "{{section name}}": [
                        {% for website in section_file.websites %}
                                "{{website}}": {
                                            "tfa": true,
                                            "other stuff": true
                               },
                       {% endfor %}
     ],
     {% endfor %}
}
```

Like I said, ugly, but at least it would get the job done...

@zbuc Is that format okay? Can you think of any suggestions based off what you see in the [`_data/`](https://github.com/jdavis/twofactorauth/tree/master/_data) folder with the yaml files?

**Comment by zbuc** [comment]
@jdavis that's pretty much exactly what I was thinking.

I am a Jekyll neophyte but I tried this and it generates something similar to what I'd like:

```
~/repos/twofactorauth:master ✗ $ cat json.html
---
layout: null
---
{
    {% for section in site.data.main.sections %}
    {% assign section_file = site.data[section.id] %}
    "{{ section.title }}": [
                        {% for website in section_file.websites %}
                                "{{ website.name }}": {
                                            "tfa": {% if website.tfa %}true{% else %}false{% endif %},
                                            "url": "{{ website.url }}",
                                            "img": "{{ website.img }}",
                                            "twitter": "{{ website.twitter }}",
                                            "sms": {% if website.sms %}true{% else %}false{% endif %},
                                            "software": {% if website.software %}true{% else %}false{% endif %},
                                            "phone": {% if website.phone %}true{% else %}false{% endif %},
                                            "hardware": {% if website.hardware %}true{% else %}false{% endif %},
                               },
                        {% endfor %}
                        false]
    {% endfor %}
}
```

with the exception that the file it generates is named `_site/json/index.html`, this is basically what I'm looking for!

**Comment by mxxcon** [comment]
(except it's not html, so let's try to make it not be that :smile: )

**Comment by zbuc** [comment]
apparently jekyll is perfectly happy parsing a file with a .json extension :)

pull request submitted.

to avoid having invalid json (trailing commas in objects), i added `"": false` after each for loop. there's probably a cleaner way but i'm unfamiliar with the templating system in use.

**Comment by jdavis** [comment]
@zbuc Excellent. I made some comments on that PR. I'm going to close this in favor of #933.
