### ISSUE TITLE
Twitter does not require SMS

### ISSUE THREAD

**Issue by craigiw** [2factorauth/twofactorauth#934]
Twitter TFA will work also using the official twitter mobile app.

**Comment by smholloway** [comment]
The [docs](https://support.twitter.com/articles/20170388) state that you have to have a verified phone number to set up the in-app 2FA. This requires SMS. Beyond trusting the docs, I've set up 2FA for twitter and SMS was required.

**Comment by craigiw** [comment]
You can also set it to "Send login verification requests to Twitter for
Android."  This is what I have set up and it works fine.

**Comment by jdavis** [comment]
Yup, I run another Twitter account and they require an unused SMS number to initially setup 2FA. You can't enable 2FA without first adding a phone number: https://support.twitter.com/articles/20170388

**Comment by Carlgo11** [comment]
Actually you can, I've had the problem that they don't support any swedish carriers and so tfa won't work, but they seem to allow tfa without SMS now because I can now use tfa^_^

**Comment by Carlgo11** [comment]
I'm guessing it's per region tho
