### ISSUE TITLE
Slack is working on two factor auth

### ISSUE THREAD

**Issue by drissamri** [2factorauth/twofactorauth#940]
Tweeted and received:

Slack ‏@SlackHQ  15h15 hours ago
@drams88 We can't share an ETA, but it's in a small beta now. We're working very hard!
6:40 PM - 27 Jan 2015 · Details

Maybe reflect this on the site?

**Comment by Carlgo11** [comment]
Could you share the link to the tweet? You can also put the link to the tweet under `status:` for slackhq

**Comment by drissamri** [comment]
Submitted a pullrequest

https://twitter.com/SlackHQ/status/560130187271352321

**Comment by mxxcon** [comment]
Um, @drissamri You asked them about Windows client, not 2FA... :confused:

**Comment by Carlgo11** [comment]
.........
<img src="http://replygif.net/i/1245.gif">

**Comment by jdavis** [comment]
I love the enthusiasm though, @drissamri =]

I'm closing this since your PR was closed: #941.
