### ISSUE TITLE
cognalys.com - two factor authentication / mobile number verification for free

### ISSUE THREAD

**Issue by anishmenon** [2factorauth/twofactorauth#945]
I've committed about https://www.cognalys.com . But its not updated on website

New method of Mobile number verification / Two factor authentication for free

**Comment by mxxcon** [comment]
I see no pull requests related to cognalys...where/when did you commit this change?

**Comment by anishmenon** [comment]
I think its 3 weeks before .

i've followed
https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md

**Comment by Carlgo11** [comment]
Could you link to your pull request?

**Comment by anishmenon** [comment]
Just created new

https://github.com/jdavis/twofactorauth/pull/947

and i dont have right access to upload logo

https://www.cognalys.com/static/logo/favi.png

**Comment by anishmenon** [comment]
and i dont have right access to upload logo

https://www.cognalys.com/static/logo/favi.png
