### ISSUE TITLE
No two-factor on Lloyds Bank

### ISSUE THREAD

**Issue by Terrance** [2factorauth/twofactorauth#948]
The docs link on [enhanced authentication](http://www.lloydsbank.com/help-guidance/security/authentication-procedure.asp) is only for adding new payees on an account - there are currently no 2FA options when actually logging in.

I guess that is still a form of 2FA, but it seems a bit misleading in the list?

**Comment by MethodGrab** [comment]
:+1: agreed!

**Comment by Carlgo11** [comment]
I agree with you as well @OllieTerrance. Could you make a PR removing the doc link or replacing it if you find a better page to link to?

If not then one of us well probably do it though that might take a while.

**Comment by jamcat22** [comment]
Only one problem, we have many sites (Wells Fargo, NatWest, and other sites) that work this way too (only use 2FA to protect certain things).

What should we do about those?

**Comment by plecavalier** [comment]
Could add a column for partial / select areas. Or whole site versus
portions thereof...etc

**Comment by RichJeanes** [comment]
I know we have at least one site listed (Domains/Dynadot) that uses an exception flag to point out that it only protects certain actions with TFA. If people would like to update sites to add exceptions, PRs are welcome.
Closing for house keeping.

**Comment by mxxcon** [comment]
@RichJeanes But then we also have sites that are tagged as `no` because they support 2fa only for some functions.. In our own https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions very last section covers this.

**Comment by jamcat22** [comment]
How about we tag them as no, but add an exception?
