### ISSUE TITLE
Missing Icon for Blackberry "Custom" Links

### ISSUE THREAD

**Issue by RichJeanes** [2factorauth/twofactorauth#95]
When I added the additional links for Blizzard in PR #75 I added a link for their app on Blackberry's AppWorld but there does not appear to be a corresponding icon for it on the live site. I was going to add one myself but I can't seem to find where to add that in the repo.

**Comment by ralfharing** [comment]
It's [css](https://github.com/jdavis/twofactorauth/blob/master/lib/semantic/css/semantic.no-resp.css#L7441), not an image that is checked in.
http://astronautweb.co/snippet/font-awesome
http://fortawesome.github.io/Font-Awesome/

**Comment by RichJeanes** [comment]
That explains why I couldn't find it. Thank you!
Also, looks like there is no Blackberry icon in the set. Guess a work around is called for. If it matters that much, that is.

**Comment by jdavis** [comment]
Would the icon called ["Mobile"](http://semantic-ui.com/elements/icon.html) work?

**Comment by ralfharing** [comment]
Looks like they've had an icon request for BB open at FortAwesome/Font-Awesome#1537 for a few months.

**Comment by RichJeanes** [comment]
I think mobile looks good. Better than a blank spot on the site. I'll add it to my next commit and PR.
