### ISSUE TITLE
Crashplan

### ISSUE THREAD

**Issue by djrarky** [2factorauth/twofactorauth#971]
[deleted]

**Comment by mxxcon** [comment]
I edited your post to remove all that other html junk.

**Comment by stevepork** [comment]
I left it to prove it’s authenticity, but thanks.


                         	 		
Steven Chorkley
chorkley.co.uk
Facebook  •  Twitter
On 8 February 2015 at 22:10:20, mxxcon (notifications@github.com) wrote:

I edited your post to remove all that other html junk.

**Comment by RichJeanes** [comment]
Should we update Crashplan's entry with this page linked for the status? Maybe not since they haven't provided any timeline (in which case close this issue for house keeping)?

**Comment by mxxcon** [comment]
Ya, "future release" with no ETA is as good as doesn't exist..Especially since this was originally brought up in Feb..closing.

**Comment by StevenChorkley** [comment]
Not really.... Considering you have other services marked as in the works.

Sent from a mobile device.
http://www.chorkley.co.uk/

**Comment by mxxcon** [comment]
If you see any that have been marked like that it's been even longer, do make a pull request or open another issue.
I don't want to let companies off the hook by feeding their users empty promises.

**Comment by StevenChorkley** [comment]
Gotcha!

Sent from a mobile device.
http://www.chorkley.co.uk/

**Comment by brianbiggs** [comment]
Looks like CrashPlan now supports Two-factor Authentication:
http://www.code42.com/resources/product-information/two-factor-authentication/
I'm new to github, so not sure how to make this update myself. Thought I'd let someone know.

**Comment by NathanielMaier** [comment]
That appears to be for their commercial product only, and only by using a
RADIUS server that is pointed at a 2FA provider.

**Comment by mxxcon** [comment]
indeed, i just tried to enable it on my account and haven't found that feature.

**Comment by brianbiggs** [comment]
Ah, yes, sorry. Didn't read carefully enough. Thanks for the correction. -- Brian
