### ISSUE TITLE
TurboTax now offers 2FA

### ISSUE THREAD

**Issue by alienesb** [2factorauth/twofactorauth#972]
Read more here:

https://nakedsecurity.sophos.com/2015/02/10/turbotax-resumes-e-filing-following-torrent-of-fraudulent-tax-returns/

**Comment by Carlgo11** [comment]
Hi @alienesb,
Thank you for informing us about this.
While we'd love to add all sites mentioned here we're volunteers who do this on our spare time.  

The best for us would be if you could make a Pull Request (PR) for adding this.
For your pull request to be accepted you need:
- To decide which category on twofactorauth.org that fits this site best. If none then choose `other`.
- Add the site to _data/<category>.yml. All sites are in alphabetical order.
- Enter a valid URL for the site and add a `doc` that's accessible for everyone, not just loged in users. If the URLs are available in HTTPS we prefer that.
- Add an appropriate 32x32 pixel logo. Use git on your workspace to upload the logo. Do not just upload the logo in the PR's description. **WE WON'T ACCEPT PRs WITHOUT A LOGO**
  For more information please look at <a href="https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md">CONTRIBUTING.md</a>  

If your PR is accepted it will be merged by us. **Note that it will take a few days before the live site shows your site.**

Once again, thank you for your contribution. All contributions helps a lot! :cake:

Thank you,
@Carlgo11 :smile:

**Comment by alienesb** [comment]
Hello,

You already have it listed as Intuit Turbo Tax under the Finance category.

Thanks,
Tim

**Comment by Carlgo11** [comment]
Then it's even easier for you to add it.
just follow the <a href="https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md">CONTRIBUTING.md</a>

**Comment by NathanielMaier** [comment]
Hi @alienesb - Where do you see that Intuit TurboTax currently offers 2FA? The Sophos article you linked to doesn't say that, and I don't see anything on Intuit's websites either.

**Comment by RichJeanes** [comment]
Paragraph 9

> As of 3 pm PST on Saturday, TurboTax was back filing state returns.
> To do that, it plugged in several security measures, one of which was multifactor authentication.

Though we will require publicly accessible documentation on the Intuit or TurboTax website before accepting any modifications to the entry.

**Comment by mxxcon** [comment]
https://twitter.com/turbotax/status/563866459995373569
Although link from that twitter is still to a vague blog post

**Comment by alienesb** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Tim

Confirm that you know Tim: https://www.linkedin.com/e/v2?e=sbfrzv-ic57u6lo-3j&amp;t=ssuw&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=gVPuZStY&amp;invitationId=6027180597242261504


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=sbfrzv-ic57u6lo-3j&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQHBsRcPbCaKDAAAAU6TY4AUHal65mj7Dfy_sUTYvXrWtkf0odC0E4O5Xcx3RMEBizEzSYxOorxPNX-JYP6-m3_5lkVTa6BuMZ8eZvdcqRVo8AnYnC0HXKsGBJnSqViX9GMvEEbmf9EUUeJu8EA3U3XTLSLEMaWS6Sm2-vQAxgk6N3bgdJ24cmVIwB7HOwMZyDmw&amp;eid=sbfrzv-ic57u6lo-3j Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=sbfrzv-ic57u6lo-3j&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by mxxcon** [comment]
@alienesb It's not polite to spam all your contacts with LinkedIn invites. :( Please control who/what gets access to your address book.

**Comment by Carlgo11** [comment]
@mxxcon probably just an accident. The same happened to my mom a year ago.
LinkedIn should remove that possibility.
I mean who really wants to spam every single person/company they've talked to via email.
