### ISSUE TITLE
add rss feed

### ISSUE THREAD

**Issue by ralfharing** [2factorauth/twofactorauth#99]
A suggestion would be an rss feed so people could stay on top of the new services as they are added. (or some other notification method)

**Comment by jdavis** [comment]
So in addition to being a list of the sites with 2FA, announce when new
sites add 2FA? Is that what you mean by that? If that is the case, I think
that's pretty brilliant... I'm going to have to think on that for a bit.

**Comment by ralfharing** [comment]
Yep, that's exactly what I mean. Transitioning to a new service is often painful and people will stick with what they're using even if it's less secure. Services themselves are often less than effective at communicating new features (buried in announcement emails few read, usually) so anything that helps get the word out would be desirable.

**Comment by regagain** [comment]
Totally agree, an RSS feed would be awesome.

**Comment by jdavis** [comment]
We have #519 that I've added to the milestone for Filtering. Refer to that issue for newly added sites discussion.
