### ISSUE TITLE
E-Mail is enhanced security but not a 2nd factor.

### ISSUE THREAD

**Issue by JosephRDawson** [2factorauth/twofactorauth#992]
By definition two factors requires two different factors from the standard list of something you know (like a password), something you have (like a token) or something you are (biometric).  E-mail is another something you know...  

You know your e-mail password.  It can be accessed from many locations so not just from one device. And someone could have access to your e-mail place a password reset get the token and delete it before you ever knew it happened.

Final big issue for it... Many systems use e-mails as part of the password reset system.  So if I have access to your e-mail but don't know your password to the service I want to access.  The service is using e-mail 2 factor.  I try to access your account on that service and I request a password reset via e-mail.  I have access to that e-mail and also to the token they will send to that same e-mail address.

I have no issue with e-mail being still listed as a method of stronger authentication that some services provide.  My heartburn is it should have a \* next to it and said that it is not two factor.

**Comment by Carlgo11** [comment]
I agree with @JosephRDawson

**Comment by smholloway** [comment]
And what if the system is currently secured by biometrics or a token? Then adding email is a second factor. You're presupposing that the only systems being secured by 2FA are knowledge-based logins.

Thank you for the reminder that while two of the same factors may improve security, it is not 2FA.

**Comment by JosephRDawson** [comment]
smholloway: I assume all sites listed on your page have username and password. The point of your page (I maybe wrong) is to point out what services provide additional security. 

Email is additional security no question but it is not 2FA. 

If a site also has token and email that is great. But the token is what made it 2FA not the addition of email. So I feel losing email without some note on it allows the uneducated to think that email and a token are both valid types of 2FA. 

I found this page because someone said email was valid 2FA because of this webpage listing it as so. 

I would just request an edit note on email or remove it because just as adding a second password two things you know is step up authentication not 2FA. 

This is a great webpage I just want to make it better. 

All the best,

Joe

**Comment by mxxcon** [comment]
This seems to be similar topic to #778.

**Comment by smholloway** [comment]
I think it would be easier to understand in code--can you make a pull request with the changes that would fix this issue?

**Comment by JosephRDawson** [comment]
I am confused. All I am saying is on the webpage https://twofactorauth.org/providers/. Email should not be listed as a 2FA for auth. 

All sited have something you know. Email is an additional something you know. So it is not a 2FA. All others listed are valid 2FA.

**Comment by mxxcon** [comment]
@JosephRDawson but then it would be not just providers but actual sites too

**Comment by JosephRDawson** [comment]
I must not understand the https://twofactorauth.org site. 

Email is listed as a method of two factor. It is only the something I know factor same as password. So if email is listed a second passwords should be listed. And sites that ask you to answer a question like your othes maiden name when you login should be listed. 

My point was none of the above examples math the industry standard for two factor. So as email is not a valid type of two factor no matter how you implement it. It should be given an explanation that it is not a second factor or removed from the list of valid types of two factors that you accept. 

This is not a code issue or an implementation issue. This is a definition issue. Email is a method of step up authentication not 2nd factor. 

The progeny is called twofactorauth. Not stronger auth. But again maybe the project just had the wrong name  maybe the goal is not two factor.

**Comment by smholloway** [comment]
I have to be pedantic because email _can_ be a second factor. Imagine a secure facility where you unlock a door with a retinal scan (inherence factor); the system looks up your unique features and knows who is at the door. From there, you are emailed a code that you must enter to fully unlock the door. You could extend this and say you have to scan a badge (possession), then scan a fingerprint (inherence), then enter a secret of some kind (knowledge).

More to the point, I am hearing, "you should remove the email column from the site" or "you should add more information that two-factor authentication requires two different factors." There's some confusion about how to satisfy this issue, so please show me in code what you'd like.

**Comment by JosephRDawson** [comment]
You pedantic man you... :) In the example you used email would be a silly choice. All retinal scans I use just have you enter a pin it password as the something you know. Making it email would be a weird choice as step. 

You can link tob wikipedia definition. I don't think you really have to get into a bunch of detail if you remove it. As you don't try to list all the things that are not 2FA.

**Comment by jamcat22** [comment]
Also, some email providers (Google, Yahoo, Microsoft, etc.) offer two factor authentication, making the platform secure for some sites. Also, some websites can't afford to send SMS or use an app, so they use email and recommend that people enable 2FA on their account. This makes it a sort of 2nd factor. The email requires a second factor besides the password, and the website (by association) requires an second factor (email) besides a password.

**Comment by JosephRDawson** [comment]
Wait now... your suggesting that if you use an e-mail for validation and if that e-mail has been setup to only work with two factor then somehow that then makes the use of e-mail a 2nd factor.

Even if that was good logic... And I am not sure it is.  The website that was allowing you to use your e-mail as a 2nd factor would have no way of knowing your gmail account was setup to support 2nd factor.  So you would have zero confidence that email was a 2nd factor.  

Google authenticator has free open source code you can use to bake it into any website for free. So any small website that wants to have 2nd factor can use google system for free.

Also I am not saying people can't or shouldn't use e-mail as a method to enhance the security of sites. It is just not a valid 2nd factor. And the fact that 2nd factor is hard or not low cost is not a reason to say e-mail is 2nd factor.  

A clear standard exists for what is and is not 2nd factor.  E-mail is someting you KNOW just like a password is... Not someting you have or are.  So if your using e-mail... you need to have something you have or are.

**Comment by mxxcon** [comment]
@JosephRDawson I'm not rejecting your notion. I think we should think it through. This is a pretty important issue.
Yes, the original site has the knowledge factor, but 2fa code sent to an email has login with a completely different and unrelated knowledge factor.
The same could be said about 2fa using SMS on a phone that is not secured with a password or a pin.

**Comment by JosephRDawson** [comment]
Same can not be said about a phone without a pin.

Phone is always a physical device.

It is not a knowledge factor it is a physical factor all the time.

**Comment by JosephRDawson** [comment]
RSA secure ID tokens always display the token and don't require any pin to have it display the token all the time.  But they are still a physical factor... It is not that a physical factor is better then a knowledge factor.   On the surface a physical factor is weak.  It is just that it is a different factor. 

And two knowledge factors, no matter how different or how strong they are is not the official definition of two factor.

**Comment by JosephRDawson** [comment]
Hi All...  I guess no appetite exists to address this.  All the best.

**Comment by mxxcon** [comment]
I would still like to have more discussion on this. Perhaps post this question to https://security.stackexchange.com/ or some security-conscious mailing list?

**Comment by PaulMoore2015** [comment]
@JosephRDawson It does resemble #778 - I tried making this point with equally bizarre replies.

@jamcat22 Google, Microsoft and Yahoo do not offer 2FA, they offer 2SV or "login verification".  To say email "makes it a sort of 2nd factor" is simply not true.  The definitions are clearly explained in SP800-63-2 (soon to be -3) and multiple instances of any single factor does not constitute multi-factor authentication.  An OTP by email falls under 6.1.4 of SP800-63-2 (multi-stage or 2 step verification), as the OTP is neither memorized (thus can't be a knowledge factor) nor independent of other factors.

If the "possession" factor is hidden behind a "knowledge" factor, the assurance level is equal to that of the lowest factor... the password.

Take 1Password for example.  They've recently introduced TOTP support (the storage of crypto seeds in the keychain).  Within minutes, Twitter lit up with "1Password supports 2FA!!!" and other such nonsense; even "experts" jumped on the bandwagon.  I replied to numerous tweets to say that although TOTP support mirrors that of Authy/Google Authenticator et al, this was not 2FA as you've now combined both factors behind a single factor, the master password.

The responses were very similar to #778... "what's that?", "what's the difference?" and "OK, it's 2SV but it's the same thing".  It wasn't until AgileBits/1Password actually blogged about it (verbatim "2nd factor, NO!") that people stopped arguing and RTFM.

Ultimately, "factors" are a stepping stone to what is actually required... higher assurance; allowing the verifier to assert with a greater degree of confidence that the bearer of the token authenticator is actually the owner of the account.  There is literally no difference between a password (either original or reset link) by email and an OTP by email, thus the assurance level remains the same.

3FA > 2FA > 2SV > 1FA.

I have to agree with @JosephRDawson - The email field either needs to be removed completely or the site overhauled to correct categorize sites as 2SV or 2FA.

**Comment by JosephRDawson** [comment]
Thanks Paul... I basically gave up because a clear definition of what is
second factor exits. And two knowledge factors can't be two factor. I think
making the change would give credibility to what is otherwise a good
project.  If you want to just have stronger authentication sure e-mail
works.  But if your going to call it two factor then you can't have e-mail
the way it exists today.

---

http://bitstop.ca

**Comment by PaulMoore2015** [comment]
Agreed @JosephRDawson 

The project is great, it's the quality of data which lets it down.  I'm sorry to say, but if the majority of contributors have never heard of 2SV and can't correctly define 2FA, it has very little credibility.

I appreciate where they're coming from wrt defining 2FA/2SV; even the latest revision of 800-63 needs updating/clarification... but I'm looking at it from both angles.  My research papers regarding Google's 2SV were featured at EUROSEC and the suggestions from it put forward to the draft of 800-63-3, but I'm also mindful of the repercussions of these inaccuracies.  There have been several high-profile cases of "2FA" accounts being breached recently, particularly wrt Google 2SV.  Thankfully, those affected were already aware of the differences, so the risk was weighted accordingly.  Unfortunately, the layman is unlikely to realize that when twofactorauth.org says "Roboform offers 2FA by email", it actually offers nothing of the sort.

I had given up too, but a colleague at OWASP raised your topic during a discussion.

"See Joseph's post here <link>, looks like _some_ progress was made"

I doubt it'll change but here's hoping ;)

**Comment by mxxcon** [comment]
@PaulMoore2015 A change in attitude and less dismissive approach could accomplish a lot more...

**Comment by JosephRDawson** [comment]
I did post the question to what I was told by the team leader to be the
right place at the time.
The topic died... the lack of anyone else really debating the point... made
me feel like the whole idea was dismissed until Paul spoke up...

You did mention to post the question to the Security exchange but I am not
quite sure how that is even connected to the 2FA project.

---

http://bitstop.ca

**Comment by jamcat22** [comment]
I'm going to go ahead and close this for housekeeping.

I feel like we use kind of a loose definition of 2FA on our website, and listing email as a step can be beneficial to some people.

In the future, we could make a way for people to send a request to a service to improve their standards and support another factor/step besides email.
