### ISSUE TITLE
Differentiate between open 2FA and closed systems.

### ISSUE THREAD

**Issue by sorcix** [2factorauth/twofactorauth#993]
It would be interesting to indicate wether a site supports [rfc6238](https://tools.ietf.org/html/rfc6238) with any application, or a bastardized version that requires a specific app like Authy. (For example, I can't use the Cloudflare 2FA because it simply doesn't work with a TOTP app from fdroid.)

**Comment by RichJeanes** [comment]
We've previously listed details about the services provided but decided to simplify and streamline. We are aiming more at an audience of people who do not understand (or anyone who doesn't care about) the technical details. If you do care, then you can use the site as a starting point for what services support 2FA and look into it more yourself.

**Comment by mxxcon** [comment]
Unless @sorcix you can come up with an elegant way to display such info that doesn't require keep adding new columns for new implementations..

**Comment by sorcix** [comment]
What about a checkmark in a different color?
- Green checkmark: rfc6238 TOTP with any app
- Blue checkmark: requires a specific app

It's less important for me to know which specific app it requires, just the fact that I can't choose would be enough.

**Comment by mxxcon** [comment]
What about "open" implementations that are not based on rfc6238, like rfc4226 or not based on any rfc at all?

**Comment by sorcix** [comment]
Most apps support both rfc6238 and rfc4226. Are there any sites on the list that use a different open standard? If there's only one site supporting a specific "standard" then it should be classified as "requires a specific app."

**Comment by mxxcon** [comment]
I have no idea. I can't tell you how many sites use any specific application or method. As you can see, we don't keep track of those specifics.
What if it's not only 1 site? At what point does it become a more generic indicator?
What about open standard based hardware 2fa?

**Comment by smholloway** [comment]
The scope expands quickly.

Rather than trying to address everything on the main page we could create new pages for these one-off ideas. We could have a page listing providers that support RFC6238, another for sites that support RFC4226, another for sites that support universal two-factor, etc. I'm not sure anyone would look at the other pages, but it provides a solution for issues like this one.

**Comment by mxxcon** [comment]
If we were to finally figure out and implement a tagging system, then I think we could add all kinds of details.

**Comment by ghost** [comment]
I agree, at least an indicator for sites requiring a specific app (e.g. Authy) would be nice.

**Comment by ghost** [comment]
I have an idea. How about a note for this is added under a warning sign, like the one other sites already have?

**Comment by rugk** [comment]
BTW instead of RFC6238 and RFC4226 I would display TOTP and HOTP - for the regular user there are better changes that they understand (and remember) this much better.

Also have a look at my idea here: https://github.com/jdavis/twofactorauth/issues/965

**Comment by RichJeanes** [comment]
If anyone would like to try and implement anything mentioned in this thread, feel free to submit a PR. Closing this for house keeping.
