### ISSUE TITLE
HSTS and Authenticated Origin Pulls! (A continuation of #670)

### ISSUE THREAD

**Issue by jamcat22** [2factorauth/twofactorauth#999]
To enforce HTTPS and ensure the connection between an end user and CloudFlare is secure, we should enable HSTS and Authenticated Origin Pulls. (As an added plus, HSTS should boost our [SSL Labs rating](https://www.ssllabs.com/ssltest/analyze.html?d=twofactorauth.org&hideResults=on) to A+.)
Of course, if we don't want to force HSTS, we don't have to enable HSTS, but I do think we should enable Authenticated Origin Pulls.

To enable HSTS or Authenticated Origin Pulls in CloudFlare, you need to use the [preview portal](https://next.cloudflare.com). You can always revert back using the button at the bottom right. ![image](https://cloud.githubusercontent.com/assets/1897053/6543359/f4f8e434-c4d5-11e4-8f31-11995b8e9bc3.png) Changes made in the preview portal will be kept even if you switch back to the original portal.

Enabling the [preview portal](https://next.cloudflare.com):
- First, [login to CloudFlare](https://www.cloudflare.com/login).
- Second, click on the ![image](https://cloud.githubusercontent.com/assets/1897053/6544480/3076b3ea-c50f-11e4-9de1-f97fbdc4075e.png)
  button at the bottom right.

Enabling HSTS:
- First, login and select a site. 
- Second, click on "Crypto" in the menu bar, and then click "Enable HSTS".
  ![image](https://cloud.githubusercontent.com/assets/1897053/6543432/406020a2-c4d8-11e4-962f-207694ca4921.png)
- Third, check the box and click "Next step". 
  ![image](https://cloud.githubusercontent.com/assets/1897053/6543447/f415dd9e-c4d8-11e4-89bd-eb983bd17544.png)
- Fourth, set the settings in the window and click "Save".
  - I recommend setting the "Max Age Header" to 6 months for maximum security, but only if we think we will have the website always on SSL/TLS. The minimum for the HSTS preload list created by Google (used by Chrome, Firefox and Safari) is 5 months.
  - I recommend turning on "Apply HSTS policy to subdomains" if we aren't using any subdomains or if we will have HTTPS on any subdomains we might have/create.
  - I recommend turning on "Preload" for maximum security, but only if we think we will have the website always on SSL/TLS. This will hard-code the website into Chrome, Firefox and Safari so that these browsers will force HTTPS even before receiving the HSTS message.
    ![image](https://cloud.githubusercontent.com/assets/1897053/6543458/6deca792-c4d9-11e4-9d55-a526eae2f6a4.png)

Enabling Authenticated Origin Pulls:
- First, if you haven't already, login and select a site.
- Second, click on "Crypto" in the menu bar, and then turn on "Authenticated Origin Pulls".
  ![image](https://cloud.githubusercontent.com/assets/1897053/6543547/f5e781aa-c4dc-11e4-95e7-0ea3b4d25925.png)

Also, congratulations on reading issue #999!

**Comment by mxxcon** [comment]
> Update: The beta is full! Thanks to those who are participating.

Can't enable any of that unless you are part of their beta portal.

**Comment by jamcat22** [comment]
Wrong beta. You're looking at the beta for installing a SSL certificate on the webserver provided by CloudFlare. The preview panel is open to everyone.

**Comment by mxxcon** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/847140/6544465/2451de68-c51f-11e4-9a9c-6dfec50432a9.png)

**Comment by jamcat22** [comment]
Ah. Let me update the steps.

**Comment by jamcat22** [comment]
Try the new instructions.

**Comment by mxxcon** [comment]
:+1: that works.

**Comment by jamcat22** [comment]
@mxxcon Awesome!

**Comment by Carlgo11** [comment]
Wait so did @mxxcon enable this or do we need josh to do it?

**Comment by jamcat22** [comment]
Looks like we need Josh. SSL Labs still says it isn't enabled.

**Comment by mxxcon** [comment]
I didn't enable it. I was just looking at my own cloudflare account.

**Comment by jdavis** [comment]
I just enabled it:

![screen shot 2015-03-12 at 8 28 30 pm](https://cloud.githubusercontent.com/assets/157801/6632614/5fa6928a-c8f6-11e4-8325-3730b98a7873.png)

Well guys, it looked like we just...

![horatio gif](http://media.giphy.com/media/9wZuFnWreJQgU/giphy.gif)

...aced our exam.

**Comment by jamcat22** [comment]
Just submitted the website to Google's HSTS preload list. Should be updated and pushed to Chrome, Firefox, Safari, and newer versions of Internet Explorer soon!
![image](https://cloud.githubusercontent.com/assets/1897053/6662076/89afd7ca-cb7c-11e4-97ca-8e8dc56148f6.jpg)
